### ISSUE TITLE
User Management | Remove restriction for phone number being too long |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1060]
**Locations:**

- Creating a new user (IDIR): Administration tab, Users sub-tab, New User button or Add Fuel Supplier User button
- Creating a new user (IDIR): Fuel Suppliers tab, Click on Company Name to go to Company Details page, New User button sub-tab, New User button or Click on existing user in table and edit details
- User Profile (IDIR & BCeID): Settings, User Profile

**Issue:**
Phone number fields (Work & Mobile) are currently restricted to a maximum of 17 characters. This throws an unclear error message (unclear in terms of which input field is causing the error). 

**Fix:**
Remove this restriction and allow numbers greater than 17 characters. We want to allow users to be able to enter in longer numbers, for example: (604) 123-4567 ext. 1234https://trello.com/c/E8wyknt1/1327-user-management-remove-restriction-for-phone-number-being-too-long-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Management | Remove restriction for phone number being too long |1|](https://trello.com/c/E8wyknt1/1327-user-management-remove-restriction-for-phone-number-being-too-long-1)
