### ISSUE TITLE
Fuel Codes | Autocomplete next version of Low Carbon Fuel Code |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1063]
**Task:** 
As an IDIR user, I want TFRS to autocomplete the next version of the Low Carbon Fuel Code field when adding a new fuel code.

**Scenario:**
GIVEN that I am an IDIR user
AND I am adding a fuel code
WHEN I select the Low Carbon Fuel Code field 
AND I start typing in the field
THEN TFRS autocomplete the next available version of the fuel code
AND I am unable to choose a different version
AND I am still able to modify the code (just not the version)

**Edge Case Error Message:**

- If two analysts are entering in the same new fuel code at the same time, the error message should read: "Error! The fuel code BCLCFXXX.X is already in use. Please consult the Fuel Codes table to ensure that this entry does not already exist." 
- In this case, BCLCFXXX.X is the specific code in question. https://trello.com/c/vMBkekOK/1319-fuel-codes-autocomplete-next-version-of-low-carbon-fuel-code-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Codes | Autocomplete next version of Low Carbon Fuel Code |5|](https://trello.com/c/vMBkekOK/1319-fuel-codes-autocomplete-next-version-of-low-carbon-fuel-code-5)
