### ISSUE TITLE
Fuel Codes | Adjustment to sorting the Low Carbon Fuel Code column ascending descending |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1064]
**Location:**
View Fuel Code table (IDIR only)

- Administration tab
- Fuel Codes sub-tab
- Column: Low Carbon Fuel Code

**Background:**
A unique fuel pathway is given a single fuel code (e.g. BCLCF101.0); the number after the decimal illustrates a new version of the same fuel pathway. For example, when BCLCF101.0 expires the fuel producer will apply for renewal. The updated pathway will be given a new fuel code (BCLCF101.1) and a new entry created in the Fuel Code table. 

When sorting these values by ascending/descending, TFRS should account for the number(s) after the decimal in determining which value is "higher" or "lower". 

**Examples:**

- BCLCF102.0 is "larger" than BCLCF101.0, which is "larger" than BCLCF101.5
- BCLCF105.10 is "larger" than BCLCF105.5, which is larger than BCLCF105.1 

**Task:**
When sorting the Low Carbon Fuel Code column by descending/ascending order (as is the default for the Fuel Codes sub-tab page), have the system account for the number(s) after the decimal in determining the appropriate order, as described above. https://trello.com/c/Uddr72G2/1320-fuel-codes-adjustment-to-sorting-the-low-carbon-fuel-code-column-ascending-descending-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Codes | Adjustment to sorting the Low Carbon Fuel Code column ascending descending |1|](https://trello.com/c/Uddr72G2/1320-fuel-codes-adjustment-to-sorting-the-low-carbon-fuel-code-column-ascending-descending-1)
