### ISSUE TITLE
Credit Calculation | View CI Limits |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1071]
**Story:**
As an IDIR user, I want to be able to view the carbon intensity limits for the two fuel classes so that I can understand how current and future credits will be calculated. 

- This card is to build a table in both the back-end and front-end to track and view the carbon intensity limits used in the calculation of credits (section 6 of the Act).
- The table can be found in section 11.02 (1) of the [Regulation](http://www.bclaws.ca/EPLibraries/bclaws_new/document/ID/freeside/394_2008). Screenshot attached.
- Instead of having a "2020 and subsequent compliance periods", have a row for each compliance period out to 2030. That is, one row for 2020, one for 2021, ... , one for 2030. The values for 2020 to 2030 are all the same right now, but this allows the Branch to make the necessary changes when reduction targets are set beyond 2020. We should also look to expand the current compliance periods in TFRS to 2030 (currently only have to 2020). 

**Scenario 1:**
GIVEN that I am an IDIR user
AND I am on the Administration tab
WHEN I click on the "Compliance Reporting" sub-tab
THEN I am taken to the Compliance Reporting sub-tab within the Administration tab
AND I can view the CI Limits

**Forward looking usage:**

- We will be using/pulling these values when we implement compliance reporting as they are used in the calculation of credits/debits. 
- We will want IDIR users to be able to edit these values as they change from time to time.https://trello.com/c/mfCiH2IR/888-credit-calculation-view-ci-limits-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | View CI Limits |5|](https://trello.com/c/mfCiH2IR/888-credit-calculation-view-ci-limits-5)
