### ISSUE TITLE
Credit Calculation | View Energy Effectiveness Ratio EER values |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1075]
**Story:**
As an IDIR user, I want to be able to view the energy effectiveness ratios for the different fuels so that I can understand how current and future credits will be calculated. 

- This card is to build a table in both the back-end and front-end to track and view the EER values used in the calculation of credits (section 6 of the Act).
- The table can be found in section 11.02 (2) of the [Regulation](http://www.bclaws.ca/EPLibraries/bclaws_new/document/ID/freeside/394_2008). Screenshot attached.

**Scenario 1:**
GIVEN that I am an IDIR user
AND I am on the Administration tab
WHEN I click on the "Compliance Reporting" sub-tab
THEN I am taken to the Compliance Reporting sub-tab within the Administration tab
AND I can view the EER values

**Forward looking usage:**

- We will be using/pulling these values when we implement compliance reporting as they are used in the calculation of credits/debits. 
- We will want IDIR users to be able to edit these values as they change from time to time.https://trello.com/c/UlZX9VeP/890-credit-calculation-view-energy-effectiveness-ratio-eer-values-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | View Energy Effectiveness Ratio EER values |5|](https://trello.com/c/UlZX9VeP/890-credit-calculation-view-energy-effectiveness-ratio-eer-values-5)
