### ISSUE TITLE
Credit Calculation | View Energy Densities |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1091]
**Story:**
As an IDIR user, I want to be able to view the energy densities for the different fuels so that I can understand how current and future credits will be calculated. 

- This card is to build a table in both the back-end and front-end to track and view the energy density values used in the calculation of credits (section 6 of the Act).
- The table can be found in section 11.02 (3) of the [Regulation](http://www.bclaws.ca/EPLibraries/bclaws_new/document/ID/freeside/394_2008). Screenshot attached.

**Scenario 1:**
GIVEN that I am an IDIR user
AND I am on the Administration tab
WHEN I click on the "Compliance Reporting" sub-tab
THEN I am taken to the Compliance Reporting sub-tab within the Administration tab
AND I can view the Energy Densities

**Forward looking usage:**

- We will be using/pulling these values when we implement compliance reporting as they are used in the calculation of credits/debits. 
- We will want IDIR users to be able to edit these values as they change from time to time.https://trello.com/c/oViXS5Ty/893-credit-calculation-view-energy-densities-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | View Energy Densities |5|](https://trello.com/c/oViXS5Ty/893-credit-calculation-view-energy-densities-5)
