### ISSUE TITLE
Credit Calculation | View Fuel Types |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1096]
**Story:**
As an IDIR user, I want to be able to view the different fuel types so that I can understand how current and future credits will be calculated. 

- This card is to build a table in both the back-end and front-end to track and view the different fuel types used in the calculation of credits (section 6 of the Act).
- The recognized fuel types can be found in [RLCF-016 - Fuel Identification Requirements](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/electricity-alternative-energy/transportation/renewable-low-carbon-fuels/rlcf016_-_fuel_identification_requirements.pdf). Specific values to use are listed below. 

**Scenario 1:**
GIVEN that I am an IDIR user
AND I am on the Administration tab
WHEN I click on the "Compliance Reporting" sub-tab
THEN I am taken to the Compliance Reporting sub-tab within the Administration tab
AND I can view the Fuel Types

**Fuel Types:**
The following is a list of fuel types we will need to include in this table:

- Biodiesel
- CNG
- Electricity
- Ethanol
- HDRD
- Hydrogen
- LNG
- Natural gas-based gasoline
- Petroleum-based diesel
- Petroleum-based gasoline
- Propane
- Renewable diesel
- Renewable gasoline

**Forward looking usage:**

- We will be using/pulling these values when we implement compliance reporting as they are used in the calculation of credits/debits. 
- We will want IDIR users to be able to edit these values as they change from time to time.https://trello.com/c/NsnndCBP/901-credit-calculation-view-fuel-types-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | View Fuel Types |2|](https://trello.com/c/NsnndCBP/901-credit-calculation-view-fuel-types-2)
