### ISSUE TITLE
Credit Calculation | Model Changes |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1098]
There are some changes that we need to do for the models relating to the Energy Effectiveness Ratio, Energy Density and Default Carbon Intensity for the fuels.

Fuels might be grouped together based on the Regulation.
e.g. Biodiesel and HDRD both fall under Petroleum-based diesel fuel or renewable fuel in relation to diesel class fuel for Energy Effectiveness Ratio, but for energy density they're separated

Please refer to the checklist below on what we need to dohttps://trello.com/c/pFO1M5OL/1358-credit-calculation-model-changes-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Model Changes |5|](https://trello.com/c/pFO1M5OL/1358-credit-calculation-model-changes-5)
