### ISSUE TITLE
Credit Calculation | View Fuel Classes |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1102]
**Story:**
As a TFRS user, I want to be able to view the different fuel classes so that I can understand how current and future credits will be calculated. 

- This card is to build a table in both the back-end and front-end to track to view the different fuel classes used in the calculation of credits (section 6 of the Act).
- The fuel classes are defined in section 1 of the [Act](http://www.bclaws.ca/EPLibraries/bclaws_new/document/ID/freeside/00_08016_01) and consist of "gasoline class" and "diesel class". 

**Scenario 1:**
GIVEN that I am an IDIR user
AND I am on the Administration tab
WHEN I click on the "Compliance Reporting" sub-tab
THEN I am taken to the Compliance Reporting sub-tab within the Administration tab
AND I can view the Fuel Classes

**Forward looking usage:**

- We will be using/pulling these values when we implement compliance reporting as they are used in the calculation of credits/debits. https://trello.com/c/eqw7vn7Q/897-credit-calculation-view-fuel-classes-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | View Fuel Classes |3|](https://trello.com/c/eqw7vn7Q/897-credit-calculation-view-fuel-classes-3)
