### ISSUE TITLE
System Alerts | Update Energy Densities |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1105]
**Task:**
Create system alert for successfully updating the Energy Densities as an IDIR user

**Messaging:**
"Energy densities saved"https://trello.com/c/VMIYm5TY/1273-system-alerts-update-energy-densities-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System Alerts | Update Energy Densities |1|](https://trello.com/c/VMIYm5TY/1273-system-alerts-update-energy-densities-1)
