### ISSUE TITLE
Confirmation Alerts | Update CI Limits IDIR |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1106]
**Task:**
Create confirmation alert for updating the CI Limits as an IDIR user

**Messaging:**
"Are you sure you want to update the prescribed carbon intensity limits?"https://trello.com/c/xqxP6tqF/1268-confirmation-alerts-update-ci-limits-idir-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confirmation Alerts | Update CI Limits IDIR |1|](https://trello.com/c/xqxP6tqF/1268-confirmation-alerts-update-ci-limits-idir-1)
