### ISSUE TITLE
System Alerts | Update CI Limits |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1107]
**Task:**
Create system alert for successfully updating the CI Limits as an IDIR user

**Messaging:**
"Carbon intensity limits saved"https://trello.com/c/ygv8zHFD/1269-system-alerts-update-ci-limits-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System Alerts | Update CI Limits |1|](https://trello.com/c/ygv8zHFD/1269-system-alerts-update-ci-limits-1)
