### ISSUE TITLE
Confirmation Alerts | Update Energy Densities IDIR |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1108]
**Task:**
Create confirmation alert for updating the Energy Densities as an IDIR user

**Messaging:**
"Are you sure you want to update the energy densities?"https://trello.com/c/Jkr4i9qZ/1272-confirmation-alerts-update-energy-densities-idir-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confirmation Alerts | Update Energy Densities IDIR |1|](https://trello.com/c/Jkr4i9qZ/1272-confirmation-alerts-update-energy-densities-idir-1)
