### ISSUE TITLE
System Alerts | Update Default Carbon Intensities |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1109]
**Task:**
Create system alert for successfully updating the Default Carbon Intensities as an IDIR user

**Messaging:**
"Default carbon intensities saved"https://trello.com/c/aR8qSQ7b/1275-system-alerts-update-default-carbon-intensities-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System Alerts | Update Default Carbon Intensities |1|](https://trello.com/c/aR8qSQ7b/1275-system-alerts-update-default-carbon-intensities-1)

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System Alerts | Update EER values |1|](https://trello.com/c/fLlcik6Z/1271-system-alerts-update-eer-values-1)
