### ISSUE TITLE
System Alerts | Update EER values |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1110]
**Task:**
Create system alert for successfully updating the EER values as an IDIR user

**Messaging:**
"Energy effectiveness ratios saved"https://trello.com/c/fLlcik6Z/1271-system-alerts-update-eer-values-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System Alerts | Update EER values |1|](https://trello.com/c/fLlcik6Z/1271-system-alerts-update-eer-values-1)
