### ISSUE TITLE
Confirmation Alerts | Update Default Carbon Intensities IDIR |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1111]
**Task:**
Create confirmation alert for updating the Default Carbon Intensities as an IDIR user

**Messaging:**
"Are you sure you want to update the default carbon intensities?"https://trello.com/c/rrsN8Du9/1274-confirmation-alerts-update-default-carbon-intensities-idir-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confirmation Alerts | Update Default Carbon Intensities IDIR |1|](https://trello.com/c/rrsN8Du9/1274-confirmation-alerts-update-default-carbon-intensities-idir-1)
