### ISSUE TITLE
Confirmation Alerts | Update EER values IDIR |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1112]
**Task:**
Create confirmation alert for updating the EER values as an IDIR user

**Messaging:**
"Are you sure you want to update the energy effectiveness ratios?"https://trello.com/c/xIZRDgBz/1270-confirmation-alerts-update-eer-values-idir-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confirmation Alerts | Update EER values IDIR |1|](https://trello.com/c/xIZRDgBz/1270-confirmation-alerts-update-eer-values-idir-1)
