### ISSUE TITLE
Credit Calculation | Show current values in the credit calculation tables |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1124]
**Story:**
As an IDIR user, I want to see the current values as they are today in the credit calculation tables

**Location:**

- IDIR user
- Administration tab, Compliance Reporting sub-tab

**Task:**
For the various identified tables, I want TFRS to show me the values that are effective today, even if there are new values that will become effective in the future. 

**Relevant Tables:**
- CI Limits
- Energy Effectiveness Ratio
- Default Carbon Intensities
- Energy Densities
- Fuel Classes https://trello.com/c/Z1mavdQe/1374-credit-calculation-show-current-values-in-the-credit-calculation-tables-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Show current values in the credit calculation tables |5|](https://trello.com/c/Z1mavdQe/1374-credit-calculation-show-current-values-in-the-credit-calculation-tables-5)
