### ISSUE TITLE
Credit Calculation | Update Functionality should not get rid of old values |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1125]
Updating a row for a credit calculation table shouldn't really "forget" the previous value, so instead of updating we really should be adding records instead.

e.g. CNG has a default carbon intensity of 64.65 with an effective for the year of 2017. If the values were supposed to change for 2018, then we want to make sure to keep the value for 2017. So we add a new record for 2018, instead. 

If the user has to make an edit for 2018, then we just add a new record again and when we have to get the value for 2018, we just get the most recent one and accept that as effective value.https://trello.com/c/ovjHPjn1/1382-credit-calculation-update-functionality-should-not-get-rid-of-old-values-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Update Functionality should not get rid of old values |5|](https://trello.com/c/ovjHPjn1/1382-credit-calculation-update-functionality-should-not-get-rid-of-old-values-5)
