### ISSUE TITLE
Credit Calculation | Lowercase labels for renewable fuel in relation within the Default Carbon Intensities table |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1127]
https://trello.com/c/GJaNHRCj/1371-credit-calculation-lowercase-labels-for-renewable-fuel-in-relation-within-the-default-carbon-intensities-table-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Lowercase labels for renewable fuel in relation within the Default Carbon Intensities table |1|](https://trello.com/c/GJaNHRCj/1371-credit-calculation-lowercase-labels-for-renewable-fuel-in-relation-within-the-default-carbon-intensities-table-1)
