### ISSUE TITLE
Fuel Codes | Autopopulate input fields for new fuel code versions |13|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1129]
**Story:**
As an IDIR user, I want TFRS to autopopulate the fuel code input fields for new versions of existing fuel codes so that I can easily and efficiently create a new field code version. 

**Scenario:**
GIVEN that I am an IDIR user
AND I am creating a new version of an existing fuel code (e.g. BCLCF101.1)
AND I have inputted the fuel code into the "Low Carbon Fuel Code" input field on the New Fuel Code page
AND TFRS has autosuggested the next version of that fuel code
WHEN I click on the autosuggested next version of the fuel code (see attached screenshot)
THEN the specified fields are automatically populated with data from the previous version of the fuel code (e.g. when creating BCLCF101.1, the data from BCLCF101.0 is shown)
AND I am able to change this data 

**Specified fields:**
The following fields should autopopulate with data from the previous version of the fuel code:

- Company
- Fuel
- Feedstock
- Feedstock location
- Feedstock Misc
- Fuel Production Facility Location
- Fuel Production Facility Nameplate Capacity
- Feedstock Transport Mode
- Finished Fuel Transport Mode

**Rationale:**
In most cases, when adding a new version of an existing fuel code, the underlying input data does not change. Usually it is only the carbon intensity value and the application date / effective dates that change. Therefore, it would be beneficial to have TFRS autopopulate this data when adding a new version of an existing fuel code. 

**Pop-up modal window:**

- Have TFRS ask the user if they want to autopopulate data from the previous version of the fuel code. Yes or no decision. 
https://trello.com/c/JTrmG5bb/1365-fuel-codes-autopopulate-input-fields-for-new-fuel-code-versions-13

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Codes | Autopopulate input fields for new fuel code versions |13|](https://trello.com/c/JTrmG5bb/1365-fuel-codes-autopopulate-input-fields-for-new-fuel-code-versions-13)
