### ISSUE TITLE
Credit Calculation | Petroleum gas and diesel carbon intensities |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1131]
**Story:**
As a TFRS user, I want to be able to view the carbon intensities for petroleum gasoline and diesel so that I can understand how current and future credits will be calculated. 

- This card is to build a table in both the back-end and front-end to track to view the carbon intensities for petroleum gasoline and diesel set by the Regulation.
- The petroleum CI's can be found in section 11.02 (4) (a) and (b) of the [Regulation](http://www.bclaws.ca/civix/document/id/complete/statreg/394_2008#section11.02). 
- Section 11.02 (4) (a): the carbon intensity for petroleum-based diesel fuel is **94.76** g CO2e/MJ,
- Section 11.02 (4) (b): the carbon intensity for petroleum-based gasoline is **88.14** g CO2e/MJ,

**Scenario 1:**
GIVEN that I am an IDIR user
AND I am on the Administration tab
WHEN I click on the "Compliance Reporting" sub-tab
THEN I am taken to the Compliance Reporting sub-tab within the Administration tab
AND I can view the carbon intensities for petroleum-based gasoline and diesel

**Forward looking usage:**

- We will be using/pulling these values when we implement compliance reporting as they are used in the calculation of credits/debits. https://trello.com/c/cM9Vrb5P/1361-credit-calculation-petroleum-gas-and-diesel-carbon-intensities-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Petroleum gas and diesel carbon intensities |5|](https://trello.com/c/cM9Vrb5P/1361-credit-calculation-petroleum-gas-and-diesel-carbon-intensities-5)
