### ISSUE TITLE
Credit Calculation | Provide an indicator when there is a revised value saved for an effective period in the future |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1140]
**Story:**
As an IDIR user, I want a simple way for TFRS to inform me that there is a revised value for a future effective period that has been saved for a particular credit calculation value. 

**Location:**

- IDIR user
- Administration tab, Compliance Reporting sub-tab

**Task:**
For each entry within the different credit calculation tables, I want TFRS to indicate which values have a revised value that has been saved and will come into effect at a future date. This allows the analyst to quickly and easily understand if upcoming revised values have been entered into TFRS. 

**Relevant Tables:**
- CI Limits
- Energy Effectiveness Ratio
- Default Carbon Intensities
- Energy Densities
- Fuel Classeshttps://trello.com/c/WEknIAi2/1380-credit-calculation-provide-an-indicator-when-there-is-a-revised-value-saved-for-an-effective-period-in-the-future-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Provide an indicator when there is a revised value saved for an effective period in the future |3|](https://trello.com/c/WEknIAi2/1380-credit-calculation-provide-an-indicator-when-there-is-a-revised-value-saved-for-an-effective-period-in-the-future-3)
