### ISSUE TITLE
Compliance Report C | Create Schedule C Fuels used for other purposes |8|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1149]
**Task:**
This card to create the Compliance Reporting sub-tab for Schedule C - Fuels used for other purposes. 

**Sub-tab label:**

- Schedule C

**Sub-tab page heading and information:**

- Sub-tab heading: **Schedule C - Fuels used for other purposes**

Below the heading will be the following information (include bold/italic text markup):

- Under section 6 (3) of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*, Part 3 requirements do not apply in relation to fuel quantities that the Part 3 fuel supplier expects, on reasonable grounds, will be used for a purpose other than transportation. The quantities and expected uses of excluded fuels must be reported in accordance with section 11.08 (4) (d) (ii) of the Regulation.
 
- **The volumes reported here should not be reported in Schedule B. This form will include the quantities entered in this Schedule in the Part 2 Summary section as appropriate.** 

- Report "middle-distillate" spec diesel heating oil as Petroleum-based diesel.

**Schedule C - Fuels used for other purposes**
The following information is required for each fuel used for other purposes (see attached screenshot):

- Fuel Type
- Fuel Class
- Quantity of Fuel Supplied
- Units
- Expected Use

**Potential Design(s):**

- Use a spreadsheet style design like Schedule B - Fuel Supply Records and the current excel-based reporting form (see attached screenshot).
- Ability to copy past (similar to Schedule B) including drop-down menu designs below (is it possible to have a drop-down menu within the spreadsheet-like design?)

**Fuel Type:**

- Drop-down menu
- Options to be selected should be informed from the back-end fuel type table created in [Card 901](https://trello.com/c/NsnndCBP/901-credit-calculation-view-fuel-types-2)

**Fuel Class:**

- Create column for Fuel Class
- [Card 1304](https://trello.com/c/24cv635h/1304-compliance-report-c) covers the functionality of this column. 

**Quantity of Fuel Supplied:**

- Entered as a number 
- Would be beneficial if the number could be formatted to place a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423 (preferably as you type)
- Restrict entry to two decimal places
- Restrict the use of negative values (only positive numbers)

**Units:**

- Create column for Units
- See [Card 1298](https://trello.com/c/7FZbLHH2/1298-compliance-report-c-autopopulate-units-column-based-on-fuel-type-choice-0) for more information about the functionality of this column. 

**Expected Use:**

- Create column for Expected Use
- See [Card 1301](https://trello.com/c/cCaMiWSZ/1301-compliance-report-c-provide-predefined-selections-for-expected-use-column-0) for more information about the functionality of this column. 

**Other Requirements:**

- This schedule must have the ability to enter an endless amount of Fuels used for other purposes. Typically, on a per supplier basis, we see no more than 0-3 entries per year. However, this Schedule needs to be capable of handling more than that, and should be designed in such a way that you can add entries as needed. In other words, you would not see tons of blank entries, but would have the ability to add entries as needed. Perhaps only show 1-5 blank entries.  https://trello.com/c/pjae2lL2/1296-compliance-report-c-create-schedule-c-fuels-used-for-other-purposes-8

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report C | Create Schedule C Fuels used for other purposes |8|](https://trello.com/c/pjae2lL2/1296-compliance-report-c-create-schedule-c-fuels-used-for-other-purposes-8)
