### ISSUE TITLE
Compliance Report C | Provide predefined selections for Expected Use column |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1151]
**Story:**
As a BCeID user, I want the system to provide me with suggestions for the expected use of Fuels used for other purposes so that I can ensure that I am reporting accurately. 

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role [Card 1299](https://trello.com/c/X6pY9KoM/1299-compliance-report-create-compliance-reporting-role)
AND I am filling out Schedule C of the Compliance Report (new report or editing a draft)
AND I am filling out a particular entry row within Schedule C
WHEN I click on the Expected Use cell
THEN a list of predefined options appear
AND I am able to select one of the options

**Options:**
The following is a list of available options for the Expected Use column:

- Heating oil
- Department of National Defence (Canada)
- Aviation
- Otherhttps://trello.com/c/cCaMiWSZ/1301-compliance-report-c-provide-predefined-selections-for-expected-use-column-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report C | Provide predefined selections for Expected Use column |3|](https://trello.com/c/cCaMiWSZ/1301-compliance-report-c-provide-predefined-selections-for-expected-use-column-3)
