### ISSUE TITLE
Compliance Report C | An additional column appears when Other is selected for Expected Use |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1152]
**Story:**
As a BCeID user, I want the system to prompt me to provide the details about Fuels used for other purposes when I select the Other category so that I can ensure that I am fulfilling my reporting obligation. 

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role [Card 1299](https://trello.com/c/X6pY9KoM/1299-compliance-report-create-compliance-reporting-role)
AND I am filling out Schedule C of the Compliance Report (new report or editing a draft)
AND I am filling out a particular entry row within Schedule C
AND I have clicked on the Expected Use cell
AND I can see the list of predefined options [Card 1301](https://trello.com/c/cCaMiWSZ/1301-compliance-report-c-provide-predefined-selections-for-expected-use-column-0)
WHEN I select the Other option
THEN a new input field/cell/column appears to the right of the Expected Use column
AND the system prompts me to "Enter in the expected use"
AND I am able to enter an explanation of the "Other" fuel use within that input field / cell / column

**Potential Design(s):**
Similar to the zero dollar option menu that appears when a user enters a zero credit price (affiliate or other), when the user selects the Other category have an additional entry field appear to the right of the expected use cell that allows the user to enter in the details of the "Other" fuel use. 

**Additional Requirements:**

- This input field should be free text (allow anything)
- The user should be required to enter something into this cell if they have selected the Other category in the Expected Use column

https://trello.com/c/eUq1jomb/1302-compliance-report-c-an-additional-column-appears-when-other-is-selected-for-expected-use-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report C | An additional column appears when Other is selected for Expected Use |2|](https://trello.com/c/eUq1jomb/1302-compliance-report-c-an-additional-column-appears-when-other-is-selected-for-expected-use-2)
