### ISSUE TITLE
Compliance Report C | Show the total fuel excluded for each fuel class |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1154]
**Story:**
As a TFRS user, I want to see the total fuel excluded within each fuel class within Schedule C. 

**Task:**

- Within the Schedule C sub-tab, show the total fuel excluded for each fuel class (gasoline and diesel). This is determined by adding up the volumes entered into the "Quantity of Fuel Supplied" columns, separated by fuel class, which is determined by the Fuel Class column selection for each row entry (gasoline or diesel).
- Where these values are shown on the page should be consistent with the totals shown in the other schedules. For example, Schedule A totals under [Card 1245](https://trello.com/c/vfOiiAxE/1245-compliance-report-a-show-the-total-fuel-received-and-transferred-for-each-fuel-class-0). https://trello.com/c/OdveyJjN/1303-compliance-report-c-show-the-total-fuel-excluded-for-each-fuel-class-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report C | Show the total fuel excluded for each fuel class |2|](https://trello.com/c/OdveyJjN/1303-compliance-report-c-show-the-total-fuel-excluded-for-each-fuel-class-2)
