### ISSUE TITLE
Compliance Report | Introduction Page |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1156]
**Task:**
This card is to create the first sub-tab of the Compliance Report, titled "Introduction". Attached is a screenshot of the Introduction page in the current excel-based reporting form; most (but not all) of the information contained on this form will need to be incorporated into the TFRS Compliance Reporting form. The content section below describes the info we need to include in the TFRS Compliance form. 

**Content:**
Sub-tab heading should be "**Compliance Report for YYYY**"

Under the heading, include the following paragraphs of text (ensure adequate spacing between "paragraphs"): 

- It is the responsibility of anyone who manufactures or imports fuel to determine whether their activities qualify them as a Part 2 (Renewable) and/or Part 3 (Low Carbon) fuel supplier under the Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act (available online at www.bclaws.ca). 
- All Part 2 and Part 3 fuel suppliers must report using this form unless they claim the Small Supplier Exemption (see below).  The YYYY compliance period for Part 2 and Part 3 requirements is from January 1 to December 31, YYYY.  Compliance reports for YYYY are due March 31, YYYY+1.
- The compliance report must be submitted by an officer or employee authorized by the fuel supplier, and records evidencing each matter reported under the Renewable and Low Carbon Fuel Requirements Regulation (Regulation) must be available for inspection upon request.  These records must be retained for a period of seven years after the compliance period to which they refer.
- Payment of penalties must be sent to the Ministry of Energy, Mines and Petroleum Resources at the same time as this report is submitted.
- Cheques or money orders are to be made payable to the Minister of Finance.

A new heading follows, titled "**Small Fuel Supplier Exemption**". This heading uses a smaller font size compared to the main "Compliance Report for YYYY" heading. 

- Fuel suppliers and their affiliates who supplied less than a total of 75 million litres of gasoline and diesel class fuels (combined) in the YYYY compliance period may apply to be exempted from Part 2 and/or Part 3 requirements.  A Part 2 or Part 3 fuel supplier who applies to be exempted must submit an Exemption Report, available from [www.gov.bc.ca/lowcarbonfuels](www.gov.bc.ca/lowcarbonfuels). A Part 3 fuel supplier who does not supply any Part 2 fuels may not be exempted.
- For more information, see Information Bulletin RLCF-005 Exemption Reports; available from [www.gov.bc.ca/lowcarbonfuels](www.gov.bc.ca/lowcarbonfuels).

A new heading follows, titled "**About this form**". This heading uses the same smaller font size as the small fuel supplier exemption heading. 

- The Declaration & Summary section of this Compliance Report compiles information from the other schedules of this report. This is the last section users should complete.

A new heading follows, titled "**Questions?**". This heading uses the same smaller font size as the small fuel supplier exemption heading. 

- Please contact lcfrr@gov.bc.ca with any questions you may have about this form. 

**Determining compliance period: "YYYY"**

- TBD; the user will need to be able to choose which compliance period their submission relates. 
- Potential options for handling this: When clicking on the New Compliance button, have a drop-down menu (similar to New SFS) show a list of the  compliance periods. The user must then select the compliance period in which the report relates. Once selected, the user is taken to the New Compliance Report page with all "YYYY" references above showing the selected year. 

**Additional Requirements:**

- Hyperlink references to www.gov.bc.ca/lowcarbonfuels. Have the hyperlink open a new window when clicked so as not to disrupt a users session within TFRS. https://trello.com/c/z85i6Ycj/1241-compliance-report-introduction-page-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Introduction Page |2|](https://trello.com/c/z85i6Ycj/1241-compliance-report-introduction-page-2)
