### ISSUE TITLE
Compliance Report | Create new Compliance Report |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1157]
**Story:**
As a BCeID user, I want to be able to create a new Compliance Report for submission to government so that I can meet my obligations under the Regulation. 

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role
AND I am on the Compliance Reporting page
WHEN I click on the New Compliance Report button
THEN a drop-down menu appears with a list of the compliance periods
AND I am able to select a compliance period from that list
AND selecting a compliance period takes me to the New Compliance Reporting page
AND I am taken to the Introduction sub-tab, see [Card 1241](https://trello.com/c/z85i6Ycj/1241-compliance-report-introduction-page-0)

**New Compliance Report button:**

- Click on the button to start a new compliance period for this year (the compliance period we are in today)
- Drop-down menu on the right-hand side of the button to select previous compliance reporting years (2013-14 to 2018)
- Do not show future compliance periodshttps://trello.com/c/4pZecUMx/1230-compliance-report-create-new-compliance-report-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Create new Compliance Report |3|](https://trello.com/c/4pZecUMx/1230-compliance-report-create-new-compliance-report-3)

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | View Compliance Reporting Materials |5|](https://trello.com/c/swV6FKKK/1228-compliance-report-view-compliance-reporting-materials-5)
