### ISSUE TITLE
Compliance Report | View Compliance Reporting Materials |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1158]
**Story:**
As a TFRS user, I want to view my compliance reporting materials in TFRS so that I can easily see the status of my compliance reporting submission. 

**Scenario 1:**
GIVEN that I am a BCeID user
AND I have been assigned the Compliance Reporting role
WHEN I click on "Compliance Reporting" on the main nav bar within TFRS
THEN I am taken to the Compliance Reporting page
AND I can view my compliance reporting submission history in a table
AND I only see the compliance reports that are associated with my organization

**Scenario 2:**
GIVEN that I am an IDIR user
WHEN I click on "Compliance Reporting" on the main nav bar within TFRS
THEN I am taken to the Compliance Reporting page
AND I can view the compliance reporting submission history in a table
AND this history includes all organizations

**Columns to include in table:**

- **Compliance Period** - the compliance period to which the submission relates
- [IDIR only] **Organization** - the organization that submitted the compliance reporting material
- **Type** - the type of compliance reporting material (e.g. Compliance Report or Exclusion Report)
- **Status** - the status of the compliance reporting submission
- **Submission date** - the date that the compliance reporting material was submitted to governmenthttps://trello.com/c/swV6FKKK/1228-compliance-report-view-compliance-reporting-materials-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | View Compliance Reporting Materials |5|](https://trello.com/c/swV6FKKK/1228-compliance-report-view-compliance-reporting-materials-5)

**Comment by KMenke** [comment]
Resolved in sprint Omicron.
