### ISSUE TITLE
User Management | Adding fuel supplier user shows all roles including government roles |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1162]
- IDIR user, Admin role
- Fuel Suppliers nav link, then choose specific fuel supplier org, then click on new user 

All roles are shown, including government roles; since this is a fuel supplier user, we should only show fuel supplier roleshttps://trello.com/c/OQjd2mVN/1436-user-management-adding-fuel-supplier-user-shows-all-roles-including-government-roles-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Management | Adding fuel supplier user shows all roles including government roles |1|](https://trello.com/c/OQjd2mVN/1436-user-management-adding-fuel-supplier-user-shows-all-roles-including-government-roles-1)
