### ISSUE TITLE
Confirmation Alerts | Delete a Saved Draft Compliance Report |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1164]
**Task:**
Create confirmation alert for deleting a Saved Draft Compliance Report

**Messaging:**
"Are you sure you want to delete the draft Compliance Report?"https://trello.com/c/2jZsXb3M/1277-confirmation-alerts-delete-a-saved-draft-compliance-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confirmation Alerts | Delete a Saved Draft Compliance Report |1|](https://trello.com/c/2jZsXb3M/1277-confirmation-alerts-delete-a-saved-draft-compliance-report-1)

**Comment by KMenke** [comment]
Resolved in Sprint Pluto.
