### ISSUE TITLE
System Alerts | Delete a Saved Draft Compliance Report |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1165]
**Task:**
Create system alert for successfully Deleting a Saved Draft Compliance Report

**Messaging:**
"Draft deleted"https://trello.com/c/qralI1gJ/1276-system-alerts-delete-a-saved-draft-compliance-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System Alerts | Delete a Saved Draft Compliance Report |1|](https://trello.com/c/qralI1gJ/1276-system-alerts-delete-a-saved-draft-compliance-report-1)

**Comment by KMenke** [comment]
Resolved in Sprint Pluto.
