### ISSUE TITLE
Fuel Codes | Provide analyst with a warning when effective dates of fuel codes within the same version overlap |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1167]
**Story:**
As an IDIR user, I want the system to provide a warning when the effective period / dates of different versions of a fuel code overlap so that I am reminded to adjust the effective dates as required.  

**Example:**
When BCLCF100.0 and BCLCF100.1 have overlapping effective dates, have a warning appear. Note that this only applies to different versions of the same fuel code (e.g. 101.0, 101.1, 101.2, etc.); there should never be two versions of the same fuel code "active" at the same time. 

**Potential Design(s):**
Presumably, an overlap would only occur when an IDIR user is adding or updating a particular fuel code / fuel code version. Therefore, potential designs include:

- Have the warning appear in the confirmation alert, specifying which fuel code versions are overlapping (see attached screenshot for design example), and 
- Highlight the overlapping fuel code versions in red within the view fuel codes table (similar to when a security scan fails in the SFS feature)

**Confirmation Alert message:**

- Warning! The effective dates of this fuel code overlap with BCLCFXXX.X. Please adjust the effective dates of the code(s) to ensure that there is no overlap.  https://trello.com/c/aOZO3pyn/1343-fuel-codes-provide-analyst-with-a-warning-when-effective-dates-of-fuel-codes-within-the-same-version-overlap-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Codes | Provide analyst with a warning when effective dates of fuel codes within the same version overlap |3|](https://trello.com/c/aOZO3pyn/1343-fuel-codes-provide-analyst-with-a-warning-when-effective-dates-of-fuel-codes-within-the-same-version-overlap-3)
