### ISSUE TITLE
Credit Calculation | Add space between heading and sub tabs on details pages |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1169]
**Location:**

- IDIR user, Admin nav link, Compliance Reporting sub-tab
- Access Details page by clicking on any entry row within one of the credit calculation tables

**Task:**

- Add space between the sub-tab menu (Current, Past and Future) and the heading for the page (see attached screenshot)https://trello.com/c/plIlSyfw/1437-credit-calculation-add-space-between-heading-and-sub-tabs-on-details-pages-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Add space between heading and sub tabs on details pages |1|](https://trello.com/c/plIlSyfw/1437-credit-calculation-add-space-between-heading-and-sub-tabs-on-details-pages-1)
