### ISSUE TITLE
Credit Trading

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#117]
CreditTrade | Update the backend code such that when a Trade is approved it is marked as completed and the trade is executed |2| !

https://trello.com/c/lmNNUp5v

**Comment by dainetrinidad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CreditTrade | Update the backend code such that when a Trade is approved it is marked as completed and the trade is executed |2| !](https://trello.com/c/lmNNUp5v/231-credittrade-update-the-backend-code-such-that-when-a-trade-is-approved-it-is-marked-as-completed-and-the-trade-is-executed-2)

**Comment by kuanfandevops** [comment]
historical data entry does this.
