### ISSUE TITLE
Compliance Report A | Create Notional Transfer Sub-tab |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1177]
**Task:**
This card to create the Compliance Reporting sub-tab for Schedule A - Notional Transfers of Renewable Fuel. 

**Sub-tab label:**

- Schedule A

**Sub-tab page heading and information:**

- Sub-tab heading: **Schedule A - Notional Transfers of Renewable Fuel**

Below the heading will be the following information:

- Under section 5.1 of the Act, a fuel supplier may transfer renewable fuel supplied in excess of the required volume for that fuel class. Fuel suppliers may also receive the excess renewable content supplied by another fuel supplier and apply that volume of renewable fuel to meet their own renewable requirement. 
- For each fuel supplier that you notionally transferred fuel to, or notionally received fuel from, you must report the fuel supplier name, address, contact information and the total volumes notionally transferred to, and/or received from that supplier.  Volumes “transferred to” are those volumes notionally transferred by you to another supplier listed in the Schedule.  Volumes “received from” are those volumes notionally received by you from another supplier listed in the Schedule. 

**Schedule A - Notional Transfers**
The following information is required for each notional transfer reported:

- Legal Name of Trading Partner
- Postal Address
- Fuel Class
- Received or Transferred
- Quantity (L)

**Potential Design(s):**

- Use a spreadsheet style design like Schedule B - Fuel Supply Records and the current excel-based reporting form (see attached screenshot).
- Ability to copy past (similar to Schedule B) including drop-down menu designs below (is it possible to have a drop-down menu within the spreadsheet-like design?)
- Other potential design(s)? This schedule doesn't necessarily need to be in an excel-based format. Although this information does feed into the Summary and Declaration page, we are not bound to an excel-based format in the UI (as we are with Schedule B, at the request of our users). However, whatever design is chosen, consistency across schedules should be a consideration (but not necessarily a requirement or THE deciding factor). 

**Legal Name of Trading Partner & Postal Address**

- Free form text with auto-complete/suggestion capabilities (see [Card 1265](https://trello.com/c/B6oNF6fn/1265-compliance-report-a-implement-autocomplete-autosuggestion-for-certain-fields-0))

**Fuel Class:**

- Currently, we only have two fuel classes: Gasoline or Diesel
- Provide the user with the ability to select the fuel class (drop-down menu?)
- Options to be selected should be drawn from the back-end fuel class table created in [Card 897](https://trello.com/c/eqw7vn7Q/897-credit-calculation-view-fuel-classes-0)

**Received or Transferred:**

- Provide the user with the ability to select whether the notional transfer was received or transferred (perhaps a drop-down menu?)

**Quantity (L):**

- Entered as a number 
- Would be beneficial if the number could be formatted to place a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423 (preferably as you type).
- Restrict entry to two decimal places
- Restrict the use of negative values (only positive numbers)

**Other Requirements:**

- Must have the ability to enter an endless amount of Notional Transfers. Typically, on a per supplier basis, we see no more than 0-5 transfers per year. However, this Schedule needs to be capable of handling more than that. There is no actual limit to the amount of notional transfers a fuel supplier can execute. The Schedule should be designed in such a way that you can add entries as needed. In other words, you would not see tons of blank entries, but would have the ability to add entries as needed. Perhaps only show 1-5 blank entries.  https://trello.com/c/ppJ1Txbe/1243-compliance-report-a-create-notional-transfer-sub-tab-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report A | Create Notional Transfer Sub-tab |5|](https://trello.com/c/ppJ1Txbe/1243-compliance-report-a-create-notional-transfer-sub-tab-5)
