### ISSUE TITLE
Compliance Report A | Show the total fuel received and transferred for each fuel class |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1178]
**Story:**
As a TFRS user, I want to see the total fuel I received and transferred within each fuel class within Schedule A. 

**Task:**

- Within the Schedule A sub-tab, show the total fuel received and transferred for each fuel class (gasoline and diesel)
- Show the net total for each fuel class (Gasoline and Diesel). The net total is Received minus Transferred. https://trello.com/c/vfOiiAxE/1245-compliance-report-a-show-the-total-fuel-received-and-transferred-for-each-fuel-class-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report A | Show the total fuel received and transferred for each fuel class |2|](https://trello.com/c/vfOiiAxE/1245-compliance-report-a-show-the-total-fuel-received-and-transferred-for-each-fuel-class-2)
