### ISSUE TITLE
Compliance Report A | Implement autocomplete autosuggestion for certain fields |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1179]
**Auto-complete/suggestion:**

- Similar to the new fuel code form, have the Legal Name of Trading Partner field auto suggest organizations. The suggested organizations would draw from the list of Part 3 fuel supplier organizations in TFRS. 
- A user must still be permitted to enter in their own legal name of trading partner if they wish. 
- If one of the suggested organizations is selected, autopopulate the postal address with the address information stored in TFRS. For each Part 3 fuel supplier in TFRS, there is an associated postal address. 
- A user must still be permitted to override the autopopulated postal address and enter their own address. https://trello.com/c/B6oNF6fn/1265-compliance-report-a-implement-autocomplete-autosuggestion-for-certain-fields-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report A | Implement autocomplete autosuggestion for certain fields |3|](https://trello.com/c/B6oNF6fn/1265-compliance-report-a-implement-autocomplete-autosuggestion-for-certain-fields-3)
