### ISSUE TITLE
Credit Trade screen to be built based on wireframe and including history

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#118]
Credit Transfer | Credit Trade screen to be built based on wireframe and including history |3| [v0.0.3-alpha]

https://trello.com/c/1XtO2C6o

**Comment by dainetrinidad** [comment]
https://trello.com/c/1XtO2C6o

**Comment by kuanfandevops** [comment]
The issue was create for experimental use. We start to actively use the issues and milestones. Close this issue for now and reopen it if needed.
