### ISSUE TITLE
Compliance Report B | Provision of the Act Column |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1183]
**Task:**
This card is to create the functionality needed for the "Provision of the Act relied upon to determine carbon intensity" column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Provision of the Act relied upon to determine carbon intensity:**

- Design: drop-down menu
- The options presented to the user in the drop-down menu are dependent on the Fuel Type selected

**Provisions of the Act:**
The determination methods can be found in [Information Bulletin RLCF-006 - Carbon Intensity Records](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/electricity-alternative-energy/transportation/renewable-low-carbon-fuels/rlcf006_-_carbon_intensity_records.pdf):

- section 6 (5) (a) - prescribed carbon intensity
- section 6 (5) (b) - prescribed carbon intensity
- section 6 (5) (c) - approved fuel code
- section 6 (5) (d) (i) - default carbon intensity value
- section 6 (5) (d) (ii) (A) - GHGenius modelled
- section 6 (5) (d) (ii) (B) - Alternative method

**Provisions of the Act by Fuel Type:**
The attached word doc "Provisions of the Act by Fuel Type.docx" explains which provisions can apply to each selected fuel type. Only the applicable provisions should appear as options in this column when a fuel type has been selected. https://trello.com/c/cVAGCBK7/1388-compliance-report-b-provision-of-the-act-column-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Provision of the Act Column |5|](https://trello.com/c/cVAGCBK7/1388-compliance-report-b-provision-of-the-act-column-5)
