### ISSUE TITLE
Compliance Report B | Fuel Class Column |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1184]
**Task:**
This card is to create the functionality needed for the Fuel Class column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Fuel Class:**

- Design: drop-down menu
- The options (gasoline or diesel class) presented to the user in the drop-down menu should be dependent on the Fuel Type selected
- Options available for each Fuel Type should be informed from the back-end fuel class table created in **[Card 897](https://trello.com/c/eqw7vn7Q/897-credit-calculation-view-fuel-classes-3-v134)**.
https://trello.com/c/R7jfIqvN/1387-compliance-report-b-fuel-class-column-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Fuel Class Column |1|](https://trello.com/c/R7jfIqvN/1387-compliance-report-b-fuel-class-column-1)
