### ISSUE TITLE
Compliance Report B | Fuel Type Column |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1185]
**Task:**
This card is to create the functionality needed for the Fuel Type column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Fuel Type:**

- Drop-down menu
- Options to be selected should be informed from the back-end fuel type table created in **[Card 901](https://trello.com/c/NsnndCBP/901-credit-calculation-view-fuel-types-2)**.
https://trello.com/c/FDEOFeBO/1386-compliance-report-b-fuel-type-column-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Fuel Type Column |1|](https://trello.com/c/FDEOFeBO/1386-compliance-report-b-fuel-type-column-1)
