### ISSUE TITLE
Compliance Report B | Fuel Code Column |8|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1189]
**Task:**
This card is to create the functionality needed for the Fuel Code (if applicable) column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Fuel Code Column Design:**

- Drop-down menu

**Description:**
This column presents fuel codes (e.g. BCLCF100.0, BCLCF251.2, etc.) depending on the fuel type selected, the provision of the Act selected, and the effective periods of the different fuel codes (see below for more information). 

**Fuel Code Options Presented:**
The options presented to the user in this drop-down menu are dependent on three factors: 

- For this column to even be selectable (i.e. applicable), the user must first choose "section 6 (5) (c) - approved fuel code" under the Provision of the Act column. If any other provision is chosen, this column should not be selectable. The provision column was created in **[Card 1388](https://trello.com/c/cVAGCBK7/1388-compliance-report-b-provision-of-the-act-column-0)**.
- The fuel selected in the Fuel Type column, which was created in **[Card 1386](https://trello.com/c/FDEOFeBO/1386-compliance-report-b-fuel-type-column-0)** (more info below).
- The effective periods of the different fuel codes. Only fuel codes that are active (or effective) during the compliance period in which the compliance report relates should be presented as options for the user to select (more info below). 

**Fuel Type Selection:**
This column should only show fuel codes that are for the Fuel Type selected. For example, if the user has selected Ethanol then the fuel codes presented as options should only be those that are for ethanol (have a fuel type of ethanol within the fuel code database). 

**Fuel Codes and Effective Periods:**
In addition, this column should only show fuel codes that are active (or effective) during the compliance period to which the compliance report relates. To qualify, the fuel code would need to be active (or have an effective period) that includes at least one day in the compliance period to which the compliance report relates. Using the ethanol example above, the ethanol fuel codes presented as options in this column should have effective periods that overlap or include the compliance period in which the report relates. If the compliance report is for 2019, then the user should be presented with all ethanol codes that have an effective period that includes at least one day within the 2019 compliance period (January 1 to December 31, 2019). Fuel Codes that have effective periods outside the 2019 compliance period should not be presented as options (should not appear in the drop-down menu). 

**Formatting for Fuel Codes Presented:**
Fuel codes meeting the above criteria should be shown:

- In the proper format; example: "**BCLCF100.0**" or "**BCLCF251.2**"
- Organized in ascending order, similar to how we organize fuel codes within the view fuel code table, which accounts for proper sorting by decimal version; see **[Card 1320](https://trello.com/c/Uddr72G2/1320-fuel-codes-adjustment-to-sorting-the-low-carbon-fuel-code-column-ascending-descending-1)** for more information. 
https://trello.com/c/HDfhl93f/1389-compliance-report-b-fuel-code-column-8

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Fuel Code Column |8|](https://trello.com/c/HDfhl93f/1389-compliance-report-b-fuel-code-column-8)
