### ISSUE TITLE
Credit Calculation | Adjust confirmation alert labels for credit calculations |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1190]
**Location:**

- IDIR user
- Administration section, Compliance Reporting sub-tab, Credit Calculation tables

**Energy Effectiveness Ratio table**

- When editing or adding a future EER ratio, the confirmation alert message includes two question marks and refers to plural "ratios" when in some cases there is only one ratio for that fuel type.
- Revised message: "Are you sure you want to update the energy effectiveness ratio(s)?"

**Default Carbon Intensities table**

- When editing or adding a future default carbon intensity, the confirmation alert message refers to plural "default carbon intensities" when the user is only able to update a single value at a time.
- Revised message: "Are you sure you want to update the default carbon intensity?"

**Energy Densities table**

- When editing or adding a energy density value, the confirmation alert message refers to plural "energy densities" when the user is only able to update a single value at a time.
- Revised message: "Are you sure you want to update the energy density?"https://trello.com/c/svXjAuGl/1464-credit-calculation-adjust-confirmation-alert-labels-for-credit-calculations-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Adjust confirmation alert labels for credit calculations |1|](https://trello.com/c/svXjAuGl/1464-credit-calculation-adjust-confirmation-alert-labels-for-credit-calculations-1)
