### ISSUE TITLE
Credit Calculation | Information indicator for the CI Limits Default CIs and Petroleum CIs tables mistakenly refers to revised values as energy densities |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1191]
**Location:**

- IDIR user
- Administration section, Compliance Reporting sub-tab, Credit Calculation tables

**Issue:**
The text within the modal window that appears when hovering your mouse over the information icon indicator is mis-labelled for the **Carbon Intensity Limits, the Default Carbon Intensities, and the Petroleum-based Carbon Intensities tables.** The label mistakenly refers to the revised values as being a "Revised Energy Density" rather than a "Revised Carbon Intensity Limit" for example. See attached screenshot for an example. 

**Solution:**
Adjust the modal window labels to refer to the correct credit calculation tables in which the values are a parthttps://trello.com/c/7JZRMbqT/1463-credit-calculation-information-indicator-for-the-ci-limits-default-cis-and-petroleum-cis-tables-mistakenly-refers-to-revised-val

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Information indicator for the CI Limits Default CIs and Petroleum CIs tables mistakenly refers to revised values as energy densities |0|](https://trello.com/c/7JZRMbqT/1463-credit-calculation-information-indicator-for-the-ci-limits-default-cis-and-petroleum-cis-tables-mistakenly-refers-to-revised-val)
