### ISSUE TITLE
Fuel Codes | Auto populate data for next fuel code version not functioning periodically |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1194]
**Description of Issue:**
When entering the next version of an existing fuel code, TFRS asks the user if they want to pre-populate the fuel code input fields within the new fuel code web form. When the user clicks yes, the fuel code data does not populate the form on occasion. Note that sometimes the autopopulate feature functions as intended, other times it fails to populate any data from the previous fuel code version. 

**Possible Cause:**

The autosave functionality that has been implemented within the fuel code feature may be causing this issue. We should "turn off" the autosave functionality for the fuel codes to determine if it is in fact the cause. https://trello.com/c/XQm6Dpch/1462-fuel-codes-auto-populate-data-for-next-fuel-code-version-not-functioning-periodically-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Codes | Auto populate data for next fuel code version not functioning periodically |1|](https://trello.com/c/XQm6Dpch/1462-fuel-codes-auto-populate-data-for-next-fuel-code-version-not-functioning-periodically-1)
