### ISSUE TITLE
Credit Calculation | Editing or updating an EER value does not save for fuels with only one fuel class |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1195]
**Location:**

- IDIR user
- Administration section, Compliance Reporting sub-tab, Energy Effectiveness Ratio table

**Issue:**
TFRS is not saving a new/edited/updated EER value for the affected fuels (see below). When a user edits the EER value, including putting in a new effective period, after saving and confirming the change within the confirmation alert, the value does not update. 

**Affected Fuels:**
This issue only affects those fuels with an EER value for a single fuel class (either gasoline **or** diesel), including LNG, Petroleum-based diesel..., and Petroleum-based gasoline. https://trello.com/c/DKxoKHeb/1465-credit-calculation-editing-or-updating-an-eer-value-does-not-save-for-fuels-with-only-one-fuel-class-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Calculation | Editing or updating an EER value does not save for fuels with only one fuel class |1|](https://trello.com/c/DKxoKHeb/1465-credit-calculation-editing-or-updating-an-eer-value-does-not-save-for-fuels-with-only-one-fuel-class-1)
