### ISSUE TITLE
Compliance Report B | Units Column |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1198]
**Task:**
This card is to create the functionality needed for the Units column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Non-editable:**
The fuel supplier user should not be able to edit this column

**Units:**
This column should be auto-populated based on the fuel selected within the Fuel Type column, created in **[Card 1386](https://trello.com/c/FDEOFeBO/1386-compliance-report-b-fuel-type-column-0)**.

**Units for the different fuel types:**

- Show '**L**': Ethanol, Biodiesel, HDRD, Petroleum-based gasoline, Petroleum-based diesel, Propane, Renewable diesel, Natural gas-based gasoline, Renewable gasoline
- Show '**kg**': Hydrogen, LNG
- Show '**kWh**': Electricity
- Show '**m3**' (the 3 should be superscript as m3 is cubic metres) for: CNG

**Schedule C:**

- Schedule C has a units column with identical functionality, see **[Card 1298](https://trello.com/c/7FZbLHH2/1298-compliance-report-c-autopopulate-units-column-based-on-fuel-type-choice-0)** for more information about the functionality of this column. 

https://trello.com/c/dtVAUz7K/1391-compliance-report-b-units-column-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Units Column |1|](https://trello.com/c/dtVAUz7K/1391-compliance-report-b-units-column-1)
