### ISSUE TITLE
Compliance Report | Auto populate fuel class when there is only one option based on fuel type selected |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1202]
**Story:**
As a BCeID user, I want the fuel class cell/column to autopopulate the appropriate fuel class based on the fuel type I have selected when there is only one fuel class applicable to that fuel type. 

**Information:**
There is only one applicable fuel class (gasoline or diesel) for a number of transportation fuels. When a user reports the supply of these fuels by selecting them as the Fuel Type, TFRS should autopopulate the applicable fuel class within the Fuel Class column. Since there is only one possible fuel class for these fuel types, it would be beneficial to have TFRS populate the fuel class rather than making the user select only available fuel class from the drop-down menu within the Fuel Class column/cell

**Applicable Compliance Reporting Schedules:**
This functionality should be applied to the Fuel Class column within Schedule B and Schedule C of the compliance report. 

**Affected Fuels:**
The following fuels have only one potential fuel class:

- Diesel class: Biodiesel, HDRD, LNG, Petroleum-based diesel, Renewable diesel
- Gasoline class: Ethanol, Natural gas-based gasoline, Petroleum-based gasoline, Renewable gasoline
https://trello.com/c/ze3xhy8k/1461-compliance-report-auto-populate-fuel-class-when-there-is-only-one-option-based-on-fuel-type-selected-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Auto populate fuel class when there is only one option based on fuel type selected |1|](https://trello.com/c/ze3xhy8k/1461-compliance-report-auto-populate-fuel-class-when-there-is-only-one-option-based-on-fuel-type-selected-1)

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Clicking on the new compliance report button shows the compliance year drop down menu |1|](https://trello.com/c/wK0ee5CQ/1445-compliance-report-clicking-on-the-new-compliance-report-button-shows-the-compliance-year-drop-down-menu-1)
