### ISSUE TITLE
Compliance Report | Clicking on the new compliance report button shows the compliance year drop down menu |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1203]
**Location:**

- "Compliance Reporting" Nav bar, "New Compliance Report" button

**Task:**
When a user clicks on the "New Compliance Report" button, have the drop-down menu appear showing the compliance periods that are available for the user to select (see attached screenshot). 

**Rationale:**
There is an overlap between when a new compliance period begins (January 1) and when the previous compliance period's compliance report must be submitted (March 31). During this overlap, there is potential for the user to select the wrong compliance period when creating a new compliance report. Users have informed us that most start filling out the compliance report after the compliance period is complete (January 1 to March 31); at the same time, we want to have the next compliance period's compliance report become available on January 1 (the start of the new compliance period). To avoid potential errors in filling out the wrong compliance report, TFRS should prompt the user to select the compliance period when creating a new compliance report (i.e. there should be no default year selected by TFRS when creating a new compliance report). https://trello.com/c/wK0ee5CQ/1445-compliance-report-clicking-on-the-new-compliance-report-button-shows-the-compliance-year-drop-down-menu-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Clicking on the new compliance report button shows the compliance year drop down menu |1|](https://trello.com/c/wK0ee5CQ/1445-compliance-report-clicking-on-the-new-compliance-report-button-shows-the-compliance-year-drop-down-menu-1)
