### ISSUE TITLE
Compliance Report B | Quantity of Fuel Supplied Column |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1204]
**Task:**
This card is to create the functionality needed for the Quantity of Fuel Supplied column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Quantity of Fuel Supplied:**

- Entered as a positive, whole number (no decimals, no negative values)
- Would be beneficial if the number could be formatted to place a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423 (preferably as you type)https://trello.com/c/ubTzBBp0/1390-compliance-report-b-quantity-of-fuel-supplied-column-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Quantity of Fuel Supplied Column |1|](https://trello.com/c/ubTzBBp0/1390-compliance-report-b-quantity-of-fuel-supplied-column-1)
