### ISSUE TITLE
Compliance Report B | Carbon Intensity Limit Column |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1205]
**Task:**
This card is to create the functionality needed for the Carbon Intensity Limit column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Non-editable:**
The fuel supplier user should not be able to edit this column.

**Carbon Intensity Limit (gCO2e/MJ):**

- This column will draw the value from the Carbon Intensity Limits table, created in **[Card 888](https://trello.com/c/mfCiH2IR/888-credit-calculation-view-ci-limits-5-v133)**. 
- This column should be auto-populated based on the fuel class selected within the Fuel Class column, created in **[Card 1387](https://trello.com/c/R7jfIqvN/1387-compliance-report-b-fuel-class-column-0)**.
- **Note:** the '2' in gCO2e/MJ should be subscript; Trello does not support this type of markup so I am unable to show the proper formatting here.

**Dependencies:**
The value populated in this column is dependent on two factors:

- What fuel class the user selects (gasoline or diesel) in the Fuel Class column (**[Card 1387](https://trello.com/c/R7jfIqvN/1387-compliance-report-b-fuel-class-column-0)**); and
- The compliance year in which the compliance report relates. 
- Effective date of carbon intensity limit value in the credit calculation table

**Compliance Year:**

- The Carbon Intensity Limits table, created in **[Card 888](https://trello.com/c/mfCiH2IR/888-credit-calculation-view-ci-limits-5-v133)**, contains the different carbon intensity limits for each compliance period/year and corresponding fuel class (gasoline or diesel). In autopopulating this column, TFRS will need to cross-check the year in which the compliance report relates to ensure that the correct value is used from the CI limits table. It will need to also ensure that it is pulling the CI Limit value that is/was effective during that compliance year (since the branch can update these values over time). 
- Recall that fuel suppliers can submit revised (supplemental) compliance reports for past years at any given time. Thus, TFRS will need to check which compliance period the compliance report relates to in determining the correct value to use / show in this cell/column. Supplemental reporting will be handled in future Trello cards. 
https://trello.com/c/WzzZMJi4/1392-compliance-report-b-carbon-intensity-limit-column-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Carbon Intensity Limit Column |5|](https://trello.com/c/WzzZMJi4/1392-compliance-report-b-carbon-intensity-limit-column-5)
