### ISSUE TITLE
Compliance Report B | Carbon Intensity of the Fuel Column |8|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1206]
**Task:**
This card is to create the functionality needed for the Carbon Intensity of the Fuel column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Non-editable:**
The fuel supplier user should not be able to edit this column.

**Carbon Intensity of the Fuel (gCO2e/MJ):**

This column/cell will display the carbon intensity of the fuel being reported, as determined by:

- The fuel type selected, see **[Card 1386](https://trello.com/c/FDEOFeBO/1386-compliance-report-b-fuel-type-column-0)**; 
- The provision of the Act relied upon to determine carbon intensity, see **[Card 1388](https://trello.com/c/cVAGCBK7/1388-compliance-report-b-provision-of-the-act-column-0)**; and
- The specific fuel code selected (if applicable), see **[Card 1389](https://trello.com/c/HDfhl93f/1389-compliance-report-b-fuel-code-column-0)**. 

**Provision of the Act relied upon to determine carbon intensity:**
The value populated in this column is dependent on the provision of the Act relied upon to determine carbon intensity (**[Card 1388](https://trello.com/c/cVAGCBK7/1388-compliance-report-b-provision-of-the-act-column-0)**):

- If "section 6 (5) (a) - prescribed carbon intensity" is selected, then show the carbon intensity for petroleum-based gasoline from the table created in **[Card 1361](https://trello.com/c/cM9Vrb5P/1361-credit-calculation-petroleum-gas-and-diesel-carbon-intensities-5)**
- If "section 6 (5) (b) - prescribed carbon intensity" is selected, then show the carbon intensity of petroleum-based diesel from the table created in **[Card 1361](https://trello.com/c/cM9Vrb5P/1361-credit-calculation-petroleum-gas-and-diesel-carbon-intensities-5)**
- If "section 6 (5) (c) - approved fuel code" is selected, **and** a specific fuel code has also been selected (**[Card 1389](https://trello.com/c/HDfhl93f/1389-compliance-report-b-fuel-code-column-0)**), then show the carbon intensity associated with that fuel code
- If "section 6 (5) (d) (i) - default carbon intensity value" is selected, then show the default carbon intensity for that fuel type, informed from the back-end table created in **[Card 895](https://trello.com/c/FCwfPTOt/895-credit-calculation-view-default-carbon-intensities-5-v133)**. 
- The functionality if the other two possible provisions are selected ("section 6 (5) (d) (ii) (A) - GHGenius modelled" and "section 6 (5) (d) (ii) (B) - Alternative method") are handled in different Trello cards (**[Card 1349](https://trello.com/c/MfX19Bob/1349-compliance-report-b-provide-a-drop-down-menu-of-schedule-d-carbon-intensities-when-the-ghgenius-determination-method-is-selected)** and **[Card 1408](https://trello.com/c/uMeIPgvE/1408-compliance-report-b-carbon-intensity-of-fuel-when-relying-on-the-alternative-method-provision-0)**)

**Additional UI requirements:**

- **Note:** the '2' in gCO2e/MJ should be subscript; Trello does not support this type of markup so I am unable to show the proper formatting here.https://trello.com/c/wy7xosc6/1393-compliance-report-b-carbon-intensity-of-the-fuel-column-8

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Carbon Intensity of the Fuel Column |8|](https://trello.com/c/wy7xosc6/1393-compliance-report-b-carbon-intensity-of-the-fuel-column-8)
