### ISSUE TITLE
Compliance Report B | Energy Density Column |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1207]
**Task:**
This card is to create the functionality needed for the Energy Density column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Non-editable:**
The fuel supplier user should not be able to edit this column

**Energy Density:**

- This column should be auto-populated based on the fuel selected within the Fuel Type column, created in **[Card 1386](https://trello.com/c/FDEOFeBO/1386-compliance-report-b-fuel-type-column-0)**.
- This column will draw values from the Energy Densities table, created in **[Card 893](https://trello.com/c/oViXS5Ty/893-credit-calculation-view-energy-densities-5-v133)**. 
- TFRS will also need to ensure that it is pulling the Energy Density value that is/was effective during that compliance year (since the branch can update these values over time). https://trello.com/c/WyO7OuRd/1394-compliance-report-b-energy-density-column-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Energy Density Column |3|](https://trello.com/c/WyO7OuRd/1394-compliance-report-b-energy-density-column-3)
