### ISSUE TITLE
Compliance Report B | EER Column |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1208]
**Task:**
This card is to create the functionality needed for the EER column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Non-editable:**
The fuel supplier user should not be able to edit this column

**Energy Effectiveness Ratio (EER):**
This column should be auto-populated based on:

- The fuel selected within the Fuel Type column, created in **[Card 1386](https://trello.com/c/FDEOFeBO/1386-compliance-report-b-fuel-type-column-0)**.
- The fuel class (gasoline or diesel) chosen within the Fuel Class column, created in **[Card 1387](https://trello.com/c/R7jfIqvN/1387-compliance-report-b-fuel-class-column-0)**.

In addition, 

- This column will draw values from the EER table, created in **[Card 890](https://trello.com/c/UlZX9VeP/890-credit-calculation-view-energy-effectiveness-ratio-eer-values-5-v133)**. 
- TFRS will also need to ensure that it is pulling the EER value that is/was effective during that compliance year (since the branch can update these values over time). https://trello.com/c/Vrl3yBzC/1395-compliance-report-b-eer-column-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | EER Column |3|](https://trello.com/c/Vrl3yBzC/1395-compliance-report-b-eer-column-3)
