### ISSUE TITLE
Compliance Report B | Energy Content Column |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1210]
**Task:**
This card is to create the functionality needed for the Energy Content (MJ) column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Non-editable:**
The fuel supplier user should not be able to edit this column

**Energy Content (MJ):**
This column is a calculation of the total energy content of the fuel reported in the entry row, determined by multiplying the quantity of fuel supplied by the fuel's energy density (as prescribed in the Regulation). 

The calculation in this column should occur automatically using the following fields: 

- The quantity of fuel entered by the user (**[Card 1390](https://trello.com/c/ubTzBBp0/1390-compliance-report-b-quantity-of-fuel-supplied-column-0)**), and

- The energy density of the fuel being reported (**[Card 1394](https://trello.com/c/WyO7OuRd/1394-compliance-report-b-energy-density-column-0)**)

**Additional Requirements:**

- The number should be formatted to place a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423
- As the default setting, the cell should be blank until the necessary information has been entered by the user (quantity of fuel, fuel type)https://trello.com/c/FM9lfr5u/1396-compliance-report-b-energy-content-column-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Energy Content Column |2|](https://trello.com/c/FM9lfr5u/1396-compliance-report-b-energy-content-column-2)
