### ISSUE TITLE
Compliance Report B | Credit or Debit Column |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1211]
**Task:**
This card is to create the functionality needed for the Credit or Debit column for each fuel reported under Schedule B - Part 3 Fuel Supply. 

**Non-editable:**
The fuel supplier user should not be able to edit this column

**Credit or Debit:**
This column is a calculation of the total credits generated or debits incurred from the supply of the reported fuel, determined by the formula in [section 6 of the Act](http://www.bclaws.ca/civix/document/id/complete/statreg/08016_01#section6).

**Credit/Debit Formula:**
From [section 6 of the Act](http://www.bclaws.ca/civix/document/id/complete/statreg/08016_01#section6), the credit/debit formula is 

**Credit or Debit = (CI class × EER fuel – CI fuel) × EC fuel/1 000 000**, where:

- **CI Class** = the prescribed carbon intensity limit for the compliance period for the class of fuel of which the fuel is a part; this value can be taken from the cell/column created in **[Card 1392](https://trello.com/c/WzzZMJi4/1392-compliance-report-b-carbon-intensity-limit-column-0)**. 
- **EER fuel** = the prescribed energy effectiveness ratio for that fuel in that class of fuel; this value can be taken from the cell/column created in **[Card 1395](https://trello.com/c/Vrl3yBzC/1395-compliance-report-b-eer-column-0)**. 
- **CI fuel** = the carbon intensity of the fuel; this value can be taken from the cell/column created in **[Card 1393](https://trello.com/c/wy7xosc6/1393-compliance-report-b-carbon-intensity-of-the-fuel-column-0)**. 
- **EC Fuel** = the energy content of the fuel; this value can be taken from the cell/column created in **[Card 1396](https://trello.com/c/FM9lfr5u/1396-compliance-report-b-energy-content-column-0)**. 

The resulting value from this formula can be either positive (generates credits) or negative (incurs debits). 

**Additional Requirements:**

- The number should be formatted to place a comma every 3 digits. We are dealing with large values and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423
- As the default setting, the cell should be blank until **all** of the necessary information has been entered by the user (all inputs into the formula described in the section above)
- Display debits as positive values
- While the resulting value will likely not be a whole number (will contain a decimal/fraction of a credit/debit), the value should be **displayed as a whole number** (no decimal / fraction of a credit/debit) and use conventional rounding (1-4 round down, 5-9 round up) when displaying. **Note:** this is just a display requirement; we will want to maintain the decimal/fraction values when we total up the credits and debits (we just don't want to display them). https://trello.com/c/WQMUpdBS/1397-compliance-report-b-credit-or-debit-column-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Credit or Debit Column |3|](https://trello.com/c/WQMUpdBS/1397-compliance-report-b-credit-or-debit-column-3)
