### ISSUE TITLE
Compliance Report B | Total Debits |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1213]
**Story:**
As a TFRS user, I want to see the total debits incurred from all of the fuel I am reporting as being supplied within Schedule B - Part 3 Fuel Supply. 

**Task:**

- Within the Schedule B sub-tab, show the total debits incurred from all of the fuel that is reported within this schedule. 
- The total debits would be determined by adding up all of the **negative values** (and only the negative values) from the credit or debit column (**[Card 1397](https://trello.com/c/WQMUpdBS/1397-compliance-report-b-credit-or-debit-column-0)**). Values in this column that are positive (credits) should be ignored in calculating the total debits incurred. 

**Design Requirements:**

- The value should be displayed as a positive, whole number
- The corresponding value should be displayed in the format that places a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423. 

**Potential Design(s):**

- Within the existing excel-based compliance report, the total credits and total debits are displayed near the bottom of the page (below the reporting of the individual fuels supplied; see attached screenshot). This location could be maintained or the values could be placed in a more prominent location (e.g. near the top of the page). 
- While the resulting value will likely not be a whole number (will contain a decimal/fraction of a credit/debit), the value should be **displayed as a whole number** (no decimal / fraction of a credit/debit) and use conventional rounding (1-4 round down, 5-9 round up) when displaying. **Note:** this is just a display requirement; we will want to maintain the decimal/fraction values when we total up the credits and debits (we just don't want to display them). https://trello.com/c/j2PDBc2f/1406-compliance-report-b-total-debits-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Total Debits |2|](https://trello.com/c/j2PDBc2f/1406-compliance-report-b-total-debits-2)
