### ISSUE TITLE
Compliance Report B | Carbon Intensity of Fuel when relying on the Alternative method provision |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1216]
**Task:**
This card is to develop the functionality required for determining carbon intensity using an alternative method approved by the Director (provision of the Act relied upon is Section 6 (5) (d) (ii) (B) - Alternative method) for Schedule B, see [**Card 1388**](https://trello.com/c/cVAGCBK7/1388-compliance-report-b-provision-of-the-act-column-5) and [**Card 1393**](https://trello.com/c/wy7xosc6/1393-compliance-report-b-carbon-intensity-of-the-fuel-column-8) for more information. 

**Alternative method description:**
Section 6 (5) (d) (ii) (B) of the Act allows a fuel supplier to use an alternative method to determine the carbon intensity of a life cycle component of a fuel. Under section 11.07 of the Regulation, a fuel supplier may apply to the Director for approval of an alternative method to determine the carbon intensity of a fuel, including the use of a version of GHGenius that is not approved for use under the Regulation.

**Relying on the Alternative method provision to determine carbon intensity:**

- Please refer to [**Card 1393**](https://trello.com/c/wy7xosc6/1393-compliance-report-b-carbon-intensity-of-the-fuel-column-8) for the conditions on which this provision becomes an option for the user to select within the drop-down menu under the "Provision of the Act relied upon to determine carbon intensity" column of Schedule B. 

**Workflow for selecting the provision "Section 6 (5) (d) (ii) (B) - Alternative method":**

- When a user relies upon the "Section 6 (5) (d) (ii) (B) - Alternative method" provision to determine carbon intensity, the user needs to input the approved carbon intensity into the "Carbon Intensity of the Fuel" column within the entry row of Schedule B. 

**Potential Design and Implementation:**

- When the user selects the "Section 6 (5) (d) (ii) (B) - Alternative method" provision, the "Carbon Intensity of the Fuel" column created in [**Card 1348**](https://trello.com/c/65d4CpMz/1348-compliance-report-d-create-ghgenius-output-table-for-schedule-d-0) turns from an uneditable cell to an editable cell. The user can then enter the carbon intensity of the fuel into the cell.

**Additional Requirements and Restrictions:**

- Restrict data entry to numbers only
- Two decimal places
- Can be positive or negativehttps://trello.com/c/uMeIPgvE/1408-compliance-report-b-carbon-intensity-of-fuel-when-relying-on-the-alternative-method-provision-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Carbon Intensity of Fuel when relying on the Alternative method provision |5|](https://trello.com/c/uMeIPgvE/1408-compliance-report-b-carbon-intensity-of-fuel-when-relying-on-the-alternative-method-provision-5)
