### ISSUE TITLE
Compliance Report D | Create GHGenius Input Table for Schedule D |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1217]
**Task:**
This card to create the GHGenius Input table for the Compliance Reporting sub-tab for Schedule D - GHGenius Input and Output Summaries. 

**Sub-tab label:**

- Schedule D

**Sub-tab page heading:**

- Sub-tab heading: **Schedule D - GHGenius Input and Output Summaries**

**Schedule D - GHGenius Input and Output Summaries**
A user must fill out an input and output summary table for each fuel that is being reported under this section. Although this schedule is seldom used, there is technically no limit to the number of fuels that can be reported under this section. 

- Input table: *this card*
- Output table: [Card 1348](https://trello.com/c/65d4CpMz/1348-compliance-report-d-create-ghgenius-output-table-for-schedule-d-0)

**Input Summary Table:**
For the Input Summary table, the following information is required (see attached screenshot):

For each fuel being reported under this schedule:

- Part 3 Fuel Type
- Feedstock
- Fuel Class

Then a user must enter in all of the relevant GHGenius inputs for the fuel in question. There can be many inputs, and each input requires the following information:

- Worksheet name
- Cell
- Value
- Units
- Description

**Part 3 Fuel Type:**

- This can be a drop-down menu informed from the fuel type list created for the fuel codes feature [Card 939](https://trello.com/c/bbSrYqfS/939-fuel-codes-select-approved-fuels-from-a-predefined-list-5-v1217). 

**Feedstock:**

- A free text input field where the user can enter any values

**Fuel Class:**

- This can be a drop-down menu informed from the fuel class table created in [Card 897](https://trello.com/c/eqw7vn7Q/897-credit-calculation-view-fuel-classes-3). 
- autoselect based on fuel type if there is only one available class for that fuel type

**Other GHGenius Inputs:**

- The rest of the inputs (worksheet name, cell, value, units, description) can be free text input fields where the user can enter any values
- It is too difficult to try and restrict these fields and the values inputted can vary widely depending on the fuel and fuel pathway being considered. 

**Potential Design(s):**

- Use a spreadsheet style design like Schedule B - Fuel Supply Records and the current excel-based reporting form (see attached screenshot).

**Other Requirements:**

- This GHGenius input table must have the ability to enter an endless amount of inputs (e.g. input rows). Typically, on a per fuel basis, we see no more than 1-15 entries per fuel. However, this table needs to be capable of handling more than that, and should be designed in such a way that you can add entries as needed. In other words, you would not see tons of blank entries, but would have the ability to add entries as needed.
- A good default starting position would be to show 10 "input rows" with the ability to add additional input rows. https://trello.com/c/y9n6D1oX/1345-compliance-report-d-create-ghgenius-input-table-for-schedule-d-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report D | Create GHGenius Input Table for Schedule D |5|](https://trello.com/c/y9n6D1oX/1345-compliance-report-d-create-ghgenius-input-table-for-schedule-d-5)

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report D | Create GHGenius Input Table for Schedule D |5|](https://trello.com/c/y9n6D1oX/1345-compliance-report-d-create-ghgenius-input-table-for-schedule-d-5)
