### ISSUE TITLE
Compliance Report D | Create GHGenius Output Table for Schedule D |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1220]
**Task:**
This card to create the GHGenius Output table for the Compliance Reporting sub-tab for Schedule D - GHGenius Input and Output Summaries. 

**Sub-tab label:**

- Schedule D

**Sub-tab page heading:**

- Sub-tab heading: **Schedule D - GHGenius Input and Output Summaries**

**Schedule D - GHGenius Input and Output Summaries**
A user must fill out an input and output summary table for each fuel that is being reported under this section. Although this schedule is seldom used, there is technically no limit to the number of fuels that can be reported under this section. 

- Input table: [Card 1345](https://trello.com/c/y9n6D1oX/1345-compliance-report-d-create-ghgenius-input-table-for-schedule-d-0)
- Output table: *this card*

**Output Summary Table:**
For the Output Summary table, an emissions value must be entered for each lifecycle component (as specified in the legislation). The units for these values are in terms of carbon intensity (gCO2e/MJ). The lifecycle components are: 

- Fuel Dispensing
- Fuel Distribution and Storage
- Fuel Production
- Feedstock Transmission
- Feedstock Recovery
- Feedstock Upgrading
- Land Use Change
- Fertilizer Manufacture
- Gas Leaks and Flares
- CO2 and H2S Removed (Note the two '2' should be subscript) 
- Emissions Displaced
- Fuel Use (High Heating Value)

Immediately following the Fuel Use row, there should then be two more rows that are bolded (see attached screenshot):

- **Total (gCO2e/GJ)**
- **Carbon Intensity (gCO2e/MJ)**

The Total row should sum all of the values inputted into the lifecycle components listed above. 

The Carbon Intensity row should take the value in the total row and divide it by 1000. 

**Potential Design(s):**

- Use a spreadsheet style design like Schedule B - Fuel Supply Records and the current excel-based reporting form (see attached screenshot). This is needed to facilitate copying and pasting the output from the GHGenius lifecycle model into this Schedule's output summary table. 

**Additional Requirements:**

- The Lifecycle component input fields should only allow the user to enter numbers (no letters) with no restrictions on how many digits can be entered after a decimal. 
- All values, including the two total fields, should be displayed to two decimal places and include separating commas per three numbers. This is simply a display requirement; meaning, we do not necessarily have to show the separating commas while the user is inputting in the data, just when they are finished entering it. For example, a user inputting 123456.32321 should be displayed as 123,456.32. The display should use conventional rounding for the last decimal digit (1-4 round down, 5-9 round up). 
- Any instance of CO2e, CO2, or H2S should be displayed with their respective '2' as subscript (unable to illustrate this in Trello). https://trello.com/c/65d4CpMz/1348-compliance-report-d-create-ghgenius-output-table-for-schedule-d-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report D | Create GHGenius Input Table for Schedule D |5|](https://trello.com/c/y9n6D1oX/1345-compliance-report-d-create-ghgenius-input-table-for-schedule-d-5)

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report D | Create GHGenius Output Table for Schedule D |5|](https://trello.com/c/65d4CpMz/1348-compliance-report-d-create-ghgenius-output-table-for-schedule-d-5)
