### ISSUE TITLE
Compliance Report D | Ability to add additional fuels into Schedule D |8|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1221]
**Story:**
As a BCeID user, I need to be able to add more than one fuel into Schedule D so that I can fulfill the requirements of reporting my fuel supply as defined in the legislation. 

**Background:**
In Card 1345 & 1348, we created the GHGenius input and output summary tables that allow a fuel supplier to report a single fuel that does not have an approved fuel code using the GHGenius model. Each fuel reported under this schedule must have a corresponding input and output summary table completed. In some cases, fuel suppliers will report more than one fuel using this method, and in fact, there is no limit to the amount of fuels that can be reported under this section. 

**Task:**
This card is to develop the ability to report more than one fuel in Schedule D (more than one input/output summary tables combination) in the event that a fuel supplier would like to report multiple fuels under this schedule.  

**Potential Design(s):**

- TBD, depends on the design of the Input/Output summary tables created in Card 1345 & 1348
- Ideally, this schedule would only show one input/output summary table, with the ability to add additional fuels (additional input/output tables) as needed. https://trello.com/c/HKzCiVRl/1346-compliance-report-d-ability-to-add-additional-fuels-into-schedule-d-8

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report D | Ability to add additional fuels into Schedule D |8|](https://trello.com/c/HKzCiVRl/1346-compliance-report-d-ability-to-add-additional-fuels-into-schedule-d-8)
