### ISSUE TITLE
Compliance Report C | Adjust Delete key functionality |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1223]
https://trello.com/c/wRbYM1aS/1507-compliance-report-c-adjust-delete-key-functionality-0

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Delete key functionality for Fuel Type selection |2|](https://trello.com/c/wRbYM1aS/1507-compliance-report-delete-key-functionality-for-fuel-type-selection-2)

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
