### ISSUE TITLE
Compliance Report | Delete key functionality for Quantity of Fuel cells |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1224]
**Issue:**

Using the delete key does not clear the selected fuel type within the Fuel Type column. 

**Solution:**
Using the delete key on a cell that has a fuel type selected clears the selection (cell turns blank)

**Locations:**

The Fuel Type cells/columns within:

- Schedule B - Part 3 Fuel Supply
- Schedule C - Fuels used for other purposes
- Schedule D - GHGenius Input and Output Summarieshttps://trello.com/c/AEvlvKen/1508-compliance-report-delete-key-functionality-for-quantity-of-fuel-cells-0

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Delete key functionality for Quantity of Fuel cells |1|](https://trello.com/c/AEvlvKen/1508-compliance-report-delete-key-functionality-for-quantity-of-fuel-cells-1)

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
