### ISSUE TITLE
Compliance Report | Part 2 Summary section of the Summary and Declaration Page |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1228]
**Task:**
This card is to create the Part 2 - Renewable Fuel Requirement Summary section of the Summary & Declaration Page. 

- See attached mockups for proposed layout (Summary Section Mockup and Part 2 and Part 3 Summaries Mockup)

**Sub-tab label:**

- Summary & Declaration

**Sub-tab heading:**

- Part 2 - Renewable Fuel Requirement Summary

**Design and Content:**

- Proposed design is to use the spreadsheet plug-in to create Summary tables similar to the ones in the existing excel-based compliance reporting spreadsheet (see attached screenshots "CR - Part 2 Summary Section.PNG" and "Part 2 and Part 3 Summaries Mockup.docx")

- **Refer to the "Part 2 and Part 3 Summaries Mockup.docx" file for the content to include in this section. Content is on page 1 under heading "Part 2 - Renewable Fuel Requirement Summary"**

**Functionality:**
The functionality behind these cells will be developed in other Trello cards. This card is simply to create the tables / layout needed prior to implementing functionality. 

https://trello.com/c/AyaNiJhL/1250-compliance-report-part-2-summary-section-of-the-summary-and-declaration-page-5#

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
