### ISSUE TITLE
Login | Login Page not displaying on some circumstances |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1235]
Matthew encountered an issue with the login page where it wasn't displaying either of the buttons. 

Upon inspection I noticed that there's a console error and that might be affecting it. https://trello.com/c/2KNfZgW5/1402-login-login-page-not-displaying-on-some-circumstances-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Login | Login Page not displaying on some circumstances |1|](https://trello.com/c/2KNfZgW5/1402-login-login-page-not-displaying-on-some-circumstances-1)

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
