### ISSUE TITLE
Compliance Report B | Incorrect CI Limit displayed for 2019 compliance year |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1239]
**Issue:**

The carbon intensity limit column is displaying the wrong gasoline and diesel CI limits. 

Referring to the attached screenshot, this example "Compliance Report for 2019" shows a CI Limit of 79.33 for the gasoline class and 85.28 for diesel. Those CI Limit values are for 2020 and beyond. The correct 2019 values that should be displayed are 81.09 (gasoline) and 87.18 (diesel).https://trello.com/c/cd7a1hkI/1514-compliance-report-b-incorrect-ci-limit-displayed-for-2019-compliance-year-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Incorrect CI Limit displayed for 2019 compliance year |3|](https://trello.com/c/cd7a1hkI/1514-compliance-report-b-incorrect-ci-limit-displayed-for-2019-compliance-year-3)

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
