### ISSUE TITLE
Fuel Codes | Provide indicator of fuel code overlap when hovering mouse over red marked fuel code entries |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1241]
**Task:**
This card is to provide an indicator of an overlap in fuel code effective dates via a modal window. Currently, TFRS uses red highlights to indicate an overlap in effective dates of fuel codes on the main fuel code page (see attached screenshot). Building off of this, we want to provide more detail via a modal warning message when a user hovers their mouse over the red highlighted entry row. 

**Warning Message:**

- "The effective dates of this fuel code overlap with BCLCFXXX.X", where BCLCFXXX.X is the fuel code version that overlaps with the fuel code that you are hovering your mouse over. https://trello.com/c/LE4otXKN/1518-fuel-codes-provide-indicator-of-fuel-code-overlap-when-hovering-mouse-over-red-marked-fuel-code-entries-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Codes | Provide indicator of fuel code overlap when hovering mouse over red marked fuel code entries |2|](https://trello.com/c/LE4otXKN/1518-fuel-codes-provide-indicator-of-fuel-code-overlap-when-hovering-mouse-over-red-marked-fuel-code-entries-2)

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
