### ISSUE TITLE
Fuel Codes | Fix issues when fuel codes overlap |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1242]
**Description:**

- When adding a new fuel code version (e.g. 300.1) of an existing fuel code (300.0), and the effective dates of the new version overlap with the previous version, a warning message is provided within the confirmation alert when the user goes to add the new fuel code (300.1). 
- **Upon testing this feature, two issues have been identified.**

**Issue #1**

- Condition: overlap between two versions exists (300.1 overlaps with 300.0). Both fuel codes already exist within the database (i.e. they have already been added).
- When the user edits either fuel code version that is apart of the overlap (e.g. either 300.0 or 300.1), and does not fix the overlap, when they click on the update button, the user receives the warning message that the fuel code version they are editing/updating overlaps with itself. 
- Example: when editing/updating 300.1 the warning message states that the code I am updating (300.1) overlaps with itself (300.1); it should say 300.0 (as it does when you first add the new fuel code version)

**Issue #2**

- Condition: overlap between two versions exists (300.1 overlaps with 300.0). Both fuel codes already exist within the database (i.e. they have already been added).
- When the user goes to fix the overlap by editing the effective dates of either fuel code, upon clicking the update button after fixing the overlap the user still receives a warning message about an overlap within the confirmation alert. The overlap warning system (red highlight & confirmation alert warning) does disappear after the user accepts the confirmation alert; however, having the warning still appear when updating the effective periods to fix the issue is confusing to the user. We should implement some form of overlap check/validation when the user clicks on the update button, rather than after the user updates the code. 
https://trello.com/c/NzKexClK/1519-fuel-codes-fix-issues-when-fuel-codes-overlap-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Codes | Fix issues when fuel codes overlap |5|](https://trello.com/c/NzKexClK/1519-fuel-codes-fix-issues-when-fuel-codes-overlap-5)

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
