### ISSUE TITLE
Compliance Report B | Rounding in the UI for debits, credits, and energy content |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1245]
**Task:**

- Display the resulting values as whole numbers (no decimals) for the credits, debits, and energy content columns, including the calculation for total credits/debits/net. 
- Use conventional rounding in displaying this information: 1-4 round down, 5-9 round up
- Rounding should be for display purposes only; meaning, we still want to maintain the decimal values, just not display them. For example, while the corresponding credit/debit value for each fuel reported in Schedule B should be displayed as a whole number, the system should still account for the decimal values when adding up the total credits and debits across all reported fuel (but again, the total values will display as whole numbers).

**Note:** it is understood that this method may lead to perceived inconsistencies in the totals displayed vs. the credit/debits shown for the individually reported fuels. This is acceptable and is present in our current reporting form. https://trello.com/c/gL4bujAk/1512-compliance-report-b-rounding-in-the-ui-for-debits-credits-and-energy-content-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Rounding in the UI for debits, credits, and energy content |2|](https://trello.com/c/gL4bujAk/1512-compliance-report-b-rounding-in-the-ui-for-debits-credits-and-energy-content-2)

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
