### ISSUE TITLE
Compliance Report D | Output Table adjustments |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1249]
**Task 1:**
Bold the "Total" and "Carbon Intensity" number values to align with the bolded labels (see red box in attached screenshot).

**Task 2:**
Allow negative values for all input values within the output table. https://trello.com/c/z54uJT88/1515-compliance-report-d-output-table-adjustments-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report D | Output Table adjustments |1|](https://trello.com/c/z54uJT88/1515-compliance-report-d-output-table-adjustments-1)

**Comment by KMenke** [comment]
Completed in Sprint Quasar
