### ISSUE TITLE
Compliance Report | Show year for Type column on main view page |0|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1250]
**Current Labels:**

- "Compliance Report" (see attached screenshot)

**Revised Labels:**

- "Compliance Report for YYYY", where YYYY is the applicable compliance reporthttps://trello.com/c/yoQc3mPz/1543-compliance-report-show-year-for-type-column-on-main-view-page-0

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Show year for Type column on main view page |0|](https://trello.com/c/yoQc3mPz/1543-compliance-report-show-year-for-type-column-on-main-view-page-0)

**Comment by KMenke** [comment]
Resolved in Sprint Quasar.
