### ISSUE TITLE
Dev Environment | Restore Dev env from templates |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1256]
The dev env was deleted when test "codeready workspace" which was introduced during the lunch learn session Jun 6. There was a known issue of the product but I wasn't aware of. I have added a comment to it, hopefully it can cause the attention from vendor. https://github.com/eclipse/che/issues/13436
https://trello.com/c/SyqVY8zC/1498-dev-environment-restore-dev-env-from-templates-5

**Comment by KMenke** [comment]
Resolved in Sprint Pluto.
