### ISSUE TITLE
Compliance Report | Edit a saved draft of a Compliance Report |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1258]
**Story:**
As a BCeID user, I want to be able to edit a saved draft of a Compliance Report so that I can continue filling out the report that I had previously saved. 

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role
AND I am on the Compliance Reporting page
AND I have saved a draft of a Compliance Report
AND I am viewing the saved draft Compliance Report
WHEN I click on the Edit button
THEN I am able to edit the draft and continue filling out the Reporthttps://trello.com/c/AvSyO94P/1233-compliance-report-edit-a-saved-draft-of-a-compliance-report-3

**Comment by KMenke** [comment]
Resolved in Sprint Pluto
