### ISSUE TITLE
Compliance Report | Delete a draft of a Compliance Report |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1259]
**Story:**
As a BCeID user, I want to be able to delete a saved draft of a Compliance Report so that I can delete draft reports that are no longer needed. 

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role
AND I am on the Compliance Reporting page
AND I have saved a draft of a Compliance Report
AND I am viewing the saved draft Compliance Report
WHEN I click on the Delete button
THEN I receive a confirmation alert asking me to confirm deletion ([Card 1277](https://trello.com/c/2jZsXb3M/1277-confirmation-alerts-delete-a-saved-draft-compliance-report-1))
AND confirming deletion deletes the draft Compliance Report (i.e. archives)
AND I am returned to the Compliance Reporting section of TFRS ([Card 1228](https://trello.com/c/swV6FKKK/1228-compliance-report-view-compliance-reporting-materials-0))
AND a system alert appears informing me that the draft has been deleted (i.e. archived) ([Card 1276](https://trello.com/c/qralI1gJ/1276-system-alerts-delete-a-saved-draft-compliance-report-1))
AND the previously saved draft entry is no longer visible in the Compliance Reporting table

**Note:**
Best practice for data management dictates that we archive the draft and not actually delete ithttps://trello.com/c/tbX7LB8t/1232-compliance-report-delete-a-draft-of-a-compliance-report-2

**Comment by KMenke** [comment]
Resolved in Sprint Pluto
