### ISSUE TITLE
Confirmation Alerts | Delete a Saved Draft Exclusion Report |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1261]
**Task:**
Create confirmation alert for deleting a Saved Draft Compliance Report

**Messaging:**
"Are you sure you want to delete the draft Compliance Report?"https://trello.com/c/3egKyHQO/1566-confirmation-alerts-delete-a-saved-draft-exclusion-report-1

**Comment by KMenke** [comment]
resolved in sprint
