### ISSUE TITLE
Compliance Report B | Minor adjustments to column labels in Schedule B |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1274]
**Task:**
This card is for some minor adjustments to the column labels in the UI in Schedule B. 

**Label 1:** Remove "Determination Method" as that portion of the label only applies to the excel-based compliance reporting form. 

#Update

- Current: "Fuel Code or Determination Method"
- Revised: "Fuel Code (if applicable)"

**Label 2:** Capitalize "Content"

- Current: "Energy content (MJ)"
- Revised: "Energy Content (MJ)"

**Label 3:** Capitalize for consistency across labels.

- Current: "Provision of the Act relied upon to determine carbon intensity"
- Revised: "Provision of the Act Relied Upon to Determine Carbon Intensity"https://trello.com/c/YcfHEguB/1513-compliance-report-b-minor-adjustments-to-column-labels-in-schedule-b-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Minor adjustments to column labels in Schedule B |1|](https://trello.com/c/YcfHEguB/1513-compliance-report-b-minor-adjustments-to-column-labels-in-schedule-b-1)

**Comment by KMenke** [comment]
completed in sprint quasar
