### ISSUE TITLE
Compliance Report | Adjust confirmation alert messaging when saving a compliance report |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1275]
**Current Messaging:**

"Are you sure you want to save this schedule?"

**Revised Messaging:**

"Are you sure you want to save this compliance report?"https://trello.com/c/TnMWkM0b/1545-compliance-report-adjust-confirmation-alert-messaging-when-saving-a-compliance-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Adjust confirmation alert messaging when saving a compliance report |1|](https://trello.com/c/TnMWkM0b/1545-compliance-report-adjust-confirmation-alert-messaging-when-saving-a-compliance-report-1)

**Comment by KMenke** [comment]
done in sprint quasar
