### ISSUE TITLE
Compliance Report | Fix the button bar to the bottom of the page |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1279]
**Task:**
This card is to fix the "button bar" (i.e. the floating bar that contains the back, delete draft, and save buttons) to the bottom of the page. 

**Rationale:**
When testing the compliance reporting feature, we are finding that the floating bar frequently blocks some of the information contained within the different schedules. To avoid this, we want to fix the button bar to the bottom of the page; with the autosave functionality, it is less important for a user to have ready access to the save button at all times. 

**Locations:**

This applies to all Schedules and the Intro page.https://trello.com/c/XcCn0kFn/1510-compliance-report-fix-the-button-bar-to-the-bottom-of-the-page-1

**Comment by KMenke** [comment]
done in sprint quasar
