### ISSUE TITLE
Compliance Report | Adjustments to the floating total windows |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1280]
**Background:**
Schedule A and Schedule B have "floating total windows". That is, a window that "floats" in front of the schedule and displays the total volumes of fuels notionally transferred (Schedule A) or total debits and credits from fuel supplied (Schedule B).

**Issues:**
During testing, two issues were identified:

- The floating total windows can be dragged below the footer bar. This creates blank space below the footer and has the potential for the floating windows to get lost well below the page. 
- The floating total windows frequently block the data contained within the schedules. 

**Proposed Solutions:**

- Provide sufficient blank space between the last "excel" row of the Schedule and the footer to comfortably fit the floating total window.
- Have the floating window start in this blank space by default.
- Maintain this blank space when adding new rows to the Schedule
- Do not allow the floating window to be dragged below the footer

**Rationale:**
The proposed solution ensures that the floating windows do not block the schedule data by default while still maintaining the ability to move the window around the screen if desired. It also ensures that the windows do not get lost below the footer. https://trello.com/c/vfj7Lo4q/1511-compliance-report-adjustments-to-the-floating-total-windows-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Adjustments to the floating total windows |2|](https://trello.com/c/vfj7Lo4q/1511-compliance-report-adjustments-to-the-floating-total-windows-2)

**Comment by KMenke** [comment]
done in sprint quasar
