### ISSUE TITLE
Compliance Report D | Minor adjustments to sub tabs when there is more then one fuel being reported |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1285]
**Task:**
This card is to make two adjustments to the sub-tabs within Schedule:

**#1:** 

Show the corresponding Carbon Intensity value to the right of the fuel type within the sub-tab label. For example, instead of having the label be based solely on fuel type (e.g. "Biodiesel"), have the label also show the corresponding carbon intensity value (e.g. "Biodiesel 45.65"). The carbon intensity for each fuel is calculated in the output table for each fuel reported under Schedule D. 

**#2:**

Change the label "Add Sheet" to "Add Fuel"https://trello.com/c/oXX8pMv9/1516-compliance-report-d-minor-adjustments-to-sub-tabs-when-there-is-more-then-one-fuel-being-reported-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report D | Minor adjustments to sub tabs when there is more then one fuel being reported |1|](https://trello.com/c/oXX8pMv9/1516-compliance-report-d-minor-adjustments-to-sub-tabs-when-there-is-more-then-one-fuel-being-reported-1)

**Comment by KMenke** [comment]
done in sprint quasar
