### ISSUE TITLE
Company Details | Managing User role can edit their organizations address |5|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1291]
**Story:**
As a BCeID admin, I want to be able to update my organization's mailing address.

**Scenario:**
GIVEN that I am a BCeID user
AND my role is Managing Users
AND I am on the Company Details page
WHEN I click on the Edit button next to my organization name
THEN I am taken to a page where I can edit my organization's mailing address
AND I can save the updated address information

**Note:**
The Edit Organization page that is accessible to IDIR users contains some editable information that we **do not** want BCeID users to be able to edit or change. These include:

- Organization name
- Organization status
- Organization Actions Type

If the Edit Organization page is re-used to enable this feature, the aforementioned fields should not be editable by the BCeID user with the Managing Users role

**History:**

- Save history of address changeshttps://trello.com/c/spq5LrnI/1504-company-details-managing-user-role-can-edit-their-organizations-address-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Company Details | Managing User role can edit their organizations address |5|](https://trello.com/c/spq5LrnI/1504-company-details-managing-user-role-can-edit-their-organizations-address-5)

**Comment by KMenke** [comment]
done in sprint quasar
