### ISSUE TITLE
Fuel Codes | Prepopulating previous version data causes partially renewable box to always be checked |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1297]
**Background:**

- IDIR user
- Location: Administration > Fuel Codes > New Fuel Code
- Action: Adding a new version of an existing fuel code and choosing to pre-populate the data from the previous version.
- **Note:** This issue only affects fuels that can be partially renewable (e.g. biodiesel, ethanol, HDRD, etc.) but are **not** partially renewable in this case (i.e. the "Is partially renewable?" checkbox is not checked). 

**Issue:**

- When adding a new version of an existing fuel code, and choosing to pre-populate the data from the previous version, the **Is partially renewable?" checkbox is automatically checked regardless of if the previous version was indicated as being partially renewable (regardless if the checkbox was checked in the previous version)

**Desired state:**

- When pre-populating data from a previous version of a fuel code, the "Is partially renewable?" checkbox should only be checked if the previous version was indicated as being partially renewable (i.e. the checkbox was checked for the previous version).  https://trello.com/c/9iS7d1DF/1571-fuel-codes-prepopulating-previous-version-data-causes-partially-renewable-box-to-always-be-checked-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Codes | Prepopulating previous version data causes partially renewable box to always be checked |1|](https://trello.com/c/9iS7d1DF/1571-fuel-codes-prepopulating-previous-version-data-causes-partially-renewable-box-to-always-be-checked-1)

**Comment by KMenke** [comment]
done in sprint quasar
