### ISSUE TITLE
Compliance Report | Adjustments to Part 2 summary section labels |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1298]
**Task:**
This card is to adjust some of the labels within the Part 2 summary section of the Summary & Declaration page. 

**Line 4:**

- Current: "Volume of Part 2 gasoline class renewable fuel required"
- Revised: "Volume of Part 2 gasoline class renewable fuel required (5% of Line 3)"

**Line 15:**

- Current: "Volume of Part 2 diesel class renewable fuel required"
- Revised: "Volume of Part 2 diesel class renewable fuel required (4% of Line 14)"

**Line 10:**

- Current: "Net volume of renewable Part 2 gasoline class fuel supplied (Total of lines 2 and 5 to 9)"
- Revised: "Net volume of renewable Part 2 gasoline class fuel supplied (Total of Line 2 + Line 5 - Line 6 + Line 7 + Line 8 - Line 9)"

**Line 21:**

- Current: "Net volume of renewable Part 2 diesel class fuel supplied (Total of lines 13 and 16 to 20)"
- Revised: "Net volume of renewable Part 2 diesel class fuel supplied (Total of Line 13 + Line 16 - Line 17 + Line 18 + Line 19 - Line 20)"https://trello.com/c/IEfMXv71/1574-compliance-report-adjustments-to-part-2-summary-section-labels-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Adjustments to Part 2 summary section labels |1|](https://trello.com/c/IEfMXv71/1574-compliance-report-adjustments-to-part-2-summary-section-labels-1)

**Comment by KMenke** [comment]
done in sprint red dwarf
