### ISSUE TITLE
Compliance Report | Adjustments to Part 2 summary section labels Round 2 |1|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1299]
**Task:**
This card is to adjust some of the labels within the Part 2 summary section of the Summary & Declaration page and to place restrictions on the data that can be inputted within the Part 2 summary section. 

**Line 6, 17, 8, 19:**
For these four labels, we would like to add two decimal places to the label. For example, using Line 6, the following change would be made: 

- Current: "Volume of renewable fuel retained (up to 5% of Line 4 is x,xxx L)"
- Revised: "Volume of renewable fuel retained (up to 5% of Line 4 is x,xxx.xx L)"

**Restrict inputting data:**

- As part of this label change, for the four lines mentioned above, we want to restrict the input of data to two decimal places. 
- We also want to maintain all of the other restrictions that were implemented in [Card 1474](https://trello.com/c/MQc801ue/1474-compliance-report-part-2-summary-line-6-and-line-17-2) and [Card 1478](https://trello.com/c/M7ErZxkL/1478-compliance-report-part-2-summary-line-8-and-line-19-2). https://trello.com/c/PCWUVZnv/1575-compliance-report-adjustments-to-part-2-summary-section-labels-round-2-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Adjustments to Part 2 summary section labels Round 2 |1|](https://trello.com/c/PCWUVZnv/1575-compliance-report-adjustments-to-part-2-summary-section-labels-round-2-1)

**Comment by KMenke** [comment]
done in sprint red dwarf
