### ISSUE TITLE
Compliance Report | Part 3 Summary Line 23 Line 24 Line 25 |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1301]
**Task:**
This card builds off of the work that was completed in [**Card 1295**](https://trello.com/c/5mK0ryHx/1295-compliance-report-part-3-summary-section-of-the-summary-and-declaration-page-0) by implementing the required functionality for the Part 3 Low Carbon Fuel Requirement Summary section of the Summary & Declaration Page. 

**Line 23 - Total credits from fuel supplied (from Schedule B)**:

- This line displays the total number of credits generated for the compliance period, based on fuel reporting within Schedule B. 
- Units are: "Credit(s)"
- This cell should display the total credits as calculated in Schedule B and within [**Card 1405**](https://trello.com/c/7ktRYDDV/1405-compliance-report-b-total-credits-2). 

**Line 24 - Total debits from fuel supplied (from Schedule B)**:

- This line displays the total number of debits incurred for the compliance period, based on fuel reporting within Schedule B. 
- Units are: "Debit(s)"
- This cell should display the total debits as calculated in Schedule B and within [**Card 1406**](https://trello.com/c/j2PDBc2f/1406-compliance-report-b-total-debits-2). 

**Line 25 - Net credit or debit balance for compliance period**:

- This line displays the net credit or debit balance for the compliance period, based on fuel reporting within Schedule B. 
- Units are: "Credits or Debits". The number should be displayed as a positive number with the corresponding units (either "Credits" or "Debits")
- This cell should display the net credit or debit balance as calculated in Schedule B and within [**Card 1407**](https://trello.com/c/Swxkwb8f/1407-compliance-report-b-net-credit-or-debit-balance-2). 

**Design:**

- Non-editable cell
- The corresponding value should be displayed in the format that places a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423. 
- While the resulting value will likely not be a whole number (will contain a decimal/fraction of a credit/debit), the value should be **displayed as a whole number** (no decimal / fraction of a credit/debit) and use conventional rounding (1-4 round down, 5-9 round up) when displaying. **Note:** this is just a display requirement; we will want to maintain the decimal/fraction values when we total up the credits and debits (we just don't want to display them). https://trello.com/c/BZgWEjqq/1482-compliance-report-part-3-summary-line-23-line-24-line-25-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Part 3 Summary Line 23 Line 24 Line 25 |2|](https://trello.com/c/BZgWEjqq/1482-compliance-report-part-3-summary-line-23-line-24-line-25-2)

**Comment by KMenke** [comment]
done in sprint red dwarf
