### ISSUE TITLE
Compliance Report | Part 3 Summary Line 26 |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1302]
**Task:**
This card builds off of the work that was completed in [**Card 1295**](https://trello.com/c/5mK0ryHx/1295-compliance-report-part-3-summary-section-of-the-summary-and-declaration-page-0) by implementing the required functionality for the Part 3 Low Carbon Fuel Requirement Summary section of the Summary & Declaration Page. 

**Line 26 - Banked credits used to offset debits (if applicable)**:

- This is an input cell that allows the user to specify the quantity of banked credits that they wish to use to offset a net debit balance accrued in the compliance period. 

**Additional Requirements and Restrictions:**

- The cell is only editable if there is a net debit balance, as determined by [Line 25](https://trello.com/c/BZgWEjqq/1482-compliance-report-part-3-summary-line-23-line-24-line-25-0)
- The user can only enter positive, whole numbers (no decimals or negative numbers)
- The user cannot enter a number higher than the net debit balance reported in Line 25
- The user cannot enter a number higher than their organization's credit balance

- The corresponding value should be displayed in the format that places a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423. Preferably the value will be displayed in this format as the user inputs the value. https://trello.com/c/sdl4oODl/1483-compliance-report-part-3-summary-line-26-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Part 3 Summary Line 26 |2|](https://trello.com/c/sdl4oODl/1483-compliance-report-part-3-summary-line-26-2)

**Comment by KMenke** [comment]
done in sprint red dwarf
