### ISSUE TITLE
Compliance Report | Part 3 Summary Line 27 and Line 28 |2|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#1303]
**Task:**
This card builds off of the work that was completed in [**Card 1295**](https://trello.com/c/5mK0ryHx/1295-compliance-report-part-3-summary-section-of-the-summary-and-declaration-page-0) by implementing the required functionality for the Part 3 Low Carbon Fuel Requirement Summary section of the Summary & Declaration Page. 

**Line 27 - Outstanding Debit Balance**:

- This line displays the remaining debit balance (if any) based on the information provided. 
- Units are: "Debit(s)"

- The value displayed in this cell is dependent on whether or not there is a net debit balance, as determined by [Line 25](https://trello.com/c/BZgWEjqq/1482-compliance-report-part-3-summary-line-23-line-24-line-25-0). 
- If there is a **net debit balance** in Line 25, then the value to display is equal to Line 25 - Line 26.
- If there is a **net credit balance** or a net balance of zero, then this cell should be blank.

**Line 28 - Part 3 non-compliance penalty payable**:

- This line displays the penalty payable and is calculated using the $200 per outstanding debit non-compliance penalty. 
- Units are: $CAD
- The value displayed in this cell is dependent on whether or not there is an outstanding debit balance, as determined by Line 27.
- If there is an outstanding debit balance in Line 27, then the value to display is equal to Line 27 x 200 
- If there is **no** outstanding debit balance in Line 27, then this cell should be blank. 

**Design:**

- Both Line 27 & 28 are non-editable cells
- The corresponding value should be displayed in the format that places a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423. 
- Show values to two decimal placeshttps://trello.com/c/4s2sHfdG/1484-compliance-report-part-3-summary-line-27-and-line-28-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Part 3 Summary Line 27 and Line 28 |2|](https://trello.com/c/4s2sHfdG/1484-compliance-report-part-3-summary-line-27-and-line-28-2)

**Comment by KMenke** [comment]
done in sprint red dwarf
