### ISSUE TITLE
Compliance Report | Part 2 and 3 Penalty Payable section of the Summary and Declaration Page |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1305]
**Task:**
This card is to create the Part 2 and Part 3 Non-compliance Penalty Payable Summary section of the Summary & Declaration Page. 

**Sub-tab label:**

- Summary & Declaration

**Sub-tab heading:**

- Part 2 and Part 3 Non-compliance Penalty Payable Summary

**Design and Content:**

- Proposed design is to use Summary tables similar to the ones in the existing excel-based compliance reporting spreadsheet 

- **Refer to the "Part 2 and Part 3 Summaries Mockup.docx" file for the content to include in this section. Content is on page 2 under heading "Part 2 and Part 3 Non-compliance Penalty Payable Summary"**

- All units are in Canadian dollar ($CAD)
- Show values to two decimal places

**Part 2 Gasoline class non-compliance payable**:

- Show the value in [Line 11](https://trello.com/c/7CwJ8zZS/1481-compliance-report-part-2-summary-line-11-and-line-22-0)

**Part 2 Diesel class non-compliance payable**:

- Show the value in [Line 22](https://trello.com/c/7CwJ8zZS/1481-compliance-report-part-2-summary-line-11-and-line-22-0)

**Part 3 non-compliance penalty payable**:

- Show the value in [Line 28](https://trello.com/c/4s2sHfdG/1484-compliance-report-part-3-summary-line-27-0)

**Total non-compliance penalty payable (Line 11 + Line 22 + Line 28)**:

- The value displayed in this cell = Line 11 + Line 22 + Line 28

https://trello.com/c/87sNI34A/1485-compliance-report-part-2-and-3-penalty-payable-section-of-the-summary-and-declaration-page-3#

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Part 2 and 3 Penalty Payable section of the Summary and Declaration Page |3|](https://trello.com/c/87sNI34A/1485-compliance-report-part-2-and-3-penalty-payable-section-of-the-summary-and-declaration-page-3)

**Comment by KMenke** [comment]
done in sprint red dwarf
