### ISSUE TITLE
Credit Transfer | Users can delete their comment |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1309]
**Background:**
Within the credit transfer feature, the ability for a user to comment has been restricted based on the status of the transaction. For example, the initiating fuel supplier can only comment on the credit transfer proposal when it is being created or in a draft state, once the transfer has been sent to the responding fuel supplier (status: Signed 1/2) the initiating fuel supplier is no longer able to add comments. An added feature allows the user to edit their existing comments.  

**Task:**
Allow users to delete their existing comments.  

**Design:**

- Provide a **Delete** button next to the **Edit** button
- **Also, remove the word comment from both the Edit and Delete buttons**. We don't need to say the word comment in each button

**Note:** 
The ability to delete a comment should follow the same restrictions we applied to enabling a user to comment. For example, the initiating fuel supplier can only comment on the credit transfer proposal when it is being created or in a draft state, once the transfer has been sent to the responding fuel supplier (status: Signed 1/2) the initiating fuel supplier is no longer able to add comments. The same restrictions should be applied to deleting comments. 

https://trello.com/c/1rEeKAsP/1506-credit-transfer-users-can-delete-their-comment-5#

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credit Transfer | Users can delete their comment |5|](https://trello.com/c/1rEeKAsP/1506-credit-transfer-users-can-delete-their-comment-5)

**Comment by KMenke** [comment]
done in sprint red dwarf
