### ISSUE TITLE
Compliance Report | Summary section penalty payable updating when adjusting value in Line 26 |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1316]
Fix issue with penalty payable section not updating correctly when changing the credit offset value in Line 26

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Summary section penalty payable updating when adjusting value in Line 26 |2|](https://trello.com/c/Tot0rcGC/1641-compliance-report-summary-section-penalty-payable-updating-when-adjusting-value-in-line-26-2)

**Comment by KMenke** [comment]
Resolved in sprint red dwarf
