### ISSUE TITLE
Exclusion Report | Create new Exclusion Report button |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1320]
**Story:**
As a BCeID user, I want to be able to create a new Exclusion Report for submission to government so that I can meet my obligations under the Regulation. 

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role
AND I am on the Compliance Reporting page
WHEN I click on the New Exclusion Report button
THEN a drop-down menu appears with a list of the compliance periods
AND I am able to select a compliance period from that list
AND selecting a compliance period takes me to the New Exclusion Report page
AND I am taken to the Introduction sub-tab, see [Card 1524](https://trello.com/c/75qadlhA/1524-exclusion-report-introduction-page-0)

**New Exclusion Report button:**
Similar to the New Compliance Report button: 

- Click on the button to bring up a drop-down menu to select the relevant compliance period (2013-14 to 2019)
- Do not show future compliance periods
- On January 1, 2020, TFRS should automatically include the Exclusion Report for the 2020 compliance period. Moving forward, the Exclusion Report for YYYY should become available on January 1, YYYY. 

https://trello.com/c/KaXTz1Rf/1522-exclusion-report-create-new-exclusion-report-button-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Create new Exclusion Report button |1|](https://trello.com/c/KaXTz1Rf/1522-exclusion-report-create-new-exclusion-report-button-1)

**Comment by KMenke** [comment]
Done in Sprint supermassive
