### ISSUE TITLE
Exclusion Report | Create Exclusion Agreements page |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1321]
**Task:**
This card to create the Exclusion Reporting sub-tab - Exclusion Agreements. 

**Sub-tab label:**

- Exclusion Agreements

**Sub-tab page heading and information:**

- Sub-tab heading: **Exclusion Report**
- Following the sub-tab heading "Exclusion Report", the following two sentences should appear: "Report all Part 3 fuels either purchased or sold under an exclusion agreement within this Compliance Period. **This report does not apply to petroleum-based gasoline or petroleum-based diesel fuel.**"  

**Exclusion Report**
The following information is required for each exclusion agreement reported within this form (see attached screenshot):

- Transaction Type
- Fuel Type
- Legal Name and Address of Transaction Partner
- Quantity
- Units
- Quantity not sold or supplied within the Compliance Period
- Units

**Note: This card is to create these required columns and labels. Other cards have been created to develop the specific functionality required for each column category.**

**Design(s):**

- Use the spreadsheet plug-in, same look and feel as the Compliance Report feature

**Other Requirements:**

- This schedule must have the ability to enter an endless amount of Exclusion Agreements. Typically, we see no more than 5-8 per compliance period; however, this form must be able to handle more than that. Having 5 blank entry rows is the desired default state when creating a new exclusion report. 

https://trello.com/c/jLDwtqhf/1528-exclusion-report-create-exclusion-agreements-page-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Create Exclusion Agreements page |5|](https://trello.com/c/jLDwtqhf/1528-exclusion-report-create-exclusion-agreements-page-5)

**Comment by KMenke** [comment]
Done in sprint supermassive
