### ISSUE TITLE
Compliance Report | Adjust tooltip description for offsetting credits credit balance restriction |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1324]
https://trello.com/c/I6uP2hcO/1640-compliance-report-adjust-tooltip-description-for-offsetting-credits-credit-balance-restriction-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Adjust tooltip description for offsetting credits credit balance restriction |1|](https://trello.com/c/I6uP2hcO/1640-compliance-report-adjust-tooltip-description-for-offsetting-credits-credit-balance-restriction-1)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
