### ISSUE TITLE
Compliance Report | Use of rounding within Schedule B and the penalty payable section |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1325]
**Task:**
Conventional rounding should be applied to the total debits and total credits calculated within Schedule B (in the actual data, not just display in the UI). These values are then populated in the Summary section and are used to calculate the penalty payable when in a net debit situation. 

https://trello.com/c/tfGkNIpE/1630-compliance-report-use-of-rounding-within-schedule-b-and-the-penalty-payable-section-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Use of rounding within Schedule B and the penalty payable section |2|](https://trello.com/c/tfGkNIpE/1630-compliance-report-use-of-rounding-within-schedule-b-and-the-penalty-payable-section-2)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
