### ISSUE TITLE
Compliance Report B | Save function does not save user inputted CI when relying on Alternative Method provision |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1329]
**Issue:**
When the user relies on the Alternative Method provision and has inputted a CI into the CI of Fuel cell, the inputted CI value does not save when the user uses the save feature (save button). Instead, the value is cleared and the cell becomes uneditable. 

**Desired state:**
When the user saves, the inputted CI of Fuel value is saved and the cell remains editable in case the user wants to adjust the inputted CI value. 

https://trello.com/c/8xIjfLVU/1619-compliance-report-b-save-function-does-not-save-user-inputted-ci-when-relying-on-alternative-method-provision-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Save function does not save user inputted CI when relying on Alternative Method provision |5|](https://trello.com/c/8xIjfLVU/1619-compliance-report-b-save-function-does-not-save-user-inputted-ci-when-relying-on-alternative-method-provision-5)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
