### ISSUE TITLE
Compliance Report C | Adjustments to the quantity of fuel supplied column |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1331]
**Issues:**

- Quantity of Fuel supplied column does not show commas when typing the value (this functionality is implemented in Schedule A and B and was intended for Schedule C)
- Quantity of Fuel supplied column should be whole numbers only (no decimals)

https://trello.com/c/0E6UplJD/1621-compliance-report-c-adjustments-to-the-quantity-of-fuel-supplied-column-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report C | Adjustments to the quantity of fuel supplied column |1|](https://trello.com/c/0E6UplJD/1621-compliance-report-c-adjustments-to-the-quantity-of-fuel-supplied-column-1)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
