### ISSUE TITLE
Company Details | Rename Company Details to Organization Details |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1332]
**Task:**

- Rename the "Company Details" label in the main nav bar to "Organization Details". 
- Change the "Company Name" label that appears in the list of fuel suppliers (IDIR user, Fuel Suppliers tab on the main nav bar)

- See attached screenshots

**Rationale:**
Some of our fuel suppliers are not technically considered "companies" with respect to the conventional definition. Suppliers such as municipalities, school districts, etc. do not fit this description. Thus, we want to change the label to reference "organization" rather than "company" 

https://trello.com/c/HOlheDTe/1591-company-details-rename-company-details-to-organization-details-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Company Details | Rename Company Details to Organization Details |1|](https://trello.com/c/HOlheDTe/1591-company-details-rename-company-details-to-organization-details-1)

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Company Details | Rename Company Details to Organization Details |1|](https://trello.com/c/HOlheDTe/1591-company-details-rename-company-details-to-organization-details-1)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
