### ISSUE TITLE
Compliance Report | Restrict Line 6 8 17 19 to whole numbers and adjust corresponding label accordingly |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1334]
**Task:**
For Line 6, 8, 17, 19 within the summary section, we want to restrict the entry of data to only positive whole numbers. The "smart" labels that go along with these line entries should also be updated to only show whole numbers. 

- Use conventional rounding (1-4 round down, 5-9 round up)

https://trello.com/c/f2LamAVL/1625-compliance-report-restrict-line-6-8-17-19-to-whole-numbers-and-adjust-corresponding-label-accordingly-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Restrict Line 6 8 17 19 to whole numbers and adjust corresponding label accordingly |1|](https://trello.com/c/f2LamAVL/1625-compliance-report-restrict-line-6-8-17-19-to-whole-numbers-and-adjust-corresponding-label-accordingly-1)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Restrict Line 6 8 17 19 to whole numbers and adjust corresponding label accordingly |1| v1.4.19](https://trello.com/c/f2LamAVL/1625-compliance-report-restrict-line-6-8-17-19-to-whole-numbers-and-adjust-corresponding-label-accordingly-1-v1419)

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Restrict Line 6 8 17 19 to whole numbers and adjust corresponding label accordingly |1| v1.4.19](https://trello.com/c/f2LamAVL/1625-compliance-report-restrict-line-6-8-17-19-to-whole-numbers-and-adjust-corresponding-label-accordingly-1-v1419)
