### ISSUE TITLE
Compliance Report | Restrict summary section tooltip for Line 6 8 17 19 to whole numbers |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1335]
**Task:**
This card is to only show whole numbers within the tooltip when entering data into Line 6, 8, 17, 19. The tooltip and corresponding functionality stops the user from entering a number that is greater than the restriction for those cells 

- screenshot attached

https://trello.com/c/kvYbKQk9/1624-compliance-report-restrict-summary-section-tooltip-for-line-6-8-17-19-to-whole-numbers-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Restrict summary section tooltip for Line 6 8 17 19 to whole numbers |1|](https://trello.com/c/kvYbKQk9/1624-compliance-report-restrict-summary-section-tooltip-for-line-6-8-17-19-to-whole-numbers-1)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
