### ISSUE TITLE
Exclusion Report | Introduction page |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1338]
**Task:**
This card is to create the first sub-tab of the Exclusion Report, titled "Introduction". Attached is a screenshot of the Introduction page in the current excel-based reporting form; most (but not all) of the information contained on this form will need to be incorporated into the TFRS Exclusion Report form. The content section below describes the info we need to include in the TFRS Exclusion Report form. 

**Content:**
Sub-tab heading should be "**Exclusion Report for YYYY**", followed by the "British Columbia Renewable and Low Carbon Fuel Requirements Regulation"

- This heading should follow the same format as the Compliance Report in TFRS (e.g. bold text, centre alignment, etc.)

Under the heading, include the following paragraphs of text (ensure adequate spacing between "paragraphs", please note and include the *italics* and **bold** font, and [subheadings] are denoted accordingly): 

- It is the responsibility of anyone who manufactures or imports fuel to determine whether their activities qualify them as a Part 2 (Renewable) and/or Part 3 (Low Carbon) fuel supplier under the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act* (available online at www.bclaws.ca).  
- The YYYY compliance period for Part 2 and Part 3 requirements is from January 1 to December 31, YYYY.  **Exclusion reports are due March 31, YYYY+1**.  
- [Subheading] **Should I complete an "Exclusion Report for YYYY"?**
- All persons who transfer fuel to a Part 3 fuel supplier under an exclusion agreement are required to submit an annual report to the Director.  For more information, see Information Bulletin RLCF-015 Exclusion Agreements and Reports, available from www.gov.bc.ca/lowcarbonfuels. **This report does not apply to petroleum-based gasoline or petroleum-based diesel fuel.**  
- [Subheading] **Questions?**
- Please contact lcfrr@gov.bc.ca with any questions you may have about this form. 

**Additional Requirements:**

- Hyperlink references to www.gov.bc.ca/lowcarbonfuels, www.bclaws.ca, and lcfrr@gov.bc.ca. Have the hyperlink open a new window when clicked so as not to disrupt a users session within TFRS. 

https://trello.com/c/75qadlhA/1524-exclusion-report-introduction-page-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Introduction page |2|](https://trello.com/c/75qadlhA/1524-exclusion-report-introduction-page-2)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
