### ISSUE TITLE
Exclusion Report | Transaction Type |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1339]
**Info:**

This card is to create the Transaction Type column, which allows the user to indicate whether they purchased or sold the fuel under an exclusion agreement.

**Design:**

Drop-down menu with two options: 

- Purchased
- Sold

https://trello.com/c/qVp55ljn/1556-exclusion-report-transaction-type-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Transaction Type |3|](https://trello.com/c/qVp55ljn/1556-exclusion-report-transaction-type-3)

**Comment by KMenke** [comment]
Done in sprint supermassive
