### ISSUE TITLE
Exclusion Report | Fuel Type |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1340]
**Info:**

This card is to create the Fuel Type column, which enables the user to indicate the type of fuel that was purchased/sold under an exclusion agreement. 

**Design:**

Drop-down menu with options informed from the "Fuel Types" Credit Calculations table. This uses the same functionality for selecting fuel types as that within the different schedules of the compliance report. 

- **Does not include petroleum-based gasoline and diesel** (it uses the same list as the fuel code features)

https://trello.com/c/gyoynfCg/1557-exclusion-report-fuel-type-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Fuel Type |1|](https://trello.com/c/gyoynfCg/1557-exclusion-report-fuel-type-1)

**Comment by KMenke** [comment]
Done in sprint supermassive
