### ISSUE TITLE
Exclusion Report | Legal Name and Address of Transaction Partner |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1341]
**Info:**

This card is to create the Legal Name and Address of Transaction Partner columns, which enables the user to identify the counter party to the exclusion agreement. 

**Note:** in contrast to the excel-based exclusion report, we will be splitting this column into two columns and borrowing the autocomplete functionality we implemented within the compliance report. 

**Design Requirements:**

- Two free form columns that allow the user to enter in any characters (no restrictions)
- Legal Name of Transaction Partner comes first, and includes autosuggest functionality. Similar to the compliance report, the autosuggest should pull suggestions from our list of recognized Part 3 fuel suppliers. 
- Address of Transaction Partner should autocomplete when a recognized Part 3 fuel supplier is selected as the transaction partner. 
- The user can change/alter the autosuggested text as they wish (no restrictions)

https://trello.com/c/UL0nnVph/1558-exclusion-report-legal-name-and-address-of-transaction-partner-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Legal Name and Address of Transaction Partner |1|](https://trello.com/c/UL0nnVph/1558-exclusion-report-legal-name-and-address-of-transaction-partner-1)

**Comment by KMenke** [comment]
Done in sprint supermassive
