### ISSUE TITLE
Compliance Report | Declaration confirmation alert when submitting a Compliance Report |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1355]
**Task:**
This card is to create the confirmation alert for when a user clicks on the Submit button within the Summary section of the Compliance Report. The confirmation alert contains:

- The Signing Authority Declaration 
- Messaging for confirming submission 
- Submit and Cancel buttons

**Signing Authority Declaration Section:**
This section will use a similar component as the Signing Declaration in the Credit Transfer feature, but with some slight adjustments and different statements (specified in the legislation). See the attached screenshot for an example but please **note that the statements in the screenshot are different than the ones we will be using here**. 

- Heading: Signing Authority Declaration
- I, <user first, last name>, <title>:
- expect, on reasonable grounds, that any fuels reported in Schedule C were used for a purpose other than transport in accordance with section 6 (3) of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*.
- certify that records evidencing each matter reported under sections 9 and 11.08 of the Renewable and Low Carbon Fuel Requirements Regulation are available on request.
- certify that I am an officer or employee of the fuel supplier, and that records evidencing my authority to submit this report are available on request.
- certify that the information in this report is true and complete to the best of my knowledge and I understand that I may be required to provide to the Director records evidencing the truth of that information. 

**Please take note of the markup in the above statements; italics should be included in TFRS where used above**

**Confirmation alert messaging:**
Following the declaration section, the following statement should appear: 

- Are you sure you want to submit this Compliance Report to the Government of British Columbia?

Followed by two buttons:

- Submit
- Cancel

**Additional Requirements:**

- If the user does not have a title then do not show anything for that portion of the declaration. For example, with no title, it should read "I, First Last Name:"
- Similar to the Credit Transfer feature, each checked box should be recorded in the database (when it was checked, the user that checked it, etc.) 
- The Submit button should be greyed out until **all four** checkboxes have been checked. 

**Role Restrictions - Signing Authority:**

- The Signing Authority role can check the boxes
- Tooltip: hovering the mouse over the Submit button **before** checking all four boxes displays the following tool tip: "Please complete the Signing Authority declaration".

https://trello.com/c/sUUZAWL4/1249-compliance-report-declaration-confirmation-alert-when-submitting-a-compliance-report-5#

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Declaration confirmation alert when submitting a Compliance Report |5|](https://trello.com/c/sUUZAWL4/1249-compliance-report-declaration-confirmation-alert-when-submitting-a-compliance-report-5)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
