### ISSUE TITLE
Compliance Report | Submit a Compliance Report |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1356]
**Story:**
As a fuel supplier user, I want to be able to submit a compliance report to government so that I can fulfill my legislated obligations.

**Scenario:**
GIVEN that I am a fuel supplier user
AND I have either the Signing Authority role
AND I am on the Summary & Declaration page
WHEN I click on the Submit button
THEN a confirmation alert appears asking me to complete the declaration section, completed in **[Card 1249](https://trello.com/c/sUUZAWL4/1249-compliance-report-declaration-confirmation-alert-0)**. 
AND I am able to confirm submission only after the declaration section has been completed (Signing Authority role only)
AND confirming the submission submits the report
AND a Transaction History record is created, completed in **[Card 1585](https://trello.com/c/IfeJdqFB/1585-compliance-report-compliance-report-history-records-0)**.
AND I am returned to the main Compliance Reporting page
AND the status updates to Submitted

**Role Restrictions:**

- Only the Signing Authority role can click the Submit button
- The button should be greyed out for a user with the Compliance Reporting role 
- Tooltip: hovering the mouse over the greyed out Submit button displays the following tool tip: "You must have the Signing Authority role to submit a Compliance Report to the Government of British Columbia."

https://trello.com/c/Zy8R6jVs/1234-compliance-report-submit-a-compliance-report-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Save button does not save incomplete rows |0|](https://trello.com/c/VMFXeyTg/1617-compliance-report-save-button-does-not-save-incomplete-rows-0)

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Submit a Compliance Report |2|](https://trello.com/c/Zy8R6jVs/1234-compliance-report-submit-a-compliance-report-2)

**Comment by KMenke** [comment]
Resolved in Sprint Tunguska
