### ISSUE TITLE
Compliance Report | Add an indicator for cells with drop-down menu functionality |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1358]
**Info:**
Currently, it is not clear to the user whether or not a cell/column contains drop-down menu functionality within the different compliance reporting schedules. To access the drop-down menu, a user must first double click on the cell (tested in Chrome); this brings up a drop-down arrow on the right-hand side of the cell, the user then needs to click again to bring up the drop-down menu. 

**Possible Design Solution:**

- Add an indicator on the right hand side of the cell when the cell is selected, similar to the indicator that appears when the user double clicks a cell that has the drop-down menu functionality (e.g. downward arrow in Windows, two opposing arrows on Mac)

https://trello.com/c/2d1msMUO/1444-compliance-report-add-an-indicator-for-cells-with-drop-down-menu-functionality-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Add an indicator for cells with drop-down menu functionality |2|](https://trello.com/c/2d1msMUO/1444-compliance-report-add-an-indicator-for-cells-with-drop-down-menu-functionality-2)

**Comment by KMenke** [comment]
done in sprint supermassive
