### ISSUE TITLE
Compliance Report C | Quantity of fuel supplied column places zero in front of single digit value |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1365]
https://trello.com/c/6dO8XMyx/1722-compliance-report-c-quantity-of-fuel-supplied-column-places-zero-in-front-of-single-digit-value-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report C | Quantity of fuel supplied column places zero in front of single digit value |1|](https://trello.com/c/6dO8XMyx/1722-compliance-report-c-quantity-of-fuel-supplied-column-places-zero-in-front-of-single-digit-value-1)

**Comment by KMenke** [comment]
Resolved in Sprint Supermassive
