### ISSUE TITLE
Compliance Report | Instructions for Summary and Declaration section |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1368]
**Task:**
This card is to create the Instructions section of the Summary and Declaration Page. 

- See attached screenshot for a mockup (Schedule D example)

**Story:**
As a BCeID user, I would like to have non-intrusive access to instructions for filling out and understanding the Summary section so that I can refer to them if needed. 

**Design(s):**

- Tooltips (icons and messaging) 

**Tooltips:**

- Line 1: This line displays the total volume of petroleum-based gasoline supplied for the compliance period as reported in Schedule B.  This is the sum of all petroleum-based gasoline that was imported, manufactured, or acquired under an agreement described in section 6 of the Regulation, and then sold or used.  
- Line 2: This line displays the total volume of renewable fuel in the gasoline fuel class for the compliance period as reported in Schedule B.  This is the sum of all renewable fuel that was imported, manufactured, or acquired under an agreement described in section 6 of the Regulation, and then sold or used.  
- Line 3: This line displays the total volume of fuel supplied in the gasoline fuel class in the compliance period.  It is the sum of Line 1 + Line 2. 
- Line 4: This line displays the volume of renewable fuel that is required in the gasoline fuel class and amounts to 5% of the total fuel volume reported. 
- Line 5: This line displays the net volume of gasoline class renewable fuel notionally transferred to and received from other suppliers under section 5 (1) of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*, as reported in Schedule A. 
- Line 6: If you exceed your renewable fuel obligation for the compliance period, under section 5 (3) (a) of the Act you may retain records of surplus volumes for up to 5% of your obligations calculated in Line 4.  Report the volume of renewable fuel retained in the gasoline fuel class for the next compliance period (if applicable).
- Line 7: The amount of renewable class fuel retained in the previous compliance period as described under section 5 (3) (b) of the Act. This value is populated automatically based on the amount reported in Line 6 in the previous compliance period (if applicable). 
- Line 8: If you do not meet your renewable fuel obligations for the compliance period, under section 5 (4) (a) of the Act you may defer the deficiency for up to 5% of your obligations calculated in Line 4 and add that volume to your obligation for the next compliance period.  Report the volume you are deferring to the next compliance period (if applicable).
- Line 9: The amount of renewable class fuel deferred from the previous compliance period as described under section 5 (4) (b) of the Act. This value is populated automatically based on the amount reported in Line 8 in the previous compliance period (if applicable).
- Line 10: This line displays the net volume of renewable fuel supplied in the gasoline fuel class for this compliance period. 
- Line 11: This line displays the Part 2 penalty payable if the volume of renewable fuel supplied does not meet the required volume for the gasoline class, as informed by the information provided in this compliance report. The penalty displayed in this line is calculated at a rate of $0.30 per litre.
- Line 12: This line displays the total volume of petroleum-based diesel supplied for the compliance period as reported in Schedule B and Schedule C with an expected use of heating oil.  This is the sum of all petroleum-based diesel that was imported, manufactured, or acquired under an agreement described in section 6 of the Regulation, and then sold or used.  
- Line 13: This line displays the total volume of renewable fuel in the diesel fuel class for the compliance period as reported in Schedule B and Schedule C with an expected use of heating oil.  This is the sum of all renewable fuel that was imported, manufactured, or acquired under an agreement described in section 6 of the Regulation, and then sold or used. 
- Line 14: This line displays the total volume of fuel supplied in the diesel fuel class in the compliance period.  It is the sum of Line 12 + Line 13. 
- Line 15: This line displays the volume of renewable fuel that is required in the diesel fuel class and amounts to 4% of the total fuel volume reported. 
- Line 16: This line displays the net volume of diesel class renewable fuel notionally transferred to and received from other suppliers under section 5 (1) of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*, as reported in Schedule A. 
- Line 17: If you exceed your renewable fuel obligation for the compliance period, under section 5 (3) (a) of the Act you may retain records of surplus volumes for up to 5% of your obligations calculated in Line 15.  Report the volume of renewable fuel retained in the diesel fuel class for the next compliance period (if applicable).
- Line 18: The amount of renewable class fuel retained in the previous compliance period as described under section 5 (3) (b) of the Act. This value is populated automatically based on the amount reported in Line 17 in the previous compliance period (if applicable). 
- Line 19: If you do not meet your renewable fuel obligations for the compliance period, under section 5 (4) (a) of the Act you may defer the deficiency for up to 5% of your obligations calculated in Line 15 and add that volume to your obligation for the next compliance period.  Report the volume you are deferring to the next compliance period (if applicable).
- Line 20: The amount of renewable class fuel deferred from the previous compliance period as described under section 5 (4) (b) of the Act. This value is populated automatically based on the amount reported in Line 19 in the previous compliance period (if applicable).
- Line 21: This line displays the net volume of renewable fuel supplied in the diesel fuel class for this compliance period. 
- Line 22: This line displays the Part 2 penalty payable if the volume of renewable fuel supplied does not meet the required volume for the diesel class, as informed by the information provided in this compliance report. The penalty displayed in this line is calculated at a rate of $0.45 per litre.
- Line 23: This line displays the total number of credits for the compliance period and is informed from reporting in Schedule B.
- Line 24: This line displays the total number of debits for the compliance period and is informed from reporting in Schedule B.
- Line 25: This line displays the net balance of credits or debits for the compliance period. 
- Line 26: Enter the quantity of banked credits used to offset debits accrued in the compliance period. This line is only available if there is a net debit balance in the compliance period, as indicated in Line 25. 
- Line 27: This line displays the outstanding debit balance (if any) based on the information provided.
- Line 28: This line displays the penalty payable based on the information provided and is calculated using the $200 per outstanding debit non-compliance penalty. 

**Note that the instructions in this card are different than the instructions included in the existing excel-based compliance reporting form.**

https://trello.com/c/4KmgB7qh/1351-compliance-report-instructions-for-summary-and-declaration-section-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Instructions for Summary and Declaration section |2|](https://trello.com/c/4KmgB7qh/1351-compliance-report-instructions-for-summary-and-declaration-section-2)

**Comment by KMenke** [comment]
Resolved in Sprint Tunguska
