### ISSUE TITLE
Compliance Report | System Alert for submitting a compliance report |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1369]
**Task:**
System alert for submitting a compliance report

**Messaging:**

"Compliance Report submitted"

https://trello.com/c/wS5v0reI/1584-compliance-report-system-alert-for-submitting-a-compliance-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | System Alert for submitting a compliance report |1|](https://trello.com/c/wS5v0reI/1584-compliance-report-system-alert-for-submitting-a-compliance-report-1)

**Comment by KMenke** [comment]
Resolved in Sprint Tunguska
