### ISSUE TITLE
Exclusion Report | Integrate exclusion reporting with the compliance reporting feature page |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1370]
Move New Exclusion Report into Compliance Reporting

https://trello.com/c/2BBKZgLI/1728-exclusion-report-integrate-exclusion-reporting-with-the-compliance-reporting-feature-page-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Integrate exclusion reporting with the compliance reporting feature page |1|](https://trello.com/c/2BBKZgLI/1728-exclusion-report-integrate-exclusion-reporting-with-the-compliance-reporting-feature-page-1)

**Comment by KMenke** [comment]
Resolved in Sprint Tunguska
