### ISSUE TITLE
Compliance Report | Create IDIR Compliance Manager Role |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1372]
**Task:** 
Create Compliance Manager role

- Label: Compliance Manager

https://trello.com/c/j3Xs2Nbw/1676-compliance-report-create-idir-compliance-manager-role-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Create IDIR Compliance Manager Role |1|](https://trello.com/c/j3Xs2Nbw/1676-compliance-report-create-idir-compliance-manager-role-1)

**Comment by KMenke** [comment]
Resolved in Sprint Tunguska
