### ISSUE TITLE
Compliance Report | Rename BCeID role to Compliance Reporting |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1373]
**Task:**
Rename Compliance Reporting role for BCeID users

- Current name: "Compliance Report Manager"
- New name: "Compliance Reporting"

https://trello.com/c/yySHiWtP/1677-compliance-report-rename-bceid-role-to-compliance-reporting-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Rename BCeID role to Compliance Reporting |1|](https://trello.com/c/yySHiWtP/1677-compliance-report-rename-bceid-role-to-compliance-reporting-1)

**Comment by KMenke** [comment]
Resolved in Sprint Tunguska
