### ISSUE TITLE
Compliance Report | Compliance Report History Records |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1378]
**Task:**
Create a compliance report history record when submitting a compliance report. Similar to the transaction history record in the Credit Transfer feature (see attached screenshot), we want to track who signed and submitted the compliance report. 

**Format:**
The record should follow the same format as the Credit Transfer feature:

- <**Status**> on Month DD, YYYY by <**First, Last Name**> of <**Organization Name**>
- Example: **Submitted** on March 31, 2019 by **Billy Biodiesel** of **TFRS Fantastic Fuels**

**Visibility:**
This entry should be visible to both the fuel supplier and government for all roles that can access the compliance reporting feature (compliance reporting role, Signing Authority, all government roles).

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Compliance Report History Records |5|](https://trello.com/c/IfeJdqFB/1585-compliance-report-compliance-report-history-records-5)

**Comment by KMenke** [comment]
resolved in sprint ursa major
