### ISSUE TITLE
Validation | Schedule B |16| v1.4.25

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1381]
**Data Validation:**
This card is to implement data validation for Schedule B of the Compliance Report. 

**Implementation:**
Validation occurs automatically during data entry and must be resolved in order to **save** or **submit** the report. 

**Validation Requirements:**

- Entry rows containing data must be complete (i.e. each editable cell must be filled out within an entry row that contains data; no partially complete rows)
- Quantity of Fuel Supplied column:
 - Only whole numbers (no decimals)
 - Only positive numbers (no negative or zero)
- No duplicates (see below)

**Duplicates Definition - Schedule B:**
There are three different types of duplicates that we want to prevent: 

**(1)** A duplicate for Schedule B in this first case means that all of the following are identical for two or more row entries:

- Fuel Type
- Fuel Class
- The following Provisions of the Act:
 - Section 6 (5) (a) - Prescribed carbon intensity
 - Section 6 (5) (b) - Prescribed carbon intensity
 - Section 6 (5) (d) (i) - Default Carbon Intensity Value

**(2)** No duplicate Fuel Codes (i.e. only one BCLCF133.2)

**(3)** No duplicate GHGenius modelled selections

**Validation Errors Communication Design:**

- See attached screenshot
- Highlight problem cells/rows in red
- Error messages displayed in red (at the top?). If we do decide to display the error messages at the top, then we should not show the messages during data entry as this will push the report down on the screen; we would need to find a more graceful way to show the errors (when saving?)

**Error message wording**

- There is missing information, please ensure all fields are completed.
- The Quantity of Fuel Supplied cannot contain a zero, negative or decimal value.
- There are duplicate trade details, please combine the quantity into a single value on one row.
- A GHGenius Fuel Code was not found, please create a record in Schedule D.

https://trello.com/c/lFpP7RVW/1713-validation-schedule-b-16#

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validation | Schedule B |16| v1.4.25](https://trello.com/c/lFpP7RVW/1713-validation-schedule-b-16)

**Comment by KMenke** [comment]
Resolved in sprint tunguska
