### ISSUE TITLE
Validation | Schedule A |5| v1.4.25

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1383]
**Data Validation:**
This card is to implement data validation for Schedule A of the Compliance Report. 

**Implementation:**
Validation occurs automatically during data entry and must be resolved in order to **save** or **submit** the report. 

- Q: Could we allow saving but not submitting? A: Data integrity issues with saving un-properly formatted data to the data base

**Validation Requirements:**

- Entry rows containing data must be complete (i.e. each editable cell must be filled out within an entry row that contains data; no partially complete rows)
- Quantity (L) column:
 - Only whole numbers (no decimals)
 - Only positive numbers (no negative or zero)
- No duplicates (see below)

**Duplicates Definition - Schedule A:**
A duplicate for Schedule A means that all of the following are identical for two or more row entries:

- Legal Name of Trading Partner
- Postal Address
- Fuel Class
- Received or Transferred

**Validation Errors Communication Design:**

- See attached screenshot
- Highlight problem cells/rows in red
- Error messages displayed in red (at the top?). If we do decide to display the error messages at the top, then we should not show the messages during data entry as this will push the report down on the screen; we would need to find a more graceful way to show the errors (when saving?)

**Error message wording**

- There is missing information, please ensure all fields are completed.
- The Quantity of Fuel Supplied cannot contain negative or decimal values.
- There are duplicate trade records, please combine the Quantity into a single value on one row.

https://trello.com/c/MyTC4z30/1712-validation-schedule-a-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validation | Schedule A |5| v1.4.25](https://trello.com/c/MyTC4z30/1712-validation-schedule-a-5)

**Comment by KMenke** [comment]
resolved in sprint tunguska
