### ISSUE TITLE
Validation | Schedule D |8| v1.4.25

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1386]
**Data Validation:**
This card is to implement data validation for Schedule D of the Compliance Report. The validation within this schedule is being kept intentionally minimal; this is because this schedule can be used in a variety of ways, which makes implementing validation difficult.

**Implementation:**
Validation occurs automatically during data entry and must be resolved in order to **save** or **submit** the report. 

**Validation Requirements:**

- If one or more of Part 3 Fuel Type, Feedstock, or Fuel Class cells contain data, then: 
 - All three must contain data (can't be blank): Part 3 Fuel Type, Feedstock, Fuel Class
 - All 12 output table cells must contain data (can't be blank). Note: positive, negative, or zero value counts as data in this case. 

**Validation Errors Communication Design:**

- See attached screenshot
- Highlight problem cells/rows in red
- Error messages displayed in red (at the top?). If we do decide to display the error messages at the top, then we should not show the messages during data entry as this will push the report down on the screen; we would need to find a more graceful way to show the errors (when saving?)

https://trello.com/c/oohcjZ7B/1715-validation-schedule-d-8

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validation | Schedule D |8| v1.4.25](https://trello.com/c/oohcjZ7B/1715-validation-schedule-d-8)

**Comment by KMenke** [comment]
resolved in sprint ursa major
