### ISSUE TITLE
Compliance Report | Grant permission to analyst to see submitted compliance reports |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1389]
As part of this card, have an organization column appear in the main compliance reporting table (IDIR only)

https://trello.com/c/HNG3OTXn/1951-compliance-report-grant-permission-to-analyst-to-see-submitted-compliance-reports-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Grant permission to analyst to see submitted compliance reports |2|](https://trello.com/c/HNG3OTXn/1951-compliance-report-grant-permission-to-analyst-to-see-submitted-compliance-reports-2)

**Comment by KMenke** [comment]
resolved in sprint ursa major
