### ISSUE TITLE
Compliance Report | Gov Analyst Recommend Acceptance |8|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1392]
**Story:** 
As a Government Analyst, I want to be able to recommend acceptance of a compliance report. 

**Scenario:**
GIVEN that I am an IDIR user
AND I have the Government Analyst role
AND I am viewing a submitted Compliance Report (i.e. status = Submitted)
AND I am on the Summary page
WHEN I click on the Recommend Acceptance button
AND I accept the confirmation alert
THEN I am returned to the main compliance reporting page
AND the status of the report in the UI changes to Reviewed - Analyst (back-end status should be "Recommended Acceptance - Analyst")
AND a report history record is created (see below)
AND a system alert appears on the screen

**Status update visibility:**

- The status change should only be visible to IDIR users. For BCeID users, the status should remain at Submitted. 

**Report History Record:**
A report history record should be created when the Gov't Analyst recommends acceptance of the report. The format should be as follows: 

- Reviewed and <**Status**> on Month DD, YYYY by <**First, Last Name**> of <**Organization Name**>
- Example: **Reviewed** and **Recommended Acceptance** on March 31, 2019 by **Justin Lepitzki** of **Government of British Columbia**

**Note:** This report history record should **only be visible to IDIR users**.

**Confirmation Alert Messaging:**

- Are you sure you want to recommend acceptance of the compliance report? 

**System Alert Messaging:**

- Acceptance Recommended

https://trello.com/c/uEIlr2hV/1670-compliance-report-gov-analyst-recommend-acceptance-8

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Gov Analyst Recommend Acceptance |8|](https://trello.com/c/uEIlr2hV/1670-compliance-report-gov-analyst-recommend-acceptance-8)

**Comment by KMenke** [comment]
resolved in sprint ursa major
