### ISSUE TITLE
Exclusion Report | Quantity |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1394]
**Info:**

This card is to create the Quantity column, which is used to indicate the quantity of fuel that was purchased/sold under an exclusion agreement. 

**Quantity:**

- Entered as a positive, whole number (no decimals, no negative values)
- Would be beneficial if the number could be formatted to place a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423 (preferably as you type)

https://trello.com/c/tWgEWxDV/1559-exclusion-report-quantity-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Quantity |1|](https://trello.com/c/tWgEWxDV/1559-exclusion-report-quantity-1)

**Comment by KMenke** [comment]
Resolved in sprint ursa major
