### ISSUE TITLE
Exclusion Report | Units |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1395]
**Info:**

This card is to create the **two** Units column. 

**Design:**

- This column will employ the same functionality as the units columns within Schedule B & C. That is, the two units columns within this report should autopopulate the corresponding unit value based on the Fuel Type selected.
- These cells should not be editable

https://trello.com/c/M4ODkVG6/1560-exclusion-report-units-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Units |1|](https://trello.com/c/M4ODkVG6/1560-exclusion-report-units-1)

**Comment by KMenke** [comment]
resolved in sprint ursa major
