### ISSUE TITLE
Exclusion Report | Quantity not sold or supplied within the Compliance Period |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1396]
**Info:**

This card is to create the "Quantity not sold or supplied within the Compliance Period" column.

**Quantity:**

- Entered as a positive, whole number (no decimals, no negative values)
- Would be beneficial if the number could be formatted to place a comma every 3 digits. We are dealing with large volumes and unformatted number values can be difficult to read at a glance. For example, instead of 4327423 have it display on the screen as 4,327,423 (preferably as you type)
- Logic restriction: This value cannot be larger than the quantity reported in the quantity column. 

https://trello.com/c/yNHjIogp/1561-exclusion-report-quantity-not-sold-or-supplied-within-the-compliance-period-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Quantity not sold or supplied within the Compliance Period |1|](https://trello.com/c/yNHjIogp/1561-exclusion-report-quantity-not-sold-or-supplied-within-the-compliance-period-1)

**Comment by KMenke** [comment]
resolved in sprint ursa major
