### ISSUE TITLE
Exclusion Report | Save a draft |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1399]
**Story:**
As a BCeID user, I want to be able to save a draft of an Exclusion Report so that I can save the work I have entered into the Report before submitting it to government.  

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role
AND I am on the Compliance Reporting page
AND I have created a new Exclusion Report
AND I am viewing the New Exclusion Report
WHEN I click on the Save Draft button
THEN the Exclusion Report is saved as a draft
AND I am returned to the Compliance Reporting section of TFRS ([Card 1228](https://trello.com/c/swV6FKKK/1228-compliance-report-view-compliance-reporting-materials-0))
AND a system alert appears informing me that the draft has been saved ([Card 1568](https://trello.com/c/J6dcmwLj/1568-system-alerts-save-a-draft-exclusion-report-1))
AND the saved draft entry in the Compliance Reporting table is highlighted yellow (similar to credit transactions table)
AND the status of the entry changes to Draft

https://trello.com/c/ZslHs17z/1563-exclusion-report-save-a-draft-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Save a draft |5|](https://trello.com/c/ZslHs17z/1563-exclusion-report-save-a-draft-5)

**Comment by KMenke** [comment]
resolved in sprint ursa major
