### ISSUE TITLE
System Alerts | Save a Draft Exclusion Report |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1400]
**Task:**
Create system alert for successfully Saving a draft Exclusion Report

**Messaging:**
"Draft saved"

https://trello.com/c/J6dcmwLj/1568-system-alerts-save-a-draft-exclusion-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System Alerts | Save a Draft Exclusion Report |1|](https://trello.com/c/J6dcmwLj/1568-system-alerts-save-a-draft-exclusion-report-1)

**Comment by KMenke** [comment]
resolved in sprint ursa major
