### ISSUE TITLE
Exclusion Report | Edit a draft |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1401]
**Story:**
As a BCeID user, I want to be able to edit a saved draft of an Exclusion Report so that I can continue filling out the report that I had previously saved. 

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role
AND I am on the Compliance Reporting page
AND I have saved a draft of an Exclusion Report
WHEN I click on the draft entry in the Compliance Reporting table
THEN I am taken to the Introduction page of the Exclusion Report
AND I am able to edit the contents of the report

https://trello.com/c/D6knfdFA/1564-exclusion-report-edit-a-draft-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Edit a draft |3|](https://trello.com/c/D6knfdFA/1564-exclusion-report-edit-a-draft-3)

**Comment by KMenke** [comment]
resolved in sprint ursa major
