### ISSUE TITLE
Compliance Report D | Allow more than two decimals and negative values in schedule D output table |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1405]
In the output table, we want to **allow** more than 2 decimals and negative values. **Note:** this should only be allowed for the output table in Schedule D, and not for the rest of the compliance report fields. 

https://trello.com/c/z4bgBib0/1737-compliance-report-d-allow-more-than-two-decimals-and-negative-values-in-schedule-d-output-table-2

**Comment by KMenke** [comment]
resolved in sprint tunguska
