### ISSUE TITLE
Compliance Report D | Output table not recognizing pasted number values from Excel |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1406]
**Issue:**
The output table in Schedule D is not recognizing some number values pasted from an excel workbook. The user can paste the values, and they show up in the corresponding cells, however, they are not being included in the totals at the bottom of the output table. 

**Example:**

- Screenshot attached showing numbers pasted from an example excel workbook (also attached) not being recognized in the calculation of the total value at the bottom of the output table. 

https://trello.com/c/iaxHlFiH/1740-compliance-report-d-output-table-not-recognizing-pasted-number-values-from-excel-2

**Comment by KMenke** [comment]
resolved in sprint ursa major
