### ISSUE TITLE
Compliance Report | Gov Analyst Recommend Rejection |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1413]
**Story:** 
As a Government Analyst, I want to be able to recommend rejection of a compliance report. 

**Scenario:**
GIVEN that I am an IDIR user
AND I have the Government Analyst role
AND I am viewing a submitted Compliance Report (i.e. status = Submitted)
AND I am on the Summary page
WHEN I click on the Recommend Rejection button
AND I accept the confirmation alert
THEN I am returned to the main compliance reporting page
AND the status of the report in the UI changes to Reviewed - Analyst (back-end status should be "Recommended Rejection - Analyst")
And a report history record is created (see below)
AND a system alert appears on the screen

**Status update visibility:**

- The status change should only be visible to IDIR users. For BCeID users, the status should remain at Submitted. 

**Report History Record:**
A report history record should be created when the Gov't Analyst recommends rejection of the report. The format should be as follows: 

- Reviewed and <**Status**> on Month DD, YYYY by <**First, Last Name**> of <**Organization Name**>
- Example: **Reviewed** and **Recommended Rejection** on March 31, 2019 by **Justin Lepitzki** of **Government of British Columbia**

**Note:** This report history record should **only be visible to IDIR users**.

**Confirmation Alert Messaging:**

- Are you sure you want to recommend rejection of the compliance report? 

**System Alert Messaging:**

- Rejection Recommended

https://trello.com/c/4HfyILRV/1671-compliance-report-gov-analyst-recommend-rejection-3

**Comment by KMenke** [comment]
resolved in sprint vulcan
