### ISSUE TITLE
Compliance Report | Compliance Manager Recommend Acceptance |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1417]
**Story:** 
As a Compliance Manager, I want to be able to recommend acceptance of a compliance report. 

**Scenario:**
GIVEN that I am an IDIR user
AND I have the Compliance Manager role
AND I am viewing a reviewed Compliance Report (i.e. front-end status = Reviewed - Analyst; back-end status = Recommended Acceptance - Analyst or Recommended Rejection - Analyst)
AND I am on the Summary page
WHEN I click on the Recommend Acceptance button
AND I accept the confirmation alert
THEN I am returned to the main compliance reporting page
AND the status of the report in the UI changes to Reviewed - Manager (back-end status should be "Recommended Acceptance - Manager")
AND a report history record is created (see below)
AND a system alert appears on the screen

**Status update visibility:**

- The status change should only be visible to IDIR users. For BCeID users, the status should remain at Submitted. 

**Report History Record:**
A report history record should be created when the Compliance Manager recommends acceptance of the report. The format should be as follows: 

- Reviewed and <**Status**> on Month DD, YYYY by <**First, Last Name**> of <**Organization Name**>
- Example: **Reviewed** and **Recommended Acceptance** on March 31, 2019 by **Justin Lepitzki** of **Government of British Columbia**

**Note:** This report history record should **only be visible to IDIR users**.

**Confirmation Alert Messaging:**

- Are you sure you want to recommend acceptance of the compliance report? 

**System Alert Messaging:**

- Acceptance Recommended

https://trello.com/c/ceLhQMaU/1674-compliance-report-compliance-manager-recommend-acceptance-3

**Comment by KMenke** [comment]
resolved in sprint vulcan
