### ISSUE TITLE
Compliance Report | Director Accept report |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1420]
**Story:** 
As a Director, I want to be able to Accept a compliance report. 

**Scenario:**
GIVEN that I am an IDIR user
AND I have the Director role
AND I am viewing a reviewed Compliance Report (i.e. front-end status = Reviewed - Manager; back-end status = Recommended Acceptance - Manager or Recommended Rejection - Manager)
AND I am on the Summary page
WHEN I click on the Accept button
AND I accept the confirmation alert
THEN I am returned to the main compliance reporting page
AND the status of the report in the UI changes to Accepted (back-end status should be Accepted, then Completed; but remain Accepted in the UI)
AND a report history record is created (see below)
AND a system alert appears on the screen
AND the credit balance increases or decreases accordingly
AND a corresponding credit transaction entry is created. 

**Status update visibility:**

- The status change should be visible to both BCeID and IDIR users. 

**Report History Record:**
A report history record should be created when the Director accepts the report. The format should be as follows: 

- <**Status**> on Month DD, YYYY by <**First, Last Name**>, <**Director Role**> under the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*.
- Example: **Accepted** on March 31, 2019 by **Justin Lepitzki**, **Deputy Director** under the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*.

**Confirmation Alert Messaging:**

- Are you sure you want to accept this compliance report? 

**System Alert Messaging:**

- Compliance report accepted 

https://trello.com/c/qS2J5Wlv/1682-compliance-report-director-accept-report-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Director Accept report |3|](https://trello.com/c/qS2J5Wlv/1682-compliance-report-director-accept-report-3)

**Comment by KMenke** [comment]
resolved in sprint vulcan
