### ISSUE TITLE
Exclusion Report | Delete a draft |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1422]
**Story:**
As a BCeID user, I want to be able to delete a saved draft of an Exclusion Report so that I can delete draft reports that are no longer needed. 

**Scenario:**
GIVEN that I am a BCeID user
AND I have the Compliance Reporting role
AND I am on the Compliance Reporting page
AND I have saved a draft of an Exclusion Report
AND I am viewing the saved draft Exclusion Report
WHEN I click on the Delete button
THEN I receive a confirmation alert asking me to confirm deletion ([Card 1566](https://trello.com/c/3egKyHQO/1566-confirmation-alerts-delete-a-saved-draft-exclusion-report-1))
AND confirming deletion deletes the draft Exclusion Report (i.e. archives)
AND I am returned to the Compliance Reporting section of TFRS ([Card 1228](https://trello.com/c/swV6FKKK/1228-compliance-report-view-compliance-reporting-materials-0))
AND a system alert appears informing me that the draft has been deleted (i.e. archived) ([Card 1567](https://trello.com/c/nuow2RcH/1567-system-alerts-delete-a-saved-draft-exclusion-report-1))
AND the previously saved draft entry is no longer visible in the Compliance Reporting table

**Note:**
Best practice for data management dictates that we archive the draft and not actually delete it

https://trello.com/c/sdX9QLJn/1565-exclusion-report-delete-a-draft-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Delete a draft |2|](https://trello.com/c/sdX9QLJn/1565-exclusion-report-delete-a-draft-2)

**Comment by KMenke** [comment]
resolved in sprint vulcan
