### ISSUE TITLE
Confirmation Alerts | Delete a Saved Draft Exclusion Report |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1423]
**Task:**
Create confirmation alert for deleting a Saved Draft Exclusion Report

**Messaging:**
"Are you sure you want to delete the draft Exclusion Report?"

https://trello.com/c/3egKyHQO/1566-confirmation-alerts-delete-a-saved-draft-exclusion-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confirmation Alerts | Delete a Saved Draft Exclusion Report |1|](https://trello.com/c/3egKyHQO/1566-confirmation-alerts-delete-a-saved-draft-exclusion-report-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
