### ISSUE TITLE
System Alerts | Delete a Saved Draft Exclusion Report |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1424]
**Task:**
Create system alert for successfully Deleting a Saved Draft Exclusion Report

**Messaging:**
"Draft deleted"

https://trello.com/c/nuow2RcH/1567-system-alerts-delete-a-saved-draft-exclusion-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System Alerts | Delete a Saved Draft Exclusion Report |1|](https://trello.com/c/nuow2RcH/1567-system-alerts-delete-a-saved-draft-exclusion-report-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
