### ISSUE TITLE
Compliance Report | Optimize save submit when there are validation errors |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1426]
**Task:**

This card is to "optimize" the save and submit functions when there validation errors. 

**Save:**

- Current state: button is greyed out and tooltip appears with back-end language
- Desired state: button is greyed out, tooltip says "Please fix validation errors before saving."

**Submit:**

- Current state: button is clickable, receive "Error saving" system alert after completing declaration and trying to submit
- Desired state: button is greyed out, tooltip says "Please fix validation errors before submitting."

https://trello.com/c/XoKdxQja/1965-compliance-report-optimize-save-submit-when-there-are-validation-errors-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Optimize save submit when there are validation errors |1|](https://trello.com/c/XoKdxQja/1965-compliance-report-optimize-save-submit-when-there-are-validation-errors-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
