### ISSUE TITLE
Exclusion Report | Declaration section |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1428]
**Task:**
This card is to create the confirmation alert for when a user clicks on the Submit button within the Exclusion Agreements section of the Exclusion Report. The confirmation alert contains:

- The Signing Authority Declaration 
- Messaging for confirming submission 
- Submit and Cancel buttons

**Signing Authority Declaration Section:**
This section will use a similar component as the Signing Declaration in the Compliance Reporting feature, but with different statements (specified in the legislation). See the attached screenshot for an example but please **note that the statements in the screenshot are different than the ones we will be using here**. 

- Heading: Signing Authority Declaration
- I, <user first, last name>, <title>:
- certify that records evidencing each matter reported under section 11.032 (4) (b) or (c) of the Renewable and Low Carbon Fuel Requirements Regulation are available on request.
- certify that records evidencing my authority to submit this report are available on request.
- certify that the information in this report is true and complete to the best of my knowledge and I understand that I may be required to provide to the Director records evidencing the truth of that information.

**Confirmation alert messaging:**
Following the declaration section, the following statement should appear: 

- Are you sure you want to submit this Exclusion Report to the Government of British Columbia?

Followed by two buttons:

- Yes
- No

**Additional Requirements:**

- If the user does not have a title then do not show anything for that portion of the declaration. For example, with no title, it should read "I, First Last Name:"
- Similar to the Compliance Reporting feature, each checked box should be recorded in the database (when it was checked, the user that checked it, etc.) 
- The Submit button should be greyed out until **all three** checkboxes have been checked. 

**Role Restrictions - Signing Authority:**

- The Signing Authority role can check the boxes
- Tooltip: hovering the mouse over the Yes button **before** checking all four boxes displays the following tool tip: "Please complete the Signing Authority declaration".

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Declaration section |3|](https://trello.com/c/GBjPoKJJ/1527-exclusion-report-declaration-section-3)

**Comment by KMenke** [comment]
resolved in sprint vulcan
