### ISSUE TITLE
Exclusion Report | Submitting report changes data to read only |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1431]
**Task:**

When a fuel supplier successfully submits an exclusion report, the inputted data should be saved and the report should change to read-only. 

**Read-only:**
Read-only in this case means that no further changes can be made to the report, including no changes:

- By a BCeID user (i.e. the fuel supplier who submitted the report)
- By an IDIR user (i.e. the gov users who receive and review the submitted report)

https://trello.com/c/OA3p3l8u/1669-exclusion-report-submitting-report-changes-data-to-read-only-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Submitting report changes data to read only |2|](https://trello.com/c/OA3p3l8u/1669-exclusion-report-submitting-report-changes-data-to-read-only-2)

**Comment by KMenke** [comment]
resolved in sprint vulcan
