### ISSUE TITLE
Exclusion Report | Submit an Exclusion Report |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1432]
**Story:**
As a fuel supplier user, I want to be able to submit an exclusion report to government so that I can fulfill my legislated obligations.

**Scenario:**
GIVEN that I am a fuel supplier user
AND I have the Signing Authority role
AND I am on the Exclusion Agreements page
WHEN I click on the Submit button
THEN a confirmation alert appears asking me to complete the declaration section, completed in **[Card 1527](https://trello.com/c/GBjPoKJJ/1527-exclusion-report-declaration-section-0)**. 
AND I am able to confirm submission only after the declaration section has been completed
AND confirming the submission submits the report
AND a Transaction History record is created, completed in **[Card 1586](https://trello.com/c/47KXyq7a/1586-exclusion-report-exclusion-report-history-records-0)**.
AND I am returned to the main Compliance Reporting page
AND the status of the Exclusion Report updates to Submitted

**Role Restrictions:**

- Only the Signing Authority role can click the Submit button
- The button should be greyed out for a user with the Compliance Reporting role 
- Tooltip: hovering the mouse over the greyed out Submit button displays the following tool tip: "You must have the Signing Authority role to submit an Exclusion Report to the Government of British Columbia."

**Task:**
Create an exclusion report history record when submitting an exclusion report. Similar to the transaction history record in the Credit Transfer feature (see attached screenshot), we want to track who signed and submitted the exclusion report. 

**History Record:**
The record should follow the same format as the Compliance Report:

- <**Status**> on Month DD, YYYY by <**First, Last Name**> of <**Organization Name**>
- Example: **Submitted** on March 31, 2019 by **Billy Biodiesel** of **TFRS Fantastic Fuels**

This entry should be visible to both the fuel supplier and government for all roles that can access the compliance reporting feature (compliance reporting role, Signing Authority, all government roles).

**System Alert:**

- "Exclusion Report submitted"

https://trello.com/c/tflmLmaQ/1554-exclusion-report-submit-an-exclusion-report-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Create a submission snapshot |8|](https://trello.com/c/gIUeVGpM/1971-exclusion-report-create-a-submission-snapshot-8)

**Comment by KMenke** [comment]
resolved in sprint vulcan
