### ISSUE TITLE
Compliance Report | Line 28 penalty not displaying in a net debit situation until after a value has been entered into Line 26 |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1444]
**Issue:**
See attached screenshot. Line 28 is not displaying a penalty value when in a net debit situation. Entering any value into Line 26 (even zero) causes the Line 28 to populate. 

**Desired State:**
Line 28 displays the penalty amount when in a net debit situation immediately and does not require a value entered into Line 26 (before displaying)

https://trello.com/c/iXmwAy0Y/1978-compliance-report-line-28-penalty-not-displaying-in-a-net-debit-situation-until-after-a-value-has-been-entered-into-line-26-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Line 28 penalty not displaying in a net debit situation until after a value has been entered into Line 26 |1|](https://trello.com/c/iXmwAy0Y/1978-compliance-report-line-28-penalty-not-displaying-in-a-net-debit-situation-until-after-a-value-has-been-entered-into-line-26-1)

**Comment by KMenke** [comment]
Resolved in sprint vulcan.
