### ISSUE TITLE
Compliance Report | Entering a value into Line 26 causes the summary page to briefly display a validation error message before the page reloads |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1445]
**Issue:**
In a net debit situation, entering a value into line 26 and hitting enter causes the summary page to "disappear" and briefly display a validation error message; the summary page then reappears with the value you entered into Line 26. 

https://trello.com/c/oO8H56bH/1979-compliance-report-entering-a-value-into-line-26-causes-the-summary-page-to-briefly-display-a-validation-error-message-before-the

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Entering a value into Line 26 causes the summary page to briefly display a validation error message before the page reloads |2|](https://trello.com/c/oO8H56bH/1979-compliance-report-entering-a-value-into-line-26-causes-the-summary-page-to-briefly-display-a-validation-error-message-before-the)

**Comment by KMenke** [comment]
resolved in sprint vulcan
