### ISSUE TITLE
Compliance Report | Left align Status column on main compliance reporting page |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1447]
**Task:**
Left align the status text in the Status column on the main compliance reporting page. 

- See attached screenshot

https://trello.com/c/iKP91oxi/1981-compliance-report-left-align-status-column-on-main-compliance-reporting-page-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Left align Status column on main compliance reporting page |1|](https://trello.com/c/iKP91oxi/1981-compliance-report-left-align-status-column-on-main-compliance-reporting-page-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
