### ISSUE TITLE
Validation | Revise validation messaging |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1448]
**Task:** 
This card is to revise some of the data validation error messages

**Schedules A, B, C:**

- Current message: "The Quantity of Fuel Supplied cannot contain a zero, negative or decimal value."
 - Revised message: "The quantity of fuel cannot be zero, negative, or contain a decimal value." 
- Current message: "There are duplicate trade records, please combine the Quantity into a single value on one row."
 - Revised message: "There are duplicate entries, please combine the quantity into a single value on one row." 

**Schedule B:**

- Current message: "A GHGenius Fuel Code was not found, please create a record in Schedule D."
 - Revised message: "A GHGenius Modelled entry was not found, please create a record in Schedule D." 

https://trello.com/c/QcjbFmAf/1964-validation-revise-validation-messaging-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validation | Revise validation messaging |1|](https://trello.com/c/QcjbFmAf/1964-validation-revise-validation-messaging-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
