### ISSUE TITLE
Compliance Report | Floating windows block report data when viewing a submitted report |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1451]
**Current State:**
When viewing a submitted compliance report, the floating windows in the different schedules block a portion of the last row entry. See attached screenshots. 

**Desired State:**
Provide enough blank space below the last row entry to fit the floating windows without blocking any data. 

https://trello.com/c/0jwsnmt0/1969-compliance-report-floating-windows-block-report-data-when-viewing-a-submitted-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Floating windows block report data when viewing a submitted report |1|](https://trello.com/c/0jwsnmt0/1969-compliance-report-floating-windows-block-report-data-when-viewing-a-submitted-report-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
