### ISSUE TITLE
Validation | Optimize Schedule D validation |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1454]
**Issue:**
The Schedule D validation error (*"There is missing information, please ensure all fields are completed."*) is being thrown while working in other schedules (e.g. Schedule B) or by viewing Schedule D (without entering any data). 

**Solution:**
Adjust the validation check to require that at least one field has inputted data before checking for empty cells. 

https://trello.com/c/UBZmOw84/1966-validation-optimize-schedule-d-validation-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validation | Optimize Schedule D validation |2|](https://trello.com/c/UBZmOw84/1966-validation-optimize-schedule-d-validation-2)

**Comment by KMenke** [comment]
resolved in sprint vulcan
