### ISSUE TITLE
Validation | Identify the specific schedule when there are validation errors in other schedules |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1455]
**Task:** 
This card is to identify the specific schedule(s) that have validation errors when viewing a different schedule. Currently, we use the message "Errors found in other schedules". The new feature would say "Errors found in schedule A and B", for example. 

- Keep the error message in one line

https://trello.com/c/mhBOAtZW/1967-validation-identify-the-specific-schedule-when-there-are-validation-errors-in-other-schedules-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validation | Identify the specific schedule when there are validation errors in other schedules |1|](https://trello.com/c/mhBOAtZW/1967-validation-identify-the-specific-schedule-when-there-are-validation-errors-in-other-schedules-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
