### ISSUE TITLE
Compliance Report | Adjust tooltip description for offsetting credits credit balance restriction |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1456]
**Current Message:**

- "Cannot be more than <xx,xxx>. This cannot be higher than the organization's credit nor the net debit."

**Revised Message:**

- "Cannot be more than <xx,xxx>. The value entered here cannot be more than your organization's credit balance or the net debit balance in Line 25." 

https://trello.com/c/HEkN5bk5/1738-compliance-report-adjust-tooltip-description-for-offsetting-credits-credit-balance-restriction-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Adjust tooltip description for offsetting credits credit balance restriction |1|](https://trello.com/c/HEkN5bk5/1738-compliance-report-adjust-tooltip-description-for-offsetting-credits-credit-balance-restriction-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
