### ISSUE TITLE
Compliance Report | Minor UI adjustments to Summary section |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1457]
**(1)**

- Remove the Amount Enclosed row within the penalty payable section of the summary page. This section was included by mistake and will not be relevant for TFRS. 

**(2)**

- For Line 26, adjust label to read "Banked credits used to offset outstanding debits (if applicable)" 
- For Line 27, adjust label to read "Outstanding debit balance"; the change here is the use of lower case for "debit balance"

https://trello.com/c/9jlZ5fJH/1644-compliance-report-minor-ui-adjustments-to-summary-section-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Minor UI adjustments to Summary section |1|](https://trello.com/c/9jlZ5fJH/1644-compliance-report-minor-ui-adjustments-to-summary-section-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
