### ISSUE TITLE
Compliance Report B | Adjust fuel code label to account for Schedule D entries |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1458]
**Location & Task:**

- Location: Schedule B, "Fuel Code (if applicable)" column
- Task: revise label to account for new Schedule D reporting feature within Schedule B

**Current Label:**

- "Fuel Code (if applicable)"

**Revised Label:**

- "Fuel Code or Schedule D Entry (if applicable)"

https://trello.com/c/dhxNRT7K/1658-compliance-report-b-adjust-fuel-code-label-to-account-for-schedule-d-entries-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Adjust fuel code label to account for Schedule D entries |1|](https://trello.com/c/dhxNRT7K/1658-compliance-report-b-adjust-fuel-code-label-to-account-for-schedule-d-entries-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
