### ISSUE TITLE
Exclusion Report | Minor adjustments to UI language |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1459]
**Tooltip when submitting Exclusion report without the Signing Authority role:**

- Current Message: "You must have the Signing Authority role to submit a Exclusion Report to the Government of British Columbia." 
- Revised Message: "You must have the Signing Authority role to submit an Exclusion Report to the Government of British Columbia." 
 - Difference is "an" before Exclusion Report rather than "a" 

**Signing Authority Declaration Confirmation Alert:**

- Current Message: "Are you sure you want to submit this Compliance Report to the Government of British Columbia?" 
- Revised Message: "Are you sure you want to submit this Exclusion Report to the Government of British Columbia?" 
 - "Exclusion" instead of "Compliance" 

**System Alert when Submitting Exclusion Report:**

- Current Message: "Compliance Report submitted"
- Revised Message: "Exclusion Report submitted"

https://trello.com/c/UzzkathD/1986-exclusion-report-minor-adjustments-to-ui-language-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Minor adjustments to UI language |1|](https://trello.com/c/UzzkathD/1986-exclusion-report-minor-adjustments-to-ui-language-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
