### ISSUE TITLE
Exclusion Report | Hide or Remove Add Row button for a Submitted Exclusion Report |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1461]
**Current State:**
When an Exclusion Report is submitted, the data changes to read only and cannot be edited (**[Card 1669](https://trello.com/c/OA3p3l8u/1669-exclusion-report-submitting-report-changes-data-to-read-only-2v151)**). Currently, the "Add Row" functionality remains on a Submitted Exclusion Report. The BCeID user is able to add new rows and enter data, although they cannot save this data. 

**Desired State:**
Hide or Remove the "Add Row" button as part of the read only process. When an Exclusion Report is submitted, a BCeID user should not be able to add new rows and/or data to the report. The "Add Row" button should remain hidden for the rest of the Exclusion Report workflow after submission. 

- **Note:** IDIR users can also see the "Add Row" button (v1.5.2). This card show also remove/hide this functionality for IDIR users as well. 

https://trello.com/c/2vR83EgG/1987-exclusion-report-hide-or-remove-add-row-button-for-a-submitted-exclusion-report-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Hide or Remove Add Row button for a Submitted Exclusion Report |1|](https://trello.com/c/2vR83EgG/1987-exclusion-report-hide-or-remove-add-row-button-for-a-submitted-exclusion-report-1)

**Comment by KMenke** [comment]
resolves in sprint vulcan
