### ISSUE TITLE
Compliance Report | Government Analyst can't access main Compliance Reporting page in Nav bar |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1462]
**Issue:**
Dev Environment (v1.5.2): the government analyst role cannot see the Compliance Reporting link in the main nav bar. 

- A permission issue? 

https://trello.com/c/JGiXWsXw/1988-compliance-report-government-analyst-cant-access-main-compliance-reporting-page-in-nav-bar-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Government Analyst can't access main Compliance Reporting page in Nav bar |1|](https://trello.com/c/JGiXWsXw/1988-compliance-report-government-analyst-cant-access-main-compliance-reporting-page-in-nav-bar-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
