### ISSUE TITLE
Exclusion Report | Minor adjustments to UI language Part 2 |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1463]
**System Alert when Director Accepts an Exclusion Report:**

- Current Message: "Compliance Report Accepted"
- Revised Message: "Exclusion Report accepted"

**System Alert when Director Rejects an Exclusion Report:**

- Current Message: "Compliance Report Rejected"
- Revised Message: "Exclusion Report rejected"

https://trello.com/c/SRjKJZZU/1989-exclusion-report-minor-adjustments-to-ui-language-part-2-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Minor adjustments to UI language Part 2 |1|](https://trello.com/c/SRjKJZZU/1989-exclusion-report-minor-adjustments-to-ui-language-part-2-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
