### ISSUE TITLE
Compliance Report A | Do not show decimal values in totals floating window |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1464]
Hide decimals in totals floating window display

https://trello.com/c/K24QVYKH/1739-compliance-report-a-do-not-show-decimal-values-in-totals-floating-window-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report A | Do not show decimal values in totals floating window |1|](https://trello.com/c/K24QVYKH/1739-compliance-report-a-do-not-show-decimal-values-in-totals-floating-window-1)

**Comment by KMenke** [comment]
resolved in sprint vulcan
