### ISSUE TITLE
Compliance Report | Request Supplemental Report |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1469]
**Story:** 
As an IDIR user, I want to be able to request a supplemental report for a compliance report I am reviewing. 

**Scenario 1:**
GIVEN that I am an IDIR user
AND I have the **Government Analyst role**
AND I am viewing a submitted Compliance Report (i.e. status = Submitted)
AND I have inputted a regular comment, see **[Card 1750](https://trello.com/c/SxKwyfxf/1750-compliance-report-require-a-comment-when-requesting-a-supplemental-report-0)**
WHEN I click on the Request Supplemental button
AND I accept the confirmation alert
THEN I am returned to the main compliance reporting page
AND the status of the report changes to Requested Supplemental 
AND a report history record is created (see below)
AND a system alert appears on the screen confirming that the supplemental has been requested

**Scenario 2:**
GIVEN that I am an IDIR user
AND I have the **Compliance Manager** role
AND I am viewing a Compliance Report (i.e. front-end status = Reviewed - Analyst; back-end status = Recommended Acceptance - Analyst or Recommended Rejection - Analyst)
AND I have inputted a regular comment, see **[Card 1750](https://trello.com/c/SxKwyfxf/1750-compliance-report-require-a-comment-when-requesting-a-supplemental-report-0)**
WHEN I click on the Request Supplemental button
AND I accept the confirmation alert
THEN I am returned to the main compliance reporting page
AND the status of the report changes to Requested Supplemental 
AND a report history record is created (see below)
AND a system alert appears on the screen confirming that the supplemental has been requested

**Note:** the scenarios above illustrate when the button should appear, based on the IDIR user's role and the status of the compliance report submission

**Status update visibility:**

- The status change should be visible to both BCeID and IDIR users.

**Report History Record:**
A report history record should also be created . The format should be as follows: 

- <**Status**> on Month DD, YYYY by <**First, Last Name**> of <**Organization Name**>
- Example: **Requested Supplemental** on March 31, 2019 by **Justin Lepitzki** of **Government of British Columbia**

**Confirmation Alert Messaging:**

- Are you sure you want to request a supplemental compliance report? 

**System Alert Messaging:**

- Supplemental Requested

https://trello.com/c/1aZzcgzB/1748-compliance-report-request-supplemental-report-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Request Supplemental Report |5|](https://trello.com/c/1aZzcgzB/1748-compliance-report-request-supplemental-report-5)

**Comment by KMenke** [comment]
resolved in sprint wormhole
