### ISSUE TITLE
Dashboard | BCEID/IDIR Dashboard panel User Settings |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1475]
The User Settings panel displays the user name and title and provides links to notifications and help info.

**Roles:** This panel and information is available to all roles including the Guest role.

**Other information:**

- If the user does not have a title inputted into the database, then show only their name. 

**Fonts and colours** are following DevHub standards:
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/H4dbnZwP/1603-dashboard-bceid-idir-dashboard-panel-user-settings-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | BCEID/IDIR Dashboard panel User Settings |1|](https://trello.com/c/H4dbnZwP/1603-dashboard-bceid-idir-dashboard-panel-user-settings-1)

**Comment by KMenke** [comment]
resolved in sprint wormhole
