### ISSUE TITLE
Dashboard | IDIR Dashboard |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1476]
Create dashboard for IDIR users as the TFRS home page. Note: the deputy director/director roles have a separate version

This dashboard will be the initial screen after logging in with a IDIR account for all roles excluding deputy director which has a separate card 
**([Card 1612](https://trello.com/c/f6fJsNLv/1612-idir-dashboard-deputy-director))**. What is displayed to the user will further depend on what roles they have been assigned.

All IDIR users will see the following components:

- 3 metric panels with content dynamically generated from database queries
 - credit balance search for organizations **([Card 1604](https://trello.com/c/xbt7BrN2/1604-idir-dashboard-metric-all-org-credit-balance))**
 - 12 month average credit dollar value **([Card 1597](https://trello.com/c/74BgEnl6/1597-bceid-idir-dashboard-metric-panel-credit-trading-value))**
 - average business days to approve transfers **([Card 1598](https://trello.com/c/1mSAGIuB/1598-bceid-idir-dashboard-metric-time-to-approve))**
- User Settings **([Card 1603](https://trello.com/c/H4dbnZwP/1603-bceid-idir-dashboard-panel-user-settings))**
 - edit their personal information, name, title, phone number etc.
 - configure notifications
 - read notifications
 - help information

The Gov Analyst, Gov Director and Gov Deputy Director roles will see varying versions of the remaining panels. **The development of these panels will be handled in other Trello cards.** A detailed review of roles and corresponding actions may be required.

The Administrator will have access to the Administrator panel to access the scope of their abilities. **([Card 1611](https://trello.com/c/d7coYauG/1611-idir-dashboard-panel-administration))**

See attachment

https://trello.com/c/W9LIwB9X/1594-dashboard-idir-dashboard-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | IDIR Dashboard |1|](https://trello.com/c/W9LIwB9X/1594-dashboard-idir-dashboard-1)

**Comment by KMenke** [comment]
resolved in sprint wormhole
