### ISSUE TITLE
Dashboard | IDIR Dashboard metric all org credit balance |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1477]
IDIR users will see a metrics panel to display the balance of validated credits for all organizations and the ability to filter to selected organizations from a drop down menu.

**Roles:** Visible to all users

**Fonts and colours** are following DevHub standards:
18px default text size
36px for yellow text
Noto Sans font
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2

https://trello.com/c/xbt7BrN2/1604-dashboard-idir-dashboard-metric-all-org-credit-balance-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | IDIR Dashboard metric all org credit balance |1|](https://trello.com/c/xbt7BrN2/1604-dashboard-idir-dashboard-metric-all-org-credit-balance-1)

**Comment by KMenke** [comment]
resolved in sprint wormhole
