### ISSUE TITLE
Dashboard | IDIR Dashboard panel Credit Transactions |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1478]
The Credit Transactions panel displays links for the various government user roles appropriate to their authorized actions.. It shows the transactions in various states along the approval process and indicates which one require action.

**Roles:**
The following IDIR roles can access the information/links developed within this card: 

- Government Analyst
- Compliance Reporting Manager (this role is not yet created in TFRS)

**Credit Transfers in progress:**

Includes credit transfers with the following statuses: Signed 2 of 2, Reviewed (Recommend/Not recommend)

- n awaiting government analyst review: status = Signed 2 of 2
- n awaiting Director review and statutory decision: status = Reviewed (Recommend/Not recommend)

**Part 3 Awards in progress:**

Includes new credit transactions with a transaction type = Part 3 Award and a status = Reviewed (Recommended)

- n awaiting Director review: status = Reviewed (Recommended)

**Fonts and colours** are following DevHub standards:
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/D9zDGD0j/1607-dashboard-idir-dashboard-panel-credit-transactions-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | IDIR Dashboard panel Credit Transactions |2|](https://trello.com/c/D9zDGD0j/1607-dashboard-idir-dashboard-panel-credit-transactions-2)

**Comment by KMenke** [comment]
resolved in sprint wormhole
