### ISSUE TITLE
IDIR Dashboard panel Compliance & Exclusion Reports​ |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1479]
The Compliance & Exclusion Reports panel displays links for some IDIR roles. It shows the reports in various states along the review process and indicates which one require action.

**Roles:**
The following IDIR roles can access the information/links developed within this card: 

- Government Analyst
- Compliance Reporting Manager (this role is not yet created in TFRS)

**Compliance Reports in progress:**

Includes compliance reports with the following statuses: Submitted, Reviewed 1, Reviewed 2 (status labels TBD)

- n awaiting government analyst review: status = Submitted 
- n awaiting compliance manager review: status = Reviewed 1
- n awaiting Director review: status = Reviewed 2

**Exclusion Reports in progress:**

Includes exclusion reports with the following statuses: Submitted, Reviewed 1, Reviewed 2 (status labels TBD)

- n awaiting government analyst review: status = Submitted 
- n awaiting compliance manager review: status = Reviewed 1
- n awaiting Director review: status = Reviewed 2

**Fonts and colours** are following DevHub standards:
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/Zv9N0ygA/1608-idir-dashboard-panel-compliance-exclusion-reports-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IDIR Dashboard panel Compliance & Exclusion Reports​ |2|](https://trello.com/c/Zv9N0ygA/1608-idir-dashboard-panel-compliance-exclusion-reports-2)

**Comment by KMenke** [comment]
resolved in sprint wormhole
