### ISSUE TITLE
Dashboard | IDIR Dashboard panel Fuel Codes​ |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1480]
The Fuel Codes panel displays links for to gov staff to show fuel codes that are in the process of be approved and a link to see all fuel codes.

**Fuel Codes in progress:**

Includes Fuel Codes in Draft state

- n awaiting Director review and statutory decision: status = Draft

**See all fuel codes:**

- Takes you to the main fuel codes page

**Additional feature:**

- Add a link to new fuel code, which takes you to the new fuel codes page

**Fonts and colours** are following DevHub standards:
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/HIDd78Gf/1609-dashboard-idir-dashboard-panel-fuel-codes-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | IDIR Dashboard panel Fuel Codes​ |2|](https://trello.com/c/HIDd78Gf/1609-dashboard-idir-dashboard-panel-fuel-codes-2)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
