### ISSUE TITLE
IDIR Dashboard panel Administration |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1481]
The Administration panel displays links for to gov staff to manage access for other government staff and to manage fuel supplier organizations. It also provides access to the historical data entry screen.

**Administration Panel Visibility and IDIR Roles:**
For the Government Analyst role, File Submission (Government) role, and Compliance Reporting Manager role (not yet created in TFRS), the user sees:

- View government users (links to Administration > Users)
- Add/edit fuel suppliers (links to IDIR Fuel Suppliers page)
- User activity (links to Administration > User Activity)
- Historical data entry (links to Administration > Historical data entry

For the Administrator role, the user sees everything listed above **and**, 

- Change the label "View government users" to "**Manage government users**" 
- **Extra:** Credit calculation tables (links to Administration > Compliance Reporting)

For the Director and Deputy Director roles, 

- This panel is **not visible** to these roles

**Fonts and colours** are following DevHub standards:
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/d7coYauG/1611-idir-dashboard-panel-administration-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IDIR Dashboard panel Administration |1|](https://trello.com/c/d7coYauG/1611-idir-dashboard-panel-administration-1)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
