### ISSUE TITLE
Dashboard | Adjust nav bar to align with dashboard design |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1486]
Include a Home link in the Nav Bar on the far left (first item on the left)

https://trello.com/c/o3fOZC7A/1973-dashboard-adjust-nav-bar-to-align-with-dashboard-design-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | Adjust nav bar to align with dashboard design |1|](https://trello.com/c/o3fOZC7A/1973-dashboard-adjust-nav-bar-to-align-with-dashboard-design-1)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
