### ISSUE TITLE
Dashboard | BCEID Dashboard |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1487]
Create dashboard for BCEID users as the TFRS home page

The BCeID dashboard will be the initial screen after logging in with a BCeID account. What is displayed to the user will depend on the roles they have been assigned.

The minimum being the Guest role, all BCeID users will see the following components:

- 3 metric panels with content dynamically generated from database queries
 - credit balance for their organization **([Card 1596](https://trello.com/c/Z4ppcGJm/1596-bceid-dashboard-metric-panel-validated-credits))**
 - 12 month average credit dollar value **([Card 1597](https://trello.com/c/74BgEnl6/1597-bceid-idir-dashboard-metric-panel-credit-trading-value))**
 - average days to approve transfers **([Card 1598](https://trello.com/c/1mSAGIuB/1598-bceid-idir-dashboard-metric-time-to-approve))**
- Credit Transactions panel **([Card 1599](https://trello.com/c/2olgJl2r/1599-bceid-dashboard-panel-credit-transactions))** including
 - credit transactions **([Card 1599](https://trello.com/c/2olgJl2r/1599-bceid-dashboard-panel-credit-transactions))**, part 3 awards in progress and approved **([Card 1600](https://trello.com/c/xXWF7Gvr/1600-bceid-dashboard-panel-part-3-agreements))**
- Organization Details **([Card 1602](https://trello.com/c/10x5eI3E/1602-bceid-dashboard-panel-organization-details))**
 - organization address
 - user
 - roles
- User Settings **([Card 1603](https://trello.com/c/H4dbnZwP/1603-bceid-idir-dashboard-panel-user-settings))** 
 - edit their personal information, name, title, phone number etc.
 - configure notifications
 - read notifications
 - help information

The Credit Transfers (and Signing Authority) role has the additional ability:

- see/access the "Start a new credit transfer proposal" link

The File Submission role can see/access the:

- Part 3 Agreements panel and links

The Compliance Report Manager role can see/access the:

- Compliance & Exclusion Reports panel and links including the Start a new submission link

The Managing User role can see the additional 3 links in the Organization Details panel:

- New user
- Create new BCeID account
- Edit Address

See attachment

https://trello.com/c/aaeqw3lX/1605-dashboard-bceid-dashboard-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | BCEID Dashboard |1|](https://trello.com/c/aaeqw3lX/1605-dashboard-bceid-dashboard-1)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
