### ISSUE TITLE
Dashboard | BCEID Dashboard metric panel Validated Credits |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1488]
BCeID users will see a metrics panel to display the balance of validated credits for the organization associated with their account.

Fonts and colours are following DevHub standards:
18px default text size
36px for yellow text
Noto Sans font
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2

https://trello.com/c/Z4ppcGJm/1596-dashboard-bceid-dashboard-metric-panel-validated-credits-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | BCEID Dashboard metric panel Validated Credits |1|](https://trello.com/c/Z4ppcGJm/1596-dashboard-bceid-dashboard-metric-panel-validated-credits-1)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
