### ISSUE TITLE
Dashboard | BCEID Dashboard panel Credit Transactions |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1489]
The Credit Transactions panels displays and provides links for the user to access their organizations credit transactions. It shows the transactions currently in process of being approved and provides links to past transactions from the current compliance period and all historical. It also provides a link to start a new proposal. There is also a link to the Part 3 Fuel Suppliers Report (PDF) so this link can be removed from the main nav bar.

These links are tied to the appropriate role, e.g. Guests will not see the link to start a new credit transfer proposal. Only the **credit trading role** can start a new credit transfer proposal.

**Credit Transfer(s) in progress**

This includes credit transfers with the following statuses:

- Signed 1 of 2, Signed 2 of 2, Reviewed (Recommend / Not Recommend)

**Note:** For BCeID users, in the UI, we have chosen not to show them the Reviewed status; we want to maintain this restriction, but ensure that those transfers with a "Reviewed" status (Recommend / not recommend) get included in calculating the total number of "transfers in progress". 

**Fonts and colours**
Follow DevHub standards:
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/2olgJl2r/1599-dashboard-bceid-dashboard-panel-credit-transactions-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | BCEID Dashboard panel Credit Transactions |2|](https://trello.com/c/2olgJl2r/1599-dashboard-bceid-dashboard-panel-credit-transactions-2)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
