### ISSUE TITLE
Dashboard | BCEID Dashboard panel Part 3 Agreements |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1490]
The Part 3 Agreement panel provides a link for information about Part 3 Agreements <https://www2.gov.bc.ca/gov/content?id=053E5694562A4F538D73A427B3B43DEC>

And access to the secure file upload page to submit new applications or provide milestone evidence for existing agreements.

**This panel is available only to users assigned the File Submission role.**

Fonts and colours are following DevHub standards:
Font Awesome icons
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/xXWF7Gvr/1600-dashboard-bceid-dashboard-panel-part-3-agreements-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | BCEID Dashboard panel Part 3 Agreements |1|](https://trello.com/c/xXWF7Gvr/1600-dashboard-bceid-dashboard-panel-part-3-agreements-1)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
