### ISSUE TITLE
Dashboard | BCEID Dashboard panel Compliance and Exclusion Reports |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1491]
The Compliance & Exclusion Reports panel provides links to the report submissions in progress and provides links to past reports from the current compliance period and all historical. It also provides a link to start a new submission.

**Roles:** This panel is only displayed to users assigned the Compliance Report Manager role and/or the Signing Authority role. 

**Compliance and Exclusion Reports in progress:**
From the attached screenshot:

- n submission(s) in draft: status = draft
- n submissions awaiting government review: status = Submitted, Reviewed (specific UI labels for statuses for this workflow are still TBD)

**Fonts and colours**
Follow DevHub standards:
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/qYuX28dU/1601-dashboard-bceid-dashboard-panel-compliance-and-exclusion-reports-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | BCEID Dashboard panel Compliance and Exclusion Reports |2|](https://trello.com/c/qYuX28dU/1601-dashboard-bceid-dashboard-panel-compliance-and-exclusion-reports-2)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
