### ISSUE TITLE
Dashboard | BCEID Dashboard panel Organization Details |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1492]
The Organization Details panel displays the organization name and mailing address and provides links to view users and roles.

**Roles:** 

- This panel and information is available to all roles including the Guest role.
- The Managing User role will have additional links to edit the organization address and information as well as links to create new BCeID user accounts and add new users.

**Create new BCeID account:**

- Link: https://www.bceid.ca/

**Fonts and colours** are following DevHub standards:
18px default text size
24px for panel headings
36px for yellow text
Noto Sans font
tundra #494949 for panel border and title text
midnight blue #003366
lightning yellow #FCBA19
concrete #F2F2F2
links are underlined
matisse #1A5A96

https://trello.com/c/10x5eI3E/1602-dashboard-bceid-dashboard-panel-organization-details-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | BCEID Dashboard panel Organization Details |1|](https://trello.com/c/10x5eI3E/1602-dashboard-bceid-dashboard-panel-organization-details-1)

**Comment by KMenke** [comment]
Resolved in sprint wormhole
