### ISSUE TITLE
IDIR Dashboard Director and Deputy Director |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1494]
The Director and Deputy Director roles will have stripped down version of the primary IDIR dashboard showing only links and actions that are relevant to them.

- See attached screenshot

**Dashboard contents:**

- All Organizations credit balance panel, created in **([Card 1604](https://trello.com/c/xbt7BrN2/1604-idir-dashboard-metric-all-org-credit-balance))**
- 12 month average credit price, created in **([Card 1597](https://trello.com/c/74BgEnl6/1597-bceid-idir-dashboard-metric-panel-credit-trading-value))**
- Average business days to approve transfers, created in **([Card 1598](https://trello.com/c/1mSAGIuB/1598-bceid-idir-dashboard-metric-time-to-approve))**
- Awaiting review (**see below**)
- User Settings, created in **([Card 1603](https://trello.com/c/H4dbnZwP/1603-bceid-idir-dashboard-panel-user-settings))**

**Awaiting Director Review section:**
This section shows the number of items in progress for your action:

- n credit transfers for your review and statutory decision: status = Reviewed (Recommended / Not Recommended)
- n compliance reports awaiting your review: status = Reviewed 2 (TBD)
- n exclusion reports awaiting your review: status = Reviewed 2 (TBD)
- n Part 3 Awards awaiting your review: status = Recommended

https://trello.com/c/f6fJsNLv/1612-idir-dashboard-director-and-deputy-director-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IDIR Dashboard Director and Deputy Director |2|](https://trello.com/c/f6fJsNLv/1612-idir-dashboard-director-and-deputy-director-2)

**Comment by KMenke** [comment]
resolved
