### ISSUE TITLE
Compliance Report | Summary page fixes and optimization |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1497]
**Description:**

- Test and try to break summary page
 - including entering various types of data into Line 6, 8, 17, 19, 26 
- Fix any issues encountered

**Known Issues:**

- Explore fix for 500 error (ID 106)
- Line 12: tooltip flashes sometimes when hovering mouse over it
- Line 28 within the "Part 2 and Part 3 Non-compliance Penalty Payable Summary" table is not populating the penalty value when in a net debit situation until after a value is entered into Line 26. This issue is similar to the one fixed in **[Card 1978](https://trello.com/c/iXmwAy0Y/1978-compliance-report-line-28-penalty-not-displaying-in-a-net-debit-situation-until-after-a-value-has-been-entered-into-line-26-1v15)** for Line 28 within the "Part 3 - Low Carbon Fuel Requirement Summary" table. 

https://trello.com/c/0h7y5SxP/2001-compliance-report-summary-page-fixes-and-optimization-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Summary page fixes and optimization |5|](https://trello.com/c/0h7y5SxP/2001-compliance-report-summary-page-fixes-and-optimization-5)

**Comment by KMenke** [comment]
resolved
