### ISSUE TITLE
Notifications | Compliance and Exclusion Reporting |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1501]
**Task:**
Implement notifications for Compliance and Exclusion Reporting

**Notification Settings Heading:**
Compliance & Exclusion Reporting

**Actions:**
The following actions, if enabled, should trigger a notification for either BCeID, IDIR, or both: 

- Draft Saved [BCeID]
- Submitted [BCeID & IDIR]
- Recommended Acceptance - Analyst [IDIR]
- Recommended Rejection - Analyst [IDIR]
- Recommended Acceptance - Manager [IDIR]
- Recommended Rejection - Manager [IDIR]
- Accepted [BCeID & IDIR]
- Rejected [BCeID & IDIR]
- Requested Supplemental [BCeID & IDIR]

**Notification Messaging:**
The notification within the Notification Center should read:

- "<Report Type> for <YYYY> <status>"
 - e.g. Compliance Report for 2019 Accepted
 - e.g. Exclusion Report for 2017 Submitted

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications | Compliance and Exclusion Reporting |5|](https://trello.com/c/TwplnO7C/1704-notifications-compliance-and-exclusion-reporting-5)

**Comment by KMenke** [comment]
resolved
