### ISSUE TITLE
Compliance Reporting | Add credit calculation values for 2013-14 2015 2016 |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1503]
Currently we have no credit calculation values for 2013-14, 2015, and 2016. This breaks the compliance reporting functionality for these compliance periods. The attached spreadsheet provides the appropriate values to add into the back-end tables so that users will be able to create and submit compliance reports for these periods. 

https://trello.com/c/Y5afOkhw/2010-compliance-reporting-add-credit-calculation-values-for-2013-14-2015-2016-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Reporting | Add credit calculation values for 2013-14 2015 2016 |2|](https://trello.com/c/Y5afOkhw/2010-compliance-reporting-add-credit-calculation-values-for-2013-14-2015-2016-2)

**Comment by KMenke** [comment]
resolved
