### ISSUE TITLE
Permissions | Revise permission descriptions in the UI |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1505]
**Task:**
Revise the permission descriptions in the UI (i.e. description 1 and 2)

- see attached spreadsheet for existing labels and description (columns C, D) and the new ones (columns E, F)

**Add in two code comments:**
There are two instances where we use one permission to enable to distinct actions, one for BCeID and one for IDIR users. We have decided to make the description for these two permissions focus on explaining the permission from the BCeID user perspective. In lieu of a proper description for IDIR users, we want to add in two code comments to explain the IDIR-side of these permissions; this will inform any future devs as to why an IDIR user has these permissions. 

- Permission 1: Create New Credit Transfer Proposal
 - For IDIR users, this permission enables the creation of a New Part 3 Award (credit transaction).

- Permission 2: Rescind a Credit Transfer Proposal
 - This permission allows an IDIR user to retract their recommendation of a Part 3 Award (credit transaction); in the UI it is called "Recall as Draft". 

https://trello.com/c/jkV4S8Fn/2023-permissions-revise-permission-descriptions-in-the-ui-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Permissions | Revise permission descriptions in the UI |2|](https://trello.com/c/jkV4S8Fn/2023-permissions-revise-permission-descriptions-in-the-ui-2)

**Comment by KMenke** [comment]
resolved
