### ISSUE TITLE
Permissions | Add and adjust permissions to all roles |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1507]
**Task:** 
This card is to add and adjust permissions to all roles. See attached spreadsheet for a complete list of permissions for each role. Permissions in TFRS should be added/removed to align the app with the spreadsheet list. 

https://trello.com/c/AJh5L4ic/2024-permissions-add-and-adjust-permissions-to-all-roles-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Permissions | Add and adjust permissions to all roles |2|](https://trello.com/c/AJh5L4ic/2024-permissions-add-and-adjust-permissions-to-all-roles-2)

**Comment by KMenke** [comment]
resolved
