### ISSUE TITLE
Dashboard | Minor tweaks and adjustments |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1510]
**User Settings: BCeID & IDIR**

- **Notifications** link takes you to the Notifications settings page
 - Have this link take you to the main notifications page ("TFRS"/notifications)
- **Help** link
 - Put a PDF icon in front of the "Help" link to indicate that it is a PDF (similar to the Credit Market Report link)

**Credit Balance: IDIR**

- Change the label "Show transactions involving:" to "Show balance for:"
- Ensure that the drop-down list of fuel supplier orgs is in alphabetical order. In dev env, some orgs are not in alphabetical order but rather displayed at the bottom of the list. 

**Credit Transactions: IDIR**

- Credit Transfers: The "awaiting government analyst review" is showing a **0** despite there being credit transfer proposals awaiting review (Signed 2/2 status)

**File Submissions: IDIR**

- Change the "n awaiting Director review and statutory decision" label to "n awaiting to be marked as received"
= Change the "n awaiting to be archived" label to "n awaiting review and archive"

**Credit Transactions: BCeID**

- The "Start a new credit transfer proposal" link doesn't appear to be working. Clicking on the link doesn't cause any action to occur. 
 - Tested in dev v1.5.6 with multiple roles: credit transfers plus compliance reporting, file submission and managing users for example. 

**Part 3 Agreements: BCeID**

- We should consider putting some form of icon next to the "Part 3 Agreement application information" link. This link takes you outside of TFRS to the low carbon fuels branch's website. Similar to how we indicate that a link is a PDF by using a PDF icon, we should consider finding a web icon or something similar to use an indicator here.  

**Compliance & Exclusion Reports: BCeID**

- The "Start a new compliance report or exclusion report" links don't appear to be working. Clicking on the link doesn't cause any action to occur. 
 - Tested in dev v1.5.6 with multiple roles: compliance reporting plus file submission, managing users, Signing Authority, and credit transfers for example. 

**Organization Details:**

- Managing Users role: the "New user" link takes you to a "New User" page. This page appears to be for **IDIR** users rather than for creating **BCeID users within one's own organization**. 

https://trello.com/c/ew4q9IMV/2026-dashboard-minor-tweaks-and-adjustments-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard | Minor tweaks and adjustments |2|](https://trello.com/c/ew4q9IMV/2026-dashboard-minor-tweaks-and-adjustments-2)

**Comment by KMenke** [comment]
resolved
