### ISSUE TITLE
Details | Change company to organization on user details page |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1514]
Change "company" label to "organization" on user details page

https://trello.com/c/XksettMJ/1721-details-change-company-to-organization-on-user-details-page-1

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Details | Change company to organization on user details page |1|](https://trello.com/c/XksettMJ/1721-details-change-company-to-organization-on-user-details-page-1)

**Comment by KMenke** [comment]
resolved
