### ISSUE TITLE
Compliance Report B | Instructions for Schedule B |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1516]
**Task:**
This card is to create the Instructions section for Schedule B. 

- See attached screenshot for how this is set up in the existing excel-based Compliance Report
- See attached screenshot for a mockup of the instructions sections in TFRS (example is of Schedule D)

**Story:**
As a BCeID user, I would like to have non-intrusive access to instructions for filling out and understanding Schedule B so that I can refer to them if needed. 

**Background:**
We want to include some instructions within Schedule B to provide the user with enough information to properly fill out and understand the schedule. 

**Design(s):**

- Brief instruction info under the heading (no need to make this collapsible because it is quite brief)
- tooltips (icons and messaging) 

**Instructions:**
The following information should be included in this section:

Report the fuel volumes supplied for transportation. Do not include fuel volumes supplied for purposes other than transportation in Schedule B; please report those fuel quantities in Schedule C.

**Tooltips:**

- Fuel Type: Select the fuel type from the drop-down list.
- Fuel Class: Select the fuel class in which the fuel was used from the drop-down list.
- Provision of the Act Relied Upon to Determine Carbon Intensity: Identify the appropriate provision of the Act relied upon to determine the carbon intensity of each Part 3 fuel. 
 - Section 6 (5) (a): The Regulation-prescribed carbon intensity for petroleum-based gasoline. 
 - Section 6 (5) (b): The Regulation-prescribed carbon intensity for petroleum-based diesel fuel. 
 - Section 6 (5) (c) - Approved fuel code: Use this method for fuels that have been assigned an approved BCLCF code. A drop-down list of appropriate fuel codes based on the selected fuel type will be provided.
 - Section 6 (5) (d) (i) - Regulation default carbon intensity value: The carbon intensity of this fuel type determined in accordance with the Regulation.
 - Section 6 (5) (d) (ii) (A) - Approved version of GHGenius. Users selecting this method are required to provide a record of inputs to the GHGenius model, as defined in section 11.06 (1) of the Regulation, and any additional information necessary to reproduce, using the approved GHGenius, the results submitted. 
 - Section 6 (5) (d) (ii) (B) - Approved alternative method: Users selecting this method are required to provide a copy of the Director's approval letter of that method and appropriate documentation of the inputs and outputs of the electronic calculation, as appropriate. 

- Fuel Code or Schedule D Entry (if applicable): 
 - Fuel Code: If an approved fuel code is relied upon to determine carbon intensity, a drop-down list of the appropriate fuel codes based on the selected fuel type will be provided.
 - Schedule D Entry: If GHGenius modelled is relied upon to determine carbon intensity, a drop-down list of the appropriate fuel(s) reported in Schedule D based on the selected fuel type and fuel class will be provided. 

A drop-down list of appropriate fuel codes based on the selected fuel type will be provided.

- Quantity of Fuel Supplied: **no tool tip**
- Units: This value will be provided based on the type of fuel reported.
- CI Limit: The prescribed carbon intensity limit for the compliance period for the class of fuel of which the fuel is a part. This value will be provided based on the fuel class reported.
- CI of Fuel: The carbon intensity of the fuel. This value will be provided based on the specific fuel and determination method reported. 
- Energy Density: This value will be provided based on the type of fuel reported as specified in section 11.02 (3) of the Regulation.
- EER: The Energy Effectiveness Ratio (EER) will be provided based on the type of fuel and fuel class reported as specified in section 11.02 (2) of the Regulation.
- Energy Content: This value will be calculated using the formula specified in section 11.02 (3) of the Regulation. The formula is Energy Content (megajoules) = Quantity of Fuel Supplied X Energy Density.
- CREDIT/DEBIT CALCULATION (Part 1): This value will be calculated based on the information provided using the formula specified in section 6 (4) of the Act. 
 - Credit or Debit = (CI class x EER fuel – CI fuel) x EC fuel / 1,000,000. 
 - where, 
  - Credit or Debit = The number of credits generated or debits incurred. This value will be displayed in the appropriate column (Credit or Debit). 
  - CI class = The prescribed carbon intensity limit for the compliance period for the class of fuel of which the fuel is a part.
  - EER fuel = The prescribed energy effectiveness ratio for that fuel in that class of fuel.
  - CI fuel = The carbon intensity of the fuel.
  - EC fuel = The energy content of the fuel calculated in accordance with section 11.02 (3) of the Regulation.

- CREDIT/DEBIT CALCULATION (Part 2): Credits and debits are displayed as whole values; fractional values are accounted for when determining the total credits generated and/or the total debits incurred from all fuel supplied within a compliance period. Conventional rounding is used only after the total credits and total debits are calculated. 

https://trello.com/c/ZksmBkIq/1366-compliance-report-b-instructions-for-schedule-b-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report B | Instructions for Schedule B |2|](https://trello.com/c/ZksmBkIq/1366-compliance-report-b-instructions-for-schedule-b-2)

**Comment by KMenke** [comment]
resolved
