### ISSUE TITLE
Compliance Report | Compliance Assessment Section |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1519]
**Information:**
The Compliance Assessment feature will be used to communicate compliance/non-compliance with the Part 2 & Part 3 requirements (compliance and exclusion reporting). This communication will use standard language that is dependent on certain factors contained within a compliance/exclusion report, and will be the government's way of communicating compliance/non-compliance following the Director's acceptance of a Compliance/Exclusion Report. We will also want to expose this section earlier in the government's workflow but restrict its visibility to IDIR only during the review process (more info below). 

**Status and Visibility:**
This section will only be visible to certain users depending on the status of the submission: 

- IDIR: Recommended Acceptance – Analyst, Recommended Acceptance – Manager, Accepted
- BCeID: Accepted

**Default Page:**
Once the compliance assessment section becomes visible, we would like to make this page the **default** page when viewing a compliance report. 

**Design:**

- TBD
- Heading: Compliance Assessment
- Location: Could be placed within the Summary sub-tab or create its own tab called "Assessment" (latter is likely preferred but there may not be enough info to warrant a separate "Assessment" sub-tab; ideally this section would be located on the same page as the Report history record section)

**Messaging:**
There are four sections with respect to messaging: 

- Part 2 requirements
- Part 3 requirements
- Validation/Reduction (adjustment to credit balance)
- Record Keeping. 

Each will have its own standard wording applied depending on certain aspects of the report and the compliance situation (compliance/non-compliance, etc.). 

**Messaging - Part 2 Requirements:**
With respect to Part 2 requirements, there are three possible states that each require different messaging: Compliant, non-compliant, and did not supply Part 2 fuel. The state that applies to the fuel supplier is determined by the information contained within the compliance report. Compliant means that the supplier complied with the Part 2 requirements (there is no penalty amount in Lines 11 and 22 of the Summary section); Non-compliant means the opposite and would be denoted by positive values being contained within one or both of Lines 11 and 22; Did not supply Part 2 fuel means that the supplier did not report the supply of Part 2 fuel within the report. 

- Compliant: Based on the information submitted, <**organization name**> was compliant with the Part 2 requirements of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act* under section 7 of the Renewable and Low Carbon Fuel Requirements Regulation for the <YYYY> compliance period. 
- Non-compliant: Based on the information submitted, <**organization name**> was **not** compliant with the Part 2 requirements of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act* under section 7 of the Renewable and Low Carbon Fuel Requirements Regulation for the <YYYY> compliance period. 
- Did not supply Part 2 fuel: Based on the information submitted, <**organization name**> did not supply Part 2 fuels and therefore was not subject to the Part 2 requirements of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act* under section 7 of the Renewable and Low Carbon Fuel Requirements Regulation for the <YYYY> compliance period.

**Part 2 fuels:**

- Schedule B or C: Biodiesel, Ethanol, HDRD, natural gas-based gasoline, petroleum-based gasoline, petroleum-based diesel, renewable diesel, renewable gasoline

**Messaging - Part 3 Requirements:**
With respect to Part 3 requirements, there are two possible states that each require different messaging: Compliant and non-compliant. Again, these states are determined by the information contained within the report. Compliant means that the supplier complied with the Part 3 requirements (there is not outstanding debit balance in Line 27); non-compliant means the opposite and is denoted by a positive value being contained within Line 27. 

- Compliant: Based on the information submitted, <**organization name**> was compliant with the Part 3 requirements under section 6 (1) of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act* for the <YYYY> compliance period. 
- Non-compliant: Based on the information submitted, <**organization name**> was **not** compliant with the Part 3 requirements under section 6 (1) of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act* for the <YYYY> compliance period. 

**Messaging - Validation/Reduction:**
This section contains messaging about the adjustment to the supplier's credit balance and is based on information contained within the compliance report. A validation occurs when there is a net credit balance (i.e. net credit balance in Line 25); a reduction occurs when banked credits are used to offset an outstanding debit balance (i.e. value entered into Line 26). We also want to include some language if there are not enough credits from a supplier's credit balance to offset the net debit balance. 

- If Validation: A validation of <**value**> credit(s) in accordance with section 8 (8) of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act* and based on the information submitted by <**organization name**>. These credits may now be transferred to other Part 3 fuel suppliers in accordance with the Renewable and Low Carbon Fuel Requirements Regulation or retained for future compliance requirements. 
 
- If Reduction and:
 - supplier has enough credits to completely offset the net debit balance (i.e. compliant with the Part 3 requirement:  <**organization name**> applied <**Line 26 value**> credits to offset a net debit balance in the YYYY compliance period. 
 - supplier does **not** have enough credits to completely offset the net debit balance (i.e. not compliant with the Part 3 requirement): <**organization name**> applied <**Line 26 value**> credits to partially offset a net debit balance in the YYYY compliance period. There were <**Line 27**> outstanding debits subject to an administrative penalty under section 10 of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*.

**Messaging - Record Keeping:**
Standard language that always appears last: 

- The information to which this assessment is based is subject to verification through on-site inspection under the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*, and records must be retained in accordance with the Renewable and Low Carbon Fuel Requirements Regulation.

https://trello.com/c/bCVQlJrw/1700-compliance-report-compliance-assessment-section-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Compliance Assessment Section |3|](https://trello.com/c/bCVQlJrw/1700-compliance-report-compliance-assessment-section-3)

**Comment by KMenke** [comment]
resolved
