### ISSUE TITLE
Exclusion Report | Compliance Assessment Section |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1520]
**Information:**
The Compliance Assessment feature will be used to communicate compliance/non-compliance with the Part 2 & Part 3 requirements (compliance and exclusion reporting). This communication will use standard language that is dependent on certain factors contained within a compliance/exclusion report, and will be the government's way of communicating compliance/non-compliance following the Director's acceptance of a Compliance/Exclusion Report. We will also want to expose this section earlier in the government's workflow but restrict its visibility to IDIR only during the review process (more info below). 

**Status and Visibility:**
This section will only be visible to certain users depending on the status of the submission: 

- IDIR: Recommended Acceptance – Analyst, Recommended Acceptance – Manager, Accepted
- BCeID: Accepted

**Default Page:**
Once the compliance assessment section becomes visible, we would like to make this page the **default** page when viewing an exclusion report. 

**Design:**

- TBD
- Heading: Compliance Assessment
- Location: Could be placed within the exclusion agreements sub-tab or create its own tab called "Assessment" (latter is likely preferred but there may not be enough info to warrant a separate "Assessment" sub-tab; ideally this section would be located on the same page as the Report history record section)

**Messaging - Exclusion Reports:**
When the conditions outlined above are met, the following messages would appear within the Compliance Assessment section: 

- Based on the information submitted, <**organization name**> was compliant with the Part 3 requirements of the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act* under section 11.032 of the Renewable and Low Carbon Fuel Requirements Regulation for the <YYYY> compliance period. 
- The information to which this assessment is based is subject to verification through on-site inspection under the *Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act*, and records must be retained in accordance with the Renewable and Low Carbon Fuel Requirements Regulation. 

https://trello.com/c/MzVWIDeH/1701-exclusion-report-compliance-assessment-section-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclusion Report | Compliance Assessment Section |2|](https://trello.com/c/MzVWIDeH/1701-exclusion-report-compliance-assessment-section-2)

**Comment by KMenke** [comment]
resolved
