### ISSUE TITLE
Fuel Supplier | Organization Status Active Inactive |5|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1523]
**Task:**
This card is to implement the functionality behind the Active / Inactive organization status types. These action types can be changed in the UI under the edit organization section of TFRS; however, they currently do not have any functionality or restrictions behind each action. 

**Active:**
This status means that the organization is actively supplying fuel and is a recognized Part 3 fuel supplier. 

- Action Type: an **Active** supplier is **Permitted to Buy and Sell Low Carbon Fuel Credits**

**Inactive:**
This status means that the organization is not actively supplying fuel and therefore is not a recognized Part 3 fuel supplier. 

- Action Types: an **Inactive** supplier can have two action types
 - Permitted to only Sell Low Carbon Fuel Credits
 - Not Permitted to Buy and Sell Low Carbon Fuel Credits

When a supplier is listed as inactive, the appropriate action type is based on whether or not they have a non-zero credit balance. 

- If they have a non-zero credit balance, then they are only permitted to sell
- If they don't have a non-zero credit balance, then they are not permitted to buy or sell. 

**Permitted to Only Sell Low Carbon Fuel Credits:**

- Can see the New Transfer button in TFRS, but cannot select "Buy" when creating a new Credit Transfer Proposal

**Not Permitted to Buy and Sell Low Carbon Fuel Credits:**

- Can **not** see the New Transfer button in TFRS. Meaning they cannot initiate a new Credit Transfer Proposal.
 - Including the "Start a new credit transfer proposal" link **and** the "X credit transfer(s) in progress" contained within the dashboard

https://trello.com/c/xLDfdh6k/2021-fuel-supplier-organization-status-active-inactive-5

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Supplier | Organization Status Active Inactive |5|](https://trello.com/c/xLDfdh6k/2021-fuel-supplier-organization-status-active-inactive-5)

**Comment by KMenke** [comment]
resolved
