### ISSUE TITLE
Fuel Supplier | Hide Part 3 Agreement SFS feature for inactive organizations |3|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1524]
**Task:**
This card is to hide the Part 3 Agreement (SFS) feature for organizations that are set as inactive. 

**Part 3 Agreements:**
An inactive fuel supplier cannot have a Part 3 Agreement, thus we want to remove/hide the SFS / Part 3 Agreement feature when a fuel supplier is set to inactive (including in the dashboard). 

- Hide Part 3 Agreement (SFS) feature, including accessing from the Nav bar and Dashboard
- Hide File Submission role when adding/editing users with the Managing Users role
- Users within that org that already have the File Submission role will have it removed; if no other roles exist, default to guest role?

https://trello.com/c/fysROuzE/2022-fuel-supplier-hide-part-3-agreement-sfs-feature-for-inactive-organizations-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel Supplier | Hide Part 3 Agreement SFS feature for inactive organizations |3|](https://trello.com/c/fysROuzE/2022-fuel-supplier-hide-part-3-agreement-sfs-feature-for-inactive-organizations-3)

**Comment by KMenke** [comment]
resolved
