### ISSUE TITLE
Compliance Report | Can only Submit from Summary page |2|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1533]
Fuel supplier user can only submit from the Summary page. 

- Also add validation panel to the summary page

https://trello.com/c/0z5egRhm/2045-compliance-report-can-only-submit-from-summary-page-2

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report | Can only Submit from Summary page |2|](https://trello.com/c/0z5egRhm/2045-compliance-report-can-only-submit-from-summary-page-2)

**Comment by KMenke** [comment]
resolved
