### ISSUE TITLE
Compliance Report D | Instructions for Schedule D |1|

### ISSUE THREAD

**Issue by amichard** [bcgov/tfrs#1538]
**Story:**
As a BCeID user, I would like to have non-intrusive access to instructions for filling out Schedule D so that I can refer to them if needed. 

**Background:**
We need to include some instructions within Schedule D to provide the user with enough information to properly fill out this Schedule. 

**Design(s):**

- See attached screenshots
- Collapsible menu for a portion of the instructions
- tool tip icons and messaging for the rest

**Collapsible Instructions:**
The following information should be included in this section (see attached screenshot, although please note that **some of the information has been changed**):

- A GHGenius Input and Output Summary Table must be completed for each separate fuel being reported with a carbon intensity determined using GHGenius under section 6 (5) (d) (ii) (A) and reported in Schedule B. 
- **Schedule D should be completed before reporting the fuel in Schedule B, as the values entered in this schedule inform the carbon intensity reported in Schedule B.**
- The approved version of GHGenius must be used as defined in section 11.06 (1) of the Renewable and Low Carbon Fuel Requirements Regulation and specified in *Information Bulletin RLCF-011 - Approved Version of GHGenius*, available from [www.gov.bc.ca/lowcarbonfuels](www.gov.bc.ca/lowcarbonfuels). 
- The Input Summary Table must include all input data required to reproduce the requested carbon intensity using the approved version of GHGenius.
- The Output Summary Table must contain the emissions associated with all twelve of the lifecycle components listed in the Output Summary Table within this schedule in accordance with section 11.05 (3) of the Renewable and Low Carbon Fuel Requirements Regulation. Input the emissions associated with each component from the GHGenius model into the appropriate row in the Output Summary Table.
- It is recommended that users consult *Information Bulletin RLCF-010 - Using GHGenius in B.C.*, available from [www.gov.bc.ca/lowcarbonfuels](www.gov.bc.ca/lowcarbonfuels), before attempting to use GHGenius.

**NOTE: default state is collapsed; no need to save the state**

**Input Summary Table Tooltips:**

- Part 3 Fuel Type: **no tooltip**
- Feedstock: The feedstock used to produce the fuel (e.g. corn, soy, etc.).
- Fuel Class: The fuel class in which the fuel was used.
- Worksheet Name: The worksheet in the GHGenius model where the change is made (e.g. Input, Coprods, etc.). 
- Cell: The cell reference in which the change is made (e.g. A1, D155, etc.).
- Value: The value that is replacing the default value.
- Units: The unit given for the Reported Value (e.g L, L/MJ, etc.).
- Description: A brief description of the nature of the input (e.g. feedstock transportation mode, natural gas usage, etc.).

**Note: we will not be doing tooltips for the output summary table.**

https://trello.com/b/O9L8CXes/transportation-fuels-reporting-system

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance Report D | Instructions for Schedule D |1|](https://trello.com/c/bJA1NNmZ/1347-compliance-report-d-instructions-for-schedule-d-1)

**Comment by KMenke** [comment]
resolved
