### ISSUE TITLE
Backup | Backup TFRS projects |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#164]
TFRS has 4 projects, dev, test, prod and tools. We need to backup the projects and figure out how to restore them in case of emergency.
https://docs.openshift.com/container-platform/3.6/admin_guide/backup_restore.html

Can this be done on an automated schedule?

Story: 
As the TFRS PO, I want to ensure that all of our projects are backed up appropriately and regularly so that we can easily and speedily recover from disasters that might affect our uptime and/or productivity.

Demo: 
Demonstrate backup process
Show where backups are stored and backup frequencyhttps://trello.com/c/mqT4vQR8/349-backup-backup-tfrs-projects-3

**Comment by kuanfandevops** [comment]
this could be done by a scheduled Jenkins job. I'll look into it..
