### ISSUE TITLE
Data Model | Rename the ID column

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#173]
**Story:**
As a TFRS Developer, I want all the ID columns to be descriptive of their table names.

**Information:**
In [Card 315](https://trello.com/c/p5y8gF4l/315-data-model-data-model-changes-2-v003-alpha), two items were skipped due to complexity:
- Rename all "Id" fields to be <table>Id (Won't be implemented due to complexity)
- Rename all “id” fields to be <table>Id and all FKs to be <table>Id except where there is more than one FK in a table – e.g. initiatorId and respondentId in the CreditTrade table. (Won't be implementing the first one due to complexity)

These changes should still be implemented. A good time to revisit this is when we get close to upgrading to Django 2.x or changing to a different framework for the API

**django2.0**, **orm**https://trello.com/c/mdE2i0xF/425-data-model-rename-the-id-column

**Comment by kuanfandevops** [comment]
The issue was create for experimental use. We start to actively use the issues and milestones. Close this issue for now and reopen it if needed.
