### ISSUE TITLE
Developing the Transportation Fuels Reporting System website front-end (BCDX-MEM-001)

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/tfrs#2]
This is a **fixed-price** opportunity governed by the [terms](https://github.com/BCDevExchange/code-with-us/raw/master/Code%20With%20Us%20Paid%20Terms_Nov_28.pdf) of the BCDevExchange's lightweight procurement model, [Code With Us](https://bcdevexchange.org/codewithus).

### Background

The Transportation Fuels Reporting System is the being designed to Streamlined compliance reporting for transportation fuel suppliers in accordance with the [Renewable & Low Carbon Fuel Requirements Regulation](http://www2.gov.bc.ca/gov/content/industry/electricity-alternative-energy/transportation-energies/renewable-low-carbon-fuels). We want you to conduct UX Design and Development of the first set of screens which will enable Credit Trading and Compliance Reporting.

### Description

You can find our current code base [here](https://github.com/bcgov/tfrs). We want you to produce layout and design templates with hooks for the developer to write code for. The site should deliver the following functionality:

### User Stories

As a **trading partner** I need to be able to navigate through a series of self-service screens to:

- view information regarding past, proposed and pending credit-related activity including a real-time credit balance and list of activity that may impact that balance. 
- enter the information required to propose a credit transaction to a trading partner; accept a proposed trade from a trading partner and submit that transaction proposal to the Director for approval. 
- view the information entered by the user on Transaction Details screen before proposing it to a trading partner or submitting it to the Director for approval.
- review before authorizing the transaction and submitting it to the Director for approval or saving it for future.

The **Low Carbon Fuels Branch staff** need to be able to:

- Input transactions to award Part 3 Agreement or fuel supply credits or adjust balances based on new information to users through the same process as above
- Run queries to produce periodic (quarterly, annually, etc.) reports on credit transaction activity with the following variables: # transfers, total credits traded, avg. market value, min/max value

Stretch goals (time permitting) - As a **fuel supplier** I need to be able to navigate through a series of self-service screens to:

- Report each fuel that I supplied in BC
- Report each fuel that I transferred as part of a fuel transfer agreement or a notional transfer
- Report that the total volume of fuels supplied is less than 75 million Litres and elect to be exempt

## Informational Open House
On **Monday, March 7th and 8th**, from **12:00-1:00 PM**, we will be hosting a drop-in session for interested developers to talk with our team about the work. If you’d like to attend, please email Matthew.Hall@gov.bc.ca.

Please also feel free to ask questions via the comments section below.

## Acceptance Criteria

To be paid for this opportunity, you will:

1. Participate as a part of our team’s sprint planning workshop from 1:00 PM - 3:00 PM on March 13, 2017 at 1012 Douglas Street in Victoria, BC.
2. Spend a minimum of 2 hours per weekday (Monday - Friday, excluding holidays, between the hours of 8:30 AM and 5:00 PM) working in person with us at our office (1012 Douglas Street in Victoria, BC) for the duration of your work. We want you to work side-by-side with our lead developer and designer to apply the the new theme and deliver the desired functionality in our dev environment.
3. Deliver hi-fidelity screens that are ready for a developer to insert the database connection code for each of the following: 

- Main Landing page
- Credit Trading home page
- Credit Trade Transaction details page
- Credit Trade Transaction Summary page
- Credit Trade Transaction Confirmation/Receipt page
- Shadow Box screen for content to collect information

Stretch goals - time permitting:

- Fuel Reporting home page
- Fuel Reporting Submission Details page
- Fuel Reporting Submission Summary page
- Fuel Reporting Submission Confirmation/Receipt page

## How to Apply

Submit your proposal by **16:00 PST, Thursday, March 9, 2017**.

## Proposal Evaluation Criteria

We will evaluate and score the proposals we receive by the following criteria. If we are satisfied with the proposals we receive, we will assign the work by 16:00 PST, Friday, March 10, 2017 with work proposed to commence on Monday, March 13, 2017.

Please email your proposal to Matthew.Hall@gov.bc.ca

Please reference the issue name "**Developing the Transportation Fuels Reporting System website front-end (BCDX-MEM-001)**" in your email. 

With your proposal, you must attach a copy of the [Code-with-Us Terms](https://github.com/BCDevExchange/code-with-us/raw/master/Code%20With%20Us%20Paid%20Terms_Nov_28.pdf), with the required information asked for in the “Acceptance” section of the Terms inserted into the document (Mandatory).

**Scoring criteria:**

- Your confirmation of being able to commit the time to meet all of the Acceptance Criteria by March 31, 2017.
- A short (around 200 words or less would be nice) summary of your experience working with agile projects (40 points).
- References to your relevant experience and demonstrated ability to do the work (60 points). For example, a link to your GitHub projects.

## Questions?

Please post a comment below.

**Comment by mark-a-wilson** [comment]
Hello @VldmrPvlvc, @khirwaa, @user373721, @mitozv, @VistaBayConsulting, @rafael-trevisan, @exe2000, @johannamcburnie, @monicag, @dskvr, @spallister, @raja, @gowheth, @jonabrow, @melavo, @cuell, @kimberleyhansen -- notifying you about this opportunity because you signed up on https://bcdevexchange.org. 

**All readers**: if you are interested in being notified of these kinds of paid opportunities, please sign up on the BCDevExchange app: https://bcdevexchange.org.

**Comment by melavo** [comment]
The deadline of March 31 seems very tight.  Also I guess this is open only for people in Victoria, considering the onsite work?  or are you open to teleconference?

**Comment by mark-a-wilson** [comment]
This is a **fixed-price** opportunity governed by the [terms](https://github.com/BCDevExchange/code-with-us/raw/master/Code%20With%20Us%20Paid%20Terms_Nov_28.pdf) of the BCDevExchange's lightweight procurement model, [Code With Us](https://bcdevexchange.org/codewithus).

### Background

The Transportation Fuels Reporting System is the being designed to Streamlined compliance reporting for transportation fuel suppliers in accordance with the Renewable & Low Carbon Fuel Requirements Regulation. We want you to conduct UX Design and Development of the first set of screens which will enable Credit Trading and Compliance Reporting.

### Description

You can find our current code base [here](https://github.com/bcgov/tfrs). We want you to produce layout and design templates with hooks for the developer to write code for. The site should deliver the following functionality:

### User Stories

As a **trading partner** I need to be able to navigate through a series of self-service screens to:

- view information regarding past, proposed and pending credit-related activity including a real-time credit balance and list of activity that may impact that balance. 
- enter the information required to propose a credit transaction to a trading partner; accept a proposed trade from a trading partner and submit that transaction proposal to the Director for approval. 
- view the information entered by the user on Transaction Details screen before proposing it to a trading partner or submitting it to the Director for approval.
- review before authorizing the transaction and submitting it to the Director for approval or saving it for future.

The **Low Carbon Fuels Branch staff** need to be able to:

- Input transactions to award Part 3 Agreement or fuel supply credits or adjust balances based on new information to users through the same process as above
- Run queries to produce periodic (quarterly, annually, etc.) reports on credit transaction activity with the following variables: # transfers, total credits traded, avg. market value, min/max value

Stretch goals (time permitting) - As a **fuel supplier** I need to be able to navigate through a series of self-service screens to:

- Report each fuel that I supplied in BC
- Report each fuel that I transferred as part of a fuel transfer agreement or a notional transfer
- Report that the total volume of fuels supplied is less than 75 million Litres and elect to be exempt

## Informational Open House
On **Monday, March 7th and 8th**, from **12:00-1:00 PM**, we will be hosting a drop-in session for interested developers to talk with our team about the work. If you’d like to attend, please email Matthew.Hall@gov.bc.ca.

Please also feel free to ask questions via the comments section below.

## Acceptance Criteria

To be paid for this opportunity, you will:

1. Participate as a part of our team’s sprint planning workshop from 1:00 PM - 3:00 PM on March 13, 2017 at 1012 Douglas Street in Victoria, BC.
2. Spend a minimum of 2 hours per weekday (Monday - Friday, excluding holidays, between the hours of 8:30 AM and 5:00 PM) working in person with us at our office (1012 Douglas Street in Victoria, BC) for the duration of your work. We want you to work side-by-side with our lead developer and designer to apply the the new theme and deliver the desired functionality in our dev environment.
3. Deliver hi-fidelity screens that are ready for a developer to insert the database connection code for each of the following: 

- Main Landing page
- Credit Trading home page
- Credit Trade Transaction details page
- Credit Trade Transaction Summary page
- Credit Trade Transaction Confirmation/Receipt page
- Shadow Box screen for content to collect information

Stretch goals - time permitting:

- Fuel Reporting home page
- Fuel Reporting Submission Details page
- Fuel Reporting Submission Summary page
- Fuel Reporting Submission Confirmation/Receipt page

## How to Apply

Submit your proposal by **16:00 PST, Thursday, March 9, 2017**.

## Proposal Evaluation Criteria

We will evaluate and score the proposals we receive by the following criteria. If we are satisfied with the proposals we receive, we will assign the work by 16:00 PST, Friday, March 10, 2017 with work proposed to commence on Monday, March 13, 2017.

Please email your proposal to Matthew.Hall@gov.bc.ca

Please reference the issue name "**Developing the Transportation Fuels Reporting System website front-end (BCDX-MEM-001)**" in your email. 

With your proposal, you must attach a copy of the [Code-with-Us Terms](https://github.com/BCDevExchange/code-with-us/raw/master/Code%20With%20Us%20Paid%20Terms_Nov_28.pdf), with the required information asked for in the “Acceptance” section of the Terms inserted into the document (Mandatory).

**Scoring criteria:**

- Your confirmation of being able to commit the time to meet all of the Acceptance Criteria by March 31, 2017.
- A short (around 200 words or less would be nice) summary of your experience working with agile projects (40 points).
- References to your relevant experience and demonstrated ability to do the work (60 points). For example, a link to your GitHub projects.

## Questions?

Please post a comment below.

**Comment by matthewhall78** [comment]
Hello, I am the person receiving the applications/proposals. The opportunity is open to all in BC who can spend an appropriate amount of ‘in person time’ with the TFRS team i.e. sprint planning/review and check-in points during the sprint (which includes calling in to daily stand-ups). The idea is to ideate and evolve the work through collaboration.  While preference will be given to those that are available to meet in person for the amount of time suggested, we will still review proposals of those who have less availability.

**Comment by samarthmod** [comment]
Hi @matthewhall78 - this is an awesome opportunity. Can we apply as a company, or does it have to an individual.

**Comment by matthewhall78** [comment]
@samarthmod Ultimately the company applying will need to put forward individuals and describe the experience and work completed by the individuals.  So we do not want to hire a company and then have them decide who will work with us. Does that make sense?

**Comment by raja** [comment]
Please remove me from all lists. 

Thanks,
RB

**Comment by samarthmod** [comment]
Thanks @matthewhall78 . It makes total sense. Thanks.

**Comment by matthewhall78** [comment]
Question: We were recently alerted to this new opportunity. I hear that there is a drop-in session for interested developers to learn more, on March 7-8, can you let me know more details?  
Answer: The drop is session will be a chance for you to see the office, learn about the Government DevOps Projects and meet the team that you will be working with. At the drop-in sessions you can ask further questions about the opportunity.   The software we are building is based on the [Renewable & Low Carbon Fuels Requirements Regulation](http://www2.gov.bc.ca/gov/content/industry/electricity-alternative-energy/transportation-energies/renewable-low-carbon-fuels)

**Comment by c3ilabuser** [comment]
Thank you to those your submitted proposals the competition is now closed. We received three proposals by the closing time. We will review and advise you of the outcome by Monday or Tuesday next week.

**Comment by matthewhall78** [comment]
Thank you to those your submitted proposals the competition is now closed. We received three proposals by the closing time. We will review and advise you of the outcome by Monday or Tuesday next week.

**Comment by matthewhall78** [comment]
After reviewing the proposal a winner has been selected.  Congratulations to Rohit Boolchandani from AirSenze.com. I would like to thank all those who submitted proposals.

**Comment by rohitboolchandani** [comment]
Thanks for selecting AirSenze Solutions. We are excited to deliver an awesome product for your team.
