### ISSUE TITLE
TFRS - Parkland company report error (line 26)

### ISSUE THREAD

**Issue by kcabhar** [bcgov/tfrs#2041]
**Description:**

Calculation error in compliance report for 2020. After the report was accepted they submitted a supplemental report.

The number of units to be used to offset their requirement is displayed as zero (Line 26)

They have been charged 83,106 (Line 26a) but they have also incurred charges of 45,023 (Line 25) and this amount should be reduced from their Outstanding debt balance (Line 27).

Line 27 should display the difference which is 38,083 (83,106-45,023)

**Acceptance Criteria:**

Given I am a <role
When I am <doing something>
Then <this happens>

**Development Checklist:**

Bring down Parkland report with the issue and associated data from prod to test.
Check if the issue exists in the same way on test.
Investigate why the issue is happening and develop fix if required.

**Comment by kcabhar** [comment]
Al to discuss what the issues exactly is with Jordan and/or Raj.

Edit by Al: we'll replicate the data in test first to see if latest updates fix the issue, by entering a new supplemental report in test, if problem persists Al will create a screen mock-up of how numbers and calculations should be displayed properly

**Comment by kcabhar** [comment]
Please refer to Jira cards 520, 521 and 522 for further information/history on this ticket

**Comment by jdon-zev** [comment]
File provide by Jordan.
[https://app.zenhub.com/files/80058415/5c9ed3de-f598-44fd-b3e5-ecd2161b2b8f/download](https://app.zenhub.com/files/80058415/5c9ed3de-f598-44fd-b3e5-ecd2161b2b8f/download)

**Comment by jdon-zev** [comment]
Ticket to be updated following spike ticket to come up with design solution for re-factor.
