### ISSUE TITLE
TFRS - [Tech Debt] Refactor UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by kcabhar** [bcgov/tfrs#2042]
Description of the Tech Debt

There are some legacy class based components that are still using the deprecated UNSAFE_componentWillReceiveProps lifecycle method. These components should be refactored to use a more modern approach to updating component state. There are approximately 33 components that need to be refactored, and a similar solution will most likely work for each of them.

Tech Debt Triage
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

**Comment by jdon-zev** [comment]
Discussed at stand-up: There are approx. 33 separate components that require different solutions. Jignesh to detail what he has done and then new card to be created to deal with the remaining components.

**Comment by AlexZorkin** [comment]
Here is a list of the changed components:
/CarbonIntensityLimitEditContainer.js
/DefaultCarbonIntensityEditContainer.js
/EnergyDensityEditContainer.js
/EnergyEffectivenessRatioEditContainer.js
/PetroleumCarbonIntensityEditContainer.js
/FuelCodeEditContainer.js
/HistoricalDataEntryContainer.js
/HistoricalDataEntryEditContainer.js
/UserAddContainer.js
/UserEditContainer.js
/Navbar.js
/SessionTimer.js
/ChangelogContainer.js
/ComplianceReportingContainer.js
/ComplianceReportingEditContainer.js
/ScheduleAContainer.js
/ScheduleBContainer.js
/ScheduleCContainer.js
/ScheduleDContainer.js
/ScheduleSummaryContainer.js
/AutosaveNotifier.js
/CreditTransferAddContainer.js
/CreditTransferEditContainer.js
/DashboardContainer.js
/components/UserSettings.js
/ExclusionReportEditContainer.js
/OrganizationEditContainer.js
/SecureFileSubmissionDetailContainer.js
/SecureFileSubmissionEditContainer.js

**Comment by jdon-zev** [comment]
Raj to test test pages relating to the list to check this is all working properly.
