### ISSUE TITLE
DevOps - TFRS - Upgrade Postgresql from v10 to v14 (Test and Prod)

### ISSUE THREAD

**Issue by kcabhar** [bcgov/tfrs#2043]
Th testing includes both application test and Metabase test

Please refer to the document at tfrs/charts/tfrs-spilo/Readme.md

**Comment by kuanfandevops** [comment]
TFRS Test database cluster is on v14

**Comment by kuanfandevops** [comment]
TFRS all environments are on v14 postgres.
