### ISSUE TITLE
TFRS - Login Issues

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2051]
**Describe the task**
Certain user accounts are not being mapped in TFRS and need manual intervention.

**Purpose**
To allow users the ability to login to TFRS.

**Acceptance Criteria**
- [x] investigate each user account and determine login issue cause
- [ ] fix user account information if possible

**Comment by emi-hi** [comment]
The spreadsheet has been updated with the fixed account and information needed on another

**Comment by emi-hi** [comment]
two of the accounts will likely need to have their keycloak id manually added

**Comment by airinggov** [comment]
Anna and Jamie resolved but other outsanding users will be fixed when update to allow IDIR admin to edit BCeID user name and email (presently uneditable)
