### ISSUE TITLE
TFRS - Three Columns not populating under File Submission tab

### ISSUE THREAD

**Issue by kcabhar** [bcgov/tfrs#2061]
**Describe the Bug**
Organization, Credit Transaction ID and Submitted on columns are not populating under File Submission tab under the second column. The fields are showing empty.

**Expected Behaviour**
When an IDIR user goes to the File Submission tab to receive a file, the organization that submitted the file, Credit transaction ID and the Submitted on date should show up in the Secure File Submissions list.

**Actual Behaviour**
Currently, there is no Organization, Credit Transaction ID or Submitted On date showing in the Secure File Submissions list.  Only when you click the submission is the organization visible in the P3A Milestone Evidence Submission page.   

**Implications**
This makes it difficult for analyst as they need to click through the submitted files to determine which file they need to process.  

**Steps to reproduce the behaviour:**
User/Role: IDIR analyst 
1. Go to 'Login to the TFRS Dashboard.'
2. Click on 'The “File Submissions” tab between “Fuel Codes” and “Compliance and Exclusion Reports.”'
3. Scroll down to 'The Secure File Submission List'
4. See error ‘No organization, credit transaction ID or submitted on date displayed, on the in the list and filtering also throws an error.’

![File Submission Page.jpg](https://images.zenhubusercontent.com/637d5c007e28c84cebc3a147/061b2c07-b81e-4c51-9a8e-3e1fbdf3bd14)

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2061?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2061?planning-poker) with Zenhub @JulianForeman
