### ISSUE TITLE
TRS - Fuel Codes not populating

### ISSUE THREAD

**Issue by kcabhar** [bcgov/tfrs#2063]
**Describe the Bug** 
Fuel codes are not being populated in the drop-down menu and cannot save fuel codes.

**Expected Behaviour** 
AS an IDIR user when adding new fuel codes or existing fuel codes to other organizations the BCLCF fuel should create a prepopulated list of codes in the search box.  

**Actual Behaviour** 
Currently, the prepopulated list is producing “No Results”.  When the information is filled in manually the IDIR user is still unable to add or save the new fuel code.  An error message pops up is asking for the information that is already filled in.  

**Implications** 
This is preventing analyst for adding new fuel codes and it is preventing fuel suppliers from submitting compliance reports that require the fuel code information.   

**Steps to reproduce the behaviour:** 
User/Role: IDIR
1. Go to 'TFRS Dashboard and navigate to the fuel codes tab.' 
2. Click on 'New Fuel Code in the fuel codes tab under fuel codes to get to the New Fuel Code Page.' 
3. Scroll down to 'the first search box “BCLCF and try to search any number sequence e.g., BCLCF101.' 
4. See error No Results shown and when filled out manually unable to save or add new fuel code.  Similar to the File submission moodle issue.

**Comment by jdon-zev** [comment]
This may have been resolved as part of ticket # . Need to check this in user testing.
