### ISSUE TITLE
TFRS - Add transaction ID to Credit Transaction pages

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2084]
**Title:** Add transaction ID to Credit Transaction H! page title

**Description:** For all TFRS users (bceid & idir) and roles that have access to credit transactions, display the transaction ID in the H1 page title.

"Transaction Type" — ID: ###

**Wireframe:** see screen capture

**Purpose and benefit to user:**
The transaction ID is useful information to help distinguish what transaction you are looking at.

**Acceptance Criteria:**

- [ ] Given I am a idir, When I am looking at the credit transaction , then it should show the transaction id beside transaction name
- [ ] Given I am a bceid, When I am looking at the credit transaction , then it should show the transaction id beside transaction name

**Development Checklist:**
- [ ] A Take the transaction id and add H1 tag with ID

**Notes:**

**Comment by airinggov** [comment]
![transaction-id.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/43518976-e037-494b-82d4-a58246d6950e)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2084?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
