### ISSUE TITLE
TFRS - New 'agreement date' entry field in new credit transfer proposal page

### ISSUE THREAD

**Issue by kcabhar** [bcgov/tfrs#2096]
**Title:**

Add new 'agreement date' entry field in new credit transfer proposal page

**Description:**

As an IDIR user, I would like to have the a widget that gets fuel suppliers to confirm the date on which the written agreement to transfer credits was reached between the two suppliers

Add new field in the new credit transfer proposal page.
Suggested text: Please confirm the date on which the written agreement to transfer credits was reached between the two suppliers.
Field should be a calendar widget
Field should be a requirement before user is able to propose the transfer
Show the entry date on the view credit transfer details page.
Back-end
New column in data table?

**Wireframes:**

Supplier draft/propose
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/163660828/?mode=cvidmf

2nd Supplier sign
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/163661254?mode=cvidmf

Analyst review
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/163660829?mode=cvhidf

Analyst recommend
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/163660830?mode=cvhidf

Director approve
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/163660831?mode=cvhidf

**Purpose:**

The requested to provide better context on the price of the traded credits.  As some trade agreements which were negotiated and sign potentially over a year ago the trades may potentially be executed at a lower cost when compared to current fair market value.  This information is then reflected in the credit market report as supplier use the market report for decision making. 

**Acceptance Criteria:**
- Given I am an IDIR user I must have a date field in the credit transfer proposal page.
- Make sure the date field is available to the credit transfer proposal page.

**Development Checklist:**
- [ ] Add a date widget field to the credit transfer proposal page .
- [ ] Add Suggested text as "Please confirm the date on which the written agreement to transfer credits was reached between the two suppliers."
- [ ] Make the entry date visible on the view credit transfer  proposal page.
- [ ] Also add a new column in data table for the proposed date field.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2096?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by airinggov** [comment]
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/161057633/simulate/no-panels?mode=mf

**Comment by justin-lepitzki** [comment]
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/162954828?mode=fm

**Comment by ChopraRaj** [comment]
Tested the scenario.  The widget appears to be working.  However, it did categorize the CTP as Category D (which it is not).  Fuel supplier is able to click and see the Category D check box.  It tosses an error when clicked.
