### ISSUE TITLE
TFRS - Add instructional text to the BCeID File Submissions - New Other Submissions page

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2125]
**Title:** Add instructional text to the BCeID File Submissions  - New Other Submissions page

this is related to card 2126

**Description:**
Add instructional text to explain how to use the Other category to submit files for a variety of different records within the system. Text is directly below and should be added as per the screen capture.

Use the Attachment Type category "Other" to submit documents and attachments associated with existing:

- Compliance Reports
- Exclusion Reports
- Carbon Intensity Applications
- Initiative Plans
- Credit Transaction Proposal

Use the Comment field to identify what records this file submission apply to. For example, "This submission pertains to our 2021 Compliance Report".

**Wireframe:** 
![file-submissions.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/331ab104-3105-4d85-bdcf-0b33614332d4)

**Purpose and benefit to user:**
BCeID users have a better understanding how to submit files for various purposes.

**Acceptance Criteria:**

- [ ] Given I am a BCeID File Submitter, When I am on the File Submission page, then I can read some instructional text

**Development Checklist:**
- [ ] A. Add the instructional text as mentioned on the description to the  "New Other Submissions page" under the file submission tab for the BCeID user.
- [ ] B. Add the text to the location in the front end as per the Wireframe attached.

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2125?planning-poker) with Zenhub @AlexZorkin

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2125?planning-poker) with Zenhub @vibhiquartech @tim738745

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2125?planning-poker) with Zenhub @jig-patel

**Comment by airinggov** [comment]
tested with business area 3/29
