### ISSUE TITLE
TFRS - Enable IDIR Users to Export Fuel Supplier User Contact Information

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2127]
**Description:**
As an IDIR user, the ability to export a list of fuel supplier user contact information in an Excel format is required. This feature will be added to the existing Fuel Suppliers page by introducing a new button for downloading user information while renaming the current button for better distinction.

**Purpose and benefit to user:**
The purpose of this feature is to facilitate efficient communication between IDIR users and fuel suppliers by providing an accessible and organized list of contact information. This will enable IDIR users to reach out to stakeholders regarding key issues, upcoming events, and other essential topics.

**Acceptance Criteria:**
- [ ] Add a new button labeled "Download User Information" on the Fuel Suppliers page.
- [ ] Rename the existing button to "Download Supplier Information" for better clarity.
- [ ] Ensure that the exported Excel file contains the following columns:
 * First name
 * Last name
 * Email BCeID 
 * BCeID Username
 * Title
 * Phone
 * Email Notifications
 * Status
 * Fuel Supplier (Organization)
 * Role(s)
- [ ] Test the new "Download User Information" button to confirm that it exports the fuel supplier user contact information in the correct format.
- [ ] Verify that the exported Excel file contains accurate and up-to-date information.

**Wireframe:** 
![fuel-suppliers.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/91e97d4c-afb3-40d6-b485-776866496b39)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2127?planning-poker) with Zenhub @AlexZorkin @vibhiquartech @tim738745

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2127?planning-poker) with Zenhub @jig-patel

**Comment by airinggov** [comment]
Can you check the BCeID Username values? they appear to be more like a GUID rather than the User Name.

Also please change the Excel file name from example BC-LCFS_organizations_2023-04-28

to change the 'organizations' to 'bceidusers' so the two download files have different names

**Comment by tim738745** [comment]
@airinggov sure, will do!

**Comment by airinggov** [comment]
@tim738745 sorry Tim, I don't think i wrote the error very well above with the username issue

previously we had a record like this
BCHydro Test zelda@gov.bc.ca user1671746007734

the update you made now returns
BCHydro	Test zelda@gov.bc.ca Test BCHydro

what I'm expecting to see instead of user1671746007734 or Test BCHydro

is bceid\tbchydro or just tbchydro

**Comment by tim738745** [comment]
@airinggov okay, let me take another look

**Comment by tim738745** [comment]
@airinggov I made a change (PR is up right now); the username you're looking for is a user's keycloak/external uername, and we don't necessarily store those; we have those if they're a mapped user and they've logged in before, so not all users will have this username.

**Comment by airinggov** [comment]
ok that's fine, thanks for looking into it

**Comment by tim738745** [comment]
@airinggov no problem!
