### ISSUE TITLE
TFRS - Add BC Attorney Address (IDIR)

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2129]
**Title:** Add a second optional address for supplier Corporation or BC Attorney address

**Description:**
If the suppliers address is not in B.C. there is a legal requirement to have their Corporation or BC Attorney address. This is the address that permits them to operate in B.C. So suppliers may require two addresses (Head Office and Corporation or BC Attorney address).

Add new address fields (including optional Corporation or BC Attorney Name) to the database. See wireframe

Additional suggested updates when making this update:
- remove Address 3 from form and database (first check for any stored info and add to Address 2 if needed)
- remove County (not Country) from form and database (first check for any stored info and add to Province/State if needed)
- convert dropdown menus of one and two values to radio buttons (Organisation Status and Type)

**Wireframe:** 
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/161516664/simulate/no-panels?mode=mf

**Purpose and benefit to user:**
This is a legal requirement.

**Acceptance Criteria:**

- [ ] Given I am a IDIR Administrator, When I am adding or editing supplier information, then I'd like to be able to add a second address for suppliers that aren't primarily located in BC.

**Development Checklist:**
- [ ] A. Add a new address(second address) field to the DB.
- [ ] B. Remove Address 3 from OrganizationEditForm and move address 3 info from DB to address 2
- [ ] C. Remove County from OrganizationEditForm and move County data from DB into Province/state field
- [ ] D. Convert Organization type to radio button on OrganizationEditForm.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2129?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2129?planning-poker) with Zenhub @emi-hi

**Comment by jdon-zev** [comment]
To be closed - testing to be done based on future cards that complete this feature.
