### ISSUE TITLE
TFRS - Display BC Attorney Address on Compliance and Exclusion Reports

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2131]
**Title:** Display BC Attorney Address on Compliance and Exclusion Reports

**Description:** All BCeID and IDIR users that can access Compliance and Exclusion Reports should see the B.C. Attorney Office address if it exists.

**Wireframe:**
![bc-address-onreport.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/ed1bc69f-5d25-4735-964e-fc8aeff1a084)

**Purpose and benefit to user:**
This is a legal requirement

**Acceptance Criteria:**

- [ ] Given I am a BCeID and IDIR users that can access Compliance and Exclusion Reports, When I am looking at Compliance and Exclusion Reports, then I can see the B.C. Attorney Office address if it exists.

**Development Checklist:**
- [ ] Check if the B.C. Attorney Office address if it exists in the DB.
- [ ] If the B.C. Attorney Office address exists in the DB then fetch the details and display on the front-end but make sure that the user have access to Compliance and Exclusion Reports.

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2131?planning-poker) with Zenhub @AlexZorkin

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2131?planning-poker) with Zenhub @vibhiquartech

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2131?planning-poker) with Zenhub @jig-patel

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2131?planning-poker) with Zenhub @tim738745

**Comment by airinggov** [comment]
Good on the BCeID side but needs to be added on the IDIR side. Also it should show the BC Attorney Name if there is a value (both BCeID and IDIR)

**Comment by tim738745** [comment]
@airinggov sure!
