### ISSUE TITLE
TFRS - Display BC Attorney Address on Organization Details page

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2145]
**Title:** Display BC Attorney Address on Organization Details page

**Description:**
Display BC Attorney Address on Organization Details page as per wireframe and add a email link for suppliers to request an address update.

Email lcfs@gov.bc.ca to update address information.

set mailto to have a subject line of TFRS Address Update

**Wireframe:**
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/161589011?mode=fm

**Purpose and benefit to user:**
Suppliers can see their address information and know how to have it updated.

**Acceptance Criteria:**
- [ ] Given I am a BCeID Managing User, When I am on the Organization Details page, then I see my company address information and have a link to request an update.

**Development Checklist:**
- [ ] Update the Organization Details page  to display BC Attorney Address after fetching the required details from the back-end. For reference refer the wireframe.
- [ ] Add an email link for suppliers on Organization Details page to request an address update.
- [ ]  Set Email as lcfs@gov.bc.ca to update address information and also set mailto to have a subject line as "TFRS Address Update".

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2145?planning-poker) with Zenhub @emi-hi

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2145?planning-poker) with Zenhub @vibhiquartech

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2145?planning-poker) with Zenhub @tim738745

**Comment by airinggov** [comment]
I can't access the Organization page as either IDIR or BCeID, we're sorry error.

**Comment by tim738745** [comment]
@airinggov I can take a look at this one
