### ISSUE TITLE
TFRS - Compliance Report Schedule D Validation Error due to character limit

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2149]
**Describe the Bug**
As a supplier trying to complete a Compliance Report, adding data to Schedule D. The Validation is giving an error "There is missing information, please ensure all fields are completed." even when the data is complete.

**Expected Behaviour**
I expect to pass validation when I have added a complete and accurate record in Schedule D so that I can save the report and carry on.

**Actual Behaviour**
The Validation is giving an error "There is missing information, please ensure all fields are completed." even when the data is complete. It appears to be triggered when a certain amount of characters are added,  breaking a maximum character limit. This is a problem for entering formula information in the Value field (formula for carbon intensity).

**Current maximum character limit is 100 character for both.
Solution - Increase Value field to 255 characters.**

**Implications**
Schedule D cannot be saved and I cannot complete my compliance report.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID Compliance Manager
1. Go to a new or existing draft compliance report
2. Click on schedule D
3. Complete a row and save record. Then add more characters to Value or Description until you see the error

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2149?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
