### ISSUE TITLE
TFRS - Bug - Error when Supplier submitting Compliance Report

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2161]
**Describe the Bug**
A supplier reported getting the following error after submitting a compliance report. The report did actually get submitted successfully.

![com-sub-error.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/6be61525-5aae-4a6b-8022-8abf0eb5a828)

Friday Mar 10, I tried to replicate the error and received the We're Sorry error when trying to access the Summary & Declaration tab to submit the report.

Tue Mar 14 I was able to submit with no errors.

**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happens.

**Implications**
A clear and concise description of any implications.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:

Development Checklist:

 A. Check if new token being used after session time out on front end.
 B. File to look into is sessionTimeout in Redux Saga.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2161?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
