### ISSUE TITLE
TFRS - Refactor Filtering on Compliance and Exclusion Report List View

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2179]
**Description:**
The objective of this sprint ticket is to refactor the filtering functionality on the compliance and exclusion report list view to improve usability and efficiency. We are awaiting input from the business area regarding the desired status columns and filtering options. Once the necessary information is received and a UI design is provided, the development team will implement the new filtering options, which may include selection dropdowns or pillboxes for multi-filter selection.

**Wireframe:** 
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/161888650?mode=fm
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/162031477?mode=fm

green pill: #578260

IDIR
For analyst review
•	Submitted

For manager review
•	Recommend Acceptance – Analyst
•	Recommend Rejection – Analyst

For director review
•	Recommend Acceptance – Manager
•	Recommend Rejection – Manager

Supplemental Requested
•	Supplemental Requested

Accepted
•	Accepted

Rejected
•	Rejected

BCeID
In Draft
•	Draft

Awaiting Government Review
•	Submitted

Supplemental Requested
•	Supplemental Requested

Accepted
•	Accepted

Rejected
•	Rejected

**Purpose and benefit to user:**
More logical and effective status filtering.

**Acceptance Criteria:**
- [ ] Confirm the status columns required by the business area.
- [ ] Reviewhttps://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/162031477?mode=fm the provided UI design and discuss the filtering options, such as selection dropdowns or pillboxes for multi-filter selection.
- [ ] Refactor the compliance and exclusion report list view to implement the new filtering options based on the received information and UI design.
- [ ]Ensure that the updated filtering options improve the usability and efficiency of the list view.
- [ ]Test the refactored filtering functionality to ensure it works as expected and satisfies the requirements of the business area.
- [ ] Update documentation and notify relevant stakeholders of the changes to the compliance and exclusion report list view.

**Notes**
Please wait for the required information from the business area and the UI design before starting the refactoring process.

Development checklist
A. Refactor filtering functionality for ComplianceReport and exclusion report once we get input from business depending on how they like to filter.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2179?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2179?planning-poker) with Zenhub @JulianForeman

**Comment by jdon-zev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2179?planning-poker) with Zenhub @emi-hi

**Comment by jdon-zev** [comment]
Al to discuss approach with the business area to confirm they are happy with the proposed approach. Following this the card is to be reviewed again and re-estimated.

**Comment by airinggov** [comment]
- Not showing Supplier column for IDIR users
- Make table default sort of last status update descending
- Have ‘Supplier’ filter list in alphabetical order.
- Deleting the ‘Supplier’ name does not clear the filter; have to click on ‘Clear Filters’ button
     - Sort of unexpected behaviour as I would think deleting the supplier’s name would remove the ‘Supplier’ filter
- Have ‘Compliance Period’ filter be in descending order (from high to low). Currently it is in ascending order
- Ascending / Descending filtering isn’t working for the 3/4 columns
- Not working:
  - Compliance Period
  - Type
  - Current Status
  - Working
  - Last Status Update
- Filtering by Exclusion Reports and then filtering by Compliance Period (YYYY) seems to hang up

**Comment by jig-patel** [comment]
i will look into it.

**Comment by justin-lepitzki** [comment]
1. The default sorting of the table is working as requested (sort by Last Status Update, descending). However, when you navigate to the next page of report entries it doesn't maintain this sorting. The list gets reordered / randomized.  
2. The compliance period drop-down filter is missing "2024" as an option to select. There are 2024 reports submitted but you can't select that year to filter. 
3. There are still some issues with sorting the columns by ascending/descending for compliance period, supplier, type, and current status columns. They seem to be sorting from bottom up rather than top down. Al and I were discussing the option to just disable the ascending/descending sorting for these columns rather than trying to fix them. With the new filtering at the top, they aren't really needed anymore; the only column that has value in sorting ascending/descending is the "Last Status Update" column.

**Comment by jig-patel** [comment]
i will take look into it.

**Comment by jig-patel** [comment]
@justin-lepitzki @airinggov @AlexZorkin should i remove sorting as mentioned in point 3 ?
