### ISSUE TITLE
TFRS - Identify Class-Based Components and Outline Required Work to Convert them to Functional

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2180]
**Describe the task**
The objective of this task is to identify all React class-based components within Project TFRS that need to be updated and outline the work required to convert each of them to functional components.

**Purpose**
The purpose of this task is to create a comprehensive list of class-based components and the necessary steps to convert them. This will serve as a foundation for future tasks focused on modernizing the project and improving consistency throughout the application.

**Acceptance Criteria**
- [ ] Identify and list all React class-based components in the project.
- [ ] For each class-based component, analyze its functionality and any state management or lifecycle methods used.
- [ ] Outline the work required to convert each class-based component to a functional component, including any changes needed for state management and lifecycle methods using React Hooks.
- [ ] Create a document or spreadsheet to organize the identified components and their respective conversion steps.
- [ ] Share the document with the development team and gather feedback on the planned conversions.

**Additional context**
- Focus on accurately identifying the components and outlining the necessary work for conversion, as this information will be used for future tasks.
- Coordinate with the development team to ensure a comprehensive understanding of the class-based components and to minimize conflicts and disruptions to ongoing work during the conversion process.

**Comment by jig-patel** [comment]
[https://app.zenhub.com/files/80058415/eb51ed17-d87f-44ef-9860-3b6bfc9ea19b/download](https://app.zenhub.com/files/80058415/eb51ed17-d87f-44ef-9860-3b6bfc9ea19b/download)

**Comment by AlexZorkin** [comment]
Thank you for the well thought out report!

**Comment by kcabhar** [comment]
Not able to test
