### ISSUE TITLE
TFRS - Squash Django Migrations for Project TFRS

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2181]
**Describe the task**
The goal of this task is to squash Django migrations in the backend for project TFRS to optimize the application's performance and reduce the time taken for running migrations during deployment.

**Purpose**
Squashing migrations will help maintain the cleanliness of the codebase, improve the application's performance, and reduce deployment times. It adds value by streamlining the development process and providing a better experience for the development team.

**Acceptance Criteria**
- [ ] Identify and list all the Django migrations that need to be squashed.
- [ ] Create a new squashed migration file combining the selected migrations.
- [ ] Ensure that the new squashed migration file correctly replaces the original individual migration files.
- [ ] Test the squashed migration file to confirm that the application's functionality remains unchanged.
- [ ] Update any relevant documentation and inform the development team about the squashed migrations.

**Additional context**
- Consider the dependencies between migrations while squashing to avoid conflicts.
- Coordinate with the development team to ensure that no ongoing work is disrupted during the migration squashing process.

**Comment by jdon-zev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2181?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745

**Comment by AlexZorkin** [comment]
This has been approved but will hold off on merging until the next tfrs prod release is deployed.

**Comment by AlexZorkin** [comment]
This pr will have to be repointed to the latest release branch 2.7.0

**Comment by kcabhar** [comment]
Not able to do user testing
