### ISSUE TITLE
TFRS - Replace Modal.js with React-Based Component in TFRS Project

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2183]
**Describe the task**
The objective of this task is to address technical debt in the TFRS project by replacing the current Modal.js implementation, which relies on jQuery, with a React-based component. This will enable the removal of jQuery as a dependency, simplifying the codebase and modernizing the project.

**Purpose**
The purpose of this task is to improve the maintainability and consistency of the TFRS project by eliminating the need for jQuery and fully adopting React as the main UI library. This will result in a more efficient and streamlined development process while minimizing potential issues arising from using multiple libraries.

**Acceptance Criteria**
- [ ] Identify all occurrences of Modal.js usage in the project.
- [ ] Create a new React-based modal component that replicates the functionality of the current Modal.js implementation.
- [ ] Replace all instances of Modal.js with the newly created React-based modal component.
- [ ] Ensure that the new React-based modal component functions correctly and maintains the same behavior as the original Modal.js.
- [ ] Test the updated modal implementation to confirm that it works as expected and does not introduce any new issues.
- [ ] Remove jQuery as a dependency once all instances of Modal.js have been successfully replaced.
- [ ] Update any relevant documentation to reflect the changes made to the modal implementation.

**Additional context**
- Consider any potential impacts on performance and user experience when creating the new React-based modal component.

Development checklist:
A. Refactor Modal.js file to use React based component.
B. Replace all instance of Modal.js with the newly created modal component
C. Make sure it doesn't break existing Modal.js functionality.

**Comment by jdon-zev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2183?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2183?planning-poker) with Zenhub @vibhiquartech

**Comment by jdon-zev** [comment]
Not able to user test - card to be closed.
