### ISSUE TITLE
TFRS - Justin Lepitzki login issues

### ISSUE THREAD

**Issue by kcabhar** [bcgov/tfrs#2190]
**Describe the Bug**
Justin Lepitzki is having issues logging into the Test Environment with his IDIR.  Justin has an old legacy account and there is no email or IDIR associated with his account.  Raj tried to add the email and IDIR however it will not save correctly.    

**Expected Behaviour**
Currently when Justin tries to login to Test with his IDIR it throws an error see screenshot.

**Actual Behaviour**
Justin has an old legacy account and there is no email or IDIR associated with his account.  Raj tried to add the email and IDIR however it will not save correctly.  There might be a conflict with one of Justin’s other Test accounts under BCeID.  One of his other accounts is under South Coast Fuels, and he is listed a Riley Jones.  However, when he logs in, the name in the corner says Justin Lepitzki.  This could be what is causing the issue with the IDIR not being able to be saved on his IDIR account.  This might have to be manually mapped by a developer.   
 
**Implications**
Justin cannot login to test.  

![JL Login Issue BCeID.png](https://images.zenhubusercontent.com/637d5c007e28c84cebc3a147/44d8d228-7121-4cdd-bd94-318cf484df57)

![JL Login Issue IDIR Error.png](https://images.zenhubusercontent.com/637d5c007e28c84cebc3a147/5990c9fd-6fdf-45ca-be88-b0090b538477)

**Comment by AlexZorkin** [comment]
I inserted a new user_creation_request for Justin's IDIR account so on his next logic his account will get mapped.

**Comment by jdon-zev** [comment]
Close card - Justin to let us know if there are still any issues.
