### ISSUE TITLE
TFRS - Saving User Profile Bug

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2269]
**Describe the Bug**
When updating the user’s information in the user profile, after going to save the information, the user must confirm the update to the profile by clicking Yes on a confirmation alert (pop up window). The confirmation alert window does not disappear after the user confirms that they want to update the profile. 

**Expected Behaviour**
The confirmation alert should disappear after the user clicks on the “Yes” button to confirm the changes to their user profile. 

**Actual Behaviour**
The confirmation alert window remains on the screen despite the user selecting "Yes" to confirm the update and the system saving the updated information.

**Steps To Reproduce**
For both BCeID & IDIR Users:
1.	Click on the User’s Name in the top right-hand corner of the page
2.	Click on Settings, then click on the ‘User Profile’ sub-tab
3.	Make a change to the information in one of the fields for the user profile 
4.	Click the ‘Save User’ button
5.	The confirmation alert window will appear asking the user to confirm the update
6.	Click “Yes”, the Confirmation window remains on the page. 

**Screenshot(s):![Screenshot_2023-04-26_User-Profile-Confirmation-Alert-Bug.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/0f8896ec-00b1-4c12-8967-d8d4d6538711)**

**Notes**
Probably just an issue in the handleSubmit() function of UserEditContainer.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2269?planning-poker) with Zenhub @AlexZorkin @jig-patel @tim738745
