### ISSUE TITLE
TFRS - Default sorting by latest file submission date for File Submissions table

### ISSUE THREAD

**Issue by kcabhar** [bcgov/tfrs#2272]
**Describe the Bug**
Default Sorting by Latest Submission Date for the Secure File Submissions Table 

**Expected Behaviour**
The main table on the File Submissions section's first entry should be the latest file submission date and the last entry at the bottom of the last page should be the oldest file submission. This table should be sorted by latest file submission date at the top. 

**Actual Behaviour**
Currently not sorting this way. 

**Implications**
This will enable the user to quickly and efficiently see the latest file submissions that are relevant to their work. We have over 200 submissions so seeing the latest submissions as they come in is critical to tracking new tasks and items to action. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR and BCeID
1. Go to the 'File Submissions' page
2. See main File Submissions table is not sorted by latest submission date (as seen in screen grab below)

![image.png](https://images.zenhubusercontent.com/637d5c007e28c84cebc3a147/09035275-5ad8-4e26-b1ac-4ce2dfdbcb72)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2272?planning-poker) with Zenhub @AlexZorkin @jig-patel @tim738745

**Comment by airinggov** [comment]
I still get the oldest records appearing at the top of the first page by default. We want to get the newest at the top of the first page descending to the oldest record at the bottom of the last page.

**Comment by prv-proton** [comment]
There seems to be problem with code merge, changed code is not available in test environment. Will raise PR once again for the changed code.
