### ISSUE TITLE
TFRS - compliance reports taking too long to load

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2273]
**Describe the Bug**
When opening a compliance report in TFRS, the system can take several minutes to actually load the report. In some instances, the report seems to get stuck loading and will not resolve itself. A refresh seems to start the process over again where it takes a while to load or gets stuck. There seems to be errors showing when Inspecting the page.

**Expected Behaviour**
When opening a compliance report in TFRS, the report should open in a timely manner. 

**Implications**
This issue is reducing user productivity in reviewing compliance reports, assessing compliance and penalties, and identifying system issues (e.g., which reports have an incorrect penalty calculation, a known bug/issue).

**Steps To Reproduce**
Steps to reproduce the behaviour:
IDIR user
1. Go to the 'Compliance & Exclusion Reports' page
2. Click on a 'Compliance Report'
3. Experience slow loading reports

**Video Example:**
https://images.zenhubusercontent.com/80058415/793ea092-62b3-44d3-ae6c-20c2a4b13a1a/screencast_lowcarbonfuels_gov_bc_ca_2023_04_28_09_38_23_slow_loading_compliance_report___mp4.mp4

**Screenshot:**
![Screenshot 2023-04-28 102700.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/1fea8a38-9d49-4420-b237-ec844f440e0e)

**Developer Requirements:**
- [ ] Investigate the current implementation of the API call and query.
- [ ] Identify bottlenecks and potential areas for optimization.
- [ ] Propose a solution to either optimize the performance of the API call and query, or rewrite it in a more efficient way.
- [ ] Implement the proposed solution and test its performance.
- [ ] Document the changes made to the code and any new dependencies added (if any).

**Suggested Steps:**
- Analyze the Django view and the corresponding queryset responsible for fetching the compliance reports. Inspect if there are any unnecessary joins or calculations being performed.
- Review the data model and identify any redundant or inefficient data structures that may be slowing down the query performance. Consider normalizing the data model if required.
- Examine the database indexes and ensure appropriate indexing is in place for the columns involved in filtering and sorting the compliance reports.
- Look into the possibility of using Django's select_related() and/or prefetch_related() queryset methods to optimize related object fetching and reduce the number of database queries.
- Implement the identified optimizations and measure the performance improvement. Use tools like Django Debug Toolbar or other profiling tools to monitor the performance of the API call and query.
- Thoroughly test the updated implementation to ensure that the functionality remains intact and the performance has improved.
- Document the changes made, any new dependencies added, and provide an overview of the optimization strategy implemented. This documentation will help future developers to understand the rationale behind the changes and make it easier for them to maintain and improve the codebase.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2273?planning-poker) with Zenhub @AlexZorkin @jig-patel @tim738745

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2273?planning-poker) with Zenhub @jig-patel

**Comment by prv-proton** [comment]
@AlexZorkin , have fixed the review comments. Please let me know if there are still any issues. Thanks

**Comment by justin-lepitzki** [comment]
Adding link to the two cards I created that are related to this: 
1) [https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2346](https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2346)
2) [https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2345](https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2345)

**Comment by justin-lepitzki** [comment]
Unable to create supplemental reports as a BCeID user. Clicking on the Create Supplemental Report button causes the spinning wheel to appear but never to actually load the report. This issue is preventing the release of other bug fixes to production.

**Comment by justin-lepitzki** [comment]
'Current Status' column in the main Compliance & Exclusion Reports table is not updating for IDIR users when a Supplemental Report is submitted. The IDIR user can view the supplemental report and make recommendations (process it) correctly, but the statuses are not updating after the recommendation is made (recommend accept or recommend reject). The status also does not update when the report is accepted by the director ('Accepted' status) or when a supplemental report is requested ('Supplemental Requested' status). This appears to only be an IDIR issue related to supplemental reporting; statuses update correctly when processing the original report (no supplementals). 

See examples in Test env:
1) Exclusion Report for 2022, ID #1006, Zapp Brannigan Electric Co.; supplemental report has been accepted but 'Current Status' column in main table is showing as 'Submitted'. 
2) Compliance Report for 2020, ID #1002, Zapp Brannigan Electric Co.; supplemental report has been reviewed and recommended for acceptance by compliance manager but 'Current Status' column in main table is showing "Supplemental Requested'.
