### ISSUE TITLE
TFRS - Correct two compliance period fields for Part 3 Award credit transactions in Prod

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2306]
**Describe the task**

This task involves correcting a data entry error in the production database concerning two Part 3 Award credit transactions. Credit transaction IDs #1490 and #1506 currently have '2022' listed as the compliance period, which is incorrect. The actual compliance period for these transactions should be '2023'. This correction needs to be done directly in the database. This is a secondary field, not to be confused with effective date.

**Purpose**

This correction is essential to maintain the accuracy of the Branch's reporting of credit transactions, which are publicly available on its website. The data regarding how many credits are issued each year under Part 3 Agreements is crucial for the Branch's compliance modeling. If left uncorrected, this error could potentially skew the data and present an inaccurate representation of credit transactions for the years in question.

**Acceptance Criteria**

- [ ] Write out the sql queries that will be used in production and review with the tfrs lead before proceeding.
- [ ] The compliance period for credit transaction IDs #1490 and #1506 has been updated in the production database from '2022' to '2023'.
- [ ] The updated data has been thoroughly checked to ensure its accuracy.
- [ ] The correction has been communicated to the necessary stakeholders and reflected appropriately in any public-facing reporting.

**Additional context**

- This task involves live production data, hence meticulous care is required to avoid disrupting ongoing operations.
- Prior experience or competence with database management is essential for this task.
- A comprehensive backup of the database should be created before making any changes to prevent potential data loss.
- Any changes made should be fully documented to maintain a record of the adjustments to the data.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2306?planning-poker) with Zenhub @AlexZorkin @jig-patel @JulianForeman @prv-proton @tim738745

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2306?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745

**Comment by justin-lepitzki** [comment]
Transaction ID# 1506 is still showing the compliance period as being 2022 in Prod, including when I download the transactions in a spreadsheet. Transaction #1490 is showing the corrected compliance period of 2023.
