### ISSUE TITLE
TFRS - Input corrected penalty amounts for certain 2022 compliance reports in Prod database 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2309]
**Describe the task**
A bug in TFRS caused some non-compliance penalties for 2022 compliance reports to be calculated at the wrong rate of $600 per outstanding debit rather than the correct amount of $200 per outstanding debit. This bug has since been fixed but the database values used for displaying the snap shots, downloading reports as xls, etc. in Prod are still showing the incorrect amounts. 

This task is to input the correct penalty amounts for the impacted 2022 compliance reports in Prod database. 

**Purpose**
This task is needed in order for the director to be comfortable with completing the processing of the compliance reports. This issue is roadblocking these reports. 

**Impacted Compliance Reports & Correct Values:**
A word document will be provided once this task has been assigned. This information is not included here as it is confidential and cannot be shared on a publicly accessible site/board. 

**Acceptance Criteria**
-  Write out all sql queries that will be run on the production database in a file and review with the tfrs lead dev
-  All affected penalties values in the JSON snapshot fields have been identified and updated in the production database.
-  The production database has been thoroughly tested and confirmed to display the corrected values in the snapshots and downloadable reports.
-  The director has reviewed and confirmed the correctness of the updated compliance reports.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2309?planning-poker) with Zenhub @AlexZorkin @jig-patel @JulianForeman @prv-proton @tim738745

**Comment by justin-lepitzki** [comment]
Report ID #1828 is still showing incorrect values for the original report and two supplementals (#1 & #2). The latest report (Supplemental Report #3) is showing the correct values. All other reports are showing the correct values.

**Comment by justin-lepitzki** [comment]
Adding link to the two cards I created that are related to this: 
1) [https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2346](https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2346)
2) [https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2345](https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2345)
