### ISSUE TITLE
TFRS - Correction of Erroneous Line 27 Values in Production Database

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2311]
**Describe the task**
This task involves rectifying inaccurate data in the production database caused by a bug in the TFRS system. The bug, which resulted in positive values being erroneously stored in Line 27 of summary snapshots instead of zeroes, has been fixed. However, the production database still holds these incorrect values in the JSON snapshot fields, affecting the display of snapshots and the download of reports. The aim of this task is to correct these values for the impacted compliance reports in the production database.

**Purpose**
The task is crucial to resume processing of the compliance reports, which is currently stalled due to this issue. The correction of these values will instill confidence in the director and allow for the continued processing of these reports.

**Impacted Compliance Reports & Correct Values:**
Detailed information regarding the impacted compliance reports and their correct values will be provided in a separate, confidential Word document once the task is assigned. As this information is sensitive, it won't be shared on any publicly accessible platform.

**Acceptance Criteria**
- [x] Write out all sql queries that will be run on the production database in a file and review with the tfrs lead dev
- [x] All affected Line 27 values in the JSON snapshot fields have been identified and updated in the production database.
- [x] The production database has been thoroughly tested and confirmed to display the corrected values in the snapshots and downloadable reports.
- [x] The director has reviewed and confirmed the correctness of the updated compliance reports.

**Additional context**

- It's important to remember that this task involves live production data, hence meticulous care is required to avoid disrupting ongoing operations.
- The PostgreSQL database changes must be done manually, therefore prior experience or competence with PostgreSQL is essential for this task.
- A comprehensive backup of the database should be created before making any changes to prevent potential data loss.
- Any changes made should be fully documented to maintain a record of the adjustments to the data.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2311?planning-poker) with Zenhub @AlexZorkin @jig-patel @JulianForeman @prv-proton @tim738745

**Comment by AlexZorkin** [comment]
@justin-lepitzki just checking in on whether the suppliers and compliance reports that were effected have been identified. Do you have a list of reports I should be taking a look at? Thanks.

**Comment by AlexZorkin** [comment]
Updated all latest reports and past reports that had incorrect line 27 values.
