### ISSUE TITLE
TFRS - Extend fuel code availability in compliance reports beyond T+1

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2314]
**Describe the task**

The task aims to modify the fuel code availability logic in the TFRS system to extend the selection of fuel codes in compliance reports to three years beyond their expiry date (T+3). Currently, the system allows for fuel codes to be available for selection up to one year (T+1) after their expiry date. This change is necessary to accommodate situations where fuel, purchased within the fuel code's active period, is supplied after the code's expiry.

For instance, consider the biodiesel fuel code BCLCF135.3. It has a carbon intensity of 3.58 gCO2e/MJ with an effective period from March 13, 2017, to January 14, 2020. Under the current logic, this fuel code is selectable for compliance reports for 2017, 2018, 2019, 2020, and 2021. With the proposed change, the fuel code would also be available for selection for 2022 and 2023.

**Purpose**

This task is necessitated by a fuel supplier's inability to correctly report the supply of fuel in their 2022 compliance report due to the expiration of the fuel code more than two years prior. The supplier bought the fuel within the fuel code's effective period but didn't supply it until a couple of years later, as it was stored in a tank. By extending the availability of expired fuel codes, we can ensure more accurate reporting in such scenarios.

**Acceptance Criteria**

- [ ] The system allows for fuel codes to be available for selection in compliance reports three years beyond their expiry date (T+3).
- [ ] The updated logic has been tested with multiple fuel codes to ensure correct functionality.
- [ ] The change has been documented and communicated to all relevant stakeholders.

**Additional context**

- This task involves altering the logic of the current system; therefore, careful testing must be performed to ensure no unintended effects occur.
- It's crucial to ensure that the newly extended fuel codes are accurately reflected in the drop-down menu for compliance reports.
- The stakeholders, especially the suppliers, should be notified about this change in the system to prevent any confusion during their reporting process.

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2314?planning-poker) with Zenhub @AlexZorkin

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2314?planning-poker) with Zenhub @jig-patel @prv-proton @JulianForeman @tim738745

**Comment by justin-lepitzki** [comment]
This is task is on hold as the business area may not want to implement. There are some potential unintended consequences to investigate before proceeding.
