### ISSUE TITLE
TFRS - Backend Package Updates

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2315]
**Describe the task**
The task is to analyze the backend package updates suggested by Snyk: cryptography, django, pyjwt, and sqlparse. These packages need to be updated wherever there are no breaking changes to the system.

**Purpose**
The purpose of this task is to ensure that our system is running the latest, most secure versions of its dependencies. By updating the packages, we're ensuring that we're protected against any known vulnerabilities that might be present in the older versions. This helps us to maintain the stability, security, and efficiency of our system, thus adding value by minimizing potential risks.

**Acceptance Criteria**
- [ ] The cryptography package is updated to the latest stable version, with no breaking changes.
- [ ] The django package is updated to the latest stable version, with no breaking changes.
- [ ] The pyjwt package is updated to the latest stable version, with no breaking changes.
- [ ] The sqlparse package is updated to the latest stable version, with no breaking changes.
- [ ] All unit and integration tests pass after the updates.
- [ ] System functionality is tested and confirmed to be working as expected after the updates.

**Additional context**

- Please ensure to test all functionalities thoroughly after updating the packages to avoid any production issues.
- Document any changes made during the update process for reference and possible troubleshooting in the future.
- Coordinate with the team to ensure that the updates do not conflict with any ongoing or planned work.

**Comment by kcabhar** [comment]
Not able to do user testing
