### ISSUE TITLE
TFRS - Credit transfers, remove tree and leaf graphics

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2325]
**Title:** Remove the tree and leaf graphics from the credit transfer screen as shown in wireframe

**Description:** The graphics are being interpreted as having some meaning. We'd like to remove the graphics and make both boxes border colour as green (change the yellow border to match the green border).

**Wireframe:** <link>
![transfer-graphic.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/5d8d2b06-e15a-4b34-aedd-9a3ecd74ce74)

**Purpose and benefit to user:**

**Acceptance Criteria:**

- [x] Both boxes should not contain any SVG or Icons
- [x] Both should have green border.

**Development Checklist:**
- [x] Remove SVG/icons from the <div>'s
- [x] change the border color of 2nd box to same color as the 1st one (green)

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2325?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745
