### ISSUE TITLE
TFRS - 2022 Exclusion Report not visible in Prod 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2328]
**Describe the Bug**
Unable to access a 2022 Exclusion Report submitted by a supplier in Prod. The report entry is not visible / showing up in the Compliance & Exclusion Reporting main table. Report ID is # 1778. When we try to access it directly via URL we receive an error message and the report does not load. When inspecting the console, there are several errors. 

**UPDATE: The report disappears for IDIR users when the fuel supplier user creates a supplemental draft report.**

**Expected Behaviour**
Compliance & Exclusion reports submitted by suppliers should show up in the main table on the Compliance & Exclusion Reporting page. These reports should be accessible to IDIR users when clicked on. 

**Actual Behaviour**
The report does not appear in the main table. Attempting to access it through the URL gives an error. 

[Link to report: https://lowcarbonfuels.gov.bc.ca/exclusion_reports/edit/1778/intro](https://lowcarbonfuels.gov.bc.ca/exclusion_reports/edit/1778/intro)

**Implications**
Unable to view or process report. **Concerns around visibility of confidential information. Can anyone else see this report?**

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR
1. Go to Compliance & Exclusion Reports page
2. View entries in main table
3. See that report # 1778 is not listed in this table: 2022 Exclusion Report for Shell Trading Canada
4. Cannot access report directly via URL: [https://lowcarbonfuels.gov.bc.ca/exclusion_reports/edit/1778/intro](https://lowcarbonfuels.gov.bc.ca/exclusion_reports/edit/1778/intro)

**Additional Notes**
There are a few found issues with this bug:
1. nextProps.exclusionReports.item.isSupplemental sometimes 'item' is null so trying to access isSupplemental breaks the view. Adding a ? after item will fix this first issue.
2. It seems that this report 1778 doesn't exist in the database. Please import prod data to local and test whether this exclusion report can be found.

**Screenshots of Console Errors:**
1. ![Screenshot 2023-05-23 115104.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/2eb9318f-c56a-4c0f-abc8-388dfd2450b6)
2. ![Screenshot 2023-05-23 115137.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/b110ee5d-7f87-48d3-b4f7-ec5f80f62a82)
3. ![Screenshot 2023-05-23 115203.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/3f6650c0-8d02-4c5c-be37-8c3cfe67971e)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2328?planning-poker) with Zenhub @AlexZorkin @tim738745 @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
UPDATE: All compliance & exclusion reports are disappearing for IDIR users when the fuel supplier user creates a supplemental draft report. This issue may be related to the redesign of the Compliance & Exclusion Reports page and the removal of 2/3 of the status columns. The issue appears to be when the fuel supplier creates a new supplemental report (draft status) that the system prevents IDIR users from accessing all versions of that report, the current draft supplemental as well as all of the previously submitted/accepted versions (original + supplementals). IDIR users should not be able to access reports that are in a draft state but should still be able to access previously submitted versions.

**Comment by justin-lepitzki** [comment]
Unable to test until the "Create Supplemental" issue with 2273 has been resolved.
