### ISSUE TITLE
TFRS - Unable to delete Schedule D entry 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2337]
**Describe the Bug**
A BCeID user is not able to delete a fuel entry created in Schedule D. 

**Expected Behaviour**
A created fuel entry in Schedule D can be deleted by clicking on the delete / remove icon on the tab of the fuel entry.

**Actual Behaviour**
Clicking on the delete / remove icon on the tab is non-responsive.

**Implications**
A fuel supplier is unable to remove an entry after it is created which could lead to inaccurate reporting. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user / Compliance Reporting Role
1. Go to the Schedule D tab of a compliance report in a **Draft** state.
2. Click on 'Add Fuel' to create a new fuel entry (e.g., Fuel 1, Fuel 2, etc.)
3. Click on the delete / remove icon in the tab of the newly created fuel entry.
4. See error (non-responsive icon)

**Note:** Schedule D fuel entries should only be removable when the compliance report is in a draft state. 

**Screenshots:**
![Screenshot 2023-05-26 085532.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/d5cde787-beb4-4b66-a231-d0b2560416ad)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2337?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745

**Comment by justin-lepitzki** [comment]
There is an issue where the Schedule D entry can still be deleted after the report is submitted to government (i.e., not in a draft state/status). Both BCeID users and IDIR users can still delete the entry after submission, but it only gets deleted in the UI. Once the user refreshes, the entry is displayed again. Users should not be able to delete entries that are not in a draft state (i.e., submitted, accepted, etc.). 

https://images.zenhubusercontent.com/80058415/62a505d6-dd9b-4899-b01d-920addb1509b/screencast_lcfs.mp4

**Comment by ChopraRaj** [comment]
Tested scenario in dev BCLCF.  Was able to add fuel, save fuel, delete fuel, and submit.  Once submitted I was unable to delete fuel all within the Schedule D.  Appears to be working accordingly.
