### ISSUE TITLE
TFRS - Update error message by removing the "We have been notified and will look into it" lip service

### ISSUE THREAD

**Issue by Kailee-Douglas** [bcgov/tfrs#2354]
**Describe the task**
Currently, the error message in TFRS says, "We are sorry. It looks like our system is experiencing some technical difficulties. We have been notified and will look into it. Please try again later." Our team is not actually notified when there is an error.

Action: Update existing error message to "We are sorry. It looks like our system is experiencing technical difficulties. Please try again later."

**Purpose**
Because our team is not actually notified when there is an error, this is untruthful, misleading, and a poor user experience.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

Development checklist:
- Change the messages as mentioned above in StatusInterceptor.js file
 

**Additional context**
One user in the LCFS branch received an error message when attempting to approve a transfer, believed our team was notified, and then waited for four days before asking Justin about it. The misleading error message led to significant processing delays for the business side (between 200% - 400% longer processing time).

Subsequent related ticket with examine a fix where the backend is easily notified when there is an error.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2354?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745
