### ISSUE TITLE
TFRS - Add credit transfer category column to download as xls for Credit Transactions

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2391]
**Title:**
Add credit transfer category column to download as xls for Credit Transactions

**Description:**
Add a column to the spreadsheet downloaded by BCeID and IDIR users that shows the category (A/B/C/D) for approved credit transfers. 

**Wireframe:** 
![Screenshot 2023-06-20 130735.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/0c542e60-0a10-4eee-ba02-2a33683f90a4)

**Purpose and benefit to user:**
Enables the Low Carbon Fuels Branch to download complete credit transfer data for publishing on website: [Information Bulletin RLCF-017](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/electricity-alternative-energy/transportation/renewable-low-carbon-fuels/rlcf017_-_low_carbon_fuel_credit_market_quarterly_report_20230209.pdf) and [Credit Market Data sheet](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/electricity-alternative-energy/transportation/renewable-low-carbon-fuels/bc-lcfs_credit_market_data_2015_to_present.xlsx?forcedownload=true).

**Acceptance Criteria:**

- [ ] Given I am a **IDIR** user on the Credit Transactions page, when click on the 'Download as .xls' button, then the spreadsheet downloads and includes a column providing the appropriate Category for approved credit transfers.
- [ ] Given I am a **BCeID** user on the Credit Transactions page, when click on the 'Download as .xls' button, then the spreadsheet downloads and includes a column providing the appropriate Category for approved credit transfers.

**Notes:**

**Comment by jdon-zev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2391?planning-poker) with Zenhub @AlexZorkin @JulianForeman @prv-proton @tim738745
