### ISSUE TITLE
TFRS - System records transfers upon director approval based on effective date entry field 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2393]
**Describe the task**
As an IDIR user, the task is to modify the TFRS system to accommodate balance changes of a credit transfer once approved or recorded by the director. The system should either consider the date of the director's recording or the date proposed by the BCeID user ('effective date') choosing the latter of the two. In instances where no date is specified in the transfer proposal by the BCeID user, the transfer should be executed immediately upon the director's approval.

**Purpose**
The purpose of this task is to align the TFRS system with the latest Act that allows BCeID users to specify a later effective date for credit transfers. 

**Acceptance Criteria**
- [ ] Implement functionality that can accurately identify and compare the recorded or immediate date using database filters.
- [ ] When aggregating a suppliers credits together, we need to account for credit transfers with an effective date, and not include credits with a credit transfer effective date in the future, for both the supplier's actual balance and also their available credit balance. 
- [ ] Construct tests to verify the future effective date functionality and robustness of the new feature.

**Additional context**
- This feature is pivotal to aligning the system with new requirements established by the Act.
- The credits must remain in the selling supplier's in-reserve (pending) balance until the transfer is executed
- The development team is advised to maintain close coordination with the stakeholder to ensure all necessary rules and exceptions are correctly implemented.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2393?planning-poker) with Zenhub @AlexZorkin @prv-proton

**Comment by justin-lepitzki** [comment]
Per card 2392, we are restricting the selection of an effective date by the BCeID user to no more than 3 months in advance.

**Comment by airinggov** [comment]
receiving a 500 server error when trying to approve a credit transfer with effective date

![eff-date-error.PNG](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/704c94bc-a951-458e-a556-5e5be32f5505)

**Comment by justin-lepitzki** [comment]
Tested w/ issues

Upon Director approval of the transfer, the effective date switches to today's date and the transfer is immediately executed / reflected in the UI. 

Screenshot of effective date prior to director approval: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWDA9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--663e13e96eb1609673e0cd6200ff27f299dcffce/Screenshot%202023-08-10%20effective-date-2023-08-14-prior-to-approval.png)
 
Screenshot of effective date after approval: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWDQ9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--20c1feae58edf1f8e4a1865f755c551726bef70f/Screenshot%202023-08-10%20effective-date-2023-08-14-after-approval.png)

**Comment by AlexZorkin** [comment]
Fixed the issue where effective date was getting reset on director approval. It now retains the set effective date.

**Comment by airinggov** [comment]
everything looks good so far, will check tomorrow if the transaction is applied Aug 16 as set. so far the credits haven't transferred as expected. even though transfer was approved Aug 15
