### ISSUE TITLE
Security | Read only in prod for TRFS team internal users

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#241]
https://trello.com/c/abhzDcgD/587-security-read-only-in-prod-for-trfs-team-internal-users

**Comment by AntonCoetzer** [comment]
Implement read-only access in prod for all members of the TFRS dev team. This is an added measure to ensure that nothing is accidentally changed in prod.

- Create a role
- create a permission
- assign user to a role
- assign permission to role
