### ISSUE TITLE
TFRS - Update xls download with compliance units for 2023 compliance reports

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2414]
**Title:** Update xls download with compliance units for 2023 compliance reports

**Description:**
Both BCeID and IDIR users can download a compliance report by clicking on the Download as xls button from within the report. As part of the compliance units work for 2023 compliance reporting, the downloaded xls file needs to be updated. 

- Schedule B: Credits & debits columns need to be replaced with a single compliance unit column
- Summary: Part 3 - Low Carbon Fuel Requirement Summary section needs to be updated to reflect the new summary section created in card # 2372. 

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/163570088?mode=fm

**Purpose and benefit to user:** Aligns downloaded spreadsheet with new compliance units design for 2023 compliance reporting

**Acceptance Criteria:**

- [ ] Given I am a BCeID user, when I click on the Download as xls button from within a 2023 compliance report, then an xls file is downloaded that includes the compliance units scheme in Schedule B & Summary tabs.
- [ ] Given I am an IDIR user, when I click on the Download as xls button from within a 2023 compliance report, then an xls file is downloaded that includes the compliance units scheme in Schedule B & Summary tabs.

**Development Checklist:**
- [ ] A update logic in sheduleB and summary part to include compliance units for 2023 and above reporting.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2414?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
