### ISSUE TITLE
TFRS - Supplemental report number starts at zero

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2417]
**Describe the Bug**
The numbering scheme for supplemental reporting has reverted back to including zero in the counting. 

**Expected Behaviour**
When creating supplemental reports, the numbering of the reports should be sequential beginning with #1. That is 'Compliance Report for YYYY - Supplemental Report #1' and then the next one 'Compliance Report for YYYY - Supplemental Report #2'. 

**Actual Behaviour**
The first supplemental compliance report created begins with #0. That is, 'Compliance Report for YYYY - Supplemental Report #1'. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID/IDIR 
1. Go to a submitted or accepted Compliance Report. 
2. Click on the Create Supplemental Report button
3. Submit the Supplemental Report to government.
4. After submission, open the Supplemental Report and click on the Report History sub-tab
5. View the Supplemental Report numbering in the 'Report History' section; see that the first supplemental report uses zero as the numbering 

**Notes**
Investigate whether a recent change removed a +1 to an index value display on the frontend.

**Screenshot:** 
![Screenshot 2023-07-04 SR-0.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/bce8a1b7-4efd-4ebf-9e72-3151fd00b37a)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2417?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
