### ISSUE TITLE
TFRS - New Act Label Changes - BCeID Home Dashboard

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2423]
**Describe the task**
Changing labels on the Home Dashboard for BCeID users and some minor styling / redesign elements. 

**Labels to change:**
See attached document for description of label changes: [https://app.zenhub.com/files/80058415/da2f82ba-9a02-4f2b-9fef-d9359cf23737/download](https://app.zenhub.com/files/80058415/da2f82ba-9a02-4f2b-9fef-d9359cf23737/download)

**Other design changes:**
See wireframe for all changes, including:
-	Move Compliance & Exclusion Reports widget box above Part 3 Agreements widget box
-	Revise Part 3 Agreements widget to focus more on File Submission rather than Part 3 Agreements
-	Organization Details box
o	Add "leaving website" icon next to "Create new BCeID account". 
o	Change label to "Create new BCeID user account"
o	Reordering of list of links / remove some:
Not on the wireframe but we want to include a link to our branch website, perhaps below the “we want to hear from you” box. 
-	Heading: Low Carbon Fuel Standard 
-	Text: Visit our website at: <URL>
-	URL: https://gov.bc.ca/lowcarbonfuels 

**Wireframe:** ![Dashboard_BCeID-mockup_v1.jpg](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/163fb89f-bfd6-410a-ba47-bf4b53fd9b0f)

**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

Development Checklist:
- [ ]  All labels need to change as per the attached document and make sure it doesn't break any existing functionality.
- [ ] Design the styling as per the requirement above
- [ ] 
**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2423?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
