### ISSUE TITLE
TFRS - New Act Label Changes - IDIR Home Dashboard

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2424]
**Describe the task**
Changing labels on the Home Dashboard for IDIR users.

**Labels to change:**
See attached document for description of label changes: 
[https://app.zenhub.com/files/80058415/6b964348-36f5-4f20-ae04-7a533b53b314/download](https://app.zenhub.com/files/80058415/6b964348-36f5-4f20-ae04-7a533b53b314/download)

**Wireframe:** 

![Dashboard_IDIR-mockup_v1.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/864097c2-13ca-4a0a-80ec-91291f1879ad)

- Note: wireframe does not include the one change on the main nav bar to change 'Fuel Codes' label to 'Administration'. This change is listed in the 'labels to change' attached document. 

**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2424?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
