### ISSUE TITLE
TFRS - New Act Label Changes - IDIR Director Home Dashboard

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2425]
**Describe the task**
Changing labels on the Home Dashboard for IDIR users with the Director/Deputy Director role.

**Labels to change:**
See attached document for description of label changes:  [https://app.zenhub.com/files/80058415/3003733d-b143-4126-9541-9ba3b9c33598/download](https://app.zenhub.com/files/80058415/3003733d-b143-4126-9541-9ba3b9c33598/download)

**Wireframe:** 
*![Dashboard_IDIR-Director-mockup_v2.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/1e242b70-282c-4895-8b50-9ac1f24f9126)

- Note: wireframe does not include the one revision on the main nav bar to change 'Fuel Codes' label to 'Administration'. However, this change is listed in the 'labels to change' attached document. 

**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

Development Checklist:
- [ ]  All labels need to change as per the attached document and make sure it doesn't break any existing functionality.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2425?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
