### ISSUE TITLE
TFRS - New Act Label Changes - Organization Changes

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2426]
**Describe the task**
Changing labels on the Organization Details page, accessible to both IDIR & BCeID users. 

**Labels to change:**
See attached document for description of label changes:  
[https://app.zenhub.com/files/80058415/0f1528ef-92c1-4ac3-9726-572cdec5d4cb/download](https://app.zenhub.com/files/80058415/0f1528ef-92c1-4ac3-9726-572cdec5d4cb/download)

**Location in app:**
- BCeID: click on 'Organization Details' heading in the main / top nav bar.
- IDIR: click on 'Fuel Suppliers' heading on the main / top nav bar and then click on an organization in the list. 

**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

Development Checklist:
- [ ]  All labels need to change as per the attached document and make sure it doesn't break any existing functionality.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2426?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
