### ISSUE TITLE
TFRS - New Act Label Changes - Notifications Settings

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2427]
**Describe the task**
Changing labels on the Notifications Settings page, accessible to both IDIR & BCeID users. 

**Labels to change:**
See attached document for description of label changes:  [https://app.zenhub.com/files/80058415/222e56bb-081e-45ec-becd-1e5640e52d6a/download](https://app.zenhub.com/files/80058415/222e56bb-081e-45ec-becd-1e5640e52d6a/download)

**Location in app:**
- BCeID & IDIR: click on the user's name in the top right corner of the heading in the main / top nav bar.

**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2427?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
