### ISSUE TITLE
TFRS - New Act Label Changes - Roles & Permissions pages

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2428]
**Describe the task**
Changing labels on the Roles description page, accessible to both IDIR & BCeID users. 

**Labels to change:**
See attached document for description of label changes:  
[https://app.zenhub.com/files/80058415/be4c49ae-ee20-48d1-bea8-2a2ce75559d0/download](https://app.zenhub.com/files/80058415/be4c49ae-ee20-48d1-bea8-2a2ce75559d0/download)

**Location in app:**
- BCeID: click on the 'Organization Details' heading on the main nav bar, then click on the 'Roles' sub-tab, then click on the available roles to see descriptions of the permissions.
- IDIR: From the Home dashboard page, click on the 'Fuel Codes' heading on the main nav bar, then click on the 'Roles' sub-tab, then click on the available roles to see descriptions of the permissions.
 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2428?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
