### ISSUE TITLE
TFRS - administrative adjustment transaction types for Historical Data Entry

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2429]
**Title:** Administrative adjustment transaction types for Historical Data Entry

**Description:**

- Add a new transaction type(s) to the Historical Data Entry
- Label is Administrative adjustment
- Uses compliance units, so can be positive or negative adjustment
- Can consider having two transaction types, one for positive and one for negative, if that is simpler to implement. 
- Includes creating a new view page(s) for the transaction (one for positive & one for negative).
- Transaction will impact available credit balance calculations, based on the transaction's effective date. This follows similar logic to Part 3 Awards and Credit Transfers, where transactions within a particular compliance period impacts the available credit balance for that period but also if it has an effective date in the first 3 months of the following compliance period (Jan 1 to Mar 31, YYYY+1) it also impacts the available credit balance for the previous period. This is the 3 months after the period has ended but before the Mar 31 reporting deadline. For example, a transaction with an effective date of February 15, 2024 will impact the available credit balance for the 2023 compliance period. 

**Wireframe:** 

Historical Data Entry: 

View page, positive adjustment: 
![2023-07-07_HDE-Positive-admin-adjustment.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/1970769c-c9b8-4690-af90-b1460be9ec23)

View page, negative adjustment: 
![2023-07-07_HDE-Negative-admin-adjustment.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/7769f9c8-8d1f-4a2f-b932-b29beb725f1a)

**Purpose and benefit to user:**
Enables Ministry staff to make administrative adjustments to a supplier's compliance unit balance in the event that there is an error in issuing credits. 

**Acceptance Criteria:**

- [ ] Given I am an IDIR user, when I am using the Historical Data Entry feature, then there is a transaction type(s) called "administrative adjustment" that allows me to create an adjustment transaction that increases or decreases an organization's compliance unit balance. 

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**
We still need to keep the "Validation" and "Reduction" transaction types using the credit/debit system as these labels may be used for supplemental reporting for 2022 and prior.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2429?planning-poker) with Zenhub @AlexZorkin @tim738745

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2429?planning-poker) with Zenhub @jig-patel @prv-proton

**Comment by AlexZorkin** [comment]
There is a followup ticket created that will handle the merge of the delayed effective_date of credits to an organization. 
https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2538
This ticket will need to be completed after the next production release and merge to master.
