### ISSUE TITLE
TFRS - System describes the impact of administrative adjustment transactions before commit

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2431]
**Title:** System describes the impact of an administrative adjustment transaction using the Historical Data Entry feature before the transactions are committed (i.e., before they are approved and applied to an organization's balance). 

**Description:**
When an IDIR user commits an [administrative adjustment transaction](https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2429) using the Historical Data Entry feature, the system displays information that describes the impact of the transactions. 

The information to display is similar (but not the same) to the newly revised summary section of a compliance report and includes:
- The organization's compliance unit balance
- The compliance unit balance change from the transaction
- The non-compliance penalty payable (CAD), if applicable 
- The organization's compliance unit balance after the transaction is committed

Other considerations / impacts include:
- These transactions will impact the available credit balances, depending on the transaction's effective date. 
- This functionality may be re-used in other parts of the app (or in the new LCFS system) so consideration should be given to its potential reuse with respect to how its developed.
- We need to retain the queue feature in the Historical Data Entry feature. How can we handle a situation where multiple transactions are added to the queue for the same organization?  

**Wireframe:** <link>
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/163742351?mode=fm

**Purpose and benefit to user:**
Provides valuable information to the government user on how administrative adjustment transactions will impact an organization's compliance unit balance, including if it would put them in a penalty situation. 

**Acceptance Criteria:**

- [ ] Given I am an IDIR user, when I am inputting an administrative adjustment transaction using the historical data entry feature, then the system shows me the impact of this transaction prior to it being committed. 

**Development Checklist:**
- [ ] Check if it's using the same data to retrieve the summary info that was modified for compliance units.
- [ ] If the summary part is same then only UI changes would be involved

**Notes:**

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2431?planning-poker) with Zenhub @AlexZorkin

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2431?planning-poker) with Zenhub @JulianForeman

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2431?planning-poker) with Zenhub @tim738745

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2431?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Tested a few different scenarios, positive and negative transactions, multiple transactions. Feature worked well :) 

One issue identified with respect to an admin adjustment transaction that puts the organization into a penalty situation. The corresponding penalty is not being displayed. The balance change from transaction is showing as positive when it should be negative, thus the 'compliance unit balance after this transaction is committed' field is incorrect. It is adding the compliance units to the balance instead of subtracting them. 

Example: dev-jan release, FS6 organization, admin adjustment for -10,000 when the organization's balance is only 9,000. See screenshot: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEVBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--892ce2480766c00ed82977f938d663be3136849f/Screenshot%202023-10-03%20no%20penalty%20wrong%20balance.png). Once committed the balance is changed to -1,000 (-10,000 transaction applied). The balance should be zeroed out (-9,000) and penalty displayed for the 1,000 remaining units.  Card # 2591 is meant to prevent transaction from causing balance to go negative.
