### ISSUE TITLE
TFRS - Testing and Deployment of Compliance Units in Compliance Report Summary View#2373

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2438]
Describe the Task:
Perform final testing and deployment of the new Compliance Units feature in the Compliance Report Summary View, as developed in the previous ticket (#2372). The task involves executing comprehensive functional, UI, and integration testing to ensure the new implementation works as expected, and facilitating its deployment into the test environment.

Purpose:
To ensure the correct functioning, stability, user-friendliness, and integrity of the newly implemented Compliance Units in the Compliance Report Summary View. This will provide a final verification that the Compliance Units feature works correctly and is ready for deployment to the production environment.

Acceptance Criteria:

1. [ ] The Compliance Units feature is thoroughly tested for functional, UI, and integration aspects.
2. [ ] All tests pass successfully without any critical or major issues.
3. [ ] Any bugs or issues found during testing are tracked, reported, and fixed promptly.
4. [ ] The feature is successfully deployed into the test environment without any errors or issues.
5. [ ] The Compliance Report Summary View correctly displays and handles Compliance Units as per the specifications in the test environment.
6. [ ] User acceptance testing (UAT) is conducted and receives positive feedback.
7. [ ] Any necessary documentation for testing and deployment, including test cases, test results, and deployment logs, are available for future reference.

Additional Context:

1. The testing must be comprehensive and cover all edge cases to ensure the feature is robust and ready for production.
2. It is recommended to conduct a walkthrough or demo of the new feature for the UX/Product Owner to ensure the final implementation aligns with the product vision and user needs.
3. Following successful deployment in the test environment, a plan should be created for the deployment of the feature in the production environment.
4. Ensure the feature is backward compatible in the test environment so that historical data is still accessible and represented accurately.
5. User training may be required post-deployment to familiarize them with the new Compliance Units system.
6. Collaboration and communication with the UX/Product Owner is key for this task to ensure the final implementation is approved and ready for production.

**Comment by justin-lepitzki** [comment]
Running into a couple of issues that are preventing me from testing the new compliance units features within the 2023 compliance report. The system is throwing an error when you try to select a fuel type within Schedule B; this is happening for all report years, including the reports under the old credit/debit system (2022 and prior). Also, the new summary section is not loading when I click on the 'Summary & Declaration' sub-tab within the 2023 report. It tries to load and then throws an error. 

The Schedule B error when trying to select a fuel type: 
![Screenshot 2023-07-28 144953.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/3fa7dd28-d708-4e85-bb41-b8401dfb08aa)
