### ISSUE TITLE
TFRS - Rebase January Release Branch with Latest Release Branch

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2441]
**Description:**

The goal of this task is to rebase the January 2024 release branch of TFRS with the latest release branch. This is needed to ensure the branch contains all the most recent features, optimizations, and bug fixes. This will enhance our ability to debug, maintain, and develop on top of the most recent and stable codebase.

---

**Acceptance Criteria:**

1. Ensure a full backup of the current January release branch is available before proceeding.
2. The January release branch is successfully rebased onto the latest release branch without any conflicts.
3. All the tests pass successfully after the rebase.
4. The rebased branch is pushed to the remote repository and a Pull Request (PR) is created for peer review.

---

**Notes:**

* Please ensure all conflicts (if any) are resolved correctly and the branch integrity is maintained.
* Follow the standard code rebase and conflict resolution best practices.

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
