### ISSUE TITLE
TFRS - Report History section grouping status changes incorrectly  

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2452]
**Feature Background:**
The report history section of a compliance report is intended to track major status changes as a report is processed. This includes when the supplier submits the report (e.g., 'Submitted' status), when the analyst & manager makes a recommendation on whether to accept the report (e.g., 'Reviewed and Recommended Acceptance), and when the director accepts or rejects the report (e.g., 'Accepted' or 'Rejected' statuses). Typically there are four entries per report as it is processed; these entries are separated by report, including for each supplemental report. 

**Describe the Bug**
Status changes are being grouped incorrectly across the different reports. When a supplier submits a supplemental report, the 'Submitted' entry is being grouped with the existing report history entries from the previous submission of that report. This bug may be related to the supplemental report numbering issue in card 2417: https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2417

**Expected Behaviour**
When a new supplemental report is submitted to government (or another status change by an IDIR user after submission), a new entry should be added to the report history in a separate section to track the processing of the report. 

**Actual Behaviour**
When a new supplemental report is submitted to government (or another status change by an IDIR user after submission), a new entry is added to the report history section of the previous submission for that report.

**Implications**
Impacting our ability to track the processing of a report and creating incorrect data for record keeping & auditing purposes. Note: this bug has impacted data in Prod.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user
1. Go to a previously submitted or accepted compliance report
2. Create a new supplemental report and submit
3. After submission, navigate to the Report History tab within the report
4. See error in status tracking within the 'Report History' section near the top of the page

Development Checklist:
[ ] - New reports should need to added into separate sections in assessments component

**Screenshot:**
![Screenshot 2023-07-21 085148.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/08a72ff8-5bde-484d-a67a-b1b17225e52a)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2452?planning-poker) with Zenhub @AlexZorkin @prv-proton @jig-patel

**Comment by justin-lepitzki** [comment]
Waiting for next Prod release to see if this issue is resolved. Need to check Test before releasing to Prod to confirm as it may have already been resolved.

**Comment by justin-lepitzki** [comment]
A potentially related issue is an erroneous entry in the Report History section when processing a compliance report in Prod. Per the attached screenshot, the Director (Jennifer Kroll) Accepted the report on June 13, 2023 which completes the workflow/process in TFRS; however, a new entry has appeared from the Compliance Manager saying that they (Jordan) Accepted the report again the next day (June 14, 2023). Jordan does not have the correct permissions (Director / Deputy Director roles) to Accept a compliance report;  his roles are File Submission, Administrator, and Compliance Manager. 
Screenshot before supplemental was processed: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTB4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68d897ddb54049ce0e9aa9321c696a69c8feee9f/MicrosoftTeams-image%20%282%29.png)
Screenshot after the supplemental was reporting: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTh4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a8634454d184b204a10ca0736b562a765e1400b/Screenshot%202023-08-23%20-%20report%20bug.png)

**Comment by justin-lepitzki** [comment]
Another example of the more general issue of the report history section putting action entries into the wrong report. This is a report in Prod (#2116). There is a duplicate Submitted entry in the Supplemental #1 report section. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmN4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--852ba8e0d8278a9cc36f8cbc3b7067dd8e9e56dc/Screenshot%202023-08-23%20BCHydro.png)
