### ISSUE TITLE
TFRS - System converts credits to compliance units when accepting a compliance report for 2022 and prior years

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2454]
**Describe the task**
When the director accepts a compliance report for 2022 and prior years, either a new report or a supplemental report, the system will need to convert the corresponding credit transaction into a compliance unit transaction in order to make the correct adjustment to the organization's compliance unit balance.

**Purpose**
On January 1, 2024, the compliance units scheme will become active; however, suppliers can still submit compliance reports (new & supplemental) for the 2022 and prior years' compliance periods. The 2022 and prior years' reports will still use the credit / debit system, but the corresponding balance change from accepting a report will need to be in compliance units. 

**Scenarios:**
To help guide this work, there are seven example scenarios in the "Credits-Debits" worksheet (see link below). Note that the statuses of the previous report submissions can have an impact on the corresponding compliance unit balance change. 

[https://app.zenhub.com/files/80058415/ea42ccce-ddec-480f-8fa3-a592fa3468e7/download](https://app.zenhub.com/files/80058415/ea42ccce-ddec-480f-8fa3-a592fa3468e7/download)

**Acceptance Criteria**
- [ ] The system should correctly identify reports for the 2022 and prior years and treat them differently from the 2024 and onward reports.
- [ ] Upon the director accepting a compliance report (either new or supplemental) for the 2022 and prior years, the system should automatically convert the credit transactions associated with the report into compliance unit transactions.
- [ ] The system must accurately calculate the compliance unit transaction amount by applying the predefined conversion rate. The rate at which credits are converted to compliance units needs to be in line with policy guidance. Any discrepancy must be flagged and resolved before the final conversion.
- [ ] The compliance unit balance for the organization must be updated accordingly, taking into consideration the status of any prior submissions, and the system should reflect the correct balance in real-time.
- [ ] After the conversion and balance update, the system should generate a detailed transaction report, which includes the old credit value, the conversion rate used, the new compliance unit value, and the updated balance.
- [ ] The system should handle both positive and negative transactions, i.e., both credits and debits, and adjust the compliance unit balance accordingly.
- [ ] Any errors during the conversion process should be logged and appropriately flagged in the system. Users should be notified about the error and the next steps to take.

Additional context

This task is a crucial part of the transition process from the credit/debit system to the compliance unit scheme. It is vital for ensuring a seamless changeover and maintaining accurate, real-time compliance reporting for all organizations. This change needs to be communicated to all stakeholders in a timely and clear manner to ensure awareness and readiness for the transition. The implementation should also be thoroughly tested to ensure accuracy and reliability.

PO Testing:

1. [x] Scenario 0
2. [x] Scenario 1
3. [x] Scenario 2
4. [x] Scenario 3a
5. [x] Scenario 3b
6. [x] Scenario 4a
7. [x] Scenario 4b
8. [x] Scenario 5a
9. [x] Scenario 5b
10. [ ] Scenario 6a
11. [x] Scenario 6b

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2454?planning-poker) with Zenhub @AlexZorkin @prv-proton @jig-patel
