### ISSUE TITLE
TFRS - Investigate how many draft 2023 & 2024 compliance & exclusion reports have been created and saved in Prod

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2455]
**Describe the task**
This task involves determining the number of draft 2023 & 2024 compliance & exclusion reports that have been created and saved in our production environment.

[Card 2416](https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2416) prevented the creation of new draft 2024 compliance & exclusion reports, but we would like to establish the number of existing drafts for both 2023 & 2024 and for both compliance & exclusion reports. This data will inform the course of action, which could be either to leave the drafts as they are or to delete/archive them. Before actioning, the business area may want to reach out to the suppliers individually. However, the focus of this task is to determine the number of existing 2023 & 2024 draft compliance & exclusion reports.

Note: in determining how many reports exist, we want to **exclude** any draft 2023 & 2024 reports that have been deleted (status = archived?). Not sure on the back-end status of deleted draft reports. 

**Purpose**
This task is necessary for determining the next steps for dealing with draft 2023 & 2024 reports in production as they are not accurate in terms of their calculations and labelling. 

**Acceptance Criteria**
- [ ] Identify all draft 2023 & 2024 compliance & exclusion reports in the production environment via sql command.
- [ ] Confirm that the identified drafts are indeed for the year 2023 & 2024 and not miscategorized or erroneously labelled.
- [ ] Ensure that deleted or archived draft 2023 & 2024 reports are not included in the final count.
- [ ] Prepare a list detailing the report ID, the org ID, and creator's username for each identified draft 2023 & 2024 report.

**Additional Context:**

The feature to generate these draft reports was introduced in version 2.3. Any drafts present would have been created post this release. Reports marked as 'Final' or 'Submitted' should not be included in this investigation as they have moved beyond the draft stage.

This task requires either direct database access or the use of a dedicated reporting tool to extract the necessary data. Ensure that you handle all data with confidentiality due to its sensitive nature.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2455?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by AlexZorkin** [comment]
By utilizing the Metabase query available at https://metabase-prod.apps.silver.devops.gov.bc.ca/question/229-tfrs-2023-draft-compliance-reports, we can observe that there are 27 compliance reports in a draft state for the year 2023, and none of them are exclusion reports. Additionally, there are no draft compliance reports currently available for the year 2024.

**Comment by AlexZorkin** [comment]
Using the Metabase query found at https://metabase-prod.apps.silver.devops.gov.bc.ca/question/229-tfrs-2023-draft-compliance-reports, we can discern that there are 27 compliance reports in a draft state for the year 2023, and none of them are exclusion reports. Furthermore, there are currently four draft compliance reports available for the year 2024, again none of which are exclusion reports.
