### ISSUE TITLE
TFRS - Credits from pending credit transfers are not being placed in reserve 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2460]
**Describe the Bug**
Credits from pending credit transfers are not being properly placed "in reserve". This issue only occurs in the dev environment and may be a result of the recent work on credit transfers (e.g., redesign, agreement date, effective date)

**Expected Behaviour**
When a credit transfer is proposed, the seller's credits are placed "in reserve" until the transfer is completed. 

Credits "in reserve" when statuses equal: Proposed, Signed, Recommended / Not Recommended

Credits are not "in reserve" when statuses equal: Draft, Approved, Declined, Refused, or Rescinded. 

**Actual Behaviour**
When a credit transfer is proposed, the seller's credits are not being placed "in reserve". 

**Implications**
By not placing pending credits "in reserve" the seller could initiate multiple transfers trying to sell the same credits, or they could use those same credits to offset debits in their compliance report. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user, Credit Transfer + Signing Authority roles
1. Go to Credit Transactions page
2. Click on "New Transfer" button to initiate the sale of credits (Sell transfer)
3. Fill out required fields and click Propose
4. See error (credits not being placed "in reserve")

**Comment by airinggov** [comment]
@justin-lepitzki did you consider also when the transfer is approved but the effective date has not yet been reached? should they remain in reserve?

**Comment by justin-lepitzki** [comment]
@airinggov yes this is part of [card 2393](https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2393) in the additional context section of the card. I haven't had a chance to test its implementation yet.

**Comment by KericeRich** [comment]
Tested this and the credit balance is not showing the reserve. Justin can double check that when he's testing

**Comment by KericeRich** [comment]
Tested this and the credit balance is not showing the reserve. Justin can double check that when he's testing

**Comment by justin-lepitzki** [comment]
Tested w/ issues. Credits are correctly going "in-reserve" when the effective date is left blank or the user enters an effective date of today's date. However, credits are not going into reserve when the user requests an effective date that is a future date. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1VQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3f5919ff3867f16e50562016f8a096b78ea0b2fd/Screenshot%202023-08-16%20in-reserve%20credits.png)
