### ISSUE TITLE
TFRS - Formatting adjustments to credit transfer transaction history section

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2467]
**Describe the tasks**

- Put Director approval or decline to approve sentence in the bulleted list like the other entries.
- Categorization sentences are missing parentheses in a couple instances (see screenshots below)
- Change the sentence "Date of written agreement reached between the two suppliers:" to "Date of written agreement reached between the two organizations:"

**Purpose**
Minor clean up of recent style changes to credit transfer UI

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Screenshots:**

Director approval not bulleted: 
![Screenshot 2023-07-25 Transaction History not in bulleted list.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/2fa0fcb2-ec9f-4845-b20c-bb9d4dbfa653)

Missing parentheses: 
![Screenshot 2023-07-25 Transaction History not in bulleted list - missing parentheses cat C.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/6b96fa6e-9f90-410a-973f-01e179ab95d8)

Missing parentheses: 
![Screenshot 2023-07-25 Transaction History not in bulleted list - missing parentheses cat A.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/86334e13-8075-4711-8096-4afd59ce9d31)

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2467?planning-poker) with Zenhub @prv-proton

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2467?planning-poker) with Zenhub @AlexZorkin

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2467?planning-poker) with Zenhub @jig-patel

**Comment by airinggov** [comment]
@justin-lepitzki some of the text is green and some is black, not very consistent, maybe just make it all black?

**Comment by airinggov** [comment]
Scope of card I think is mostly achieved but there are still formatting issues with Rescinded and Declined transfers. For instance Cat D checkbox still appears on both and throws error if clicked.
