### ISSUE TITLE
TFRS - prevent BCeID users from entering future dates in the credit transfer agreement date field

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2468]
**Title:** prevent BCeID users from entering future dates in the credit transfer agreement date field

**Description:**
Prevent BCeID users from entering future dates in the credit transfer agreement field. This field is for entering the date in which the agreement to transfer credits was reached. By definition, this date must be either today or a day in the past; it cannot be a date in the future. 

Note: this prevention should include both selecting a future date from within the calendar widget and manually entering in a date into the field using the keyboard. 

**Screenshot:** 
![Screenshot 2023-07-25 Agreement Date.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/594cc88a-bb22-4f0c-9b82-dbfbb3ff60eb)

**Purpose and benefit to user:**
Prevent errors in data entry which will help facilitate efficient processing of transfers.

**Acceptance Criteria:**

- [ ] Given I am a BCeID user, when I am entering a date into the agreement date field on the New Transfer page, then I am only able to select today's date or a date in the past. 

**Development Checklist:**
- [ ] Disable future dates.
- [ ] Validate the manually entered date.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2468?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
