### ISSUE TITLE
TFRS - Adjust credit transfer agreement date error message

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2469]
**Describe the task**
Adjust the error message that appears in the UI when the agreement date field within a draft credit transfer is left blank. This message appears when the user clicks on the Propose button. 

- Current message: "Error! Date has wrong format. Use one of these formats instead: YYYY-MM-DD."

- Revised message: "Error! Please enter a valid date in the Agreement Date field: YYYY-MM-DD."

**Purpose**
More descriptive of the issue to help the user understand what went wrong. 

**Acceptance Criteria**
- [ ] When a user proposes a credit transfer with an empty agreement date, they should see the revised error message.

**Screenshot:**
![Screenshot 2023-07-25 CTP agreement date error.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/5ded287c-7580-45c6-92f8-2f6f6db29401)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2469?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
