### ISSUE TITLE
TFRS - Hide Category D selection after director decision on credit transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2470]
**Describe the task**
The task involves modifying the UI to hide the 'Category D' selection option for IDIR users once a decision (either approved or declined) has been made by the director regarding a credit transfer.

**Purpose**
The purpose of this task is to enhance user experience and prevent confusion. Currently, the 'Category D' selection appears as if it's still selectable even after a credit transfer has been processed, although users cannot actually select it. Therefore, it should be hidden from the UI to reflect its actual functionality.

**Acceptance Criteria**
- [ ] If Category D was not selected, then the text should not be visible after approval
- [ ] Once the director's decision has been made, if 'Category D' was selected, it should be shown as selected, but not editable.
- [ ] Proper unit tests should be implemented to ensure that the 'Category D' selection displays in the right scenarios

**Screenshot:**
![Screenshot 2023-07-25 Hide category D selection once transfer has been approved or declined.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/6e69a133-f772-4432-8409-784f4212a39c)

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2470?planning-poker) with Zenhub @jig-patel @prv-proton @tim738745
