### ISSUE TITLE
TFRS - Download as xls workbook not displaying correct category in category column

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2472]
**Describe the Bug**
There's an inconsistency between the category displayed in the User Interface (UI) and that in the 'Download as xls' workbook for approved credit transfers. The category column in the downloaded workbook always displays 'Category A' for all approved transfers, regardless of their actual categories assigned in the UI.

**Expected Behaviour**
The 'Download as xls' workbook should correctly reflect the category assigned to each approved credit transfer in the category column, as per the UI.

**Actual Behaviour**
Regardless of the actual category assigned in the UI, the category column within the downloaded workbook displays 'Category A' for all approved credit transfers.

**Implications**
This bug prevents IDIR users from accurately aggregating transfers based on their assigned categories.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR user
1. As an IDIR user, navigate to the 'Credit Transactions' page.
2. Click on 'Download as xls'.
3. Open the downloaded workbook.
4. Observe the error in the 'category' column for approved transfers.

**Examples in Test Env:** 

In the test environment, credit transfers #1065, 1066, 1067, 1068 are affected:
- The UI correctly displays four categories: A, B, C, D for these transfers.
- However, the 'Download as xls' workbook incorrectly shows 'Category A' for all these transfers.

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2472?planning-poker) with Zenhub @AlexZorkin

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2472?planning-poker) with Zenhub @prv-proton

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2472?planning-poker) with Zenhub @jig-patel

**Comment by airinggov** [comment]
@AlexZorkin 1076 is displaying as A when it should be D

**Comment by airinggov** [comment]
A, B and C seem to be displaying properly in the spreadsheet, it may just be D not appearing properly

**Comment by justin-lepitzki** [comment]
Tested w/ issues. Seems to be correctly showing category A & B transfers but is still listing category C & D transfers as category A. See attached spreadsheet for example transfers (#1072 to #1076 inclusive)

[Uploading... BC-LCFS_credit_transactions_2023-08-16.xls]

**Comment by AlexZorkin** [comment]
Fixed issue with Category D not being set when admin has selected it
