### ISSUE TITLE
TFRS - Credit transfer categorization displaying the wrong approval dates prior to approval

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2473]
**Describe the Bug**
The credit transfer categorization feature is displaying incorrect dates when it forecasts what category a transfer may end up being classified as. This is a sentence that is located within the Transaction History section of the View Transfer page. 

**Expected Behaviour**
The system should predict the category for the credit transfer based on the different ranges of the three categories and the date of written agreement specified by the suppliers. 

**Actual Behaviour**
The system is predicting a category for the credit transfer but is displaying incorrect "if approved by" dates. 

**Implications**
Doesn't provide accurate information to the IDIR user

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR role
1. Go to a credit transfer with a 'Signed' status
2. Scroll down to 'Transaction History' section
3. See error 

Development Checklist :
[ ] - Fix the logic to implement the date for different Category.

**Category Definition:**
![Screenshot 2023-07-25 credit transfer cat.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/0ac96bc0-a98b-4245-973b-d60ae0553eb6)

**Example 1: transaction ID# 1065 in Dev env**

- Date of written agreement is March 15, 2023
- Category A is if agreement to transfer was reached within six months of submitting the transfer to government for approval.
- Therefore, the system should say "(proposal falls under Category A if approved by: September 15, 2023)" which is six months after March 15, 2023
- Per screenshot below, system is saying if approved by June 15, 2023 

![Screenshot 2023-07-25 incorrect categorization forecasting.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/e8e70cc1-80bc-4e72-a304-3c1b300c0eca)

**Example 2: transaction ID# 1066 in Dev env**

- Date of written agreement is October 31, 2022
- Category B is if the agreement to transfer was reached between six months to one year prior to the credit transfer being submitted to government for approval.
- Therefore, the system should say "(proposal falls under Category B if approved by: October 31, 2023)" which is one year after October 31, 2022
- Per screenshot below, system is saying if approved by February 28, 2023 

![Screenshot 2023-07-25 incorrect categorization forecasting 2.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/7ff9b0f7-fc79-4f24-9553-7ea380fee08b)

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2473?planning-poker) with Zenhub @prv-proton @AlexZorkin

**Comment by jig-patel** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2473?planning-poker) with Zenhub @jig-patel
