### ISSUE TITLE
TFRS - Revise Schedule B tooltip for 2023 compliance reports

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2476]
**Describe the task**
Currently, Schedule B in 2023 compliance reports has a label called "CREDIT/DEBIT CALCULATION" that includes a tooltip with a extensive description of the credit/debit formula in the former Act. 

Task is to:

- Remove Schedule B label called "CREDIT/DEBIT CALCULATION" 
- Remove corresponding tooltip
- Add tooltip to new 'Compliance Units' label (in the cell immediately below the "CREDIT/DEBIT CALCULATION" label)
- New tooltip message: "The number of compliance units to be issued is determined in accordance with the formula set out in the former Act; that is, section 6 (4) of the Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act. 

**Purpose**
Compliance units are replacing credit/debit system for 2023 compliance reports. Therefore, we need to remove references to the old credit/debit system.

**Acceptance Criteria**
- [ ] Changes shouldn't affect existing functionality or break sizing of the table.

**Screenshots:**

"CREDIT/DEBIT CALCULATION" label

![Screenshot 2023-07-28 Credit-Debit-heading.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/7ce8d7f0-cef6-405d-8c8f-4c60bd093c40)

Tooltip to remove

![Screenshot 2023-07-28 Credit-Debit-heading-Tooltip.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/49d1fa70-4dbd-4c30-8bec-dc4d4892e466)

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2476?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Removal of Schedule B label called "CREDIT/DEBIT CALCULATION" and corresponding tooltip has been applied to compliance reports for all years. This change should only be applied to 2023+ compliance reports, and not 2022 and prior years reports.

**Comment by AlexZorkin** [comment]
updated the schedule b table to display credit/debit and compliance unit tooltips based upon compliance period.

**Comment by justin-lepitzki** [comment]
Can we fix the formatting? It doesn't seem to be displaying as nicely in terms of the layout. See this screenshot for what it looks like now: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28aec63ee3f79f17fbb5bb3e2f42d708ad0a2397/Screenshot%202023-10-03%20Tooltip-formatting.png). The original formatting is in the screenshot in the card description.
