### ISSUE TITLE
TFRS - Prevent Inactive organization from transferring credits buy or sell

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2484]
**Title:** Prevent Inactive organization from transferring credits buy or sell

**Description:**
Currently in TFRS, we control the transferring of credits through the organization status. An 'Active' status means an organization can buy or sell credits whereas an 'Inactive' status means an organization cannot buy credits but is still able to sell credits if they have a positive credit balance. 

Under the new Act, organizations must be registered in order to transfer credits. If they are not registered they are not able to transfer credits. In the new Act, whether a supplier is 'active' or 'inactive' in terms of supplying fuel is not relevant to the question of whether they can transfer credits. Therefore, we want to repurpose this existing status feature in TFRS to align with the new Act. 

Prevent 'Inactive' suppliers from initiating credit transfers, including:
- Removing the 'New Transfer' button
- Prevent them from 'Signing' a credit transfer proposal sent from another organization

There are no changes required for the 'Active' status in terms of functionality. 

**Related cards:**

- Card #2483 is to change the labels for the active/inactive status to account for the new Act changes. 
- Card #2485 is to remove the ability to initiate a 'buy' credit transfer by removing the drop-down menu selection for buy/sell and having 'sell' be the default. 

**Wireframe:** <link>

**Purpose and benefit to user:** In the new Act, whether a supplier is 'active' or 'inactive' in terms of supplying fuel is not relevant to the question of whether they can transfer credits. Therefore, we want to repurpose this existing status feature in TFRS to align with the new Act. 

**Acceptance Criteria:**

- [ ] Given I am a BCeID user, when my organization is set to 'Inactive', then I am not able to transfer credits, either initiating a transfer or accepting a proposal from another organization. 

**Development Checklist:**
- [ ] Use existing re-purposed status field to consider whether the organization is registered or not.

**Notes:**

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2484?planning-poker) with Zenhub @jig-patel @prv-proton
