### ISSUE TITLE
TFRS - Remove the ability to initiate a buy credit transfer 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2485]
**Title:** Remove the ability to initiate a buy credit transfer. 

**Description:**
When initiating a credit transfer, the BCeID user is able to select whether they want to buy or sell credits through a drop down selection. This card is to remove the ability to initiate a 'buy' transfer and make it so users can only initiate sell transfers. In other words, remove the drop-down menu and have the system default to the sell transfer. 

**Screenshots**: 

![Screenshot 2023-08-02 Remove-buy.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/111d87d7-6d64-4d6c-b5b1-b6f39bcd28e2)

**Wireframe:**
![Wireframe 2023-08-02 Sell only.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/4b94df8b-f26d-40c0-93b8-9f4931a5cdbf)

**Purpose and benefit to user:** To simply the credit transfer workflow and implement user feedback.

**Acceptance Criteria:**

- [ ] Given I am a BCeID user with the credit transfer role, when I am creating a New Transfer, then the system defaults to it being a 'sell' transfer and I am not able to select an option to 'Buy' credits. 

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2485?planning-poker) with Zenhub @prv-proton @jig-patel
