### ISSUE TITLE
TFRS - Filter organization list for when initiating a new credit transfer based on organization status 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2486]
**Title:** Filter organization list for when initiating a new credit transfer based on organization status 

**Description:**
Only show organization's with an 'Active' status in the drop-down menu when initiating a new credit transfer

**Screenshot:** 

![Screenshot 2023-08-02 'Inactive' suppliers.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/af2219f5-6a63-4ace-a0c1-a4971d89115f)**Purpose and benefit to user:**

**Acceptance Criteria:**

- [ ] Given I am a BCeID user, when I am selecting a fuel supplier from the drop-down menu on the New Transfer page, then I am only able to see (and select) the suppliers that have an 'Active' status. 

**Development Checklist:**
- [ ] It is advisable to make the changes in frontend only with filter option
- [ ] /api/organizations/fuel_suppliers - endpoint

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2486?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
