### ISSUE TITLE
TFRS - New Act Label Changes - Organizations page IDIR only

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2488]
**Describe the task**
This task involves updating labels on the 'Organizations' page of the application, which is only accessible to IDIR users. Additionally, status labels on the 'Download Supplier Information' excel workbook are to be updated. The label changes are detailed in the attached document.

- Changing labels on the Organizations page, only accessible to IDIR users. 
- Changing status labels on the Download Supplier Information xls workbook

**Labels to change:**
See attached document for description of label changes:  
[https://app.zenhub.com/files/80058415/5361e624-4a84-4584-8f76-b7d30a759057/download](https://app.zenhub.com/files/80058415/5361e624-4a84-4584-8f76-b7d30a759057/download)

**Screenshot:**
Organizations page: 
![Screenshot 2023-08-03 Labels_Organizations-IDIR-1.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/3e710054-32ea-452f-90ba-c197345b4d38)

Download Supplier Information workbook:
![Screenshot 2023-08-03 orgs-download-as-xls-status.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/984271b2-a7fb-442b-a4d2-b434036c85c8)

**Location in app:**
- IDIR: From the Home dashboard page, click on the 'Organizations' heading on the main nav bar.
 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality
- [ ] Update excel download column name and row values with new outputs

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2488?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
