### ISSUE TITLE
TFRS - Remove Actions and Last Transaction column from Organizations table - IDIR only

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2489]
**Describe the task**

- Remove two columns from the Organizations page: the Actions column and the Last Transaction column. Don't want to show them in the UI. 
- Also remove the Actions column from the Download Supplier Information xls workbook. 
 
**Purpose**
These columns are not being used by IDIR users so in an effort to simplify pages, the two columns will be removed.

**Screenshot:**
Organizations page:
![Screenshot 2023-08-03 Labels_Organizations-IDIR.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/9be37ad6-e38d-48e3-a34c-d56f57781799)

Download Supplier Information workbook:
![Screenshot 2023-08-03 orgs-download-as-xls.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/1dc092d0-1091-40bd-b7f5-6d9c48cf5c6a)

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2489?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Actions column is still visible in the downloaded worksheet ('Download Organization Information' button)
