### ISSUE TITLE
TFRS - Adjust filtering in the back end for new registered yes no column on Organizations page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2490]
**Describe the task**
As per the changes introduced in [Card #2488](https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2488), the labels for the 'Status' column (previously labeled as 'Active/Inactive') on the 'Organizations' page have been updated to a 'Registered' column with 'Yes/No' labels. This task entails adjusting the back-end logic to ensure that the table filters correctly when the user enters 'Yes' or 'No' into the search field at the top of the 'Registered' column.

**Screenshot:**
![Screenshot 2023-08-03 Labels_Organizations-IDIR-1.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/494ad528-74f6-4cfe-beeb-6a4874e53263)

**Purpose**
The main aim of this task is to maintain the search filter functionality on the 'Organizations' page following the label changes.

**Acceptance Criteria**
- [ ] When a user enters 'Yes' or just 'y' in the search field at the top of the 'Registered' column, the filter should return all registered organizations.
- [ ] When a user enters 'No' or just 'n' in the search field, the filter should return all non-registered organizations.
- [ ] The search filter functionality should work as expected without impacting the overall performance of the 'Organizations' page.

**Additional context**
- Please ensure all the changes made on the back-end are well-documented and compatible with the existing architecture. The filtering logic adjustments should not affect any other functionalities on the 'Organizations' page.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2490?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by AlexZorkin** [comment]
Because we are still using frontend filtering, there is no need to update the backend with status filtering. The frontend list view receives all organizations on load and can easily filter in the table.
