### ISSUE TITLE
TFRS - New Act Label Changes - New Part 3 Award page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2491]
**Describe the task**
Changing labels on the New Part 3 Award page, only accessible to IDIR users.

**Labels to change:**
See attached document for description of label changes:  
[https://app.zenhub.com/files/80058415/abade0b1-89a2-4e5d-a98d-beacf2c27add/download](https://app.zenhub.com/files/80058415/abade0b1-89a2-4e5d-a98d-beacf2c27add/download)

**Location in app:**
- IDIR: From the Home dashboard page, click on the 'File Submissions' heading on the main nav bar, then click on the 'New Part 3 Award' button.

**Disclosure notice label change:**
Note that it appears that we are using the same disclosure notice message for comments for both credit transfers and Part 3 Awards. The label changes we want to make to the Part 3 Award feature in this card includes a change to the disclosure notice language that is unique to the Part 3 Award feature. This change should only happen to the disclosure notice within the Part 3 Award feature and **not** the credit transfer feature. 
 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2491?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
