### ISSUE TITLE
TFRS - New Act Label Changes - File Submissions page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2492]
**Describe the task**
Changing labels on the File Submissions page, accessible to both BCeID and IDIR users.

**Labels to change:**
See attached document for description of label changes:  
[New-Act-Label-Changes_File-Submissions.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWxnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--88a75324211f24147437c8fbc51f98805cbadc7d/New-Act-Label-Changes_File-Submissions.docx)

**Location in app:**
- From the Home dashboard page, click on the 'File Submissions' heading on the main nav bar.
 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2492?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
