### ISSUE TITLE
TFRS - New Act Label Changes - New File Submission page - BCeID

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2493]
**Describe the task**
Changing labels on the New File Submissions page, only accessible to BCeID users.

**Labels to change:**
See attached document for description of label changes:  
[https://app.zenhub.com/files/80058415/407136cc-938c-40c0-a2e0-742417202d8b/download](https://app.zenhub.com/files/80058415/407136cc-938c-40c0-a2e0-742417202d8b/download)

**Location in app:**
- BCeID: From the Home dashboard page, click on the 'File Submissions' heading on the main nav bar, the click on the New Submission button.
 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2493?planning-poker) with Zenhub @jig-patel @prv-proton
