### ISSUE TITLE
TFRS - increase font size for info tooltips

### ISSUE THREAD

**Issue by Kailee-Douglas** [bcgov/tfrs#2496]
**Title:**
Increase font size for informational tooltips

**Description:**
From the i icon in TFRS, informational tooltips pop-up when the user hovers over top. The font size within these tooltips needs to be increased to a level where it is more easily-readable. Perhaps a 1-2 point increase in font size.

**Screenshot:** <link>
Here is a screenshot of one of the tooltips (current state) in TFRS.
![TFRS current tooltip.png](https://images.zenhubusercontent.com/645177718f83818ac1c5f4c3/5953fe79-f5d3-4075-b3cf-1b8e6e6637ee)**Purpose and benefit to user:**

This is in alignment to accessibility requirements, readability of our content, and a general positive user experience. The current font size is too small for the average user to easily read, particularly with all the legal jargon.

**Acceptance Criteria:**
- [ ] Given I am a user, When I am hovering over the i icon to see the tooltip, then I can easily read the content within it.

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2496?planning-poker) with Zenhub @AlexZorkin

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2496?planning-poker) with Zenhub @jig-patel

**Comment by jig-patel** [comment]
@Kailee-Douglas @justin-lepitzki  Do we want to increase font-size everywhere or just one instance that shows in attached image in ticket ?

**Comment by justin-lepitzki** [comment]
@jig-patel we want to increase the font size for all tool tips
