### ISSUE TITLE
TFRS - Show final category for credit transfers upon director approval - IDIR users

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2503]
**Title:**
Show the final category (A/B/C/D) for credit transfers upon director approval.

**Description:**
Once the director has approved a credit transfer, on the view transfer page, update the bullet within the transaction history section to reflect the final category of the transfer. Currently, the sentence still refers to the transfer as a "proposal" and uses language like "if approved by". Once the transfer is approved, the part of the sentence in parentheses should update to reflect the final category. 

Examples of current language: 
[Example 1](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/c8453720-efe4-4d06-9e4e-8264b4910333); 
[Example 2](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/f2bee51f-a636-4abc-ad96-399425309f9c).

**Wireframe:** 
[Wireframe 1 - Category A .png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/291df53e-5014-4e4e-a56d-6da3c9e169f1).

[Wireframe 2 - Category D.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/1bdfb760-38fc-4c3f-89b3-efbd3140d6c0).

**Purpose and benefit to user:** 
Better informs the IDIR user of the category of the transfer and that this categorization won't change now that the transfer has been approved. 

**Acceptance Criteria:**

- [ ] Given I am an IDIR user, When I am viewing an approved credit transfer, then I see the final category of the transfer in parentheses within the sentence in the transaction history sector on the view transfer page. 

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by airinggov** [comment]
Limited testing it looks to be working well, should probably do some additional testing. Not sure if there are any edge cases to consider
