### ISSUE TITLE
TFRS - Show requested effective date in modal window when proposing a new credit transfer - BCeID users

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2504]
**Description:**
When a BCeID user with the Signing Authority role inputs an effective date into the optional field on the New Transfer page, this date should be visible in the modal window while proposing the transfer to another organization. This provides an added layer of confirmation and accuracy check for the user.

**Wireframe:** 
[Effective-date-requested-modal-window-v1.png](https://images.zenhubusercontent.com/644963ac99f1d06cf29952ef/b53de291-bdc2-4138-8772-c2e81394cb41)

**Purpose and benefit to user:**
Displaying the entered effective date in the modal window ensures BCeID users have a clear overview and verification of the details they've entered. This minimizes the potential for errors, ensuring the user's confidence in the accuracy of the proposal before submitting it to the counterparty.

**Acceptance Criteria:**

Given I am a BCeID user with the Signing Authority role:
And I have inputted an effective date in the optional field on the New Transfer page.
When I click the "Propose" button,
Then the Credit Transfer summary modal window should appear displaying the requested effective date.

**Development Checklist:**
- [ ] Update the Credit Transfer summary modal window to display the requested effective date when provided by the user.
- [ ] Ensure that the modal window's display of the effective date is clear and easy to understand.
- [ ] Implement a testing protocol to ensure the modal window correctly displays the effective date and that no other functions are impacted by this change.

**Notes:**
- Ensure the effective date is displayed in a standardized date format.
- Please review with the design team to confirm alignment with existing UI/UX guidelines.

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2504?planning-poker) with Zenhub @jig-patel
