### ISSUE TITLE
TFRS - Delete button not working for notification entries on the notifications page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2513]
**Describe the Bug**
The delete icon/button is not working (non-responsive) when trying to delete a notification entry on the notifications page

**Expected Behaviour**
Clicking on the delete icon allows the user to remove/delete the notification entry from the main table within the notifications page. I believe there was a confirmation alert (modal window) to confirm this action as well. 

**Actual Behaviour**
The delete icon is non-responsive. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: all users
1. Go to bell icon in the top right hand side of the page to go to the notifications page
2. Click on the red delete icon next to a notification entry in the main table
3. See error

**Screenshot:**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWDg9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf4ba6aa7c1a0667e2cad3afb7483c7e84625909/Screenshot%202023-08-11%20delete%20not%20working%20notifications.png)

**Comment by KericeRich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2513?planning-poker) with Zenhub @AlexZorkin @jig-patel
