### ISSUE TITLE
TFRS - Download as xls for 2023 compliance reports showing incorrect date in summary section

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2517]
**Describe the Bug**
Two labels are incorrect within the Low Carbon Fuel Requirement section of the Summary tab of the Download as XLS workbook for 2023 compliance reports. 

See the attached screenshot for the two labels. 

**Expected Behaviour**
Labels should read: 
- Available compliance unit balance on March 31, 2024
- Available compliance unit balance after assessment on March 31, 2024

**Actual Behaviour**
Labels are currently showing the wrong year (2023): 
- Available compliance unit balance on March 31, 2023
- Available compliance unit balance after assessment on March 31, 2023

Note that the labels in the UI within TFRS are correct, just the labels in the download as xls workbook are incorrect. 

**Implications**
Showing incorrect information to the user

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR or BCeID user 
1. Go to 2023 compliance report 
2. Click on Download as XLS button
3. Navigate to Summary tab
4. See error in labels

**Screenshot of workbook w/ highlighed incorrect labels:**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBYlE9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5e6e7aa8f22dc898cc05da3b3d9184ead73c8ef1/Screenshot%202023-08-11%20Download%20as%20xls%20-%20Summary%20-%20showing%20incorrect%20date.png)

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2517?planning-poker) with Zenhub @jig-patel
