### ISSUE TITLE
TFRS - Credit Transfer Rescinded and Declined Format Issues

### ISSUE THREAD

**Issue by airinggov** [bcgov/tfrs#2523]
**Description:** Some final clean up of display issues with credit transfers in rescinded and declined status.

This task aims to address the display issues present in credit transfers, specifically when they are in a rescinded or declined status. It requires:

- Adjusting the formatting of the "Declined" status in the history, to appear as a bullet point.
- Introducing a new bullet line for the "Rescind" action that includes the username and date of action.
- Removing the "Schedule D" text and associated checkbox due to its irrelevance and a potential error trigger.

**Wireframe:** <link>
![rescinded-transfer-format-issues.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/45c5efaa-b74b-44d5-89e5-03a37c35d682)
![declined-transfer-format-issues.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/ce65f314-8921-4f33-a4b8-3204db8f6149)

**Purpose and benefit to user:**
By refining the display of these statuses, users can enjoy a cleaner interface, reducing the chances of mistakes or misunderstandings.

**Acceptance Criteria:**

- [ ] Given I am a [user role], When I am [viewing a declined credit transfer], then [it should appear as a bullet point in the history].
- [ ] Given I am a [user role], When I am [viewing a rescinded credit transfer], then [a new bullet line with the "Rescind" action should appear, showing the username and date of the action].
- [ ] Given I am a [user role], When I am [editing/creating a credit transfer], then [the "Schedule D" text and checkbox should not be present].

**Development Checklist:**
- [ ] Adjust the format of the "Declined" line to appear as a bullet point in the history.
- [ ] Add a new bulleted line for the "Rescind" action.
- [ ] Remove the "Schedule D" text and its associated checkbox on rescinded status.

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2523?planning-poker) with Zenhub @jig-patel

**Comment by justin-lepitzki** [comment]
Main dev release. Not seeing a rescind entry within the Transaction History section for both BCeID & IDIR users. The Category D box is also still visible (IDIR users only). 

Screenshot of IDIR view: [Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWh0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--db5db8e6f408a9fd4d73f2558b14d9aa74446cc8/Screenshot%202023-09-05%20Rescind%201175%20IDIR%20view.png)

Screenshot of BCeID view: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXB0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0eac43115476ce969d9cce13ecb905f2865b3b12/Screenshot%202023-09-05%20Rescind%201175%20BCeID%20view.png)
