### ISSUE TITLE
TFRS - Edge Case Testing and Unit Test Coverage for Compliance Units in Compliance Reports

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2543]
**Describe the task**
Conduct thorough testing for all 17 identified edge cases related to the Compliance Reports and Compliance Units. Ensure that there are unit tests covering each scenario and implement any missing tests.

https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2506

**Purpose**
To ensure that the Compliance Units feature in the Compliance Report Summary View is robust, can handle all possible edge cases, and has comprehensive test coverage for those scenarios. This ensures the stability and reliability of the feature in production.

**Scenario Importances**
Main: S1, S2, S3, S4, S5, S7, S9, S13, S14
Secondary: S6, S8, S10, S15, S16
Outlier: S11, S12, S17

**Acceptance Criteria**
- [ ] All 17 edge cases related to compliance reports and compliance units are tested.
- [ ] Existing unit tests are confirmed to cover each of the 17 scenarios adequately.
- [ ] Any missing tests for these scenarios are identified and implemented.
- [ ] All tests, both old and new, pass successfully without any issues.
- [ ] Documentation is updated to include details of the edge cases, testing process, and results.

**Additional context**
- This is a follow-up ticket to TFRS - Testing and Deployment of Compliance Units in Compliance Report#2506.
- Collaboration and communication with the UX/Product Owner will be vital to ensure all edge case scenarios align with the product vision and user needs.
- Developers should liaise with QA teams to facilitate smooth testing and quick identification of any potential issues.
- Feedback from this testing phase should be promptly integrated to ensure the highest quality feature deployment.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2543?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test
