### ISSUE TITLE
TFRS - Missing information on credit transfer view page for rescinded credit transfers

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2557]
**Describe the Bug**
The credit transfer view page is missing information when the credit transfer has been rescinded. 

- The rescind entry is not showing in Transaction History section.
- The second sentence is not showing that says the transfer has been rescinded and by which organization.  

**Expected Behaviour**
When a credit transfer is rescinded, 
- there should be an entry added to the transaction history section stating that the proposal was rescinded on this date by the user of this organization. For example, "Rescinded on August 25, 2023 by User Name of Organization Name"
- An additional sentence should be added to the credit transfer sentence saying that the transfer has been rescinded and by which organization. For example, "Organization Name rescinded the proposal."

Screenshot, confidential info redacted:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmsrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a345120b248e37645053fdbb41342f7499581b88/Screenshot%202023-08-25%20Rescind%20entry%20showing%20in%20Prod.png)

**Actual Behaviour**
When the transfer is rescinded, neither of these two components are showing in the UI. 

Dev screenshot: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclkrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a362a030ec59a060485d4b198671334fea9e9c87/Screenshot%202023-08-25%20Rescind%20entry%20not%20showing%20in%20transaction%20history.png)

**Implications**
Users need to be informed of who rescinded a transfer proposal and when. 

Acceptance Criteria:
- [ ] Dev changes should be in sync with prod and all the missing information should reflect in dev UI.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2557?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
