### ISSUE TITLE
TFRS - Make date of written agreement and categorization information visible to BCeID users

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2558]
**Describe the task**
BCeID users, who are parties to a credit transfer, should be able to view the date of the written agreement and the categorization information in the Transaction History section. Currently, this information is only accessible to IDIR users. The new change should allow BCeID users to view both the potential categorization category ("if approved by") and the final categorization category.

**Purpose**
The change is driven by feedback from IDIR users involved in processing credit transfers. They've observed a genuine interest from fuel suppliers to have direct access to this data, and by granting it, we can potentially reduce the frequency of inquiries directed to the business area.

**Screenshots of information, currently only visible to IDIR users**
Prior to approval:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjgrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2480b214279d15736a06cc924a84a014d0b8d7d6/Agreement%20date%20-%20prior%20to%20approval.png)

After approval:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0ErIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--486b439cb5f4cd0c96efb6d237f53eed4d91f6d2/Agreement%20date%20-%20after%20approval.png)

**Acceptance Criteria**
- [x] **Visibility**: BCeID users who are parties to a credit transfer can see the date of written agreement.
- [x] **Potential Categorization**: BCeID users can view the potential categorization category labeled as "if approved by".
- [x] **Final Categorization**: BCeID users can view the final categorization category once the transfer is approved.
- [x] BCeID users do not see the select category D checkbox selection option

**Additional context**
- Ensure that the change doesn't inadvertently expose other sensitive information that should remain hidden to BCeID users.
- It's important to communicate this change to the BCeID users so they are aware of the new information available to them.
- There might be a need for additional training or documentation to help BCeID users understand the context and importance of the displayed data.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2558?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
