### ISSUE TITLE
TFRS - Delete one more duplicate organization in Prod

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2569]
**Describe the task**
Delete an organization in Prod that was created by mistake. 

The organization ID# is 470 and the name is 'Deleted'.

**Purpose**
Card #2471 was to delete five organizations created in error. This card is to delete another organization that was missed when the business area was identifying the organizations to delete for #2471. 

All of these organizations were created before it was discovered / identified that they were not actually reporting the supply of fuel. The business area has changed its workflow process to better review supply claims prior to creating an organization in TFRS, to help reduce future mistakes in onboarding organizations. 

Link to card 2471: https://app.zenhub.com/workspaces/team-zelda-637d5bc12e6201001055b745/issues/gh/bcgov/tfrs/2471

**Acceptance Criteria**
- [ ] Identify and delete the duplicate organizations after confirmation. 
- [ ] Ensure to have the backup.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2569?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by AlexZorkin** [comment]
Here are the queries run to delete the 'Deleted' organization:

```
delete from organization_address where organization_id = 470;
delete from organization where id = 470;
```
