### ISSUE TITLE
TFRS - Summary section showing incorrect values when there are multiple supplemental report submissions

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2573]
**Describe the Bug**
The Low Carbon Fuel Requirement summary section is not showing the correct values when there is more than one supplemental report submission: two or more supplemental reports. 

For example, the summary section is incorrect for both scenario 4 & scenario 5 when there has already been both an original report and supplemental #1 submitted and accepted. When you go to create a second supplemental report (Supplemental #2) the summary section is not recognizing the previous reports & corresponding balance changes. The numbers showing are like if the 2nd supplemental report was the original report (i.e., no previous submissions). 

For clarity, scenario 4 & 5 are working correctly for the first supplemental report submission (Original report accepted, then submit Supplemental #1). 

Examples in the dev-jan environment: 
- Scenario 4: Org ID# 137, Report ID# 1092
- Scenario 5: Org ID# 137, Report ID# 1093

**Expected Behaviour**
The summary section recognizes previous submissions for the report, including whether they have been assessed or not, and shows the correct values accordingly (as per the information outlined in the "example new values" section of the Scenarios spreadsheet). 

**Actual Behaviour**
The summary section is not recognizing previous submissions for the report.

**Comment by AlexZorkin** [comment]
great thank you. I will ask Justin to test this afternoon.
