### ISSUE TITLE
TFRS - revise messaging for category D checkbox

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2576]
**Describe the task**
Revise the UI messaging for the category D checkbox. 

**Current messaging:** "Category D, approve as Category D if zero dollar value or significantly less than fair market value."

**Revised messaging:** "Select the checkbox to set the transfer as Category D if the price is significantly less than fair market value. This will override the default category determined by the agreement and approval dates indicated below."

**Purpose**
IDIR user feedback aimed at improving clarity and understanding

**Acceptance Criteria**
- [ ] The current messaging on the UI should be replaced with the revised messaging provided above.
- [ ] The revised messaging should be clearly visible and legible to users.
- [ ] Any interaction with the checkbox (i.e., selection or deselection) should not alter the clarity or visibility of the revised message.

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2576?planning-poker) with Zenhub @prv-proton
