### ISSUE TITLE
TFRS - Net compliance unit rounding discrepency between Schedule B & summary section

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2577]
**Describe the Bug**
In some cases, the net compliance units displayed in the modal window in Schedule B differs from the net compliance units displayed in the Low Carbon Fuel Requirement summary section on the Summary & Declaration page.

**Expected Behaviour**
These values should be the same. 

**Actual Behaviour**
These values are different.

**Implications**
Confusing to the user to see two different totals for their compliance standing. 

**Example: Scenario 7**

Schedule B value is -490; copy Schedule B values to excel shows full decimals confirming value is correct at -490:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFZWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--447322ed91f38b9250462506c32899d126f8d363/Screenshot%202023-08-30%20Sch-B%20rounding%20vs%20Summary.png)

Summary value is showing -491, it should show -490: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGhWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aa086bd9fe72482707a88cd16f12ec6807174c5c/Screenshot%202023-08-30%20S7-Summary-rounding.png)

**Rules for Rounding**
- Uses conventional rounding: round down when <5, round up when >= 5.
- We implement rounding only when totaling up the net compliance units from all entries in Schedule B. 
- Although we do not show decimals in the UI, we do not round compliance units for individual entries in Schedule B. Instead we total up the individual rows (including decimals) and then round at the end to get the net compliance units. 
- This is the more accurate method of determining net compliance units for an organization.

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2577?planning-poker) with Zenhub @prv-proton
