### ISSUE TITLE
TFRS - new input field for organization details - IDIR only

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2579]
**Title:**
New input field for Organization Details 

**Description:**
- New input field when creating or editing an organization
- Text field label: 'Company profile (EDRMS Record #):' 
- Free form text field that can accept numbers and letters (e.g., D4327343F)
- Make field visible on the Organization Details page, below the head office address
- Make field visible when viewing a compliance report, near the top of the page but below the head office address
- Only visible to IDIR users

**Wireframes:**
- Create / edit organization page: https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/161516664?mode=fm
- Organization Details page (see also note below with screen capture): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164218730/simulate/no-panels?mode=mf
- Viewing a Compliance Report page (see also note below with second screen capture): https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164219272?mode=fm

**Purpose and benefit to user:**
- IDIR user feature request
- Will streamline the review of compliance reports by removing redundancies and/or external tracking sheets currently used when processing reports.

**Acceptance Criteria:**

- [ ] Given I am an IDIR user, When I am <doing something>, then <this happens>
- [ ] Given I am an IDIR user, When I am <doing something>, then <this happens>

**Development Checklist:**
- [ ] New column and necessary migrations to be included
- [ ] UI changes at multiple pages
- [ ] Backend changes to perform CRUD operation for this new column

**Notes:**

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2579?planning-poker) with Zenhub @AlexZorkin @prv-proton

**Comment by justin-lepitzki** [comment]
The new field is not being displayed on the Organizations Details page or when viewing a compliance report. We want to show the new field on these two pages for IDIR users. See the wireframes for mockup. 

Also, when creating a new organization, the supplier type 'Part 3 Fuel Supplier' should be selected by default because it is the only available option. Right now it is not selected.

**Comment by justin-lepitzki** [comment]
The new field is now displaying on the Organizations Details page and when viewing a compliance report. However, it is visible to both BCeID and IDIR users. This field should only be visible to IDIR users.

**Comment by justin-lepitzki** [comment]
The new field is still visible to BCeID users on the organization details page. See here: https://drive.google.com/file/d/1oEyiwi81uHcwqWicuSaDy6rxQqBzHq8i/view?usp=sharing 

The heading label "Company Profile, EDRMS Record #:" isn't visible but the actual record # is visible when there is one in the database.

**Comment by justin-lepitzki** [comment]
Tested and working :)
