### ISSUE TITLE
TFRS - new Act label revisions - removing some references to credits 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2583]
**Describe the task**
Adjustments to some recent new Act label changes to remove references to "credit transfers". The thinking is to use the label "transfers" for the new Act. 

**Labels to change:**
See attached document for description of label changes: 
[New-Act-Label-Changes_Removing-credit-transfer-ref.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDFnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12155919ee906d87f9c48a51d593b25e4ae7c92e/New-Act-Label-Changes_Removing-credit-transfer-ref.docx)

**Purpose**
To align with the new Act naming conventions and business area preferences.

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2583?planning-poker) with Zenhub @AlexZorkin @prv-proton
