### ISSUE TITLE
TFRS - New Act Label Changes - Credit Transfer feature

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2590]
**Describe the task**
Changing labels within the credit transfer feature, for both BCeID and IDIR users. 

**Labels to change:**
See attached document for description of label changes:  
[New-Act-Label-Changes_Credit-Transfers.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkZzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bb81852dc304a8c185b3e3fde9fb5432d2a78a3/New-Act-Label-Changes_Credit-Transfers.docx)
 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2590?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Reviewed and identified some issues with certain labels being unchanged or needing minor tweaks/revisions. See attached document below for more information; yellow highlighted cells have identified issues, left comment providing more information. 

Attached: [New-Act-Label-Changes_Credit-Transfers REVIEW.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXovIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1e1bf6d8918f0cd987fbf722d416a3fb71019729/New-Act-Label-Changes_Credit-Transfers%20REVIEW.docx)
