### ISSUE TITLE
TFRS - Prevent an administrative adjustment transaction from causing a negative compliance unit balance

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2591]
**Describe the task**
Ensure that when committing an administrative adjustment transaction, if it results in a negative balance for the organization's compliance unit, the system should set the organization's balance to zero rather than allowing a negative value.

**Example**
For instance, an organization possesses a balance of 1,000 compliance units. The IDIR user queues an administrative adjustment of -1,500 within the Historical Data Entry feature. On committing this adjustment, the system should apply an administrative adjustment of -1,000, effectively setting the organization's balance to zero.

**Purpose**
With the current dev-jan release, committing an administrative adjustment transaction can inadvertently lead to negative balances. Such occurrences are problematic since real-world consequences entail notifying the organization of the deficit and imposing penalties (handled outside of TFRS/LCFS). Within TFRS/LCFS, a negative balance scenario should be avoided.

**Acceptance Criteria**
- [ ] When an administrative adjustment is queued that would result in a negative compliance unit balance, the system should automatically adjust the value to prevent this outcome.
- [ ] After committing the adjusted transaction, the organization's compliance unit balance should reflect a zero balance and not a negative value.
- [ ] Write robust unit tests that cover this logic to ensure organization balances never go negative.

**Additional context**
- Card #2431 is related to this work and may be better to do together / at the same time.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2591?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
System allows the admin adjustment feature to cause a negative compliance unit balance. For an example, see the dev-jan release, organization name = FS6, transaction ID #1191 (-10,000 admin adjustment) caused the balance to go to -1,000.

**Comment by AlexZorkin** [comment]
Transactions are now auto-adjusted to match the org balance if the overall effect would put the org in a negative balance. There is also now validation that prevents negative transactions from being committed if the organization has a zero balance.

**Comment by justin-lepitzki** [comment]
Receiving an error when trying to commit a -5000 adjustment transaction on an organization that has a +3000 balance. The system should initiate a -3000 admin adjustment transaction in this instance (upon commit).

See screenshot: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk0yQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b98d04bf9eba9e7084625efb9e926792269ba9e3/Screenshot%202023-10-13%20FS10.png)
