### ISSUE TITLE
 TFRS - Analyst recommend transfer approval buttons not appearing in Jan release  

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2598]
**Describe the Bug**
The recommend / not recommend approval for transfers is not appearing in the Jan release when viewing a transfer with the government analyst role. This issue is only occurring in the Jan release, and not the main dev branch (nor in test/prod).

**Expected Behaviour**
When viewing a transfer with a 'Signed' status as a government analyst, two buttons should be visible to process the transfer: recommend and not recommend approval

**Actual Behaviour**
The recommend / not recommend buttons are not visible when viewing a transfer with a 'Signed' status as a government analyst.

**Implications**
Unable to process a transfer

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR, government analyst role
1. Go to a transfer with the 'Signed' status
2. See error

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2598?planning-poker) with Zenhub @jig-patel @prv-proton
