### ISSUE TITLE
TFRS - Remove two of the declaration statements from the credit transfer feature

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2599]
**Describe the task**
Refactor the transfer proposal interface to eliminate two of the Signing Authority declaration statements currently mandated when proposing a new transfer to an alternative supplier. This adjustment is necessary for BCeID users with the Signing Authority role when they initiate a new transfer.

When a BCeID user creates a new transfer, a user must have the Signing Authority role to complete the three Signing Authority declaration statements that are required for the transfer to be signed and sent to the counterparty. 

**Screenshot:**
[Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczJLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50e7b9ab466f22f90bc3d9852971b606aeca9348/Screenshot%202023-09-11%20transfer%20signing%20declaration.png)

**Purpose**
Feedback from fuel supplier users, further validated by legal consultations, highlighted that the two declaration statements are superfluous for the signing and submission process of transfers. Their presence is impeding certain user profiles (e.g., agents) from executing and forwarding transfers on behalf of the supplier. To improve usability and compliance, these statements need to be removed.

**Acceptance Criteria**
- [x] Identification and removal of the two unnecessary Signing Authority declaration statements from the transfer interface.
- [x] Ensure BCeID users with the Signing Authority role can seamlessly initiate transfers without the removed statements.
- [x] Conduct a user test to confirm that agents can now sign and submit transfers without any hitches.
- [x] Add or update unit tests to allow for submission without all 3 signings
- [x] Ensure that previously signed submission still show all three checked lines, while new submissions only show the one

**Additional context**
- Analyzing the current codebase can give insight into how these declaration statements have been implemented and guide their removal process.
- Post-removal, a brief communication or update guide might be necessary for existing users to understand the changes made.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2599?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
The declaration statements are still showing in dev: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFRjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cd6a9714a855b82111b65b5c2ac3cbdf852dc59/screencapture-tfrs-dev-apps-silver-devops-gov-bc-ca-credit-transactions-add-2023-11-15-15_49_29.png)

**Comment by justin-lepitzki** [comment]
Tested and working :)
