### ISSUE TITLE
TFRS - Miscellaneous new Act label changes

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2600]
**Describe the task**
Some miscellaneous label adjustments following: (1) further discussion / thought, (2) previously overlooked by PO, (3) issues identified after close out of previous label card.

**Labels to change:**
See attached document for description of label changes:  
[New-Act-Label-Changes_Clean-up_Missed-labels.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8440fe78a0d87ede581d61c9655deb7a7f95230/New-Act-Label-Changes_Clean-up_Missed-labels.docx)

 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality
- [ ] 

**Review:**
See here: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3hIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09e14698f76fe1beca0ff6138b4bb01155befd71/Screenshot%202023-10-17%20141446.png)

[Missed-labels_REVIEW.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40354c2b0012c67ddfb5bc28cdaa44cc2ca6d23c/Missed-labels_REVIEW.docx)

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2600?planning-poker) with Zenhub @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
There are four label changes that need to be adjusted. Attached the word document with these changes in the description of the card, under the **Review:** heading. Zenhub upload feature not working for comments so added document to the main description.

**Comment by justin-lepitzki** [comment]
Partially tested and working. Unable to test final label due to time-based label changes for transactions
