### ISSUE TITLE
TFRS - Time-based transaction label changes for the new Act

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2601]
**Describe the task**
Implement changes to the labels used to describe transactions based on when the transactions were inputted into TFRS. 

- New labels for transactions occurring on or after January 1, 2024; maintain old labels for transactions that occurred prior to January 1, 2024. 
- Note: Focus is on when the transaction is approved/applied, not it's effective date. For example, a Part 3 Award created and approved on January 5, 2024 with an effective date of November 25, 2023, would use the new label because it was approved on or after January 1, 2024. 

**Label changes:**
- Current labels: (1) Validation, (2) Reduction, (3) Part 3 Award, (4) Transfer
- New labels: (1/2) Assessment, (3) Initiative Agreement, (4) Transfer

See attached document: [New-Act-Label-Changes_Time-based-Transaction-Type-Labels.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXVLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--611a30a52459374a5f8e151c3a0076441d576c90/New-Act-Label-Changes_Time-based-Transaction-Type-Labels.docx)

**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality, ensuring labels change based on the compliance period.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2601?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Not able to test until after January 1, 2024, since we cannot create a transaction with an effective date in the future.
