### ISSUE TITLE
TFRS - New Act Label Changes - Transactions view page using HDE - time based

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2602]
**Describe the task**
Changing labels when viewing credit transactions created by the Historical Data Entry feature. 

- label changes only apply to transactions approved on or after January 1, 2024. Focus is on when the transaction is approved/applied, not it's effective date. For example, a Part 3 Award created and approved on January 5, 2024 with an effective date of November 25, 2023, would use these new labels because it was approved on or after January 1, 2024. 
- label changes for transactions created by features within TFRS are handled in separate cards, although there is likely a bit of overlap. 
- the requested label changes to the tool tip for the eye icon within comments on transactions should only be made to these view pages for transactions. We appear to be using the same text for the hover over tool tip on the eye icon in other areas of the app (i.e., the credit transfer feature). We want to separate these label changes so that the changes made as part of this card don't lead to the same change happening in the credit transfer feature. Currently, I believe they are all connected in terms of using the same tool tip language. 

**Labels to change:**
See attached document for description of label changes:  
[New-Act-Label-Changes_Transactions-View-page-HDE.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdG1QIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--05fdaa6eb405e4b2c1eb2d020faf24091258721a/New-Act-Label-Changes_Transactions-View-page-HDE.docx)

 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by KericeRich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2602?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
The new labels are showing when viewing a transaction that was created prior to January 1, 2024; this is happening for all transaction types. The new labels on the view transaction page (i.e., after clicking on a transaction in the main Transactions table) should only be visible for transactions created on or after January 1, 2024.
