### ISSUE TITLE
TFRS - new Act label changes - New Part 3 Award feature - IDIR view review and approve

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2603]
**Describe the task**
Changing labels within the new Part 3 Award feature, visible to only IDIR users until approved or declined then visible to BCeID users as well. 

**Labels to change:**
See attached document for description of label changes:  
[New-Act-Label-Changes_New-Part-3-Award-IDIR-Review-Approve.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUNQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ad8b6e8e424a23ad3206ab32b7f3e3b3ce7f2ee9/New-Act-Label-Changes_New-Part-3-Award-IDIR-Review-Approve.docx)

- Note: the requested label changes to the tool tip for the eye icon within comments on Part 3 Award transactions should only be made to these view transaction pages. We appear to be using the same text for the hover over tool tip on the eye icon in other areas of the app (i.e., the credit transfer feature). We want to separate these label changes so that the changes made as part of this card don't lead to the same change happening in the credit transfer feature (or elsewhere). Currently, I believe they are all connected in terms of using the same tool tip language. 

 
**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2603?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Reviewed and identified some issues with certain labels. See attached document below for more information; yellow highlighted cells have identified issues, left comment providing more information. There might be a larger issue here as many of the labels showing for this feature (Initiative Agreements) are labels from the Transfer feature. Not sure if this is a bug or both features use the same label in the back-end and changing it for transfers changed it here. We may need to separate labels if this is the case as they need to be different for transfers and Initiative Agreements in some cases. 

Attached: [New-Act-Label-Changes_New-Part-3-Award-IDIR-Review-Approve REVIEWED.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnovIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40b121e58661324f94dbe1a31f51d4c62045dff2/New-Act-Label-Changes_New-Part-3-Award-IDIR-Review-Approve%20REVIEWED.docx)
