### ISSUE TITLE
TFRS - Scenario 8 not showing correct balance change from assessment for supplement report 2

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2606]
**Describe the Bug**

The summary section is not calculating the correct values for Scenario 8. Tested when there is more than one supplemental. System is often throwing an error when trying to view the summary section in this scenario; refreshing the page reloads the page.

**Expected Behaviour**
The new summary values should align with Scenario 8 in the spreadsheet. 

**Actual Behaviour**
The new summary values are not calculating correctly in alignment with scenario 8 in the spreadsheet.

**Example of Scenario 8 issues: Dev-jan release report ID# 1143**
- see image below for comparison. Penalty amount is correct but balance change is not. Showing 3,597 when it should be 0.
[Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXFYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51a2ba250fc350a1de466a2819ffa45501283d47/Screenshot%202023-09-13%20101811.png)

Error screen that shows up when trying to view summary section: 
[Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2FTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cbc5c05eddee40a34460d126122b3801d744ea63/Screenshot%202023-09-12%20S8%20Error%20screen.png)

Acceptance Criteria:
- Edge case scenario showed in spreadsheet screenshot need to check on logic to calculate compliance unit balance when penalty is paid off to make it zero.

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2606?planning-poker) with Zenhub @jig-patel @AlexZorkin @prv-proton

**Comment by justin-lepitzki** [comment]
Still seeing issues with S8. Report ID# 1143 in dev-jan release, FS3 org

The 'compliance unit balance change from assessment is showing as 430 when it should be 0.
The 'non-compliance penalty payable' is incorrect in the penalty amount (showing $1,902,000 when it should show $1,800) and the number of units (showing 10,003 units when it should be 4 units).

See screenshot: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0s5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--023fa18be0dda4fc1392f6c6b3718d77f9f58a1c/Screenshot%202023-09-20%20S8.png)
