### ISSUE TITLE
TFRS - Scenario 10 not showing the correct math for calculating the penalty amount

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2607]
**Describe the Bug**
The summary section is not showing the correct math for calculating the non-compliance penalty for Scenario 10. The actual penalty amount displayed is correct, but the information about how that amount is calculated (i.e., how many units out of compliance) is not correct. 
**Expected Behaviour**
The non-compliance penalty calculation information displayed should align with the penalty amount displayed.  

**Actual Behaviour**
The non-compliance penalty calculation information displayed is different than the actual non-compliance penalty amount being displayed (which is correct).  

**Example of Scenario 10 issues: Dev-jan release report ID# 1140**
Displaying wrong unit amount for non-compliance penalty. Showing 3600 when it should be 434:
[Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2lTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb24bc79b93f114de7460511319e6160ea3ad592/Screenshot%202023-09-12%20S10%20displaying%20wrong%20unit%20amount%20for%20non-compliance%20penalty.png)

Correct amounts for this S10 example: 
[Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb21TIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ba058c2b41253baa9dc437f1feef94335813c13/Screenshot%202023-09-12%20S10%20correct%20amounts.png)

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2607?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
