### ISSUE TITLE
TFRS - Unable to submit a 2023 compliance report for Scenario 3

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2609]
**Describe the Bug**
When attempting to submit a 2023 report for Scenario 3, an error message appears. Additionally, the Summary page throws errors when loading for the first time.

**Expected Behaviour**
Users should be able to submit a 2023 report for Scenario 3 seamlessly, and the Summary page should load successfully without any errors on the first attempt.

**Actual Behaviour**
When trying to submit the 2023 report for Scenario 3, users receive an error message. The Summary page also displays errors upon initial load.

**Implications**
This bug disrupts the report submission process for Scenario 3, potentially preventing users from completing their tasks. Furthermore, the inability to access the Summary page on the first attempt hinders the user experience and could erode trust in the application's reliability.

**Steps To Reproduce**
- User/Role: (Specific user/role affected, if known)
- Go to '2023 report submission page'.
- Select 'Scenario 3' from the available options.
- Fill in the necessary details for the report.
- Click on 'Submit'.
- See error message related to report submission.
- Navigate to 'Summary' page.
- See error upon initial load.

**Attachments:**
Screenshot: [Bug Screenshot](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHlUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--910e90030525b788fecfb877d311d4715baa48a7/Screenshot%202023-09-12%20Error%20loading%20and%20submitting%20scenario%203.png)

Log of console errors when first loading scenario page: [tfrs-dev-jan.apps.silver.devops.gov.bc.ca-1694581863917.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbCtUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5242ab86002553872a1c27a62b7067b67c17fcff/tfrs-dev-jan.apps.silver.devops.gov.bc.ca-1694581863917.pdf)

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2609?planning-poker) with Zenhub @jig-patel @AlexZorkin @prv-proton
