### ISSUE TITLE
TFRS - Scenario 15 showing incorrect available balance and compliance unit 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2610]
**Describe the Bug**

The summary section is not calculating the correct values for Scenario 15. Tested when there is one supplemental. 

**Expected Behaviour**
The new summary values should align with Scenario 15 in the spreadsheet. 

**Actual Behaviour**
The new summary values are not calculating correctly in alignment with scenario 15 in the spreadsheet.

**Example of Scenario 8 issues: Dev-jan release report ID# 1151**
- see image below for comparison. Penalty amount is incorrect; available compliance balance isn't accounting for in-reserve credits related to the same report
 
[Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbCtYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0433f5aac8d211be964f2fc614d9bb7d7e7ae9ce/Screenshot%202023-09-13%20S15.png)

**Comment by jig-patel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/tfrs/2610?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Penalty amount is correct but the values are still incorrect for: 
(1) Available compliance unit balance on March 31, YYYY: showing 10,200 instead of 0
(2) Compliance unit balance change from assessment: showing -10,200 instead of -283
