### ISSUE TITLE
TFRS - Fix Broken Unit Tests Surrounding Lines 26A and 26B for Compliance Years 2022 and Below

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/tfrs#2619]
**Describe the task**
Address and correct the broken unit tests related to lines 26a and 26b. Ensure these fields are relevant for compliance periods of 2022 and below and do not interfere with the new logic for years above 2022 when integrating the `compliance_units`.

**Purpose**
To maintain the accuracy and reliability of the codebase, especially concerning compliance logic for different years, and to ensure the system correctly handles credits and debits scenarios for the years mentioned.

**Acceptance Criteria**
- [ ] The broken unit tests for lines 26a and 26b are corrected and pass successfully.
- [ ] The fields for lines 26a and 26b are only applicable for compliance periods of 2022 and below.
- [ ] Ensure the new logic for years above 2022 does not disrupt the existing logic for years 2022 and below.
- [ ] Tests are in place to verify that the logic for 2022 and below in credits and debits scenarios remains unaffected when adding in the `compliance_units` logic for years above 2022.

**Additional context**
- Test file with broken test is named Part3CalculatePart3.test.js specifically the 'is supplementary debit scenario' test
- The current tests are failing around the expectations set for `part3[SCHEDULE_SUMMARY.LINE_26_A][2].value` and `part3[SCHEDULE_SUMMARY.LINE_26_B][2].value`.
- The goal is to seamlessly integrate compliance logic for different years without introducing regressions to existing functionalities.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2619?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing for PO to test :)
