### ISSUE TITLE
TFRS - Remove or hide balance change statements within the Assessment section for 2023 reporting 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2625]
**Describe the task**
Remove, or hide in the UI, the balance change statements within the Assessment section of a reviewed/accepted compliance report for the 2023 compliance period. This needs to be done for the assessment section under all scenarios, including supplemental reporting which adds an additional sentence describing the balance change that will occur / occurred.  

**Examples of statements to remove within the assessment section:**

- Scenario 1: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3kzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b1b65d02de5d1373ecdf0521078c5da4af9a0dac/Screenshot%202023-08-25%20Assessment-section-S1.png)

- Scenario 2: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcyszIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--20384cf9eb085056e7558a0f3471d7e6fe72ab72/Screenshot%202023-08-25%20Assessment-section-S2.png)

- Scenario 3: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEMzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ab4e51232a052a2d63d955aedc7dca98e2414928/Screenshot%202023-08-25%20Assessment-section-S3.png)

- Scenario 4: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEczIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d916877f3f0fb57e608284f055db9c76111cc757/Screenshot%202023-08-25%20Assessment-section-S4.png)

- Scenario 5: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFczIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--04d681f188e554c7a4ef8fd0fae4b51929709a45/Screenshot%202023-08-25%20Assessment-section-S5.png)

**Purpose**
Statements are not always correct in terms of the type of balance change that is occurring. This issue is a result of the recent changes to the Summary section of the 2023 reports. Instead of spending significant development time resolving the inaccuracies for each scenario, we want to simply hide or remove these statements for the 2023 reports. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2625?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
Working for 2023 reports. Unable to test if it is still available in 2022 and prior reports due to a bug with viewing summary and declaration section. Unable to submit new reports to test. Closing out this ticket and will test 2022 and prior once the bug is resolved.
