### ISSUE TITLE
TFRS - Summary & Declaration page not loading for 2022 and prior compliance reports

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2647]
**Describe the Bug**
The Summary & Declaration page is not loading for 2022 and prior compliance reports. This occurs regardless of the data entered into the report: (1) no data, (2) net debit position, or (3) net credit position. Under all scenarios, the system throws and error and fails to load the page. 

**Expected Behaviour**
The page loads when the user clicks on the 'Summary & Declaration' tab

**Actual Behaviour**
The system throws an error when the user clicks on the 'Summary & Declaration' tab

**Implications**
Unable to submit a report 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user
1. Go to a 2022 or prior compliance report in the dev-jan release
2. Click on the 'Summary & Declaration' tab
3. See error

*Error message:**
Screenshot of error message in UI: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnY5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2cc736c63b2f3b2e2a0d5420f77769b78b9d6cae/Screenshot%202023-10-03%20error%20message.png)

Log of console error messages: [tfrs-dev-jan.apps.silver.devops.gov.bc.ca-1696350837031.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0g5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5c88f5c1085b8e423b6ecb7b3a35bbe15c3841d5/tfrs-dev-jan.apps.silver.devops.gov.bc.ca-1696350837031.docx)

**Comment by justin-lepitzki** [comment]
Note for PO for testing: see card #2625 for additional testing that needs to be done once this bug is resolved. Could not fully test 2625 due to this bug blocking the ability to submit new reports for 2022 and prior.

**Comment by KericeRich** [comment]
@AlexZorkin  reminder to create tech debt ticket related to this.

**Comment by KericeRich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2647?planning-poker) with Zenhub @AlexZorkin @prv-proton

**Comment by KericeRich** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2647?planning-poker) with Zenhub @jig-patel
