### ISSUE TITLE
TFRS - Separate comment disclosure notice based on feature and comment type

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2652]
**Describe the task**
The disclosure notice is visible to users when they are first adding a comment to a transfer (BCeID & IDIR) and new Initiative Agreement Issuance, formerly Part 3 Award (IDIR only). Recently, we made some adjustments to the disclosure notice labels for the comment feature in transfers; this caused the disclosure notice labels for comments to change for both regular and internal comments and for the notice in the Initiative Agreement comment feature. 

It appears that the disclosure notice for the comment feature is the same for both transfers and Initiative Agreements. We want to separate them so that we can have different disclosure notices for each. 

**Transfers:**
- Regular comment disclosure notice: Information entered in this comment field will be visible to both parties of the transaction and government.
- Internal comment disclosure notice: Information entered in this comment field will only be visible to government.

**Initiative Agreement (formerly Part 3 Award):**
- Regular comment disclosure notice: Information entered in this comment field will be visible to both the organization and government.
- Internal comment disclosure notice: Information entered in this comment field will only be visible to government.

**Acceptance Criteria**

*Separate Disclosure Notices:*
- Implement separate disclosure notices for Transfers and Initiative Agreements.
- Ensure that the correct disclosure notice is displayed based on the feature and comment type.

*Validation:*
- Verify that for Transfers, the regular comment disclosure notice states: "Information entered in this comment field will be visible to both parties of the transaction and government."
- Verify that for Transfers, the internal comment disclosure notice states: "Information entered in this comment field will only be visible to government."
- Verify that for Initiative Agreements, the regular comment disclosure notice states: "Information entered in this comment field will be visible to both the organization and government."
- Verify that for Initiative Agreements, the internal comment disclosure notice states: "Information entered in this comment field will only be visible to government."

*Usability:*
- Ensure that the disclosure notices are clearly visible and legible to users when adding a comment.
- Check that the notices are placed in a way that they're hard to miss before a user proceeds to add a comment.

*Testing:*
- Conduct unit testing to ensure the disclosure notices are functioning as expected.
- Conduct user acceptance testing (UAT) to ensure that the changes meet user expectations and comply with the described requirements.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2652?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
The disclosure notice for transfers is showing the wrong notice: "Information entered in this comment field will be visible to both the organization and government." 

Tested with a BCeID user creating a new transfer and an IDIR analyst reviewing a submitted transfer.
