### ISSUE TITLE
TFRS - Revise filtering from BCeID and IDIR dashboard links to align with the new Act labels  

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2662]
**Describe the task**
Links on the dashboard provide information to the user about items in progress, such as transfers in progress. Clicking on these links takes the user to filtered views of the different tables. For example, clicking on the "transfers in progress" link takes the user to a filtered view of the credit transactions table. This filtered view uses the built-in filtering within the react tables. 

The filtering is now broken as a result of changing labels. We need to adjust this filtering to align with the changes we made to certain labels.

The required changes are included in this screenshot: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG9vQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1cdde720c8ef432716ed3a9692cd7983d017521/Screenshot%202023-10-11%20115800.png)

Screenshot of one of the filtered tables: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFlvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4646c13bb0c0420e8536350dcd56abb98c68268e/Screenshot%202023-10-11%20120209.png)

**Purpose**
To fix the filtering that broke as a result of the changes we made to certain labels. 

**Acceptance Criteria**
- [ ] Update all link filter text to align with new labels
- [ ] Test each link to make sure filtering returns expected results

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2662?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by prv-proton** [comment]
Fixes are only done for Credit Transactions and Compliance reports filters as there is a separate ticket TFRS#2664 to address file submissions.
