### ISSUE TITLE
TFRS - Do not display BC Attorney default fields in a compliance report when only the default fields are filled 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2676]
**Describe the task**
The BC Attorney information should not be displayed if there is no attorney address information associated with the organization. The 'BC' and 'Canada' fields are default fields for this part of the organization details form because by definition the 'Corporation or Attorney in B.C.' is located in BC, Canada. However, we don't want to display these two default fields if there is no other information entered into this section of the organizations details page, such as the name of the representative, the street address, etc.

Screenshots: 

Organizations Details input form: [Uploading... Screenshot 2023-10-17 org details.png]

View in a compliance report: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk5jIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d42f6a2905b8e0924d92cdccb93455a671c641a9/null-bc-address.png)

**Purpose**
To only display relevant organization information in a compliance report

**Acceptance Criteria**
- [ ] The BC Attorney address should be concealed in both the Compliance Report and the Organization Details Views if the BC Attorney address is either null or empty.
- [ ] Ensure that other fields in the form are unaffected.
- [ ] Test for various scenarios to ensure consistent behavior, and update any view snapshots if neccessary.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2676?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
