### ISSUE TITLE
TFRS - Erroneous penalty showing for a supplemental report Line 26 issue

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2679]
**Describe the Bug**
A supplier submitted a supplemental compliance report for 2021 that is showing an erroneous penalty and incorrect Line 26 value in Prod.

**Report Details:**
- Original report was in a net debit position and used credits to offset debits
- Supplemental report #1 was submitted that slightly changed the volume of one fuel but not to the extent that changed the credit/debit position. This report was Accepted and the credits used to offset the net debit position were removed from the supplier's balance.
- Supplemental Report #2 was submitted that increased the net debit position; additional credits were used to offset this obligation. The report was reviewed by the analyst and recommended for acceptance (report was not accepted).
- Supplemental Report #3 was submitted that **did not change any Schedule B information**; this report only changed the volume of Part 2 fuel retained for the next compliance period. This report has a zero value for Line 26 and is showing a large penalty. We suspect the issue to be caused by the system not being able to handle a situation where the net debit/credit position does not change from the previous submission. 

**Report specific info to be provided outside of Zenhub due to confidentiality concerns.**

**Expected Behaviour**
Line 26 in the summary section should recognize the previous use of credits to offset debits and not show a penalty. 

**Actual Behaviour**
Line 26 in the summary section is not recognizing the previous use of credits to offset debits and is showing an erroneous penalty.

**Implications**
The system is indicating an organization is out of compliance when they are in compliance. This issue is in production. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID / compliance reporting & signing authority role
1. Submit compliance report for 2021 that is in a net debit position (negative Line 25) that uses credits to offset debits (Line 26)
2. Director accepts report and credits are removed from the organization's balance (a reduction transaction)
3. Submit supplemental report #1 that increases debit obligation and uses additional credits to offset this new deficit (Line 26b)
3. Submit supplemental report #2 that does not change the debit/credit position (no changes to Schedule B)
4. See error in summary section

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2679?planning-poker) with Zenhub @jig-patel @prv-proton

**Comment by prv-proton** [comment]
Unable to reproduce the scenario. Could be a one time issue caused by the browser. Requesting to resubmit the compliance report, which would fix this issue.
