### ISSUE TITLE
TFRS - Categories being assigned to non-transfer transactions 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2683]
**Describe the Bug**
Non-transfer transactions (i.e., validations, reductions, Part 3 Awards) are being assigned a category (e.g., Category A) upon approval. 

**Expected Behaviour**
Only transfers that are completed through the credit transfer feature (i.e., created by BCeID users and approved by the director) should be assigned a category, based on the date of written agreement provided by the BCeID users and the date of approval by the director. Non-transfer transactions and transfers recorded using the Historical Data Entry (HDE) feature should not be assigned a category.

**Actual Behaviour**
Non-transfer transactions (i.e., validations, reductions, Part 3 Awards) are being assigned a category (e.g., Category A) upon approval or recording within the HDE feature. 

**Implications**
Creating incorrect and confusing data that will impact analysis and reporting of transfers based on assigned category. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR user
1. Login to tfrs-dev main release
2. Click on the Credit Transactions heading on the main nav bar
3. Click on the Download as .xls button 
4. See the Category column: non-transfer transactions are being assigned as Category A

**Developer Notes**
1. Might require migration for existing data fix and column type change
2. Business logic change

**Comment by KericeRich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2683?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2683?planning-poker) with Zenhub @hvalioll

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2683?planning-poker) with Zenhub @kevin-hashimoto

**Comment by justin-lepitzki** [comment]
It looks like some transactions are still being assigned as category A: 
1) Validations and Reductions from the acceptance of a compliance report
2) Part 3 Awards from Director approval
3) Transfers approved through the Historical Data Entry feature

We would like all of the above to not be assigned a Category since there is no agreement date associated with them. 

The following transactions have been tested and are working (i.e., no category is being assigned)
1) Validations and Reductions recorded/approved through the Historical Data Entry feature
2) Part 3 Awards recorded/approved through the Historical Data Entry feature

**Comment by justin-lepitzki** [comment]
I'm still experiencing the same transactions being assigned as category A:

1. Validations and Reductions from the acceptance of a compliance report
2. Part 3 Awards from Director approval
3. Transfers approved through the Historical Data Entry feature (which has no agreement date field and therefore should not be categorized) 

Here is a screenshot of the downloaded transactions spreadsheet from this morning's testing: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeURhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dd13d3887eac4001561b1e9762e5526260a8312/Screenshot%202023-11-15%20cat%20error.png)

**Comment by justin-lepitzki** [comment]
This fix might not be deployed correctly. Kuan is investigating. Going to pause testing for now.

**Comment by justin-lepitzki** [comment]
Tested :) will create a new card to handle the historical transactions in Prod
