### ISSUE TITLE
TFRS - Adjust default width of columns in Transactions sheet download as .xls 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2684]
**Describe the task**
Adjust the default width of the columns in the (Credit) Transactions excel spreadsheet that BCeID and IDIR users can download from the Transactions page (via the download as .xls button). 

Recently, we added a new column 'Category' for the categorization of transfers. This addition moved other columns one spot over to the right. The 'Effective Date' column is now too wide and the 'Comments' column is now too narrow. We would like to reduce the default width of the 'Effective Date' column and widen the 'Comments' column to better fit the data.

**Purpose**
To better display the data to the user when viewing the downloaded transactions worksheet. 

**Acceptance Criteria**
- [ ] reduce the width of Effective Date column so that its not too wide. 
- [ ] Increase the width of "Comments" column to better fit the data
- [ ] Make sure it doesn't affect width of other column.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2684?planning-poker) with Zenhub @jig-patel @prv-proton @hvalioll @kevin-hashimoto
