### ISSUE TITLE
TFRS - revert org status label changes on Edit organization page in main release

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2704]
**Describe the task**
In a recent update to the main release of the 'Edit Organization' page (accessible only via IDIR), label changes were mistakenly applied. These changes were intended solely for the January release. This task is to restore the original labels. Below are the screenshots that illustrate the current state in the development environment and the desired labels for the main release. See screenshots below for current state and desired change for **main release**. 

Screenshot of current dev env, main release: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--626d230c5168cc872be91e133be216f93866c8ec/screencapture-tfrs-dev-apps-silver-devops-gov-bc-ca-organizations-edit-57-2023-10-30-14_37_47.png)

Screenshot of desired label changes in **main release**: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5108e8403ab99eede16b896671ddbae491fb0ca2/Screenshot%202023-10-30%20150822.png)

**Purpose**
To rectify and align the label presentation on the 'Edit Organization' page in production, ensuring consistency and avoiding confusion among IDIR users.

**Acceptance Criteria**
- [x] Make necessary code changes to revert the labels to their original state as shown in the desired label change screenshot.
- [x] Ensure no other sections or elements of the 'Edit Organization' page are altered during this process.
- [ ] Test the changes in a staging environment to confirm the labels reflect the desired state.
  
**Additional context**

- This oversight might be due to a merge into the wrong release branch. Finding and reviewing the commit where this issue originated would help make sure there are no other issues.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2704?planning-poker) with Zenhub @AlexZorkin @hvalioll @jig-patel @kevin-hashimoto @prv-proton
