### ISSUE TITLE
TFRS - Resolve incorrect categorization of historical transactions in Prod

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2747]
**Describe the task**
A bug in TFRS was causing several issues with the categorization feature for credit transfers: 
- Non-transfer transactions (Validations, Reductions, Part 3 Awards) were being incorrectly categorized as Category A; they should not be categorized at all (null value)
- All transactions recorded/approved through the historical data entry (HDE) feature were being incorrectly categorized as Category A; they should not be categorized at all (null value), including credit transfers approved through the HDE feature
- Some transactions are not assigned a category in the database despite the category being visible in the UI: one impacted transaction identified in Prod, ID #1835 

This card is to resolve the discrepancies in the categorization data (both database & UI) for impacted historical transactions. A spreadsheet of impacted transactions (including the issue and desired fix) will be provided to the developer that works on this task. Due to confidentiality concerns, this information will not be provided in this card. 

Note that card # 2683 resolved the bug that was causing the incorrect categorization of these transactions: https://app.zenhub.com/workspaces/low-carbon-fuel-standard-644c2db3be098a001977ad0b/issues/gh/bcgov/tfrs/2683. 

**Purpose**
Resolve issues with incorrect data in Prod (both database and UI). 

**Acceptance Criteria**
- [ ] Review and understand the spreadsheet of impacted transactions to identify the exact issues and required fixes for each transaction.
- [ ] Implement database corrections to ensure that non-transfer transactions have a null value in the categorization field.
- [ ] Adjust any transactions recorded through the HDE feature that have been incorrectly categorized as Category A.
- [ ] Verify and correct the categorization of transaction ID #1835 and any other identified transactions where the database and UI categorization are misaligned.
- [ ] Perform thorough testing to ensure that the corrections are accurately reflected in both the database and the user interface.
- [ ] Conduct a final review to confirm that no other transactions are affected by similar categorization issues.

**Additional Context**
- This task follows the resolution of the categorization bug as addressed in card #2683. Refer to this card for context on the initial issue and the implemented fix: [Link to card #2683]
- Due to the sensitive nature of the data, access to the spreadsheet of impacted transactions will be restricted and provided only to the developer assigned to this task.
- Coordinate with the database administration team if necessary for any complex database queries or updates required for this task.
- Keep track of all changes made for audit purposes and potential rollback scenarios.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2747?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by AlexZorkin** [comment]
Updated all credit transfer categories referenced in the excel file.
