### ISSUE TITLE
TFRS - Modal window bug when completing actions in TFRS jan release test environment

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2748]
**Describe the Bug**
- System is not proceeding to the next stage in a process when compliance actions for transfers, compliance reports, etc.
- Issue with modal window throwing an error in the console
- Examples include: Signing and sending a new transfer (BCeID user), recommending a submitted transfer or compliance report (Government analyst), accepting a compliance report (Director), and approving a transfer (director)
- Issue is only occurring in the TFRS jan-release test environment. This issue does not occur in TFRS jan-release dev environment or the TFRS main-release test environment.

**Expected Behaviour**
When a user takes an action, such as signing and sending a new transfer, the system should respond by confirming that the transfer has been sent (green success alert) and then take the user back to the main transactions table.  

**Actual Behaviour**
When a user takes an action, such as signing and sending new transfer, the system does not respond. The user remains on the new transfer page and there is no green success alert message. Refreshing the page or navigating manually to the transactions page shows that the new transfer did in fact successfully send (i.e., save in database and status change)

Screenshot of console error: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkFWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ddc0f962232510df330f681e509d15a076ba0d6/Screenshot%202023-11-28%20Modal%20Error.png)

**Implications**
It appears like the system is not successfully completing actions. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user, transfer & Signing authority roles
1. Go to Transactions page
2. Click on New Transfer button
3. Fill out required fields 
4. Click on Sign & Send button
5. Click on Sign & Send button again within the modal window
6. See error

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2748?planning-poker) with Zenhub @AlexZorkin @jig-patel @kevin-hashimoto @prv-proton @hamed-valiollahi

**Comment by hamed-valiollahi** [comment]
@AlexZorkin I tested the code from the `jan-2024` branch on my local using the same test environment database, and it worked fine. I also asked Kuan about any differences between the different environments, but everything seems similar. I've already sent you the logs. I'd appreciate it if you could check into this issue. Please let me know if you need any additional information.
