### ISSUE TITLE
TFRS - Transfer effective date appears in 'Trade Effective Date' column in the database for transfers with an agreement date

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2751]
**Describe the task**
Historically, transfers that were approved by the Director had their effective date stored in the 'Trade Effective Date' column in the database (TFRS / public / Credit Trade). We recently added a new feature to the transfers component called the agreement date. This feature requires the BCeID user to provide the date in which the agreement to transfer was reached; TFRS then categorizes the transfer (as A, B, C, D) based on the agreement date and the date the director approves the transfer. In the case of category D, it is a manual selection to assign a transfer as category D (override). Since we implemented this feature, the effective date for transfers is no longer being stored in the 'Trade Effective Date' column. This creates issues with data organization and challenges with data analysis using Metabase. 

This task is to have the effective date for approved transfers be stored in the 'Trade Effective Date' column in the database (TFRS / public / Credit Trade). Note that only transfers approved after the release of the agreement date feature are missing an effective date in this column; previously approved transfers do have an effective date in the 'Trade Effective Date' column. 

Please note that a transfer's effective date is the date the director approves (records) the transfer (the date they click the Approve / Record button).

**Purpose**
Ensure consistent data storage and better facilitate data analysis in Metabase. 

**Acceptance Criteria**
- [ ] Given a transfer has been approved by the Director, when the 'Approve / Record' button is clicked, then the system should store the current date as the 'Trade Effective Date' in the database for that transfer.
- [ ] Given the agreement date feature is in use, when a BCeID user enters an agreement date and the Director approves the transfer, then the system should categorize the transfer accordingly and the 'Trade Effective Date' should be the Director’s approval date.
- [ ] Given a transfer is manually categorized as category D, when the Director approves the transfer, then the approval date should be recorded as the 'Trade Effective Date' in the database.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2751?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Nothing to test until its released to Prod
