### ISSUE TITLE
TFRS - Two approved transfers showing incorrect category in the UI

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2752]
**Describe the Bug**

- Two transactions are assigned the correct category in the database, but are showing a different, incorrect category in the UI: two impacted transactions identified in Prod, ID #1895, #1879
- Showing category B in the UI (6-12 months between agreement date & approval date) whereas the database (and downloaded spreadsheet of transactions) has the correct category A (approved within 6 months of the agreement date). 

**Expected Behaviour**
The category in UI should align with the category in the database / downloaded spreadsheet

**Actual Behaviour**
The category in UI is different than the category in the database / downloaded spreadsheet. 

**Implications**
Inaccurate information in Prod; conflict between UI & database. 

**Steps To Reproduce**

See two impacted transactions identified in Prod, ID #1895, #1879

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2752?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by AlexZorkin** [comment]
confirmed locally that these now correctly show category A.

**Comment by justin-lepitzki** [comment]
Confirmed to be working locally. Closing out and will confirm fix is applied to impacted transactions when released to Prod
