### ISSUE TITLE
TFRS - Fix broken File Submission link on BCeID dashboard

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2764]
**Describe the task**

- The link to create a new file submission from the dashboard is broken in the January release
- Task is to update the link

Current (broken) link: https://tfrs-dev-jan.apps.silver.devops.gov.bc.ca/part_3_agreements/add/ 
New link to add: https://tfrs-dev-jan.apps.silver.devops.gov.bc.ca/part_3_agreements/add/2

**Screenshot of BCeID dashboard:** 
<img width="1354" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekdkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b22657a550defd7c9f03cae6e40ad4ada50655f2/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-2024-01-04-11_35_11.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-2024-01-04-11_35_11.png" />

**Purpose**
Fix a broken link that resulted from changes to the File Submission feature

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2764?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton
