### ISSUE TITLE
TFRS - Update Notification descriptions to align with new Act labels

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2765]
**Describe the task**
The notifications page is still displaying old Act language, including labels and statuses This card is to update the labelling to align with the new Act labels we have used elsewhere in the application. 

**Screenshot of current notification labels:**
<img width="1130" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemVkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d333cb38667fc735049f6de657bf0f773b43e6e3/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-notifications-2024-01-04-11_39_54.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-notifications-2024-01-04-11_39_54.png" />

**Label changes:**
See word document here: [Notification Type label changes.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d41a66494245494654d9621c57fe089488fc4eb/Notification%20Type%20label%20changes.docx)

**Purpose:**
The primary goal of this task is to update the notification labels on a specific page of your application to align with the new Act language. This involves changing the terminology used in labels and statuses to be consistent with the language adopted elsewhere in the application.

**Acceptance Criteria:**
- [ ] Use the refined list from product owner to update notification labels.
- [ ] Ensure that the label "Part 3 Award" is changed to "Initiative Agreement."
- [ ] Replace "Credit Transfer Proposal" with "Transfer" and update "Credit Validation" as well as "Credit Reduction" to "Assessment."
- [ ] Adjust the statuses associated with transfers, ensuring they are in line with the new labels. This includes changing old status labels like 'proposed', 'signed', and 'approved' to their new equivalents.

**Additional Context:**
- This task might require attention to detail to ensure all labels and statuses are updated correctly.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2765?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton
