### ISSUE TITLE
TFRS - Wrong labels showing in confirmation alert for director recording a transfer in jan release

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2766]
**Describe the Bug**
The old Act labels are showing in the confirmation modal window when the director goes to record a transfer. These labels were previously changed but it appears that the system has reverted back to the old labels.

**Expected Behaviour**
Show the new labels: 
<img width="537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2lkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--455bed5659e053f4488aaa2f32bf238324cb35dd/Screenshot%202024-01-04%20correct%20labels%20director%20recording%20transfer.png" alt="Screenshot 2024-01-04 correct labels director recording transfer.png" />

**Actual Behaviour**
Showing the old labels: 
<img width="538" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21kQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc4c2aa1399cf1413ca5901c0da9681861ef6174/Screenshot%202024-01-04%20old%20labels%20director%20recording%20transfer.png" alt="Screenshot 2024-01-04 old labels director recording transfer.png" />

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR user, Director role
1. Go to a transfer with a reviewed status
2. Click on Record transfer button
3. See error in confirmation modal

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2766?planning-poker) with Zenhub @AlexZorkin @kevin-hashimoto @prv-proton
