### ISSUE TITLE
TFRS - Issues with the effective date for transactions entered using the Historical Data Entry feature

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2769]
**Background**
Transactions entered using the historical data entry (HDE) feature have three dates associated with them: 
- Effective date: a specific input field in the HDE form that describes when the transaction is effective (when it occurred)
- Recorded date: the date the transaction was added to the queue in the HDE feature
- Approved date: the date the transaction was committed (approved) in the HDE feature

The download as xls feature allows the user to download data directly from TFRS. This feature is available on the Transactions page. Downloading the transactions data into a spreadsheet includes a column called 'Effective Date' that is intended to display the effective date for the different approved transactions. 

**Describe the Bugs**
Bug #1: The effective date is being changed to a future date (tomorrow's date) regardless of what the user inputs in the Effective Date field within the Historical Data Entry (HDE) feature. For example, today is January 5, 2024; the user inputs a transaction into the HDE feature and indicates that the effective date is December 15, 2023. Upon committing the transaction, the effective date is changed to January 6, 2024 (which is tomorrow's date, a future date). The effective date should be December 15, 2023. 
- Bug #1: is impacting TFRS main release dev

Bug #2:  The date being displayed in the downloaded transactions sheet for transactions entered using the historical data entry feature is the "Approved date". This is not the correct date to display. It should be showing the Effective date, which is the date entered into the specific input field in the HDE form. 
- Bug #2 is impacting TFRS main release Prod, but not TFRS main release Dev
- Bug #2 is impacting TFRS January release Dev

**Impacted transactions:**

- Both of these bugs are only impacting transactions entered using the HDE feature. They are not impacting transactions approved within the credit transfer feature and/or the compliance reporting feature. 

**Steps To Reproduce**
Bug #1: 
1) Login to TFRS dev, main release as an IDIR user: https://tfrs-dev.apps.silver.devops.gov.bc.ca/
2) Click on Historical Data Entry within the Administration section of the dashboard
3) Enter in a new transaction with an effective date in the past (e.g., some date in 2023).
4) Add the transaction to the queue, note that the correct effective date is displayed in the queue
5) Commit the transaction by clicking on the Commit button
6) Navigate back to the Credit Transactions page and click on the transactions you just committed
7) See error in effective date

Bug #2: 
See transaction ID #1217 in TFRS January release, dev environment: https://tfrs-dev.apps.silver.devops.gov.bc.ca/credit_transactions/view/1217
- NOTE: Bug #2 is impacting Prod, we need to fix the issue on the main branch as well. 

Screenshot of Historical Data Entry form: 
<img width="1219" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0NqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3798de0824281c213de961d483415469aefcd07/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-admin-historical-data-entry-2024-01-05-16_50_15.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-admin-historical-data-entry-2024-01-05-16_50_15.png" />

**Bug #1 Screenshots: taken from TFRS main branch, dev environment**
Transaction ID# 1279 added to the queue showing the correct effective date that the user inputted (2023-09-01):
<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1dqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47c841ebdaed7a7b735ed923789a4f24e189aa0a/screencapture-tfrs-dev-apps-silver-devops-gov-bc-ca-admin-historical-data-entry-2024-01-05-17_03_56.png" alt="screencapture-tfrs-dev-apps-silver-devops-gov-bc-ca-admin-historical-data-entry-2024-01-05-17_03_56.png" />

Transaction ID# 1279 after commit, showing incorrect future effective date of January 6; transaction was committed on January 5: 
<img width="1489" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--344769afa5a1a86ab20e8d721b94dca693a48f52/screencapture-tfrs-dev-apps-silver-devops-gov-bc-ca-credit-transactions-view-1279-2024-01-05-17_07_38.png" alt="screencapture-tfrs-dev-apps-silver-devops-gov-bc-ca-credit-transactions-view-1279-2024-01-05-17_07_38.png" />

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2769?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton
