### ISSUE TITLE
TFRS - old Part 3 Award label and sentence language showing for newly created Initiative Agreement Issuance transaction

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2772]
**Describe the Bug**
The 'Part 3 Award' label, graphic and old sentence language is still visible when viewing a newly created Initiative Agreement Issuance. 

**Expected Behaviour**
The newly created Initiative Agreement transaction should use the label Initiative Agreement when viewing the transaction details page, use the new labels in the transaction graphic, and use the new sentence language previously provided and implemented. 

**Actual Behaviour**
The Part 3 Award label, old graphic language, and old sentence language is still being used when viewing the transaction details page. 

**Steps To Reproduce**
Steps to reproduce the behaviour: TFRS dev, January release
User/Role: IDIR, Government Analyst role
1. Go to File Submissions in the main nav bar
2. Click on the 'New Initiative Agreement Issuance' button
3. Fill out the form and click on either Save Draft or Recommend issuance buttons
4. Click on the newly created transaction from within the main Transactions table
5. See error

Screenshot of error: 
<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65ed83b1d099376f7b40678a20407e570ef06b23/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-view-1222-2024-01-08-11_24_56.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-view-1222-2024-01-08-11_24_56.png" />

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2772?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton
