### ISSUE TITLE
TFRS - Adjust 'Part 3 Award' label for transaction type in the Historical Data Entry feature

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2773]
**Describe the task**
Change the 'Part 3 Award' transaction label in the Historical Data Entry feature to 'Initiative Agreement'. This label change includes ensuring that the resulting transaction type is labeled as an 'Initiative Agreement'. 

- this is for the January release

**Purpose**
Align with the new act language

**Screenshot of HDE:**
<img width="1045" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0655556bf76cff70ffff897dd0d9c8ed0e744501/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-admin-historical-data-entry-2024-01-08-15_15_55.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-admin-historical-data-entry-2024-01-08-15_15_55.png" />

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2773?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Tested and confirmed label change when first creating the new Initiative Agreement transaction and when committing it (approving it). One minor issue discovered is that the "Part 3 Award" label still shows when adding the transaction to the queue (from within the historical data entry feature; see screenshot). Can we change the transaction type label to Initiative Agreement as well? 

Screenshot: <img width="1045" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy9QQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1c22d369d25d9ad9f78c3858975f9d22135e533/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-admin-historical-data-entry-2024-01-16-11_21_03.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-admin-historical-data-entry-2024-01-16-11_21_03.png" />
