### ISSUE TITLE
TFRS - more New Act Label Changes - Notifications Settings

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2774]
**Describe the task**
Changing labels on the Notifications Settings page, accessible to both IDIR & BCeID users. 

**Labels to change:**
[more New Act Label Changes - Notifications Settings.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0NxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f69b3f3ddf3a0b30f97dbdc947d7bee9d4b0c0c/more%20New%20Act%20Label%20Changes%20-%20Notifications%20Settings.docx)

**Location in app:**
- BCeID & IDIR: click on the user's name in the top right corner of the heading in the main / top nav bar.

**Purpose**
Changes labels and messaging to align with the language and framing used in the new Act. 

**Acceptance Criteria**
- [ ] All the labels need to be changed as per the attached document without breaking the functionality

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2774?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Tested and all of the requested label changes are confirmed to be displaying correctly! However, it looks like two of the previously changed labels have reverted back (?).

For IDIR users, under Transfers, the following two labels need to be changed:
- 'Recommend DIrector Approval' changed to 'Recommend recording transfer'
- 'Recommend Director Approval Decline' changed to 'Recommend refusing transfer'

Screenshot of current labels for IDIR users in the notification settings page: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ZQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff22406d5db7ce405416d553d0711c821ddda47f/Screenshot%202024-01-16%20notification%20settings%20labels%20idir.png" alt="Screenshot 2024-01-16 notification settings labels idir.png" />

**Comment by hamed-valiollahi** [comment]
Thanks, Justin, for the testing and feedback.
