### ISSUE TITLE
TFRS - Update links to BCeID and IDIR user guides to use external URLs from CMS lite system

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2785]
**Describe the task**
TFRS includes user guides that are accessible by clicking on the question mark in the top-right-hand corner of the main nav bar. If you are an IDIR user, the link takes you to a PDF of the IDIR user guide; if you are a BCeID user, the link takes you to a PDF of the BCeID user guide. Currently, the PDF guides are stored/hosted within TFRS. This task is to update the URLs for these two guides to point towards external URLs. 

- This is for the TFRS January release

BCeID user guide external URL: https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/electricity-alternative-energy/transportation/renewable-low-carbon-fuels/transportation_fuels_reporting_system_bceid_user_guide.pdf

IDIR user guide external URL: https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/electricity-alternative-energy/transportation/renewable-low-carbon-fuels/transportation_fuels_reporting_system_idir_user_guide.pdf

**Purpose**
Updating the user guides for the January release, and enables the business area to manage access and versions of these guides. Currently a developer is required to update these guides when a new version has been created. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2785?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton
