### ISSUE TITLE
2024 credit transactions still shows the recorded by director line of the transaction history text as citing the "Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act"

### ISSUE THREAD

**Issue by Grulin** [bcgov/tfrs#2813]
**Describe the task**
Once a credit transfer has a "recorded" status on the Transactions page, individual **2024** credit transactions still shows the recorded by director line of the transaction history text as citing the "Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act". Any transactions recorded with an effective date from January 1st, 2024 onward should say "under the Low Carbon Fuels Act" (name of the Act in italics) on the recorded by director line in the transaction history section. 

Any transfers recorded with an effective date previous to January 1st, 2024, should continue to show "under the Greenhouse Gas Reduction (Renewable and Low Carbon Fuel Requirements) Act" (name of Act in italics) on the recorded by director line in the transaction history section.

Note: we have already implemented logic that shows different labels for transactions depending on the effective date or create date. This task builds off of that by adding a new requirement for labeling the director entry within the transaction history section. 

**Purpose**
Adds the value of citing the correct in-force Act for transfers with an effective date of 2024 and beyond.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Screenshot**
<img width="1587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWp4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--523b0cc8701652d0bacf83f31e88436e09faa894/recorded%20by%20director%20under%20old%20Act.png" alt="recorded by director under old Act.png" />

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2813?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by Grulin** [comment]
Unable to test. Blocked due to bug in historical data entry.
