### ISSUE TITLE
Date/time stamp records twice in report history box when hitting "recommend for acceptance"

### ISSUE THREAD

**Issue by Grulin** [bcgov/tfrs#2814]
**Describe the Bug**
IDIR user with government analyst role double clicks "Recommend for Acceptance" button on assessment page of report and the date/time stamp records twice in report history box.

**Expected Behaviour**
Should only record date/time stamp once when "Recommend for Acceptance" button is pressed. 

**Implications**
Unnecessary date/time stamp that could cause confusion for recommended for acceptance date. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR Government Analyst
1. Go to Assessment page of a submitted compliance report
2. Click on "Recommend for Acceptance" twice quickly or if page does not immediately load
3. Scroll up to grey text box and see if date/time stamp was recorded twice.
<img width="1566" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekh5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82370eb115cacbd491ece4a73ea5a348021accc4/Double%20time%20stamp.png" alt="Double time stamp.png" />

![Image](https://github.com/bcgov/tfrs/assets/130073308/c3211b51-5908-4a29-bb54-10b465ea6140)

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2814?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by prv-proton** [comment]
Wasn't able to re-create the bug as the button click will create a pop-up confirmation window. But have added extra check to prevent any duplicate history records from creating.
