### ISSUE TITLE
Front End | Unit Testing |3|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#282]
Front-end testing is currently not working. This card is to explore the potential issues with the existing front-end tests, and to look for solutions to implement functioning front-end testing. https://trello.com/c/aMeS3ZEf/604-front-end-unit-testing-3

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Front End | Unit Testing |3|](https://trello.com/c/aMeS3ZEf/604-front-end-unit-testing-3)
