### ISSUE TITLE
TFRS - Exclusion reports with a submitted status not loading

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2854]
**Describe the Bug**
Exclusion reports with a Submitted status are not loading in Prod. There are a couple errors in the console (404, 500). 

Tested and reproduced in dev env. As a BCeID user, I am still able to create a new draft report, enter information, and then submit it; only when I try to view the submitted report (both as BCeID and IDIR) do I get the spinning wheel of death and console errors

Screenshot of console errors: 

![Image](https://github.com/bcgov/tfrs/assets/131904954/b24b735d-d684-4a30-9f38-80d4da45acf7)

**Implications**
Unable to view or process exclusion reports

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID and IDIR users
1. Go to an Exclusion Report with the Submitted status
2. See error

**Comment by AlexZorkin** [comment]
The 2023 Exclusion Reports were attempting to calculate summary logic that was designed for the new legislation, even though they do not have summaries like the Compliance Reports do. I have now excluded Exclusion Reports from this calculation.
