### ISSUE TITLE
TFRS - Compliance report filtering by 'last status update' in ascending order does not persist when navigating to next page

### ISSUE THREAD

**Issue by Grulin** [bcgov/tfrs#2866]
**Describe the Bug**
For IDIR users on the compliance reporting tab, when applying an ascending filter on the 'Last Status Update' column, the filter does not persist when the user navigates to the next page. The filter reverts back to descending order when you navigate to the next page. 

**Expected Behaviour**
The expected behaviour is that the "Last Status Update" filter in ascending order persists even when a user navigates to the next page of the table. 

**Actual Behaviour**
The actual behaviour is that the "Last Status Update" filter in ascending order reverts back to descending order when a user navigates to the next page of the table. 

**Implications**
The implication is that a IDIR user searching through compliance reports can be easily confused if the 'Last Status Update' filter reverts back to a different sorting order from page to page. One way around this for now is to expand the rows before filtering, but different users have reported that they use the 'next' button and are frustrated with the reset back to descending on the next page

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR
1. Go to 'Compliance Reporting' tab and view the table
2. Click on 'Last Status Update' filter in ascending order (listed by earliest date to latest date)
3. Click on 'Next' button
4. See error that has relisted reports in descending order

**Comment by justin-lepitzki** [comment]
We may not do this as we are trying to limit development in TFRS and we have been spending quite a bit of time fixing critical bugs.

**Comment by justin-lepitzki** [comment]
Not doing this.
