### ISSUE TITLE
Trello ticket 622 - UX Refactor | Update Breadcrumb appearance

### ISSUE THREAD

**Issue by rajpersram** [bcgov/tfrs#340]
https://trello.com/c/YTGvnrfP

**Comment by matthewhall78** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX Refactor | Update Breadcrumb appearance |1| [v0.3.0]](https://trello.com/c/YTGvnrfP/622-ux-refactor-update-breadcrumb-appearance-1-v030)
