### ISSUE TITLE
DEVELOPING THE TFRS WEBSITE FRONT-END (BCDX-MEM-004)

### ISSUE THREAD

**Issue by matthewhall78** [bcgov/tfrs#35]
# [DEVELOPING THE TFRS WEBSITE FRONT-END (BCDX-MEM-004)](https://bcdevexchange.org/opportunities/opp-developing-the-transportation-fuels-reporting-system-website-back-end--bcdx-mem-004-)

_Code Repo:_ [https://github.com/bcgov/tfrs](https://github.com/bcgov/tfrs)
_Wiki:_ [https://github.com/bcgov/tfrs/wiki](https://github.com/bcgov/tfrs/wiki)

## OVERVIEW OF OPPORTUNITY
> The Transportation Fuels Reporting System is being designed to streamline compliance reporting for transportation fuel suppliers in accordance with the Renewable & Low Carbon Fuel Requirements Regulation.  
>  
> We want you to replace the previously developed Django screen templates (Views) with a REACT / REDUX based front end using the Balsamiq screens we have produced. The REACT front end will utilize the REST API that is currently being developed.

### BACKEND DEVELOPMENT:

- A Python/Django server was developed that implements a REST interface and database design for the specifications of the TFRS application. 
- The database is implement in POSTGRESQL
- Users in the system are authenticated by Siteminder (via an independent process) however roles authorization is going to be developed in a future milestone.

### MILESTONES

As a **trading partner** I need to be able to navigate through a series of self-service screens to:

1. view information regarding past, proposed and pending credit-related activity including a real-time credit balance and list of activities that may impact that balance.
2. enter and submit the information required to propose a credit transaction to a trading partner; accept a proposed trade from a trading partner and submit that transaction proposal to the Director for approval.
3. view the information entered by the user on Transaction Details screen before proposing it to a trading partner or submitting it to the Director for approval.
4. review before authorising the transaction and submitting it to the Director for approval or saving it for future.
5. post a credit transfer opportunity. The offer needs to have the same information that a credit transaction proposal would have, without the transfer partner. Offer and credit transfers are separate entities.
6. respond to a credit transfer opportunity with acceptance of the terms, or respond to the credit transfer opportunity with a proposal that has modified terms

The **Low Carbon Fuels Branch staff** need to be able to:

1. input transactions to award credits for a "Part 3 Agreement" or to add validated fuel supply credits or to retire credits used for offsets in annual compliance reporting.
2. sort and search the list of all transactions and be able to export/download the tabular data for analysis in excel.
3. add companies, contacts, users, roles and permissions through the Swagger API
4. recommend approval of a proposed low carbon fuel credit transfer
5. approve the credit transfers
6. retire credits from or adjust a company's credit balance

## ACCEPTANCE CRITERIA

To be paid for this opportunity, you will:

1. Participate as a part of our team's sprint planning workshop from **1pm to 4pm on July 18th, 2017** at 3rd Floor - 1012 Douglas Street in Victoria, BC. The planning session can be rescheduled if the selected individual is not available at that time.
2. Spend a minimum of **2 hours per weekday (Tuesday - Thursday, excluding holidays, between the hours of 8:30 AM and 5:00 PM)** working in person with us at our office (1012 Douglas Street in Victoria, BC) for the duration of your work. We want you to work side-by-side with our back-end developer to implement the desired functionality in our dev environment.
3. Develop the screens in REACT using the [balsamiq wireframes](https://cloudcompass.mybalsamiq.com/projects/tfrs/grid) with the following directions:
     a. Implement a Client REST web service to consume the provided [Swagger REST API Specifications](https://github.com/bcgov/tfrs/tree/master/APISpec),
     b. Use the [Gov 2.0 Bootstrap Skeleton](https://github.com/bcgov/tfrs/tree/master/mockups) for look and feel,
     c. implement the provided [Behavior Driven Development scenarios](https://raw.githubusercontent.com/bcgov/tfrs/master/specifications/scenarios.md) and [system messaging](https://raw.githubusercontent.com/bcgov/tfrs/master/specifications/systemMessaging.md),
     d. create the NavUnit templates for automated functional testing,
     e. create functions for validation of form data, 
4. Use Trello to document the work completed, to demonstrate completion of the work in this opportunity, and include as appropriate references and links on each trello task to github commits
5. Conduct knowledge transfer with the Ministry Full Stack Developer and Front-End Developer.

## HOW TO APPLY

Please send a proposal by **16:00 PST, 14 July 2017**.

Within your email, indicate your acceptance of the [Code With Us terms](https://github.com/BCDevExchange/code-with-us/raw/master/Code%20With%20Us%20Paid%20Terms_Nov_28.pdf), you **must** attach a copy of the terms along with any information requested in the "Acceptance" section of the document.

If we are satisfied with the proposals we receive, we will assign this opportunity by **16:00 PST, 17 July 2017** with work proposed to start as soon as possible on/after **18 July 2017**.

## PROPOSAL EVALUATION CRITERIA
Please email your proposal to Matthew.Hall@gov.bc.ca.

Please reference the issue name "**Developing the TFRS website back-end (BCDX-MEM-004)**" in your proposal.

### SCORING CRITERIA
Please provide:  
- Confirmation that you can meet all the Acceptance Criteria by **17 August 2017**
- Your Approach for meeting each of the Acceptance Criteria. (60 points)
- Your Experience working with relevant agile projects (40 points).

> **NOTE**:
> In your _**Experience**_, include a description of the **work you have done recently** that demonstrates your capability to deliver similar work and (_preferred_) a link to examples of your work (e.g. GitHub projects). If needed, explain how your experience is relevant.  
> In your _**Approach**_ you should explain how you will work with us. For example, you may identify certain tools, techniques or methodologies that you would use and explain how you might use them.

### INFORMATIONAL OPEN HOUSE
On **7 July 2017**, we will host an information session from **12pm to 1pm**, for interested developers to talk with our team about the work. If you'd like to attend, please email Matthew.Hall@gov.bc.ca.

Please also feel free to ask questions via the comments section on the issue in GitHub.

### QUESTIONS?
Please provide comments below

**Comment by tweeres04** [comment]
If selected, is it possible to borrow a Windows machine for on-site development? I have a macbook pro and a windows desktop PC, but no transportable windows machine. Thanks!

**Comment by matthewhall78** [comment]
We have not yet completed the evaluation of submissions. We have been impacted the past few days with additional workload due to the government response to wildfire in BC.  You patience is appreciated.  I will post an updated timeline today.

**Comment by matthewhall78** [comment]
The previously planned Sprint Planning meeting will be moved to Friday July 21st from 1pm to 4pm.

**Comment by matthewhall78** [comment]
Evaluations have completed and the work has been awarded to @Kiesum 
Thank you for all who submitted proposals. You can contact me to setup a time to meet if you would like a debrief on your proposal.
