### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by matthewhall78** [bcgov/tfrs#40]
Authenticate users view list of companies update company details Add contacts to a company

**Comment by dainetrinidad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Authentication | Extend the User API as appropriate to relate the User information from the HTTP request header to a user record in the TFRS database |3|](https://trello.com/c/ZMqEQOZu/110-authentication-extend-the-user-api-as-appropriate-to-relate-the-user-information-from-the-http-request-header-to-a-user-record-i)

**Comment by kuanfandevops** [comment]
implemented
