### ISSUE TITLE
Historical Data Entry | Replace Notes field with Comments

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#451]
https://trello.com/c/4prYEj1l/725-historical-data-entry-replace-notes-field-with-comments

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Historical Data Entry | Replace Notes field with Comments |3|](https://trello.com/c/4prYEj1l/725-historical-data-entry-replace-notes-field-with-comments-3)
