### ISSUE TITLE
Security | Allow Multiple Roles for Users |8|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#454]
We should allow multiple roles for the users. 

A lot of stuff might need be tested as currently we expect one role per user.https://trello.com/c/Vqu6m3p0/730-security-allow-multiple-roles-for-users-8

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Security | Allow Multiple Roles for Users |8| [v0.3.1]](https://trello.com/c/Vqu6m3p0/730-security-allow-multiple-roles-for-users-8-v031)
