### ISSUE TITLE
DEVELOPING THE TFRS WEBSITE BACK-END (BCDX-MEM-002)

### ISSUE THREAD

**Issue by matthewhall78** [bcgov/tfrs#5]
The Transportation Fuels Reporting System is being designed to streamline compliance reporting for transportation fuel suppliers in accordance with the Renewable & Low Carbon Fuel Requirements Regulation. We want you to complete back-end development of the first set of screens which will enable Credit Trading.

[DEVELOPING THE TRANSPORTATION FUELS REPORTING SYSTEM WEBSITE BACK-END (BCDX-MEM-002)](https://bcdevexchange.org/opportunities/opp-developing-the-transportation-fuels-reporting-system-website-back-end--bcdx-mem-002-)

You can find our current code base at [https://github.com/bcgov/tfrs](https://github.com/bcgov/tfrs).

We want you to use the previously developed layout and design templates (Views) and complete the back-end development work. The site should deliver the following functionality:

## User Stories

As a **trading partner** I need to be able to navigate through a series of self-service screens to:

- view information regarding past, proposed and pending credit-related activity including a real-time credit balance and list of activity that may impact that balance. 
- enter the information required to propose a credit transaction to a trading partner; accept a proposed trade from a trading partner and submit that transaction proposal to the Director for approval. 
- view the information entered by the user on Transaction Details screen before proposing it to a trading partner or submitting it to the Director for approval.
- review before authorising the transaction and submitting it to the Director for approval or saving it for future.

The **Low Carbon Fuels Branch staff** need to be able to:

- Input transactions to award Part 3 Agreement or fuel supply credits or adjust balances based on new information to users through the same process as above
- Run queries to produce periodic (quarterly, annually, etc.) reports on credit transaction activity with the following variables:
      - Number of transfers
      - Total credits traded
      - Avg. market value
      - Min/max value 

## ACCEPTANCE CRITERIA

To be paid for this opportunity, you will:

1. Participate as a part of our team’s sprint planning workshop from 10:00 PM - 12:00 PM on April 10, 2017 at 1012 Douglas Street in Victoria, BC.
2. Spend a minimum of 2 hours per weekday (Tuesday - Thursday, excluding holidays, between the hours of 8:30 AM and 5:00 PM) working in person with us at our office (1012 Douglas Street in Victoria, BC) for the duration of your work. We want you to work side-by-side with our front-end developer and DevOps specialist to implement the desired functionality in our dev environment.
3. Develop the back-end model, controller, form endpoints, validation of form data, automated tests for all applicable code for each of the following views: 
```
      i.    Credit Trading Dashboard containing summary views of 
               Credit Balance, 
               Notifications, and 
               Transaction Activity
      ii.   Credit Trade Create Transaction view
      iii.  Credit Trade Transaction Summary view
      iv.   Credit Trade Account Balance view
      v.    Credit Trade Alerts view
      vi.   Credit Trade Notifications view
      vii.  Credit Trade Alert Settings view
```
4. A notification microservice for communicating transaction events via text or email
5. Develop an OpenAPI (Swagger) specification

## HOW TO APPLY

Please send a proposal to by 16:00 PST, Tuesday, April 4, 2017.

With your email, to indicate your acceptance of the [Code With Us terms](https://github.com/BCDevExchange/code-with-us/raw/master/Code%20With%20Us%20Paid%20Terms_Nov_28.pdf), you must attach a copy of the terms along with the required information asked for in the "Acceptance" section of the document.

If we are satisfied with the proposals we receive, we will assign this opportunity by **16:00 PST, Friday, April 7, 2017** with work proposed to start on **Monday, April 10, 2017**.

### Informational Open House
On Tuesday, March 21th and 22nd, from 12:00-1:00 PM, we will be hosting a drop-in session for interested developers to talk with our team about the work. If you’d like to attend, please email Matthew.Hall@gov.bc.ca.

Please also feel free to ask questions via the comments section on the issue in GitHub.

## PROPOSAL EVALUATION CRITERIA
Please email your proposal to Matthew.Hall@gov.bc.ca. 

Please reference the issue name "**Developing the Transportation Fuels Reporting System website back-end (BCDX-MEM-002)**" in your email. 

### Scoring criteria:
- Your confirmation of being able to commit the time to meet all of the Acceptance Criteria by April 28, 2017.
- A short (around 200 words or less would be nice) summary of your experience working with agile projects (40 points).
- References to your relevant experience and demonstrated ability to do the work (60 points). For example, a link to your GitHub projects.

## QUESTIONS?
Please provide comments below

**Comment by matthewhall78** [comment]
The open house is at 3rd Floor - 1012 Douglas Street in Victoria, BC

**Comment by johannamcburnie** [comment]
Hi there Matthew, is it correct that the work needs to be completed in a week (March 27-31st)?

**Comment by matthewhall78** [comment]
In order to meet acceptance criteria, work should be substantially complete prior to mar 31st, but can be completely after that. The definition of "substantially" if left flexible and can be discussed if your proposal is selected.

**Comment by matthewhall78** [comment]
The is opportunity is going to be extended to close on April 4th. please refer back to the BCDevexchange.org website (https://bcdevexchange.org/opportunities/opp-developing-the-transportation-fuels-reporting-system-website-back-end--bcdx-mem-002-) for details. I will update the Github page shortly.

**Comment by kheera** [comment]
Hey Mathew, I just discovered this bc dev exchange on Saturday and am looking to put in a proposal on this project. I've reviewed the proposal requirements and see the sorting criteria lists 200 words for the agile summary. There seems to be no other sections required. This seems very limited - can more sections be included in the proposal or are we limited to what's listed as sorting criteria?  Thanks, Shane

**Comment by matthewhall78** [comment]
200 word maximum is not a mandatory requirement. If you have additional sections that you would like to add, you may do so but please indicate why you are providing the information and how it relates to the things listed in the scoring criteria section.

**Comment by matthewhall78** [comment]
Thank you to all those who submitted proposals! 
The competition is now closed. We received 6 proposals by the closing time. 
We will review and advise you of the outcome by Monday or Tuesday next week.

**Comment by matthewhall78** [comment]
Thank you to all who have put time into their proposals. We have completed the evaluation for 
opportunity `DEVELOPING THE TFRS WEBSITE BACK-END (BCDX-MEM-002)`

>We have selected _Walker Software_ as the successful proponent for this opportunity.  

**_Please stay tuned for additional opportunities in the near future._**

If you would like feedback on your proposal you can send a request to @matthewhall78

**Comment by matthewhall78** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(13) Django generator from swagger specification [13]](https://trello.com/c/Ykzc9Zx2/57-13-django-generator-from-swagger-specification-13)

**Comment by matthewhall78** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Back End Development: Extend current Django implementation to use the Django REST Framework [5]](https://trello.com/c/mYKwO0aV/58-5-back-end-development-extend-current-django-implementation-to-use-the-django-rest-framework-5)
