### ISSUE TITLE
User Management | Create 'TFRS Admin' Role

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#552]
**Task:**
Create 'Managing Users' role that will provide the following permissions:

- Add a new user within your company [IDIR & BCeID]
- Edit an existing user within your company, including setting active/inactive status [IDIR & BCeID]
- Add a new organization [IDIR Only]
- Edit a new organization, including setting active/inactive status and buy/sell, sell only, none [IDIR Only]https://trello.com/c/EBj5R04J/810-user-management-create-tfrs-admin-role

**Comment by amichard** [comment]
Duplicate issue. Please refer to #656
