### ISSUE TITLE
User Management | Create Managing Users Role BCeID

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#637]
**Task:**
Create 'Managing Users' role that will provide the following permissions:

- Add a new user within your company
- Edit an existing user within your company, including setting active/inactive status
- Assign roles to your company's users (including yourself): Credit Trader, Signing Authority, Managing Users
- Can see the 'Add User' button on the Company Details page
- Can see the edit icon(s) in the user table on the Company Details page https://trello.com/c/7165Swbm/912-user-management-create-managing-users-role-bceid

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Management | Create Managing Users Role BCeID |3|](https://trello.com/c/y9nmULjV/798-user-management-create-managing-users-role-bceid-3)
