### ISSUE TITLE
Roles | Change "Credit Trader" role label to "Credit Transfers"

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#690]
https://trello.com/c/mruZSv9Q/995-roles-change-credit-trader-role-label-to-credit-transfers

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Roles | Change Credit Trader role label to Credit Transfers |1|](https://trello.com/c/mruZSv9Q/995-roles-change-credit-trader-role-label-to-credit-transfers-1)
