### ISSUE TITLE
Login | Discuss Whether we keep the management of roles and permissions in TFRS or in Keycloak

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#758]
after the presentation about block chain and the org book i think we should consider trying to conceptually follow that pattern of isolated our application from any login roles and permissions.

the concept or architectural model of trusting the provider of roles and permissions rather than handling it in the app seems like the right way to go https://trello.com/c/fdYYOKh8/1046-login-discuss-whether-we-keep-the-management-of-roles-and-permissions-in-tfrs-or-in-keycloak

**Comment by KMenke** [comment]
@amichard can this issue be closed?
