### ISSUE TITLE
Authentication | Allow multiple accounts to use the same email |8|

### ISSUE THREAD

**Issue by dainetrinidad** [bcgov/tfrs#940]
**Story:**
As a BCEID user, I want to be able have multiple accounts in the system using the same email address so I don't have to manage multiple email addresses if I'm working for multiple organizations.

https://trello.com/c/tt5twM7l/1198-authentication-allow-multiple-accounts-to-use-the-same-email-8

**Comment by amichard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Authentication | Allow multiple accounts to use the same email |8|](https://trello.com/c/tt5twM7l/1198-authentication-allow-multiple-accounts-to-use-the-same-email-8)
